### ISSUE TITLE
Inline picker should scroll the view to show entire picker

### ISSUE THREAD

**Issue by ksbecker** [xmartlabs/XLForm#101]
When an inline picker view is rendered, the view should scroll up (when necessary) to ensure that the entire picker view is displayed. This effect can be seen when using the Calendar app on an iPhone in landscape mode. When adding a new event turn the phone to landscape and scroll so that the start or end date is at the bottom of the screen. Tap the start/end date and notice how the screen scrolls up to show the date picker.

**Comment by C4Grey** [comment]
+1, can somebody direct me to the place in code where to look for a possibility of implementation of a such feature? It will be very useful, especially for forms with multiple entries, where pickers are on boundaries of a form.
