### ISSUE TITLE
Change color to text section 

### ISSUE THREAD

**Issue by AVAlex** [xmartlabs/XLForm#1016]
I'am unable to change the color and the font to XLFormSectionDescriptor. It's possible?

XLFormSectionDescriptor * section;
 // Basic Information
 section = [XLFormSectionDescriptor formSectionWithTitle:@"Other Cells"];
 [form addFormSection:section];

**Comment by mats-claassen** [comment]
Hi, do you want to change font and color of the header?

The section header and footer are the default of iOS. 

You can have a look [here](https://github.com/xmartlabs/XLForm#how-to-customize-the-header-andor-footer-of-a-section) for help setting a view as header which you could customize

**Comment by AVAlex** [comment]
Hi. Great!
Thank you
