### ISSUE TITLE
Slider doesn't work

### ISSUE THREAD

**Issue by JGK01** [xmartlabs/XLForm#1019]
hi,

i'm trying to create a slider row but it doesn't work. the row doesn't want to display on the screen.

using this code : 
```
row = XLFormRowDescriptor.init(tag: "test", rowType: "slider", title:"")
row.cellConfig.setValue(UIColor(red: 1, green: 1, blue: 1, alpha: 0.6), forKey: "backgroundColor")
section.addFormRow(row)
```

every other types work fine

Thanks !

**Comment by mats-claassen** [comment]
I copied your code to the Examples project and it works fine. A few things to check: Are you adding that section to the form? Do you have another row with that tag?

**Comment by JGK01** [comment]
thanks ! the problem was that i had a second row with the same id
