### ISSUE TITLE
Font bug

### ISSUE THREAD

**Issue by doremifaJ** [xmartlabs/XLForm#1031]
When I change the system font on iPhone X , the form's font changed, not beautiful! How to fix it？

**Comment by mats-claassen** [comment]
By default, XLForm uses the `[UIFont preferredFontForTextStyle:]` font. If you want a fixed font you could use `cellConfig` on each row to set the font, even if this is a bit tedious

**Comment by jazzwsr** [comment]
thanks a lot，i got it，and use cellConfig fix it!

**Comment by jazzwsr** [comment]
thanks a lot，i got it，and use cellConfig fix it!
