### ISSUE TITLE
how to change buttons' action and events of custom row in View Controller

### ISSUE THREAD

**Issue by HelloButler** [xmartlabs/XLForm#1042]
inside a ViewController.m
```
//cellImageBtn is a UIButton define in a custom upLoadImageCell 
   {
row =[XLFormRowDescriptor formRowDescriptorWithTag:@"uploadImage" rowType:XLFormRowDescriptorTypeUploadImage];
   [row.cellConfigAtConfigure setObject:@"YES" forKey:@"cellImageBtn.hidden"];//this works ok
    [[row.cellConfigAtConfigure objectForKey:@"cellImageBtn"] addTarget:self action:@selector(photoBtnTap) forControlEvents:UIControlEventTouchUpInside];// this is not working
}

-(void)photoBtnTap{
//do sth...
}
```
anyone have idea?

**Comment by mats-claassen** [comment]
`cellConfigAtConfigure` cannot be used like that to get properties of the row. It is just used to store values of properties which will later be set on the row. What you could do is setting the controller as a delegate to the row

**Comment by HelloButler** [comment]
I am new to Objective c, 
how to do that? a example will be appreciated :)
this is normal way to do that, but with xlfrom, there's not such thing like cell instance;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    PreferentialCell *cell = [tableView dequeueReusableCellWithIdentifier:@"preferentialCell" forIndexPath:indexPath];
    
    YXHGoods *goods = self.dataArray[indexPath.row];
    cell.goods = goods;
    
    __weak typeof(self) wself = self;
    cell.onClickShareButtonHandler = ^(YXHGoods *model) {
        [wself _handleShareEventWithGoods:model];
    };
    cell.onClickCommentButtonHandler = ^(YXHGoods *model) {
        [wself _handleCommentEventWithGoods:model];
    };
    
    return cell ;
}

**Comment by HelloButler** [comment]
I did it alternative way, thx anyway:)
