### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPush如何动态设置选择项，如通过网络获取的

### ISSUE THREAD

**Issue by yiliazhang** [xmartlabs/XLForm#1051]
XLFormRowDescriptorTypeSelectorPush如何动态设置选择项，如通过网络获取的

**Comment by harveyseeking** [comment]
XLFormRowDescriptor *row = [self.form formRowWithTag:@""];

**Comment by harveyseeking** [comment]
XLFormRowDescriptor *row = [self.form formRowWithTag:@""];
 row.selectorOptions = array;
[self reloadFormRow:row];
Dose it work?
