### ISSUE TITLE
XLFormViewController crashing - Xcode 11.0 Beta 6

### ISSUE THREAD

**Issue by nabanita-mukherjee** [xmartlabs/XLForm#1061]
When we build our existing project in new Xcode 11.0 Beta 6 its crashing with the following console logs:

Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23afdbde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff5015cb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23afda1c +[NSException raise:format:] + 188
	3   UIKitCore                           0x00007fff471fbf44 -[UITextField valueForKey:] + 84
	4   Foundation                          0x00007fff2557a29c -[NSObject(NSKeyValueCoding) valueForKeyPath:] + 242
	5   Jifflenow                           0x0000000106e07fe4 __50+[UITextView(Placeholder) defaultPlaceholderColor]_block_invoke + 132
	6   libdispatch.dylib                   0x0000000108ddfd64 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x0000000108de12b3 _dispatch_once_callout + 66
	8   Jifflenow                           0x0000000106e07f34 +[UITextView(Placeholder) defaultPlaceholderColor] + 84
	9   Jifflenow                           0x0000000106e08220 -[UITextView(Placeholder) placeholderLabel] + 320
	10  Jifflenow                           0x0000000106e086cb -[UITextView(Placeholder) setPlaceholder:] + 75
	11  Jifflenow                           0x00000001066bc7e7 -[JiffleSelectorCell update] + 3735
	12  Jifflenow                           0x00000001066bb92d -[JiffleSelectorCell setParentRowDescriptorAndCustomInfoField:] + 605
	13  Foundation                          0x00007fff25579a18 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 325
	14  UIKitCore                           0x00007fff473dca7c -[UIView(CALayerDelegate) setValue:forKey:] + 171
	15  Jifflenow                           0x0000000106e67056 __38-[XLFormViewController configureCell:]_block_invoke + 214
	16  CoreFoundation                      0x00007fff23b861f7 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	17  CoreFoundation                      0x00007fff23b5f48e -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 238
	18  Jifflenow                           0x0000000106e66df2 -[XLFormViewController configureCell:] + 242
	19  Jifflenow                           0x0000000106e66c98 -[XLFormViewController updateFormRow:] + 104
	20  Jifflenow                           0x0000000106e67505 -[XLFormViewController tableView:cellForRowAtIndexPath:] + 181
	21  UIKitCore                           0x00007fff47107d5f -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 787
	22  UIKitCore                           0x00007fff470d12da -[UITableView _updateVisibleCellsNow:] + 3081
	23  UIKitCore                           0x00007fff470f122c -[UITableView layoutSubviews] + 163
	24  UIKitCore                           0x00007fff473dd66e -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	25  QuartzCore                          0x00007fff2af782bd -[CALayer layoutSublayers] + 255
	26  QuartzCore                          0x00007fff2af7ccc3 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 517
	27  QuartzCore                          0x00007fff2af893a8 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 80
	28  QuartzCore                          0x00007fff2aed1a20 _ZN2CA7Context18commit_transactionEPNS_11TransactionEd + 324
	29  QuartzCore                          0x00007fff2af0702b _ZN2CA11Transaction6commitEv + 643
	30  QuartzCore                          0x00007fff2af07992 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	31  CoreFoundation                      0x00007fff23a5feb7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	32  CoreFoundation                      0x00007fff23a5a94e __CFRunLoopDoObservers + 430
	33  CoreFoundation                      0x00007fff23a5afca __CFRunLoopRun + 1514
	34  CoreFoundation                      0x00007fff23a5a6b6 CFRunLoopRunSpecific + 438
	35  GraphicsServices                    0x00007fff38016bb0 GSEventRunModal + 65
	36  UIKitCore                           0x00007fff46f0990f UIApplicationMain + 1621
	37  Jifflenow                           0x0000000106694a10 main + 112
	38  libdyld.dylib                       0x00007fff50fe1cf5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mats-claassen** [comment]
Hi, which version of XLForm are you using? 4.1.0? 
Also, does this crash happen in Xcode 11 (not beta)? And if so, could you provide steps to reproduce it?

**Comment by harveyseeking** [comment]
I have the same problem in Xcode Version 11.1 (11A1027)

**Comment by harveyseeking** [comment]
When I am use "XLFormRowDescriptorTypeSelectorAlertView" and click, chash and log:Message from debugger: Terminated due to memory issue
