### ISSUE TITLE
How to wait the response and then update the value -  need to refresh the data in time 

### ISSUE THREAD

**Issue by MarcSteven** [xmartlabs/XLForm#1083]
I met one weird issue about the framework, I got the data earlier and then update the row, but I found the process of rendering is not done, so how to get the data and update  @mats-claassen

**Comment by MarcSteven** [comment]
@mats-claassen  There are lots of similar issue about it , but in the doc cannot find the correct way to update , and in your example project there are no description to update it.

I  reviewed your source code and then cannot find the solution.


Render the Cell and then update the data, perhaps the data is from Hardware or network....

**Comment by MarcSteven** [comment]
@mats-claassen  I got the value but cannot display

**Comment by mats-claassen** [comment]
Hi @MarcSteven I believe you should be able to follow the NativeEventFormViewController example which shows how to use `updateFormRow` which is a function of XLFormViewController to update a row

**Comment by MarcSteven** [comment]
@mats-claassen Thank you so much!
