### ISSUE TITLE
XML or JSON DSL that can be loaded on the fly

### ISSUE THREAD

**Issue by tobinharris** [xmartlabs/XLForm#114]
Hi there

This looks awesome. 

Is it possible to create forms from a definition loaded from an XML or JSON file? I'd like to be able to update form definitions and download them to the app.

If such a mechanism doesn't exist, do you think it would be a big job for me to create it?

Tobin

**Comment by mats-claassen** [comment]
This has not been implemented and we do not plan to support it.
