### ISSUE TITLE
Clear / Reset Form

### ISSUE THREAD

**Issue by CBeloch** [xmartlabs/XLForm#117]
It would be great if there would be any option to clear/reset the form.
As an example: If it is used as a contact form it would be a normal behavior to clear the data on a successful submit (with an additional alert that will be implemented by the developer).

**Comment by simogerard** [comment]
Is there a Swift solution for that?
Thank you

**Comment by conradwt** [comment]
@simogerard You should be able to do something like the following:

```swift
  func reset() {
    var sections = self.form.formSections as NSArray as! [XLFormSectionDescriptor]
    
    sections.map { self.resetFormRowsFor( $0  ) }
  }
  
  func resetFormRowsFor( var section: XLFormSectionDescriptor ) {
    var rows = section.formRows as NSArray as! [XLFormRowDescriptor]
    
    rows.map { (row: XLFormRowDescriptor) -> Void in
      row.value = nil
      self.reloadFormRow( row )
    }
}
```
