### ISSUE TITLE
formDescriptorCellResignFirstResponder not called

### ISSUE THREAD

**Issue by jschmid** [xmartlabs/XLForm#119]
I am trying to create a custom cell. I want to know when the cell looses the first responder status to update its view.

The README explains I should implement `formDescriptorCellResignFirstResponder`. However, it does not get called. 

By digging in the code I found that this method should be called when the user presses the `return` key. ([This part](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.m#L444)).
Unless you are the very last cell in the form, the method never get called since the calling method returns before. 
Maybe reversing the two `if` in `textFieldShouldReturn` would be enough to fix this.

Still, this does not work for cells that do not have a `UITextField`. Maybe the doc could be updated (or the problem fixed)

Cheers

**Comment by bdalziel** [comment]
I added the following to my subclass of XLFormViewController:
```Objective-C
#pragma mark - UITextFieldDelegate

- (void)textFieldDidBeginEditing:(UITextField *)textField
{
    UITableViewCell<XLFormDescriptorCell> * cell = [textField formDescriptorCell];
    if ([cell respondsToSelector:@selector(formDescriptorCellBecomeFirstResponder)]){
        [cell formDescriptorCellBecomeFirstResponder];
    }
}

- (void)textFieldDidEndEditing:(UITextField *)textField
{
    UITableViewCell<XLFormDescriptorCell> * cell = [textField formDescriptorCell];
    if ([cell respondsToSelector:@selector(formDescriptorCellResignFirstResponder)]){
        [cell formDescriptorCellResignFirstResponder];
    }
}
```

Then to avoid an infinite loop, I use the following logic rather than calling super (XLFormTextFieldCell):

```Objective-C
// called when cell wants to become active
-(BOOL)formDescriptorCellBecomeFirstResponder
{
    BOOL become = YES;
    if(!self.textField.isFirstResponder) {
        become = [self.textField becomeFirstResponder];
    }
    if (become) {
        // Do something to your cell
    }
    return become;
}

// called when cell requested to loss first responder
-(BOOL)formDescriptorCellResignFirstResponder
{
    BOOL resign = YES;
    if (self.textField.isFirstResponder) {
        return [self.textField resignFirstResponder];
    }
    if (resign) {
        // Do something to your cell
    }
    return resign;
}

```

**Comment by mats-claassen** [comment]
You have to override the `resignFirstResponder` method.
