### ISSUE TITLE
How to align text fields?

### ISSUE THREAD

**Issue by Tatsh** [xmartlabs/XLForm#123]
I would like to have the `UITextField` views (the `textField` property of `XLFormTextFieldCell`) in each row align at the same x position rather than being adjacent to the label.

I have tried using KVO `textField.frame` and `textField.bounds` with `CGRect` values (converted to NSValue), and overriding `-[tableView: cellForRowAtIndexPath:]`. Neither of these ways work.

Has no effect that I can see:
```objective-c
NSValue *rect = [NSValue valueForCGRect:CGRectMake(CONSTANT_X, /* rest of values */);

row = [XLFormRowDescriptor formRowDescriptorWithTag:name rowType:XLFormRowDescriptorTypeText];
[row setObject:rect forKey:@"textField.frame"];
```

**Comment by tobinharris** [comment]
+1

**Comment by calvinlai** [comment]
+1

**Comment by wm-j-ray** [comment]
+1

**Comment by sdsykes** [comment]
I find it helps to right align the values, at least it looks neater:

[row.cellConfig setObject:@(NSTextAlignmentRight) forKey:@"textField.textAlignment"];

**Comment by Lakhman** [comment]
Related #80 - I think it would be great to have more documentation on this, seems like a common question.

---

## Right aligning Text Field Text in XLForm

The screenshot below shows an example, the code is also commented.

![screen shot 2015-06-03 at 18 37 50](https://cloud.githubusercontent.com/assets/1582690/7967487/442dcd08-0a22-11e5-8a35-ce6cfa753a46.png)


    // Create a Dictionary with our "rightView" key values, these will be reused so we can't put a view in here
    NSDictionary *defaultValuesRight = @{
                                    @"textField.rightViewMode":@(UITextFieldViewModeAlways),
                                    @"textField.textAlignment":@(NSTextAlignmentRight)
                                    };

    // Text 1 - Right Align & NO Padding View
    row = [XLFormRowDescriptor formRowDescriptorWithTag:kName rowType:XLFormRowDescriptorTypeText title:@"Text 1:"];
    [row.cellConfigAtConfigure setObject:@"right align & no right padding view" forKey:@"textField.placeholder"];
    [row.cellConfigAtConfigure setValuesForKeysWithDictionary:defaultValuesRight];
    [section addFormRow:row];

    // Text 2 - Right Align & Right Padding View
    row = [XLFormRowDescriptor formRowDescriptorWithTag:kInternalIp rowType:XLFormRowDescriptorTypeText title:@"Text 2:"];
    [row.cellConfigAtConfigure setObject:@"right align & right padding view" forKey:@"textField.placeholder"];
    [row.cellConfigAtConfigure setValuesForKeysWithDictionary:defaultValuesRight];
    // Add our Right Padding view for "Text 2"
    [row.cellConfigAtConfigure setValue:[[UIView alloc] initWithFrame:CGRectMake(0, 0, 20, 20)]  forKey:@"textField.rightView"];
    [section addFormRow:row];

    // Text 3 - Left Align & Left Padding View
    row = [XLFormRowDescriptor formRowDescriptorWithTag:kInternalIp rowType:XLFormRowDescriptorTypeText title:@"Text 3:"];
    [row.cellConfigAtConfigure setObject:@"left align & left padding view" forKey:@"textField.placeholder"];
    // An example of putting it into a function (including a padding view as we need a new instance each time)
    [row.cellConfigAtConfigure setValuesForKeysWithDictionary:[self getLeftViewDefaults]];
    [section addFormRow:row];

    // A function which returns the default values,
    // We need a new instance of "paddingView" each time we "addFormRow"
    - (NSDictionary *)getLeftViewDefaults {
        // Create a new paddingView
        UIView *paddingView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 20, 20)];

        return @{
                @"textField.leftView": paddingView,
                @"textField.leftViewMode":@(UITextFieldViewModeAlways),
                @"textField.textAlignment":@(NSTextAlignmentLeft)
                };
    }

Hopefully this helps! ;)

**Comment by pastorin** [comment]
Hi everybody,

In the last commit (#472) support to change the UITextField length was added. It can be used to achieve the behaviour that you want. 
Let me know if you have any question.

Regards,
Martin

**Comment by elioscordo** [comment]
Hi, thanks for the work!
textViewLengthPercentage is still missing.
