### ISSUE TITLE
Selector uncheck

### ISSUE THREAD

**Issue by hellojjun99** [xmartlabs/XLForm#125]
![ios simulator screen shot 2014 9 4 3 12 38](https://cloud.githubusercontent.com/assets/8645624/4138985/4e55c488-3396-11e4-8681-7e133eaf78c0.png)

![ios simulator screen shot 2014 9 4 3 12 42](https://cloud.githubusercontent.com/assets/8645624/4138992/52aab232-3396-11e4-80be-229d4dd40ed3.png)

is impossible always checked?

**Comment by mtnbarreto** [comment]
@hellojjun99 fixed.
