### ISSUE TITLE
Set value for rowType:XLFormRowDescriptorTypeMultipleSelector doesn't refresh displayText

### ISSUE THREAD

**Issue by Darkpif** [xmartlabs/XLForm#126]
Hi,

I've used setValue on a row with rowType:XLFormRowDescriptorTypeMultipleSelector and the displayText hasn't refreshed.
But actually the value is correcly setted to the values in the array, and if I open the selector, the values are checked.

Regards,
Dom

**Comment by memmons-ntst** [comment]
That does not at all sound like expected behavior. A multi-select row should display the value once it's set without having to reload the table, like any other row type.
