### ISSUE TITLE
Height of section footer doesn't expand to contain contents

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#130]
Section footers are fixed to one-line of text rather than wrapping, shrinking the font and increasing the footer height. Are there attributes I can access to achieve this?

**Comment by mtnbarreto** [comment]
@carlhunterroach 

The only thing that XLForm does regarding header and footer is just returning the title as it shown below:

```obj-c
-(NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section
{
    return [[self.form.formSections objectAtIndex:section] title];
}

-(NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section
{
    return [[self.form.formSections objectAtIndex:section] footerTitle];
}
``` 

You can customize the header and footer views in the same way you do it in a generic tableView, either overriding the above methods or  implementing the relevant `UITableViewDelegate` methods to provide the header and footer views and calculate the heights.

Regards
