### ISSUE TITLE
Going back from a Push selector is painfully slow

### ISSUE THREAD

**Issue by jschmid** [xmartlabs/XLForm#132]
When you have a field that pushes a new view controller, it is noticeably slow to come back to the main form.

This happens only when cells with autolayout are shown. The demo project does not show the problem because it never has a mix between cells with autolayout and push cells.

To prove this, I just added a push field in `InputsFormViewController`. You can see [my branch](https://github.com/jschmid/XLForm/tree/hellaslow) with only [one commit](https://github.com/jschmid/XLForm/commit/7b084ca325ec31589d2821ac48e07861342a7e28).

I did my tests with an iPhone 4. Once you select a value, it takes **two seconds** to go back to the main form. See here in instruments:

![screen shot 2014-09-11 at 14 59 21](https://cloud.githubusercontent.com/assets/574168/4234106/865bad02-39b3-11e4-9557-a3ed4b5999b6.png)

This is caused because `reloadRowsAtIndexPaths` is called in `viewWillAppear`. ([here](https://github.com/xmartlabs/XLForm/blob/93a0c407adc1cfc2d80fcf5534ad2c853e7b4164/XLForm/XL/Controllers/XLFormViewController.m#L109-114))

If you remove this code and place it in `viewDidAppear` instead of `viewWillAppear`, the result is quite faster...

![screen shot 2014-09-11 at 15 04 21](https://cloud.githubusercontent.com/assets/574168/4234169/31bba49a-39b4-11e4-9211-b6d6d7450b01.png)

Of course you don't have the fancy animation, but the user won't break his phone screaming at your f*cking slow app. In my case, I recreated cells with autolayout to create my own design, and it take up to 7 seconds to go back... :disappointed:

What do you think ?

**Comment by mtnbarreto** [comment]
@jschmid Thanks for contributing!
https://github.com/jschmid/XLForm/commit/7f56820f93da807d6400b7fee7a296af989c3117#diff-5b96fc911294fdc37ea94cf013d06af9L111 line is also causing #217 #215  issues. I think it would be better to reload the entire table view instead of invoking the delegate method directly.
