### ISSUE TITLE
formValidationErrors for fields with no title displays "(null)"

### ISSUE THREAD

**Issue by silverh00d** [xmartlabs/XLForm#134]
Hi,

Right now, for rows without title, "(null)" will be used in the alert for `formValidationErrors`

Is there a way to
1. hide the title of the row if I set it? OR
2. Make the alert search for the placeholder when title is absent?

It does make sense to use the placeholder in place of the title, since the rows look nicer using placeholders rather than titles.

Any help or suggestion is greatly appreciated! =D

**Comment by mtnbarreto** [comment]
As @jasoncox said setting up `requireMsg` do the trick.

Regards
