### ISSUE TITLE
Validation after user has changed a field

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#136]
I'd like to validate when a UITextField loses focus or when a UISwitch changes value

I've read that a validation framework might be implemented but, until then, what approach could I use?

If I have an XLFormRowDescriptor how would I go about adding an observer for KeyValue changes? And is that a practical route for me?

**Comment by mats-claassen** [comment]
I believe this issue is pretty old and there is no answer needed but for any future readers: `XLFormViewController` has an `endEditing` which receives a `XLFormRowDescriptor`. You can identify your row descriptors with tags.
