### ISSUE TITLE
How to change row style

### ISSUE THREAD

**Issue by alyssabrookes** [xmartlabs/XLForm#139]
Hi folks

We want to change the style of the cells a little, can you give us any pointers on how to do this.

For example:

![image](https://cloud.githubusercontent.com/assets/6350298/4303854/378eedc6-3e6b-11e4-8aac-a156fc0cf70b.png)

This means changing the font color/style of the label, and moving the text field/input onto a new line etc.

Is there a way to do this without hacking the library?

Ta!

**Comment by oschobel** [comment]
Same here. How can I change fonts and colors? 
I made it work with buttons:
row = [XLFormRowDescriptor formRowDescriptorWithTag:kSaveButton rowType:XLFormRowDescriptorTypeButton title:@"Save"];
    [row.cellConfigAtConfigure setObject:[UIColor blackColor] forKey:@"backgroundColor"];
    [row.cellConfig setObject:[UIColor whiteColor] forKey:@"textLabel.color"];
    [row.cellConfig setObject:[UIFont fontWithName:@"Roboto-Light" size:18.0] forKey:@"textLabel.font"];

But the same codes shows no effect on textfields etc.

**Comment by mats-claassen** [comment]
For this special designs it is recommended to create custom rows. 
It is not really that complicated and you will get exactly what you want. You can obviously subclass one of XLForm's row descriptors.
