### ISSUE TITLE
TextField don't scroll when caret reaches right side of field

### ISSUE THREAD

**Issue by romanr** [xmartlabs/XLForm#140]
Create XLForm with:
```
[XLFormRowDescriptor formRowDescriptorWithTag:@"title" rowType:XLFormRowDescriptorTypeText];
```
When during editing caret reaches the end of field, the text does not scroll left and you end up typing "blindly". If you press backspace, the textField scrolls the end of text into view.

**Comment by mats-claassen** [comment]
I believe this is not happening anymore, right?

**Comment by cerupcat** [comment]
I'm seeing this happen still. Can anyone else confirm?

**Comment by mats-claassen** [comment]
How is your row set up? It cannot reproduce it in the examples

**Comment by cerupcat** [comment]
I ended up being an issue with font size. I had set a custom font to a size that caused this (I think it was 24px+). Lowering the size fixed it. Unfortunately, I didn't have the time to come up with a proper solution other than that.

**Comment by mats-claassen** [comment]
As you say that I remember to have seen this happening with a custom font. 
So in my opinion this is related to the fonts or UITextField but not really a XLForm issue. Do you agree?

**Comment by cerupcat** [comment]
Yeah, I'm not sure what causes this. It may be more related to custom font size. Either way, it's probably uncommon so it's fine to be closed.
