### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPush doesn't set 'value' after each selection

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#152]
I've set-up a XLFormRowDescriptorTypeSelectorPush row with 3 options [(0,"Male"),(1,"Female"),(2,"Not specified")] using an array of XLFormOptionsObject objects. I then set the row value to XLFormOptionsObject(value:1, displayText:"Male")

The row in the main table appears and the options slide into view fine. I can tap any option, a tick appears but when the view slides off screen the row in the main table isn't updated to reflect the change.

What might I be missing in setting this up? I can't see anytihng else in the example Objective C samples.

**Comment by iAmNaz** [comment]
There is no need to use a separate VC. Make sure the VC where the selector is is within a UINavigationController. I initially was not able to make XLFormRowDescriptorTypeSelectorPush work until I tried to embed the VC in a navcontroller and it worked. The selected values are returned or set to the field previously tapped/selected.
