### ISSUE TITLE
Text color issue

### ISSUE THREAD

**Issue by arsonik** [xmartlabs/XLForm#156]
Hi !

There is few color issue across the library
about maintaining definition trough cycle (select, deselect, change...)

here is my swift code 
```
let rowGender = XLFormRowDescriptor(tag: "gender", rowType: XLFormRowDescriptorTypeSelectorPickerViewInline, title: "I am")
rowGender.selectorOptions = ["a man", "a woman"]
rowGender.noValueDisplayText = "required"
rowGender.cellConfig.setObject(UIColor.purpleColor(), forKey: "textLabel.color")
section.addFormRow(rowGender)
```

Then when I pick a gender from the list, the cell label : "I am" which was purple,
come back to black because of that line (XLFormInlineSelectorCell.m)
```
-(void)update
{
    [super update];
    [...]
    self.textLabel.textColor  = self.rowDescriptor.disabled ? [UIColor grayColor] : [UIColor blackColor];
```

Can't we handle the disabled property in a different way than everytime update is called ?
so it apply the disabled color only when we specifically set the row to disabled ?
Would be great to have a setter for that color by the way :)

PS : No problem with XLFormRowDescriptorTypeDateInline who doesnt go trough update everytime !

Cheers

**Comment by mtnbarreto** [comment]
@arsonik it should be fixed. Take a look at master branch version.
We will be releasing a new pod version soon. 
Regards.
