### ISSUE TITLE
XLFormRowDescriptorTypeSelectorSegmentedControl with no title renders as a Line in iOS 7.1 (Seen in Example code).

### ISSUE THREAD

**Issue by PWani** [xmartlabs/XLForm#157]
XLFormRowDescriptorTypeSelectorSegmentedControl with no title renders as a squashed thin Line in iOS 7.1 (Happens in Example code as well if Title is set as below.).

    // Segmented Control
    XLFormRowDescriptor * row = [XLFormRowDescriptor formRowDescriptorWithTag:kSegmentedControl rowType:XLFormRowDescriptorTypeSelectorSegmentedControl title:@""];
    row.selectorOptions = @[@"Apple", @"Orange", @"Pear"];
    row.value = @"Pear";
    [section addFormRow:row];

**Comment by fwhenin** [comment]
Anybody find a fix to this? not sure why an empty string would throw this off

**Comment by RyanBertrand** [comment]
I fixed it by adding a default height for the cell.

```
+(CGFloat)formDescriptorCellHeightForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor
{
    return 44.0f;
}
```
