### ISSUE TITLE
XLFormRowDescriptorTypeDateInline cell doesn't expand and DatePicker doesn't appear

### ISSUE THREAD

**Issue by ReDetection** [xmartlabs/XLForm#170]
I've just did this from README example and watched date cell become blue (tint), but no datepicker appeared. Without inline option datepicker appears from bottom as expected.
```Swift
    override func viewDidLoad() {
        super.viewDidLoad()

        let form = XLFormDescriptor .formDescriptorWithTitle("Add Event")
        var section: XLFormSectionDescriptor
        var row: XLFormRowDescriptor
        
        // First section
        section = XLFormSectionDescriptor()
        form.addFormSection(section)
        
        row = XLFormRowDescriptor(tag: "When", rowType: XLFormRowDescriptorTypeDateInline, title: "When:")
        row.value = NSDate()
        section.addFormRow(row)
        
        // Title
        row = XLFormRowDescriptor(tag: "Reason:", rowType: XLFormRowDescriptorTypeText)
        section.addFormRow(row)
        
        self.form = form
    }
```
OS X 10.10.1 (14B25) 
Xcode Version 6.0 (6A313)
iOS Simulator Version 8.0 (550.1)

**Comment by ReDetection** [comment]
@mats-claassen please tell a reason why did you closed the issue. It's now working without any workaround? (sorry @HanseThommy, your workaround is great and I used it but I can't say it's a solution)

**Comment by mats-claassen** [comment]
Hi, I closed this because this is working in iOS 9 and 8.4 from XCode 7 with the same code posted above.
If you should be working with an older version and it does not work then we can reopen it.
