### ISSUE TITLE
Custom text color for XLFormRowDescriptorTypeSelectorPush option cells?

### ISSUE THREAD

**Issue by PhilJay** [xmartlabs/XLForm#173]
Is it possible to set a custom text color for the predefined cells used to display the various selection options when using `XLFormRowDescriptorTypeSelectorPush`?

Or do I have to create a custom cell myself?

**Comment by ciponthenet** [comment]
I think this is what you are looking for:
`[row.cellConfigAtConfigure setObject:[UIColor redColor] forKey:@"detailTextLabel.textColor"]`

**Comment by PhilJay** [comment]
Thanks :-)
