### ISSUE TITLE
Rows disappear after scroll

### ISSUE THREAD

**Issue by binho** [xmartlabs/XLForm#175]
Hi,
I'm creating a form and when I scroll the form the rows disappear :(

Code sample:

``` objc
- (instancetype)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil {
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        [self initializeForm];
    }
    return self;
}

- (id)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        [self initializeForm];
    }
    return self;
}

- (void)initializeForm {
    XLFormDescriptor *form = [XLFormDescriptor formDescriptorWithTitle:@"Recipientes"];
    XLFormRowDescriptor *row;

    form.assignFirstResponderOnShow = NO;

    XLFormSectionDescriptor *section = [XLFormSectionDescriptor formSection];
    [form addFormSection:section];

   // ... add some rows in section

   self.form = form;
}
```

Animated gif of the problem:
http://cl.ly/image/1n2m232o0C15

I'm using version 2.1.0 (via Cocoapods) and already tried using from master branch.

Affected devices:
iPad & iPhone (Simulator and Device) - iOS 7 & 8

Thanks! :+1:

**Comment by IvanDev** [comment]
Had similar issue with row disappearing on storyboard. Turns out tableview was duplicated by XLFormViewController.
So I assigned tableview in storyboard to controller tableview outlet and removed this code from XLFormViewController viewDidLoad (you can just override viewDidLoad):
```
if (!self.tableView.superview){
        [self.view addSubview:self.tableView];;
    } 
```
