### ISSUE TITLE
Number Formatting

### ISSUE THREAD

**Issue by dformoso** [xmartlabs/XLForm#176]
Is there a quick way to have as-you-type number formatting?

The idea is to have the String 100, represented as $100.00, and to have it change to $1,000.00 as you type that extra zero on the integer field.

I know I can format an integer like this:

            var numberFormatter = NSNumberFormatter()
            numberFormatter.numberStyle = NSNumberFormatterStyle.CurrencyStyle
            var number = numberFormatter.stringFromNumber((value!.description as NSString).integerValue)
            return number!

But I don't know whether I can apply that to... a transformer?, and/or how.

Thanks for the help!
Dan.

**Comment by ziogaschr** [comment]
+1

I need that feature to format phone numbers.
I had this implemented in a UIViewController using the UITextFieldDelegate. Although I don't know where to place similar functionality in XLForms.

I have tried **formRowDescriptorValueHasChanged** with some hacks, but still when I am updating the formRow the keyboard closes and the endEditing is being called.

```swift
    func formRowDescriptorValueHasChanged(formRow: XLFormRowDescriptor!, oldValue: AnyObject!, newValue: AnyObject!) {
        
        // hack to stop reprocessing the changed field when we change the .value below
        if skipPhoneNumberUpdate {
            skipPhoneNumberUpdate = false
            return
        }
        
        if formRow.tag == Fields.Phone.rawValue {
            skipPhoneNumberUpdate = true

            formRow.value = typeFormatter?.inputStringAndRememberPosition(newValue)
            
            // reload row in view so as changes will be shown to user
            self.reloadFormRow(formRow)
        }
    }
```

**Comment by fwhenin** [comment]
I just created a pull request to apply any type of Number Formatter...there's an example in there for phone numbers...https://github.com/xmartlabs/XLForm/pull/195

**Comment by ziogaschr** [comment]
That's great @fwhenin. I was just looking the pull request by @bhirt-bpl and was thinking to bring it inline with the current master. Thanks a lot you've done that.

It was just in time.
