### ISSUE TITLE
Whats the problem Descriptor

### ISSUE THREAD

**Issue by marinofaggiana** [xmartlabs/XLForm#177]
```
XLFormButtonCell *buttonChangeCartella = (XLFormButtonCell *)[[self.form formRowWithTag:@"cartella"] cellForFormController:self];
buttonChangeCartella.rowDescriptor.title = @"Home";
[buttonChangeCartella.rowDescriptor.cellConfig setObject:@(NSTextAlignmentLeft) forKey:@"textLabel.textAlignment"];
[buttonChangeCartella.rowDescriptor.cellConfig setObject:@(UITableViewCellAccessoryDisclosureIndicator) forKey:@"accessoryType"];
[buttonChangeCartella update];
```

I have write this code for changed the title at XLFormRowDescriptorTypeButton with :@(NSTextAlignmentLeft) forKey:@"textLabel.textAlignment" and @(UITableViewCellAccessoryDisclosureIndicator) forKey:@"accessoryType". The title changed but loses formatting and disclosure Indicator; I tried to reset them as code but does not work .... why ?

**Comment by mats-claassen** [comment]
This is a very old question so it is probably not needed anymore but I think the issue lays in that you should not call `update` on that cell directly but rather call `reloadRowAtIndexPath` on your tableView.
