### ISSUE TITLE
Crash when trying to set returnKeyType on UITextField

### ISSUE THREAD

**Issue by pmaccamp** [xmartlabs/XLForm#180]
Hopefully this isn't a stupid question, but I couldn't figure out how to set the returnKeyType.

Calling
    [row.cellConfigAtConfigure setObject:@(UIReturnKeyDone) forKey:@"textField.returnKeyType"];
leads to
 '[<UITextField 0x7fbc816dfbe0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key returnKeyType.'

Is this key just not exposed to the cell's setValue:forKey: method?

Thanks for the great library,
Patrick

**Comment by pmaccamp** [comment]
Thanks @afnan-ahmad for the workaround.  It would still be nice to use cellConfig to avoid having to check tags on textfields each time they begin editing.

**Comment by bladev2** [comment]
Hi, just bumping this as it's still relevant as of today on master :(

**Comment by sao101** [comment]
@bladev2 do you have an example of that working with `@"returnKeyType"`

`[row.cellConfigAtConfigure setObject:@(UIReturnKeyDone) forKey:@"returnKeyType"];`

I'm getting the same non KVO compliant issue with

    XLFormRowDescriptor *row = nil;

   row = [XLFormRowDescriptor formRowDescriptorWithTag:@"myTag"
                                                rowType:XLFormRowDescriptorTypeTextView
                                                  title:@"Info:"];

Note: rowType = `XLFormRowDescriptorTypeTextView`

**Comment by bladev2** [comment]
Example of current workaround using the `setObject:` selector:

    row = [XLFormRowDescriptor formRowDescriptorWithTag:@"name" rowType:XLFormRowDescriptorTypeName];
    [row.cellConfigAtConfigure setObject:@"New Client" forKey:@"textField.placeholder"];
    [row.cellConfig setObject:[UIFont systemFontOfSize:30] forKey:@"textField.font"];
    // Workaround
    [row.cellConfigAtConfigure setObject:@(UIReturnKeyNext) forKey:@"returnKeyType"];
    [section addFormRow:row];
