### ISSUE TITLE
XLFormDescriptor.h: Default initialization of an object of const type 'NSString *const __strong'

### ISSUE THREAD

**Issue by maarcosd** [xmartlabs/XLForm#190]
Hi guys,

I have a project which most of its code is written in Swift, but there is some Objective-C and C++ as well. 

I use XLForm in only one view controller, which until now was in ObjC but needs to be ported to Swift. Once I switched it to Swift (added XLForm to the bridging header and rewrote the code) I started getting the following error on line 31 of the file `XLFormDescriptor.h`

`XLFormDescriptor.h:31:18: Default initialization of an object of const type 'NSString *const __strong'`

Is it something wrong with my project or just a bug with ObjC++?

I'm on Xcode 6.1.1

Thanks!

**Comment by mtnbarreto** [comment]
@maarcosd 
Should be already fixed. I've tested it from a swift project (master branch code) and it works properly. 
Is the issue still happening for you?

Regards
