### ISSUE TITLE
Feature Req: XLFormOptionsViewController keeping at least one value selected

### ISSUE THREAD

**Issue by jpmhouston** [xmartlabs/XLForm#192]
I'd like a way to specify to `XLFormOptionsViewController` that it should enforce at least one row selected, doing nothing when the only / last selected row is tapped instead of deselecting it. Would the way to do this be to make another row descriptor type, like there's one for allowing multiple selection?

In fact, I guess this would mean 2 more types, one behaving mostly like `TypeSelectorPush` another like `TypeMultipleSelector`. Or would it be 4 more, with others like `TypeSelectorPopover` and `TypeMultipleSelectorPopover`? This is starts to get rather unruly, is anyone planning another mechanism to specify a subtype, or option flags?

**Comment by RyanBertrand** [comment]
You can make a subclass of XLFormOptionsViewController which you implement the logic for selecting minimum X options.  Then set the selectorControllerClass property on that rowDescriptor to be your subclass which will open your subclass instead of the default (XLFormOptionsViewController).

**Comment by mats-claassen** [comment]
Push selector has this functionality now.

For multiple selector, I believe that this is a rather custom approach and should be implemented subclassing XLFormOptionsViewController as @RyanBertrand mentioned.
