### ISSUE TITLE
hi,how i reset the form values?

### ISSUE THREAD

**Issue by wengfujia** [xmartlabs/XLForm#193]
hi,i want to reset the form values.how to do ?thank you.

**Comment by nefarianblack** [comment]
@wengfujia did you find any solution to this. I am stuck at the same situation.

I have a date field which selects date from UIPickerView. But when user selects the date, there is not way to deselect it. @wengfujia : Do you have a solution for this?

Thanks

**Comment by silverh00d** [comment]
Try this:
> self.form.formRowWithTag("whatever-your-tag-name-is").value = nil
> self.tableView.reloadData()

Key is to reload `UITableView`

**Comment by skarctop** [comment]
i want to reset all values  

      [self.tableView reloadData];

but this not useful

**Comment by noelhunter** [comment]
I use this, which I modified from the form validation code.  It could use some improvement, but it does clear all values:

`-(void)clearForm:(UIBarButtonItem *)buttonItem
{
    NSMutableDictionary * result = [NSMutableDictionary dictionary];
    for (XLFormSectionDescriptor * section in self.form.formSections) {
        if (!section.isMultivaluedSection){
            for (XLFormRowDescriptor * row in section.formRows) {
                if (row.tag && ![row.tag isEqualToString:@""]){
                    row.value=nil;
                }
            }
        }
        else{
            NSMutableArray * multiValuedValuesArray = [NSMutableArray new];
            for (XLFormRowDescriptor * row in section.formRows) {
                if (row.value){
                    row.value=nil;
                }
            }
            [result setObject:multiValuedValuesArray forKey:section.multivaluedTag];
        }
    }
    [self.tableView reloadData];
}
`
