### ISSUE TITLE
hi,how i to use the selectorControllerClass in swift?

### ISSUE THREAD

**Issue by wengfujia** [xmartlabs/XLForm#194]
thank you!

**Comment by ageorgios** [comment]
I also have problems with selectorControllerClass
I use:
row.selectorControllerClass = CommandsTableViewController.self;
where CommandsTableViewController is defined in a storyboard and properly registered but I get:
'unable to dequeue a cell with identifier command - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'

**Comment by mats-claassen** [comment]
Sorry for no response. I am closing this issue as it is very old. If somebody still has this question feel free to reopen.
