### ISSUE TITLE
Update Footer Title

### ISSUE THREAD

**Issue by fwhenin** [xmartlabs/XLForm#196]
How can I change the footer title Dynamically at run time?

**Comment by RyanBertrand** [comment]
Set the section.footerTitle to your new value then reloadData on your UITableView.

**Comment by mtnbarreto** [comment]
:+1:   Depending on your needs, you can opt for only reload the relevant section instead.

**Comment by MuscleRumble** [comment]
Is there any particular reason why there are no equivalents of `indexPathOfFormRow:` and `reloadFormRow:` for sections? I mean, it's easy and fine to do that with `UITableView`'s methods, but I'm still curious...
