### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPickerViewInline needs to close before dismissing controller

### ISSUE THREAD

**Issue by ageorgios** [xmartlabs/XLForm#198]
If you         self.presentingViewController?.dismissViewControllerAnimated(true, completion: nil)
before closing the inline pickerview it crashes

**Comment by kleiram** [comment]
Just ran into the same issue with a `XLFormRowDescriptorDateTimeInline` field. Very weird.

**Comment by mtnbarreto** [comment]
@ageorgios @kleiram 
Thanks for the issue report. 
It should be fixed on master branch. 
Regards
