### ISSUE TITLE
Issue with IQKeyboardManager and Selector Types

### ISSUE THREAD

**Issue by fwhenin** [xmartlabs/XLForm#199]
I'm using XLForm and IQKeyboardManager. running into an issue where the toolbar provided by IQKeybaordManager doesn't show up when Selector Type field is set. works fine with TextFields, not Selector

**Comment by mtnbarreto** [comment]
@fwhenin take a look at master branch. We have implemented our field navigation solution. We also added an example showing how to configure the toolbar, in particular how to navigate among fields and make toolbar visible/hidden.  
You can opt for our solution or keep using IQKeyboardManager.

Regards.
