### ISSUE TITLE
UIKeyboardTypeDecimalPad - XLFormRowDescriptorTypeText

### ISSUE THREAD

**Issue by marinotws** [xmartlabs/XLForm#200]
Is possible use XLFormRowDescriptorTypeText with UIKeyboardTypeDecimalPad or UIKeyboardType.. etc ?

**Comment by smebberson** [comment]
Have you tried `XLFormRowDescriptorTypeDecimal`?

This is from the README:

---
```
static NSString *const XLFormRowDescriptorTypeDecimal = @"decimal";
```
Will be represented by a UITextField with UIKeyboardTypeDecimalPad.

---

**Comment by mtnbarreto** [comment]
@marinotws you can but you will get a `string` value and not a decimal. I mean row.value will contains a string.

This section explains how to configure the cell: https://github.com/xmartlabs/XLForm#additional-configuration-of-rows

**Comment by mtnbarreto** [comment]
@smebberson :+1:
