### ISSUE TITLE
Setting VC  row.buttonViewController In swift

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#204]
I can't set my VC as  row.buttonViewController because it gives the error, "VC" is not convertible to 'AnyClass'

**Comment by mtnbarreto** [comment]
@focusedonfit  i think you should use `ViewController.self` instead.

```swift
let row2 = XLFormRowDescriptor(tag: "button", rowType: XLFormRowDescriptorTypeButton, title: "Button");
row2.action.viewControllerClass = ButtonViewController.self;
section.addFormRow(row2); 
```

Take a look at meta tags section: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Types.html

Regards
