### ISSUE TITLE
XLFormRegexValidator only checks regex validation not working for number.

### ISSUE THREAD

**Issue by aksswami** [xmartlabs/XLForm#206]
XLFormRegexValidator only checks regex validation checks for [XLFormRowDescriptor.value class] == "NSString" 

So this only works for text, textViews. In case of number Regex validator not working because of this code in XLFormRegexValidator

```
-(XLFormValidationStatus *)isValid: (XLFormRowDescriptor *)row {
    if (row != nil && row.value != nil &&  [row.value isKindOfClass:[NSString class]]) {
        // we only validate if there is a value
        // assumption: required validation is already triggered
        // if this field is optional, we only validate if there is a value
        if (row.value != nil && [row.value length] > 0) {
            BOOL isValid = [[NSPredicate predicateWithFormat:@"SELF MATCHES %@",self.regex] evaluateWithObject:[row.value stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]]];
            
            return [XLFormValidationStatus formValidationStatusWithMsg:self.msg status:isValid];
        }
    }
    
    return nil;
};

```

In above we need to also check for other property type like numbers etc.

**Comment by mtnbarreto** [comment]
@aksswami `XLFormRegexValidator` is just a concrete class to validate strings. What matters is that you can create your own validators by conforming `XLFormValidatorProtocol` protocol. 

Anyway i made the changes to convert the NSNumber to NSString. I also added a example of a integer validation.

Regards
