### ISSUE TITLE
having trouble implementing formOptionsOptionForDisplayText:fromOptions

### ISSUE THREAD

**Issue by nspcr** [xmartlabs/XLForm#210]
I tried creating an array and filling in the method like this 

NSArray *choices = @[@"one", @"two"];
row.selectorOptions = @[[XLFormOptionsObject formOptionsOptionForDisplayText:@"one"
                                                                    fromOptions:choices]];

this is just a sample, not my actual code.

The app keeps crashing. How do I implement this method?

**Comment by mats-claassen** [comment]
The choices array should be of `XLFormOptionsObject` instances and not Strings.
