### ISSUE TITLE
Change UIDatePicker format

### ISSUE THREAD

**Issue by depl0y** [xmartlabs/XLForm#211]
I am implementing XLFormRowDescriptorTypeDateTimeInline in my form, and I have changed the way the date is formatted in the cell itself, but I would like to change the format of the UIDatePicker as well.

```
row = XLFormRowDescriptor(tag: "task_start", rowType: XLFormRowDescriptorTypeDateTimeInline, title: NSLocalizedString("TASK_START_TIME", comment: "Task start time"));
row.value = NSDate();
row.cellConfigAtConfigure.setObject(NSDate.dateFormatter(), forKey: "dateFormatter");
timeSection.addFormRow(row);
```

This changes the format for showing the date in that cell, but when the UIDatePicker appears, it still shows AM/PM and a 12 hour clock. Can you give me hint on how to change the format of the UIDatePicker also?

The locale of my iOS simulator is set to "The Netherlands" and in the calendar app (on the simulator) it shows the datepicker with a 24 hour format.

**Comment by RyanBertrand** [comment]
Have you tried setting the locale on the datePicker in the cell?  Untested objective-c below

[row.cellConfigAtConfigure setObject:[NSLocale systemLocale] forKey: "locale"];

**Comment by depl0y** [comment]
Yup, I did, but it seems that my iOS simulator does not respect my settings completely. Once the app is transferred to my iOS device, it works as expected.

So, I better close this.
