### ISSUE TITLE
Wierd pushing 

### ISSUE THREAD

**Issue by f33chobits** [xmartlabs/XLForm#217]
Hey, @martinnormark 
    This lib has better effect than the FXForms, especially the inlineDate part. But I recently found that when a table row is selected and push another controller for optional values, the tableView reset the contentOffset when the pushing animation is running. So is this a bug or an intentional design?

**Comment by martinnormark** [comment]
I don't know. I've only used XLForm a couple of times, and it's great.

It seems you think I'm the owner of the repo - I'm not :smile: 

Maybe @mtnbarreto can help you on this one?

**Comment by f33chobits** [comment]
Sorry I muddled up your names......

**Comment by mtnbarreto** [comment]
@f33chobits thanks for reporting the bug!
It's fixed on master branch now.

Regards
