### ISSUE TITLE
Need to label each row in a multivaluesection by index path when removing rows

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#220]
Each one of my rows should be labeled by number (first row 1, second row 2, etc) I'm setting a label.text with indexPath + 1, however when I remove a row, the cells don't get updated. Is there a way to accomplish this without hacking the library? 

Thank you

**Comment by timshim** [comment]
Hey, I've been trying to figure out how to increment the row titles. How did you go about doing it? I'm not sure what you mean by setting a label.text with indexPath + 1.

**Comment by focusedonfit** [comment]
I haven't found a solution yet. With a standard section with rows, you can get the indexPath.row which will be 0 - how many number rows you have. Then you could add 1 to get a numbered list 1-x.

**Comment by focusedonfit** [comment]
I was able to override formRowHasBeenAdded and get the desired result
 override func formRowHasBeenAdded(formRow: XLFormRowDescriptor!, atIndexPath indexPath: NSIndexPath!) {
       
             formRow.title = "Set \(indexPath.row + 1)"
    
       
        super.formRowHasBeenAdded(formRow, atIndexPath: indexPath)
  }
