### ISSUE TITLE
Support for AutoLayout & multiple columns?

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/XLForm#223]
Is it possible to have multiple columns and AutoLayout them as with UICollectionView?
So we're able to dynamically adjust the layout based upon the orientation & the device?

**Comment by mtnbarreto** [comment]
@marbetschar The answer is no. XLForm provides a table-based way to create forms. XLForm main view is a UITableView and each row is translated to UITableViewCell representation. 

Regards
