### ISSUE TITLE
formRowDescriptorValueHasChanged + Modify formRow.value

### ISSUE THREAD

**Issue by gltiich** [xmartlabs/XLForm#231]
This is what I'm trying to accomplish;
```
-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)formRow oldValue:(id)oldValue newValue:(id)newValue {
    if([frmRow.tag isEqualToString@"myfield"]) {
        NSString * evenMoreNewValue = [[NSString alloc] initWithFormat:@"Hi %@ !", newvalue];
        formRow.value = evenMoreNewValue;
        // this updatge triggers this method call again, infinitely, which I could probably prevent by checking for oldValue == newValue.
    }
}
```
However, the value of formRow never actually changes in the view. Very frustrating, I really need to be able to modify the text field as the user is providing input (to enforce certain constraints on-the-fly).

So I hacked something together that basically does the job, just not very well;
```
//...
@property NSString * theValue;
//...
-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)formRow oldValue:(id)oldValue newValue:(id)newValue {
    if([frmRow.tag isEqualToString@"myfield"]) {
        NSString * evenMoreNewValue = [[NSString alloc] initWithFormat:@"Hi %@ !", newvalue];
        XLFormTextFieldCell *cell = (XLFormTextFieldCell*)[formRow cellForFormController:self];
        cell.textField.text = evenMoreNewValue;
        self.theValue = evenMoreNewValue;
        // at least this doesn't trigger the formRowDescriptorValueHasChanged method again
        // probably because I'm bypassing XLFormRowDescriptor 
    }
}
```
This worked! BUT the value of the XLFormRowDescriptor doesn't actually change, only the value of the textField behind the XLFormRowDescriptor. So the downside is now I have to read the 'value' for this field via a globally defined property.

This basically sucks, but works, which sucks. I've searched around and dug through the example code, I just can't find any example of how this is supposed to work... is this a limitation of XLForms or am I missing something?

**Comment by jkereako** [comment]
You're trying to bend XLForm to your will.

> I really need to be able to modify the text field as the user is providing input (to enforce certain constraints on-the-fly)

Do you need to perform validation in real-time, or can you wait until the user taps "Save"?

If you must validate in real time, do you need to overwrite the user's input, or can you display a message to the user explaining that the input is invalid?

The behavior you're trying to accomplish is unusual. When the user enters in information, he doesn't his input to automatically change on him. And, as you've already experienced, writing code to deal with this behavior is pretty difficult.

**Comment by gastonborba** [comment]
@gltiich 
If you want to update the cell you should call `reloadFormRow`, this is an example:

```objc
row = [self.form formRowWithTag:kRowTag];
[row setDisabled:YES];
[self reloadFormRow:row];
```

**Comment by mtnbarreto** [comment]
@gltiich 

XLForm will call `-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)formRow oldValue:(id)oldValue newValue:(id)newValue` each time `XLFormRowDescriptor` value is changed. 

if the value you want to assign is the same as the current row value, do not assign it. In case you assign a new NSString the method will be invoked again since is a different string instance.

Whenever you want to reload the cell you should follow @gastonborba suggestion:

```objc
row = [self.form formRowWithTag:kRowTag];
[row setDisabled:YES];
[self reloadFormRow:row];
``` 

these 3 lines of code will result in a view update.

Regards

**Comment by hamedmohammadi** [comment]
@mtnbarreto 
reloadrow cause keyboard to resign .how to cope with this problem

**Comment by mats-claassen** [comment]
You could reassign first responder after that.
