### ISSUE TITLE
Add header to optionsViewController when using XLFormRowDescriptorTypeMultipleSelector

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#236]
I would like to add some text, perhaps in a header above my XLFormRowDescriptorTypeMultipleSelector options. Is there a way to add some text here, or could an option to add a title or header be added?
Another option would be a way to disable a row in a row.selectorOptions

Thank you

**Comment by mats-claassen** [comment]
You can use `rowDescriptor.action.viewControllerClass`, `rowDescriptor.action.viewControllerNibName` or `rowDescriptor.action.viewControllerStoryboardId` to use a custom view controller for that row. Then you can add that header to its sections
