### ISSUE TITLE
Duplicate and misplaced section headers

### ISSUE THREAD

**Issue by vIiRuS** [xmartlabs/XLForm#237]
Hey,

I'm having a problem with one of my forms. With XLForm 2.0 it worked fine, but now with 2.1 it looks strange. Each section header is there twice and with each section it gets more and more misplaced (see attached screenshot)
I already tried removing anything unneeded from the form and only having the bare minimum, but there are still always two headers.

![screen shot 2015-02-21 at 14 27 26](https://cloud.githubusercontent.com/assets/298062/6314212/41ad20ca-b9d6-11e4-9182-160b317de1f0.png)

**Comment by mtnbarreto** [comment]
@vIiRuS Have you tried using master branch? 
Does you check you have not wrongly added twice the section description?

If nothing works, please create a public repository reproducing the issue so i can look into it. I also need to know the ios version you are using.

Thanks

**Comment by carlhunterroach** [comment]
Are you using a Storyboard?

I had duplicate section headings because I had a UITableView in my Storyboard. Removing the UITableView from the Storyboard removed the duplicate headings.

**Comment by mtnbarreto** [comment]
@vIiRuS @carlhunterroach It seems to me that it may be something wrongly set up on the storyboard.
Could you check if you have two table views in the view hierarchy?

The steps to use it through storyboard are:

1. Drag out a UIViewController (not a UITableViewController)
2. Set up the custom view controller. it must extend XLFormViewController.
3. Put a UITableView inside main view of view controller recently added.
4. Connect UITableView outlet (There is a tableView property within XLFormViewController to do so).
5. Optionally (not needed) connect UITableView dataSource and delegate's outlets.

Please make sure you are following these steps. 

Regards

**Comment by mtnbarreto** [comment]
@vIiRuS  i think it would be related with #248

**Comment by vIiRuS** [comment]
I finally got around to test this.
I originally had a UITableView for my settings view (as I wasn't using XLForm in the beginning), so there still was a tableview in there. Not sure why it worked without a problem in 2.0, but I removed the Tableview from the UIViewcontroller and now it works fine. So now I have a UIViewController extending my SettingsViewController class (which is a subclass of XLFormViewController) that does not have a tableview in it.

Sorry for the apparently unnecessary Issue

**Comment by amadeu01** [comment]
I'm having the problem, but I do not have a tableview in the storyboard. And, I'm not using storyboards in this project.

![IMG_4E59B0DD8762-1](https://user-images.githubusercontent.com/11631092/55994875-57832c00-5c89-11e9-9a31-1a414c533570.jpeg)
