### ISSUE TITLE
How to change height of XLFormRowDescriptorTypeMultipleSelector options

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#239]
I have changed the height of the form row to 60 and I want the same height of each option row when its pushed over to the XLFormRowDescriptorTypeMultipleSelector view.  

How can this be achieved?
Thank you

**Comment by zhjuncai** [comment]
You could subclass XLFormLeftRightSelectorCell for example and only change the auto layout constraints to change the row height.

**Comment by focusedonfit** [comment]
My app is in Swift. I tried to subclass XLFormOptionsViewController but I can't access any of the methods of the super. I always can't access the properties either but could get the values using KVC. I'm not sure why my swift subclass can't access self.<methodname>
