### ISSUE TITLE
Swift

### ISSUE THREAD

**Issue by ptdenovo** [xmartlabs/XLForm#240]
How do you translate this to swift code ?

 row.selectorOptions = @[[XLFormOptionsObject formOptionsObjectWithValue:@(0) displayText:@"Never"],
        [XLFormOptionsObject formOptionsObjectWithValue:@(1) displayText:@"Every Day"],
        [XLFormOptionsObject formOptionsObjectWithValue:@(2) displayText:@"Every Week"],
        [XLFormOptionsObject formOptionsObjectWithValue:@(3) displayText:@"Every 2 Weeks"],
        [XLFormOptionsObject formOptionsObjectWithValue:@(4) displayText:@"Every Month"],
        [XLFormOptionsObject formOptionsObjectWithValue:@(5) displayText:@"Every Year"],
        ];

tried to do this, but it crashes

        row.selectorOptions = [
            XLFormOptionsObject.formOptionsOptionForDisplayText("Daily", fromOptions: [0]),
            XLFormOptionsObject.formOptionsOptionForDisplayText("Weekly", fromOptions: [1]),
            XLFormOptionsObject.formOptionsOptionForDisplayText("Monthly", fromOptions: [2])]

**Comment by ptdenovo** [comment]
Anyone here ??

**Comment by focusedonfit** [comment]
try this
row.selectorOptions = [XLFormOptionsObject(value:0, displayText:"Daily"), 
            XLFormOptionsObject(value:1, displayText:"Weekly"),
            XLFormOptionsObject(value:2, displayText:"Monthly"),
        ]

**Comment by ptdenovo** [comment]
Great! Thanks!

**Comment by zhjuncai** [comment]
```
row.selectorOptions = field.options?.map({XLFormOptionsObject(value: $0.value, displayText: $0.displayText)})
```
My line of code transform an array of struct object to selectorOptions, hope that helps

**Comment by Asinox** [comment]
I know this is closed but @zhjuncai  what is "field.options?" ?, from where that came?
