### ISSUE TITLE
UITextField placeholder text color

### ISSUE THREAD

**Issue by VrasidasP** [xmartlabs/XLForm#241]
Hello,
is there a way to customize the placeholder text color of a UITextField? I have tried changing the value for @"textfield.placeholderColor" but it crashes, this key must not exist.

Normally you would do it like this:

    NSDictionary *attributesDict = @{ 
    NSForegroundColorAttributeName : [UIColor blueColor],
    NSFontAttributeName :  [UIFont fontWithName:@"Helvetica" size:17]
     };

     NSAttributedString *string = [[NSAttributedString alloc] initWithString:@"Enter your email here"
                                                              attributes:attributesDict];
    emailField.attributedPlaceholder = string;

What is the XLForm equivalent?
Thanks!

**Comment by mtnbarreto** [comment]
@VrasidasP 
```objc
XLFormRowDescriptor * row = ......
NSAttributedString *string = ....
[row.cellConfig setObject:string forKey:@"textField.attributedPlaceholder"];
```
Hope it helps!

**Comment by VrasidasP** [comment]
Thank you very much mtnbarreto!
It works fine with that.
:)

**Comment by negry** [comment]
row.cellConfig.setObject(UIColor.whiteColor(), forKey: "self.textField.attributedPlaceholder")
 this is not working for me

**Comment by mats-claassen** [comment]
@negry You have to set an attributed string and not a color to the attributed placeholder
