### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPickerViewInline no longer works with latest Swift 1.2 

### ISSUE THREAD

**Issue by elprl** [xmartlabs/XLForm#242]
Using the latest Xcode 6.3 beta 2 with Swift 1.2 my XLForms have stopped working - specifically the inline types now don't drop down. Anyone else seeing this?

**Comment by mtnbarreto** [comment]
@elprl Let me know if my comment on #244 helps to solve the issue.

Regards

**Comment by elprl** [comment]
It did solve it, thanks.
