### ISSUE TITLE
Ambiguous table view cell configuration

### ISSUE THREAD

**Issue by jkereako** [xmartlabs/XLForm#246]
# Issues
1. **The properties [`cellConfig ` and `cellConfigAtConfigure `](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Descriptors/XLFormRowDescriptor.h#L53-L54) are identical in type and purpose.**
2. **The method  [`configureCellAtCreationTime`](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Descriptors/XLFormRowDescriptor.m#L90-L95) is needless.** The delegate method [`tableView:tableView cellForRowAtIndexPath:`](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.m#L437-L439) has the same logic as `configureCellAtCreationTime`, except it references the property `cellConfig` instead of `cellConfigAtConfigure`.

Because the table views for all XLForms are dynamic, it's guaranteed that `tableView:tableView cellForRowAtIndexPath:` will be invoked.

# Solution
Remove the property `cellConfigAtConfigure` and the method `configureCellAtCreationTime` and all references to either. I'll create a pull request for this.

**Comment by mtnbarreto** [comment]
@jkereako 

The properties  `cellConfig ` and `cellConfigAtConfigure ` are completely different. There are some scenarios in which no matter which method you use you will get the same result.

`cellConfigAtConfigure` is used right after [[cell alloc] init] is invoked ( [take a look here](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Descriptors/XLFormRowDescriptor.m#L76) ), once per UITableViewCell.
`cellConfig` is used from inside `tableView:cellForRowAtIndexpath:` method, each time the cell will be shown.  

Based on that, `cellConfig` gives us the ability to override properties that are set up from [update method](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormBaseCell.m#L57) and configure the cell properties based on context values (for example the value of another row).

`cellConfigAtConfigure` give us the ability to set up a property only once at memory allocation time. All the properties that are not set up in the update method can be set up using `cellConfigAtConfigure`

Regards

**Comment by jkereako** [comment]
@mtnbarreto 

Thank you for the reply. I have some comments:

> The properties cellConfig and cellConfigAtConfigure are completely different. There are some scenarios in which no matter which method you use you will get the same result.

[Here is an example of that.](https://github.com/xmartlabs/XLForm/blob/1ed3f016c7e396d0a7a904f52f2455d07ca82219/Examples/Objective-C/Examples/UICustomization/UICustomizationFormViewController.m#L49-L57).

Why is `cellConfigAtConfigure` used to configure the background while other properties reference `cellConfig`? You can swap one property for the other and still get the same result.

Also, because each row maintains its own copy of `cellConfig` and `cellConfigAtConfigure`, why are the dictionaries mutable? Why not have a writable property of type `NSDictionary` instead?

**Comment by mats-claassen** [comment]
@jkereako while it is true that sometimes you can swap one for the other and get the same result, there are cases where having both of them is useful.
