### ISSUE TITLE
Losing rows when flipping back and forth in UITabeBarController

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#248]
I have "ProfileViewController" derived from XLFormViewController and XLFormDescriptorDelgate

This is one tab in a UITabBarController.

When viewDidLoad() is called for ProfileViewController I setup my form (I don't have the required data when init() is called)

All details well (although the section headings are displayed in ALL CAPS in tall section bars).

If I flip to another tab and back to ProfileViewController then the section headings are repeated (using two styles) and the rows are present but blank.

See the two images.
![first view](https://cloud.githubusercontent.com/assets/1036041/6524214/30e121e2-c3ef-11e4-985a-183b38a6e6fe.png)
![second view](https://cloud.githubusercontent.com/assets/1036041/6524215/30e24efa-c3ef-11e4-938b-39e513a870e7.png)

My code:

    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        form = XLFormDescriptor(title: "Profile")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        populateForm()
    }

populateForm() is composed of:

a loop for each row. if the row defines a "section header" then

    section = XLFormSectionDescriptor()
    section?.title = sectionHeader
    form.addFormSection(section)

and for each row:

    var row = XLFormRowDescriptor()
    row = XLFormRowDescriptor(tag: key, rowType: XLFormRowDescriptorTypePhone, title: prompt)
    row.cellConfig.setObject(UIColor.lightGrayColor(), forKey: "textField.textColor")
    row.value = answer

The appearance of the two section headers is probably the biggest clue of where I'm going wrong.
Why, in the first image are there no blue headings? And why two headings in the second?

**Comment by carlhunterroach** [comment]
I replaced:

    section = XLFormSectionDescriptor()

with:

    section = XLFormSectionDescriptor.formSection() as? XLFormSectionDescriptor

but it made no difference

**Comment by carlhunterroach** [comment]
I had a UITableVIew in the storyboard. Unreferenced but, in some way, XLForm picks it up when the form is returned to.

**Comment by amadeu01** [comment]
@mtnbarreto @carlhunterroach I'm having the same problem, but I do not have any extra `UITableView`
