### ISSUE TITLE
Issue #235 Repost..not sure if it got the attention of Xmartlabs..

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/XLForm#257]
When selecting value from pickerview the new row creation using the following method:
self.form.addFormRow(<#formRow: XLFormRowDescriptor!#>, afterRow: <#XLFormRowDescriptor!#>)

should result in row being created below the in-line pickerview. Instead the row is created before the in-line picker view!

Issue Update: The issue I notices is that that the inline picker shows up as one of the rows in section.formRows with a tag = nil. This messes up the ability to add a new row at the right location in the array.

Workaround: The fix I am using is to filter out the tag = nil from formRows array. Ideally, this should be fixed in the base code logic, so that the same logic for adding a new row can be used whether the selector is "inline" or "push".

**Comment by mtnbarreto** [comment]
@newbie27 we are aware of it. I need to look into it to find a elegant solution. 
This issue is related with #203. 

Thanks for the report. 
Regards.

**Comment by m-revetria** [comment]
Closing this as it duplicates #235
