### ISSUE TITLE
How to get event when row loses focus

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#258]
I'm adding validation to my XLForm instance.

I'd like this to happen at 3 places.

1. a call to formValidationErrors() to check for errors before I use all the values

2. when c() is called
e.g., I note which field has the focus, and then when a Done button is tapped, I can tell the user that an email field is invalid

3. there is a hole in #2. if the user taps another field then formRowDescriptorValueHasChanged() isn't called until the new field's content changes.

How can I check the content of a field when the user tries to tap to another field?

Or is this a wrong approach when using XLForm?

**Comment by gclsoft** [comment]
#351 How to get event XLFormRowDescriptorTypeSelectorPopover has changed select?
How did you solve it?
