### ISSUE TITLE
XLFormViewController.m viewWillAppear is not called

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#263]
I was working how best to scroll the form fields into view when the keyboard appeared (and back again when the keyboard is hidden) when I found that XLForm already does this.

Alas, for me, viewWillAppear: is not called.
viewDidLoad: is called.
viewDidAppear is called
(breakpoints place at the head of each method)

The view is appearing - I can see it ;) and I can enter data into the florm's fields.

This article (from 2011) might explain why viewWillAppear is not called.
http://benscheirman.com/2011/08/when-viewwillappear-isnt-called/

Deleting viewWillAppear() from XLForViewController.m and changing viewDidAppear to the following re-enables the field scrolling functionality.

As I couldn't find this issue already - and it's so obvious - I'm assuming there's every chance I've made an error in my app (breaking the view hierarchy) and that this change isn't appropriate.

    - (void)viewDidAppear:(BOOL)animated
    {
        [super viewDidAppear:animated];

        NSIndexPath *selected = [self.tableView indexPathForSelectedRow];
        if (selected){
            [self.tableView reloadRowsAtIndexPaths:@[selected] withRowAnimation:UITableViewRowAnimationNone];
            [self.tableView selectRowAtIndexPath:selected animated:NO scrollPosition:UITableViewScrollPositionNone];
            [self.tableView selectRowAtIndexPath:nil animated:YES scrollPosition:UITableViewScrollPositionNone];
        }
        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(contentSizeCategoryChanged:)
                                                     name:UIContentSizeCategoryDidChangeNotification
                                                   object:nil];
        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(keyboardWillShow:)
                                                     name:UIKeyboardWillShowNotification
                                                   object:nil];
    
        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(keyboardWillHide:)
                                                     name:UIKeyboardWillHideNotification
                                                   object:nil];
    
        
        if (self.form.assignFirstResponderOnShow) {
            self.form.assignFirstResponderOnShow = NO;
            [self.form setFirstResponder:self];
        }
    }

**Comment by mtnbarreto** [comment]
@carlhunterroach Could you push a small project containing the error? i want to reproduce it.
I can't figure out what is happening just taking a look at the info you provided me.

Are you calling `super viewWillAppear:`?
Are you implementing some sort of [Custom Container View Controller](https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/CreatingCustomContainerViewControllers/CreatingCustomContainerViewControllers.html)?

**Comment by carlhunterroach** [comment]
Apologies for wasting your time!

Yes, I'd not called super.viewWillAppear:
(how could I miss that out?!)

Thanks for your patience and... for this excellent library.
