### ISSUE TITLE
is there any way to dismiss keyboards or date picker when tap tableview (tap on the section header or footer view)

### ISSUE THREAD

**Issue by peterfor** [xmartlabs/XLForm#276]
First of all, XLForm is really awesome!

![img_2756](https://cloud.githubusercontent.com/assets/4435408/6723233/c4a8f1fe-ce1f-11e4-81e8-473559f28c28.PNG)

what i want is that when tap the section header or footer, i want to dismiss the datepicker and keyboards ?  any help ?

Thanks,

**Comment by mtnbarreto** [comment]
you can dismiss the keyboard or the inline picker view by doing: `[self.tableView endEditing:YES]`, this resign the first responder.

Regards
