### ISSUE TITLE
Selecting dates by scrolling Inline DatePicker scrolls tableview.

### ISSUE THREAD

**Issue by askarimov** [xmartlabs/XLForm#277]
Hi, 

I programmatically alloc init XLFormViewController and call initializeForm from init method. If I try to select dates inside inline date picker, then tableview scrolls up/down with the finger swipe (not like in the sample app). Any solutions to this issue?

**Comment by code-K** [comment]
Hi @askarimov, please show code example what exactly you're doing...

**Comment by askarimov** [comment]
Hi @code-K, looks like it is working now. I dont really know what may have fixed this issue. Closing. Thanks
