### ISSUE TITLE
XLForm do not update cell displace text(but did update value) after select value in custom view controller for   XLFormRowDescriptorTypeSelectorPush

### ISSUE THREAD

**Issue by peterfor** [xmartlabs/XLForm#282]
Here is my code:
XLForm VC :
  row = [XLFormRowDescriptor formRowDescriptorWithTag:kZone r   rowType:XLFormRowDescriptorTypeSelectorPush title:NSLocalizedString(@"phone_zone_title", nil)];
    CountryAndAreaCode *country = [[CountryAndAreaCode alloc] init];
    country.countryName = _defaultCountryName;
    country.areaCode = _areaCode;
    row.selectorControllerClass = [SectionsViewController class];
    row.valueTransformer = [AreaCodeTransformer class];
    row.value = country;
    [section addFormRow:row];

Custom VC:

@interface SectionsViewController : SubViewController
<UITableViewDataSource, UITableViewDelegate,UISearchBarDelegate,XLFormRowDescriptorViewController>
@end

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    NSUInteger section = [indexPath section];
    NSString *key = [keys objectAtIndex:section];
    NSArray *nameSection = [names objectForKey:key];
    
    NSString* str1 = [nameSection objectAtIndex:indexPath.row];
    
    NSRange range=[str1 rangeOfString:@"+"];
    
    NSString* str2=[str1 substringFromIndex:range.location];
    
    NSString* areaCode=[str2 stringByReplacingOccurrencesOfString:@"+" withString:@""];
    
    NSString* countryName=[str1 substringToIndex:range.location];
    
    CountryAndAreaCode* country=[[CountryAndAreaCode alloc] init];
    country.countryName=countryName;
    country.areaCode=areaCode;
    
    self.rowDescriptor.value = country;
    
    [self.navigationController popViewControllerAnimated:YES];
    
}

Transformer:

@implementation AreaCodeTransformer

+ (Class)transformedValueClass
{
    return [NSString class];
}

+ (BOOL)allowsReverseTransformation
{
    return NO;
}

- (id)transformedValue:(id)value
{
    if (!value) return nil;
   CountryAndAreaCode *country = (CountryAndAreaCode *)value;
    return country.countryName;
}

@end

any help ?

**Comment by peterfor** [comment]
i download the demo code, it works, but demo code is old, now  set row. selectorControllerClass instead of  row.action.viewControllerClass, i

**Comment by peterfor** [comment]
just fixed it by reload row on  -(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)formRow oldValue:(id)oldValue newValue:(id)newValue  method

**Comment by hamedmohammadi** [comment]
reload row cause keyboard to dismiss is there a way to stop this behavior
