### ISSUE TITLE
any possibility to check which Row is currently first responder?

### ISSUE THREAD

**Issue by code-K** [xmartlabs/XLForm#284]
Hi there, is there any possibility to check which row is currently first responder?

As i have few textfields where i need only one of the textfields to show a tableview where user can select something. currently i do this through textField delegate method:

```swift
override func textFieldShouldBeginEditing(textField: UITextField) -> Bool {
        println(textField)
        autoCompleteTableView.showTableView(textField.frame.origin, size: textField.frame.size, textField:textField)
        return true
    }
```

but this shows the tableview always when selecting a textfield... ;)
So i need to know if the textfield currently being first responder is the textfield from which XLForm row...

Thanks much for any help/suggestions on this and best regards,
C

**Comment by code-K** [comment]
Hi there, meanwhile found an easy solution for this by myself... ^^ Didn't think about this first...

Assigning the textField a tag value through cellConfigAtConfigure
```swift
self.destinationRow.cellConfigAtConfigure.setObject(111, forKey: "textField.tag")
```

and then in the textField delegate method checking for the correct textfield this has the tag and is firstResponder.

```swift
//check if it's the correct textfield and do your stuff
        if (textField.tag == 111 && textField.isFirstResponder())
        {
            autoCompleteTableView.showTableView(textField.frame.origin, size: textField.frame.size, textField:textField)
        }
```

**Comment by mtnbarreto** [comment]
@code-K 

The easiest way to get it is using `UIView+XLFormAdditions` category.
```obj-c
formViewController.findFirstResponder.formDescriptorCell.rowDescriptor
```

Regards
