### ISSUE TITLE
possibility to set onTintColor for booleanSwitch ?

### ISSUE THREAD

**Issue by code-K** [xmartlabs/XLForm#286]
Hi there, is there a possibility to set the "onTintColor" for the booleanSwitch?

Thanks so much for guidance and best regards,
C

**Comment by mtnbarreto** [comment]
@code-K have you tried using https://github.com/xmartlabs/XLForm#additional-configuration-of-rows ?

```obje-c
    [row.cellConfig setObject:[UIColor redColor] forKey:@"accessoryView.onTintColor"];
```

Regards

**Comment by code-K** [comment]
Works like charm! Thank you... :)

**Comment by code-K** [comment]
@mtnbarreto is there any way to find out about all KVC keys which are supported?
I'm new to this and can't find out how i can see what keys are available...

Thanks much and best regards,
C
