### ISSUE TITLE
Set the first responder to another row

### ISSUE THREAD

**Issue by ankraft** [xmartlabs/XLForm#294]
Is there an easy way to set the first responder to a row that is not the first row in a form? I tried `formDescriptor.assignFirstResponderOnShow = YES;`, but this assigns the first responder only to the first row.
Thanks in advance!

**Comment by pastorin** [comment]
Hi @ankraft,

You can do that easily adding the following lines in your subclass of XLFormViewController

```objc
@interface MyXLFormViewController()
@property XLFormRowDescriptor *formRowDescriptorToAssignAsFirstResponse;
@end

@implementation MyXLFormViewController
-(void)viewDidLoad
{
    [super viewDidLoad];
    if (self.formRowDescriptorToAssignAsFirstResponse) {
        UITableViewCell<XLFormDescriptorCell> * cell = [self.formRowDescriptorToAssignAsFirstResponse cellForFormController:self];
        if ([cell formDescriptorCellCanBecomeFirstResponder]){
            [cell formDescriptorCellBecomeFirstResponder];
        }
    }
}
@end
```

And then assign ```self.formRowDescriptorToAssignAsFirstResponse``` with the row you want to to set as first responder

```objc
row = [XLFormRowDescriptor formRowDescriptorWithTag:kName rowType:XLFormRowDescriptorTypeText title:@"Name"];
self.formRowDescriptorToAssignAsFirstResponse = row;
[section addFormRow:row];
```

Regards

**Comment by ankraft** [comment]
Hi @pastorin,

thank you very much, this works like a charm!
