### ISSUE TITLE
Is there any way to configure the XLFormRowDescriptorTypeDateInline (or TimeLine) mode to be a Countdown timer?

### ISSUE THREAD

**Issue by kotarofujita** [xmartlabs/XLForm#295]
It seems that if I tried to configure the date picker itself, it doesn't seem to acknowledge the change. 

row = [XLFormRowDescriptor formRowDescriptorWithTag:kDuration rowType:XLFormRowDescriptorTypeTimeInline title:@"Duration"];
 [row.cellConfigAtConfigure setObject:@(UIDatePickerModeCountDownTimer) forKey:@"datePicker.datePickerMode"];

There doesn't seem to be a direct way to manually change the mode to Count down timer. Am I missing something? Thanks in advance!

**Comment by pastorin** [comment]
Hi @kotarofujita,

You can create a date picker using the CountDownTimer mode from version 2.2.1
Here an example of how to do that:
```objc
row = [XLFormRowDescriptor formRowDescriptorWithTag:kCountDownTimerInline rowType:XLFormRowDescriptorTypeCountDownTimerInline title:@"Countdown Timer"];
row.value = [NSDate new];
[section addFormRow:row];
```

Regards,

**Comment by kotarofujita** [comment]
oh cool. thx!
