### ISSUE TITLE
Cocoapods build is broken

### ISSUE THREAD

**Issue by KostyaChoporov** [xmartlabs/XLForm#296]
Hi guys,
today I tried to install xlform 2.2.0 in my project and recieved this error:
```
Unable to satisfy the following requirements:

- `XLForm (from `../../`)` required by `Podfile`
- `XLForm (= 2.1.0)` required by `Podfile.lock`
```
this error also throws when I try to run example project by ```pod try xlform```

Thanks for your reply

**Comment by colmdoyle** [comment]
https://github.com/xmartlabs/XLForm/pull/297

**Comment by mtnbarreto** [comment]
@KostyaChoporov fixed.
