### ISSUE TITLE
XLFormTextFieldCell autolayout issue

### ISSUE THREAD

**Issue by colmdoyle** [xmartlabs/XLForm#298]
If you have a `XLFormTextFieldCell` with a longish `textLabel`, it resizes the accompanying `textField` such that it becomes basically unusable.

This occurs even if you set `textLabel.adjustsFontSizeToFitWidth` to `true`.
![ios simulator screen shot 1 apr 2015 14 29 35](https://cloud.githubusercontent.com/assets/406463/6941915/9a4a23c2-d87b-11e4-976f-b3dc3385964f.png)

**Comment by colmdoyle** [comment]
Looks like this is involved - https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormTextFieldCell.m#L184

When I set a minimum width of `>=60` on `textField`, it renders without issue.

**Comment by mtnbarreto** [comment]
@colmdoyle thanks for reporting it!
Now it's fixed, this is the pull request #449.
regards
