### ISSUE TITLE
Problem adding a custom row type from XIB with Swift

### ISSUE THREAD

**Issue by tobinharris** [xmartlabs/XLForm#300]
Hi folks

I've copied the example but can't get my custom row type to work when using a NIB. The row appears empty.

I have a nib called `MyCustomRowType.xib` and have created a `XLFormBaseCell` subclass in a file called`MyCustomRowType.swift`

I've registered the type using this code

    XLFormViewController.cellClassesForRowDescriptorTypes().setObject(MyCustomRowType.self, forKey:MyCustomRowType.rowTypeName)

In the NIB, the File's Owner is set to `MyCustomRowType` and the nib contains a single `UITableViewCell`.

The only thing that works is if I do this in my subclass of `XLFormBaseCell`:

    override func configure() {
        super.configure()
        let nib = UINib(nibName: "MyCustomRowType", bundle: nil)
        let objects = nib.instantiateWithOwner(self, options: nil) as NSArray;
        let first = objects[0] as UIView
        self.clipsToBounds = true
        self.contentView.addSubview(first)
    } 

Any help welcome.

**Comment by ziogaschr** [comment]
Can you give it a try as a String:

```
XLFormViewController.cellClassesForRowDescriptorTypes().setObject("MyCustomRowType", forKey:MyCustomRowType.rowTypeName)
```

**Comment by tobinharris** [comment]
Thanks for the feedback. Did try that as per the `README`. Just tried again.

    class override func load() {
        XLFormViewController.cellClassesForRowDescriptorTypes().setObject("MyCustomRowType", forKey: XLFormTextInputCell.rowTypeName)
    }

It's blowing up when I try and set any properties 

    *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: 
    '[<NSObject 0x7f9f3adb2a40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key textField.'

My custom row type inherits from `XLFormBaseCell` so that should be there.

If I log out the cellClass it's `nil`

    row = XLFormRowDescriptor(tag: id, rowType: MyCustomRowType.rowTypeName)
    // row.cellClass = MyCustomRowType.self // <-- Putting this in fixes it, but that's pretty horrible
    println(row.cellClass)

So it's as if the `xib` isn't being found, but the file name is definitely matching "MyCustomRow". 

Thanks

Tobin

**Comment by tobinharris** [comment]
Ok, I got this working. Might be down to 2.2, or just because I was doing something stupid. Here's what works for me.

### XIB File
* Name of XIB is whatever I want, e.g. `XLFormMyCellClass.xib`
* Owner set to nothing
* Xib contains a single TableView Cell
* Set the custom class on the cell to my own class `XLFormMyCellClass`
* Link labels, inputs etc to outlets on UIView `XLFormMyCellClass.swift`

### View File
* Name is something like `XLFormMyCellClass.swift`
* Subclasses `XLFormBaseCell`
* Implements `XLFormDescriptorCell` and `UITextFieldDelegate` (optional?)
* `configure()` pretty much empty at the moment, no need to do anything here
* Has helper class method initialise (see below). This is because cannot override `load()`

### View Controller
* Calls `XLFormMyCellClass.initialize()` class method
* Row descriptor instantiated like this `row = XLFormRowDescriptor(tag: id, rowType: "XLFormRowDescriptorTypeMyCellClass", title: name)
* Set properties as usual e.g. `row.cellConfigAtConfigure.setObject(true, forKey: "textHelp.hidden")`

   override class func initialize() {
      XLFormViewController.cellClassesForRowDescriptorTypes().setObject("XLFormMyCellClass", forKey:"XLFormRowDescriptorTypeMyCellClass")
    }
