### ISSUE TITLE
how can i remove the XLFormViewController's head space?

### ISSUE THREAD

**Issue by jbasttdi** [xmartlabs/XLForm#301]
I want to remove the XLFormViewController's head space like this screenshot.How can I do it?thanks.
![remove](https://cloud.githubusercontent.com/assets/4523109/6995411/55261408-db79-11e4-945d-f93031bad6d1.png)

**Comment by ziogaschr** [comment]
You can try this in swift.

```
extension XLFormViewController {
    func tableView(tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        
        if (section == 0) {
          return 0.1
        }

        return UITableViewAutomaticDimension
    }
}
```

**Comment by jbasttdi** [comment]
hi @ziogaschr ,
Thanks,I use OC.

**Comment by msczr** [comment]
你好，请问用 OC 是怎么解决remove the XLFormViewController's head space 的，谢谢！
