### ISSUE TITLE
Begin editing text field when form row/cell is tapped?

### ISSUE THREAD

**Issue by tobinharris** [xmartlabs/XLForm#305]
I want to automatically select the text field in a row when the table cell is tapped, so the keyboard appears. Thought this would do it in my `XLFormBaseCell` subclass but it's not working, any ideas?

    override func formDescriptorCellBecomeFirstResponder() -> Bool {
        return self.textField.becomeFirstResponder()
    }

**Comment by pastorin** [comment]
Hi @tobinharris,

Before call ```formDescriptorCellBecomeFirstResponder``` the view controller ask if the cell can become first responder calling the ```formDescriptorCellBecomeFirstResponder``` method. Maybe you forgot to implement it.

Let me know if this is the problem

Regards

**Comment by tobinharris** [comment]
Thanks @pastorin 

I have these implemented. Is that everything I need?

![image](https://cloud.githubusercontent.com/assets/25578/7153668/54391dea-e346-11e4-8756-62cde613ced8.png)

**Comment by pastorin** [comment]
@tobinharris,

Sorry, I just forgot to tell you that you need to implement the ```formDescriptorCellCanBecomeFirstResponder``` method too which has to return a boolean value of ```true```

**Comment by tobinharris** [comment]
Not seeing this in `XLForm (2.1.0)` so trying now from `master`

**Comment by tobinharris** [comment]
Ok, got this working

`class XLFormTextInputCell: XLFormBaseCell, XLFormDescriptorCell, UITextFieldDelegate { ....`

Then 

      override func formDescriptorCellCanBecomeFirstResponder() -> Bool {
        return true
      }
  
      override func formDescriptorCellBecomeFirstResponder() -> Bool {
        return self.textField.becomeFirstResponder()
      }

Think there was something funky going on with how I setup my Xib and cell subclass. Working now, thanks for your help.
