### ISSUE TITLE
Add dynamic sections with multiple rows

### ISSUE THREAD

**Issue by jmgarben** [xmartlabs/XLForm#308]
Hi!

I need to add dynamic sections with multiple rows. Example: 
<p>
---------<br />
Row Language: Spanish<br />
Row Level: C2 <br />
---------<br />
Row Language: French<br />
Row Level: B2<br />
---------<br />
+<br />
</p>
It's possible? Thanks!

Regards!

**Comment by mtnbarreto** [comment]
@jmgarben  Could you explain me in detail what you want to accomplish.

What I understood based on your diagram is that you want to have a button to add sections that contains 2 rows each one and you will not add or delete rows on these sections. Each time you tap on the button the form should add a new section containing the exactly 2 rows containing in the already added sections.

Let me know if this is the scenario.

Regards

**Comment by jmgarben** [comment]
Hi @mtnbarreto !

Thanks you for your request. Exactly! This is the scenario. 

I need create others types sections multivalued with more rows, but if you can explain me about this, I could develop the others scenaries bassed in your explication.

Thanks! Regards!

**Comment by mats-claassen** [comment]
I believe this can be done with a custom view as header or footer of the tableView or one section (using tableviews delegates) and then adding sections to the form.
