### ISSUE TITLE
formDescriptorCellHeightForRowDescriptor never execute!

### ISSUE THREAD

**Issue by perfmlin** [xmartlabs/XLForm#309]
formDescriptorCellHeightForRowDescriptor never execute when custom cell used nib file to define the cell.
and registe like this:
+(void)load
{
    [XLFormViewController.cellClassesForRowDescriptorTypes setObject:NSStringFromClass([XLFormWeekDaysCell class]) forKey:XLFormRowDescriptorTypeWeekDays];
}

**Comment by mtnbarreto** [comment]
@perfmlin 
This is very weird. Which XLForm version are you using?
I have tested it using last version and it works properly. 
Take a look at my Xcode screenshot: 

![screen shot 2015-04-13 at 6 10 46 pm](https://cloud.githubusercontent.com/assets/1746532/7125591/9bf0104c-e208-11e4-8c51-a3ea425dbe79.png)

Regards

**Comment by perfmlin** [comment]
@mtnbarreto 
thx,i am using 2.1.0
i had fixed this problem by upgrade to 2.2.0.
