### ISSUE TITLE
I want to hide the delete icon,plz help.

### ISSUE THREAD

**Issue by jbasttdi** [xmartlabs/XLForm#310]
In my app i use 
```
    _companionSection=[XLFormSectionDescriptor formSectionWithTitle:@"companion" sectionOptions:XLFormSectionOptionCanDelete];
```
it will show the delete icon
![14](https://cloud.githubusercontent.com/assets/4523109/7119069/f15d4a68-e235-11e4-9c3e-340bdaaf195f.jpeg)
I want to hide the delete icon. how can i do it ?thanks.

**Comment by pastorin** [comment]
Hi @jbasttdi,

What is the behaviour you want to?
If you want to delete with a swipe gesture and use the last row to insert tags you have to use:

companionSection = [XLFormSectionDescriptor formSectionWithTitle:@"companion" sectionOptions: XLFormSectionOptionCanDelete | XLFormSectionOptionCanInsert];

And then, add the following line in the viewDidLoad event
    [self.tableView setEditing:NO];

Martin

**Comment by jbasttdi** [comment]
Hi @pastorin 
Thank you very much,That's what we needed.
[self.tableView setEditing:NO];   is ok!!
