### ISSUE TITLE
XLFormBaseCell setEditingAccessoryType limitations

### ISSUE THREAD

**Issue by ziogaschr** [xmartlabs/XLForm#312]
As a user using XLForm from a Swift project I would like to be able to create a custom cell in my project that I will be able to use in XLForm and on iOS UITableViewController.

In previous versions of XLForm I was able to build a class for this use, though in the latest version I have problems on setting `setAccessoryType` and/or `setEditingAccessoryType` as you have mixed them together.

In [XLFormBaseCell](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormBaseCell.m#L137) you set both `accessoryType` and `editingAccessoryType`, while I only want to set `accessoryType`.

In my code I am creating a custom cell like:
```
class CustomTableViewCell: XLFormBaseCell {
  override func update() {
        super.update()
        ...
  }

  override func formDescriptorCellDidSelectedWithFormController(controller: XLFormViewController) {
        ...
  }
}
```

When I use `AQScopeTableViewCell` in a `UITableViewController` and I set the `cell.accessoryType` the  `editingAccessoryType` is being set too, which makes my UI look different from what I want.

Can you handle the behaviour you want to achieve in another way so as it doesn't mix/conflict with the iOS default APIs behaviour?

**Comment by mtnbarreto** [comment]
@ziogaschr 
master branch already has the change. 
Thanks

**Comment by ziogaschr** [comment]
Thanks a lot @mtnbarreto.
