### ISSUE TITLE
Run example code and get weird display.

### ISSUE THREAD

**Issue by fantasywindy** [xmartlabs/XLForm#324]
I have downloaded the example code. After updating the pod, the example project is built successfully. As you can see, the example code main UI has several sections. I click the "Text Field" and navigate into it, but the UI seems to be incorrect. Can anyone figure out why the presentation of the "Twitter" row seems to be incomplete. Does this has anything to do auto layout? Thanks in advance.
![screen shot 2015-04-20 at 6 52 17](https://cloud.githubusercontent.com/assets/7200812/7221736/4cdbb2a0-e72a-11e4-9c3a-ed687fbdaa6d.png)

**Comment by mats-claassen** [comment]
What iOS version are you using?

**Comment by fantasywindy** [comment]
I'm using SDK iOS 7.1 , running on a iPhone Retina (4-inch) simulator, my Xcode version is 5.1.1

**Comment by fantasywindy** [comment]
@mats-claassen  I'm using SDK iOS 7.1 , running on a iPhone Retina (4-inch) simulator, my Xcode version is 5.1.1

**Comment by fantasywindy** [comment]
@mats-claassen This issues still exists even if I am running it on a iPhone Retina (4-inch) simulator.

**Comment by mats-claassen** [comment]
Thank you. It did not appear in iOS 8.
