### ISSUE TITLE
Accessory view should not be displayed on Inline date picker

### ISSUE THREAD

**Issue by colmdoyle** [xmartlabs/XLForm#325]
Having the accessory view appear with an inline date picker is inconsistent with standard iOS forms

![img_1675](https://cloud.githubusercontent.com/assets/406463/7231297/63b8fb62-e76c-11e4-893a-f24a1bc0b7f6.jpg)

**Comment by mtnbarreto** [comment]
@colmdoyle you can easily change the behaviour provided by default just overriding 

```objc
-(UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor;
```
`XLFormViewController` method.

You should check the rowDescriptor.rowType value and return nil or super implementation depending on it. 

Anyway, we will stick XLForm to standard iOS forms behaviour not showing the Accessory view in these cases. Please, use the workaround I mentioned for now.

Regards,
Martin
