### ISSUE TITLE
Hidden property of the XLFormRowDescriptor class

### ISSUE THREAD

**Issue by dmorentsov** [xmartlabs/XLForm#326]
I am using the XLForm library in swift but having trouble with the .hidden property. The property is not being recognized by the compiler when I try to use it. I also had a hard time finding this property in the XLFormRowDescriptor files in the source code. 

The examples do reference this property in the predicates section. Here is the snippet of the code:
```
let pictureRow:XLFormRowDescriptor = form.formRowWithTag(tag.picture) as XLFormRowDescriptor
pictureRow.hidden = true // this is where the compiler has an issue
```
I must be missing something. Can someone help? Thanks!

**Comment by mtnbarreto** [comment]
@dmorentsov 
Have you tried 
```objc
row.disabled = NSNumber(bool: true)
```
?

Regards
