### ISSUE TITLE
For countdown timer, formRowDescriptorValueHasChanged requires me to change BOTH hours and minutes before being called.

### ISSUE THREAD

**Issue by kotarofujita** [xmartlabs/XLForm#330]
Is there any way we can get it so that I only need to pick either the hour or the min for the formRowDescriptorValueHasChanged to trigger?

Thanks in advance and sorry if this is a duplicate somewhere else.

**Comment by mats-claassen** [comment]
It is an issue with the countdown datePicker. When setting it, it has to be done with animated:YES
We will fix it soon.

**Comment by kotarofujita** [comment]
Awesome! Thx!
