### ISSUE TITLE
Line #136 - textColor is overwritten/set to Black in update method in XLFormTextFieldCell.m, XLFormBaseCell.m and XLFormTextViewCell.m

### ISSUE THREAD

**Issue by mgleason** [xmartlabs/XLForm#333]
The text color is always set to black (or gray if disabled) - by Line #136 in "XLFormTextFieldCell.m":
```objective-c
self.textField.textColor = self.rowDescriptor.isDisabled ? [UIColor grayColor] : [UIColor blackColor];
```

So, even if the color is set to red using one of the lines below, it comes out black:
```swift
row.cellConfigAtConfigure.setObject(UIColor.redColor(), forKey: "textField.textColor")  
```
or 
```objective-c
[row.cellConfigAtConfigure setObject:[UIColor redColor] forKey:@"textField.textColor"];
```

**Comment by RabbeN** [comment]
Use `row.cellConfig` instead of `row.cellConfigAtConfigure`.

**Comment by mtnbarreto** [comment]
@RabbeN :+1: 

you can also find the answer here: https://github.com/xmartlabs/XLForm#additional-configuration-of-rows
