### ISSUE TITLE
Change background color and tint of section

### ISSUE THREAD

**Issue by HanseThommy** [xmartlabs/XLForm#335]
Hello at all.

I´d like to change the background color and the tint of a section (XLFormSectionDescriptor) within an form.

Maybe someone can help me doing it.

Thank you in advance.

Greetings, Thommy

**Comment by ericcgu** [comment]
https://github.com/xmartlabs/XLForm/issues/347

**Comment by AlexHedley** [comment]
Which property do you set on a normal section?

---
Section - Multi Valued Row Template.
```objc
section.multivaluedRowTemplate.cellConfig[@"backgroundColor"] = kBackgroundColor;
```

Rows are working fine
```objc
row.cellConfigAtConfigure[@"backgroundColor"] = kBackgroundColor;
```

**Comment by mats-claassen** [comment]
@AlexHedley What do you mean by background of normal section? The header and footer of the section or the background of its rows?

For the rows you have to do it for each of them separately. For the headers and footers you must use `-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section` and its footer counterpart.

**Comment by AlexHedley** [comment]
@mats-claassen  I got rows working with the above code, it was the Header/Footer of a section I was trying.

Thanks for pointing me in the right direction, I've used to the following to change the Section background colour.

```objc
- (void)viewDidLoad {
    [[self tableView] registerClass:[UITableViewHeaderFooterView class] forHeaderFooterViewReuseIdentifier:@"headerFooterReuseIdentifier"];
}
```

**Header**
```objc
-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
    UITableViewHeaderFooterView *headerFooterView = [[self tableView] dequeueReusableHeaderFooterViewWithIdentifier:@"headerFooterReuseIdentifier"];
    headerFooterView.contentView.backgroundColor = kBackgroundColor;
    
    return headerFooterView;
}
```

**Footer**
```objc
-(UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section {
    UITableViewHeaderFooterView *headerFooterView = [[self tableView] dequeueReusableHeaderFooterViewWithIdentifier:@"headerFooterReuseIdentifier"];
    headerFooterView.contentView.backgroundColor = kBackgroundColor;
    
    return headerFooterView;
}
```
