### ISSUE TITLE
Linker Command Failed.

### ISSUE THREAD

**Issue by Jamongkad** [xmartlabs/XLForm#336]
Whenever I create an XLFormViewController I keep getting this error. Take note I deleted and reinstalled the library via Cocoapods and this error still persists. 

duplicate symbol _XLValidationStatusErrorKey

**Comment by mtnbarreto** [comment]
@Jamongkad i think this issue is related with https://github.com/xmartlabs/XLForm/issues/311 and should be already solved in master branch.  
could you please use the master branch version for now? 

Regards

**Comment by Jamongkad** [comment]
Ah ok so it's not checked into Cocoapods yet?
