### ISSUE TITLE
How to I scroll a row into view using the API?

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#337]
I'm implementing Restoration to my view controller that contains an XLForm.
I'm calling becomeFirstResponder when the row is a UITextField or UITextView
but how do I have XLForm scroll the field into view?

If the row is already in view them the iOS keyboard is displayed and all is well. If the row isn't visible then the keyboard is only displayed once swipe the screen to scroll down.

**Comment by mats-claassen** [comment]
Did you try the scrollToRowAtIndexPath:atScrollPosition:animated: method?

**Comment by carlhunterroach** [comment]
Thanks. I tried that and it works. The return of NSIndex of course but I'll be able to wrap that and hide it away.
