### ISSUE TITLE
SubClass of XLFormViewController loaded from Nib does not show Form

### ISSUE THREAD

**Issue by confile** [xmartlabs/XLForm#340]
I created a FormViewController which is a subclass of XLFormViewController:
```
@objc(FormViewController)
class FormViewController: XLFormViewController {
  
  struct tag {
    static let dateTime = "dateTime"
    static let date = "date"
    static let time = "time"
  }
  
  
  
  @IBOutlet weak var myTableView: UITableView! {
    didSet {
      self.tableView = myTableView
    }
  }
  
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  
  override func viewDidAppear(animated: Bool) {
    
     self.initializeForm()
  }
  
  
  func initializeForm() {
    var form : XLFormDescriptor
    var section : XLFormSectionDescriptor
    var row : XLFormRowDescriptor
    
    form = XLFormDescriptor.formDescriptorWithTitle("Dates") as! XLFormDescriptor
    
    section = XLFormSectionDescriptor.formSectionWithTitle("Inline Dates") as! XLFormSectionDescriptor
    form.addFormSection(section)
    
    // Date
    row = XLFormRowDescriptor(tag: tag.date, rowType: XLFormRowDescriptorTypeDateInline, title:"Date")
    row.value = NSDate()
    section.addFormRow(row)
    
    // Time
    row = XLFormRowDescriptor(tag: tag.time, rowType: XLFormRowDescriptorTypeTimeInline, title: "Time")
    row.value = NSDate()
    section.addFormRow(row)
    
    // DateTime
    row = XLFormRowDescriptor(tag: tag.dateTime, rowType: XLFormRowDescriptorTypeDateTimeInline, title: "Date Time")
    row.value = NSDate()
    section.addFormRow(row)
    
    self.form = form;
  }
  
}
````
This is from your Swift example. I also have a corresponding nib: ``FormViewController.xib`` which has a UITableView inside: 

![formview_xib](https://cloud.githubusercontent.com/assets/64265/7325771/04fb1a1c-eac1-11e4-809b-530f3d86a40a.png)
 
I connected the UITableView with the ``myTableView`` from above and set 
```
self.tableView = myTableView
```
such that the ``XLFormViewController`` has access to the UITableView from the Nib. 

No form has been shown. Here is a screenshot: 

![ios_simulator_-_iphone_5_-_iphone_5___ios_7_1__11d167_](https://cloud.githubusercontent.com/assets/64265/7325842/6bfc04ec-eac1-11e4-8deb-bc82a5ca422b.png)

**Comment by mtnbarreto** [comment]
@confile  if you set up the form inside viewDidAppear you should call `self.tableView.reloadData()` to make the cell visible.   BTW you should call viewDidAppear super implementation.

if you initialize the form from inside the viewDidLoad you don't need to reload the tableview.

Regards

**Comment by confile** [comment]
Is there a way to prevent the form from showing the remaining unused lines?

![ios_simulator_-_iphone_5_-_iphone_5___ios_7_1__11d167_](https://cloud.githubusercontent.com/assets/64265/7326242/3bc17782-eac4-11e4-9e81-c5710088b30d.png)

**Comment by mtnbarreto** [comment]
@confile `XLFormViewController has a tableView outlet that you can connect with the tableView added to xib file. You may want to use Grouped Style TableView or set an empty footer view by `self.tableView.tableFooterView = UIView(frame: CGRect.zeroRect)`

**Comment by confile** [comment]
@mtnbarreto Could you please link some code example. I could not find ``grouped``as a keyword somewhere in the docs.

**Comment by confile** [comment]
By the way what does ``zeroRect``?

**Comment by confile** [comment]
I tried you Swift example with some of the code here: https://github.com/xmartlabs/XLForm#lets-see-part-of-the-ios-calendar-event-form-definition

Your example looks like this: 

![ios_simulator_-_iphone_5_-_iphone_5___ios_8_4__12h4074d_](https://cloud.githubusercontent.com/assets/64265/7330038/cd89cdae-eae7-11e4-9fdc-5b7ba1cead47.png)

When I run the code in my example I get this: 

![ios_simulator_-_iphone_5_-_iphone_5___ios_7_1__11d167_](https://cloud.githubusercontent.com/assets/64265/7330045/e8d3a210-eae7-11e4-9535-232f4e278239.png)

Why are the layouts so different did I miss something here?

**Comment by confile** [comment]
Even with style grouped it looks different: 

![screenshot_25_04_15_01_33](https://cloud.githubusercontent.com/assets/64265/7330246/0ea80c9e-eaeb-11e4-90f4-cd7399e826b6.png)

**Comment by mtnbarreto** [comment]
@confile i need to see your code to see what may be wrong. Please make sure that you are adding the rows to a section and the sections to the form. 

Regarding how to use XLForm from swift base code i will add many examples shortly.

Regards

**Comment by confile** [comment]
Here is a demo project to show the problem: https://github.com/confile/XLForm-Test

**Comment by confile** [comment]
@mtnbarreto Do you have any idea what is the problem here?
