### ISSUE TITLE
Retrieve XLFormViewController of XLFormRowDescriptor

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#341]
If I have an instance of XLFormRowDescriptor is there a way to access its XLFormViewController?

**Comment by mats-claassen** [comment]
What do you want it for?
```objc
rowDescriptor.sectionDescriptor.formDescriptor.delegate 
```
gives you the XLFormDescriptorDelegate, which most times is the XLFormViewController. But it is rare to invoke other functions that are not in the delegates definition.

**Comment by carlhunterroach** [comment]
I've written two Swift extensions.
I wanted to remove the 'formController' func parameter for something
derived from a row.

scrollIntoView(formController:XLFormViewController, animated:Bool=true)  {
        let selected = formController.form.indexPathOfFormRow(self)
        formController.tableView.beginUpdates()
        formController.tableView.scrollToRowAtIndexPath(selected,
atScrollPosition: UITableViewScrollPosition.None, animated:animated)
        formController.tableView.endUpdates()
    }
and another
becomeFirstResponder(formController:XLFormViewController)

With both of these I can handle iOS restoration for an XLForm if a user was
editing a field when they switched apps and iOS killed my app whilst in the
background.

The rowDescriptor.sectionDescriptor.formDescriptor.delegate I can access
indexPathOfFormRow() but I can't dind tableView.

a) is this a valid approach? b) given a rowDescriptor how to I access its
form's tableView member?

**Comment by carlhunterroach** [comment]
Accessing tableView of the form was straightforward.

let vc = self.sectionDescriptor.formDescriptor.delegate as!
XLFormViewController
vc.tableView ...
