### ISSUE TITLE
Creating a custom inline row

### ISSUE THREAD

**Issue by alexperezpaya** [xmartlabs/XLForm#343]
Hey! I've been trying to create a custom row, I managed to get full functionality except one thing... been trying so hard to create a custom-inline-row.

Can I get some help? Btw, i'm using Swift.

**Comment by alexperezpaya** [comment]
Maybe adding my row to: XLFormViewController.inlineRowDescriptorTypesForRowDescriptorTypes ?

**Comment by focusedonfit** [comment]
I would like a way to make my custom rows inline as well. Is it possible?
