### ISSUE TITLE
Question about formValues(tag) vs formRowWithTag(tag).value

### ISSUE THREAD

**Issue by Brisdo** [xmartlabs/XLForm#344]
Is there any reason to use formValues(tag) instead of formRowWithTag(tag).value or vise-versa?

**Comment by mats-claassen** [comment]
Not really. 
formRowWithTag(tag).value accesses a stored dictionary while `formValues(tag)` loops through the form getting all the values. 
So if you just want one row then formRowWithTag(tag).value will be more performant
