### ISSUE TITLE
How to make the form smaller size on iPad?

### ISSUE THREAD

**Issue by gclsoft** [xmartlabs/XLForm#345]
![image](https://cloud.githubusercontent.com/assets/1269898/7534086/ba8274f0-f5a9-11e4-8771-b27aa1d81fa9.png)
The form is too big in size. User has to look left, then turn right to see more information.

**Comment by ericcgu** [comment]
Increase the rowHeight and increase the fonts.

**Comment by gclsoft** [comment]
@ericcgu I mean the width of the form is too bigger

**Comment by mtnbarreto** [comment]
Hey @gclsoft. 
You can make the table view smaller by using either a storyboard or a xib file to specify the table view size. Don't forget to connect the [tableView](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.h#L82) IBOutlet.

Hope it helps. 
Regards.

**Comment by ericcgu** [comment]
@gclsoft 
```Swift
 override func viewDidLayoutSubviews() {
        tableView.frame.size.width = view.frame.width / 2
        tableView.center.x = view.center.x   
    }

```

![screen shot 2015-05-20 at 10 56 31 pm](https://cloud.githubusercontent.com/assets/4943759/7740700/b73b9468-ff43-11e4-8f9b-615b46080158.png)

**Comment by gclsoft** [comment]
@ericcgu Thanks, but
![image](https://cloud.githubusercontent.com/assets/1269898/7740988/fb9d7ab4-ffab-11e4-9f41-5405acd96e13.png)

```
- (void)viewDidLayoutSubviews
{
    CGRect rc=self.tableView.frame;
    rc.size.width= self.view.frame.size.width / 2;
    
    self.tableView.frame =rc;
    CGPoint pos=self.tableView.center;
    pos.x=self.view.center.x;
    self.tableView.center =pos;
    self.view.backgroundColor=[UIColor clearColor];
}
```

**Comment by ericcgu** [comment]
@gclsoft 
Not to be rude but perhaps in the future you can consider asking this question on Stackoverflow.com.  It doesn't seem to be directly related to this Issue or XLForm.  

With that being said you can change view background color using:

```Swift
override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor.blackColor()
}
```
Check out this this article on table view backgrounds:
https://medium.com/@ericgu/beautify-your-data-driven-ios-app-a70f7b22f963

**Comment by gclsoft** [comment]
@ericcgu Thanks!
