### ISSUE TITLE
Remove top line from Keyboard

### ISSUE THREAD

**Issue by steffimueller** [xmartlabs/XLForm#346]
How can I remove the line marked in the image below from the keyboard?

![ios_simulator_-_iphone_5_-_iphone_5___ios_7_1__11d167_](https://cloud.githubusercontent.com/assets/5350431/7534566/08a6f4ea-f57c-11e4-92e2-a99b5f8fb243.png)

**Comment by RabbeN** [comment]
Just override `inputAccessoryViewForRowDescriptor:` XLFormViewController method.

```objective-c
- (UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor {
      return nil;
}
```

**Comment by mtnbarreto** [comment]
:+1:
