### ISSUE TITLE
Customize Section Header and Footer

### ISSUE THREAD

**Issue by confile** [xmartlabs/XLForm#347]
Is it possible to customize the Section Header and Footer? 

For example setting the footer text to center and add a UIImageView?

**Comment by ericcgu** [comment]
```Swift  
  override func tableView(tableView: UITableView, willDisplayHeaderView view: UIView, forSection section: Int) {
        let header: UITableViewHeaderFooterView = view as! UITableViewHeaderFooterView //recast your view as a UITableViewHeaderFooterView
        header.contentView.backgroundColor = UIColor(red: 0/255, green: 181/255, blue: 229/255, alpha: 1.0) //make the background color light blue
        header.textLabel.textColor = UIColor.whiteColor() //make the text white
        header.alpha = 0.5 //make the header transparent
    }

```

**Comment by ericcgu** [comment]
@mtnbarreto 
Is it possible to allow multi-value section to be overridden by tableView willDisplayHeaderView?

![a](https://cloud.githubusercontent.com/assets/4943759/7789586/df374e14-0234-11e5-9669-e0aa933af820.png)


```Swift
section = XLFormSectionDescriptor.formSectionWithTitle("Team", sectionOptions:XLFormSectionOptions.CanReorder | XLFormSectionOptions.CanInsert | XLFormSectionOptions.CanDelete, sectionInsertMode:XLFormSectionInsertMode.Button) as! XLFormSectionDescriptor
section.multivaluedAddButton.title = "Add New Team"
row = XLFormRowDescriptor(tag: nil, rowType: XLFormRowDescriptorTypeName, title: nil)
row.cellConfigAtConfigure["textField.placeholder"] = "Tag Name"
section.multivaluedRowTemplate = row
section.multivaluedRowTemplate.cellConfig["backgroundColor"] = kStandardBackgroundColor
row.cellConfigAtConfigure["backgroundColor"] = kStandardBackgroundColor
row.cellConfig["textLabel.textColor"] = kPrimaryFontColor
row.cellConfig["textLabel.font"] = kStandardFont
row.cellConfig["self.tintColor"] = kPrimaryFontColor
        
row.cellConfig["textField.textColor"] = kPrimaryFontColor
row.cellConfig["textField.font"] = kStandardFont
        
masterForm.addFormSection(section)
```

**Comment by mtnbarreto** [comment]
@ericcgu 
`Add new Team` is actually a row, not a section. Do you want to customize the look and feel of it?
Regards

**Comment by ericcgu** [comment]
Yes. Can you advise? @mtnbarreto

**Comment by ericcgu** [comment]
Also multi selector on new VC

**Comment by conradwt** [comment]
@confile Did you get a solution for adding an UIImageView because I'm looking to also create a profile form as well?

**Comment by confile** [comment]
I have no solution yet.

**Comment by focusedonfit** [comment]
I'm interested in the same.

**Comment by focusedonfit** [comment]
@ericcgu  Try this - section.multivaluedAddButton.cellConfigAtConfigure["backgroundColor"] = UIColor.blackColor()

**Comment by batnom** [comment]
@ericcgu did you find out how to change the background colour of a pushed view from a multi selector?

**Comment by FCorellis** [comment]
did you managed to customize this row man ? Thx

**Comment by FCorellis** [comment]
@mtnbarreto how can i customize the Add row cell ?

**Comment by mats-claassen** [comment]
Sorry for the late response but I hope this helps future searches.

For @confile's question about setting a header to a section use:
`-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section`
and return the view you want. This works just the same as any UITableView.

To edit the `Add New Tag` row you should use `section.multivaluedAddButton` property `cellConfigAtConfigure` or `cellConfig` as @focusedonfit said.

Feel free to open a new issue if something was not answered.
