### ISSUE TITLE
Slider used as Range Slider

### ISSUE THREAD

**Issue by confile** [xmartlabs/XLForm#350]
Is it possible to have a Slider (``XLFormSliderCell``) as a range slider where I can set a min and max?

**Comment by mtnbarreto** [comment]
@confile  #405 has the answer.

**Comment by carbocation** [comment]
Is it possible that @confile means that he is interested in having two buttons on the same slider, one which selects the minimum value and the other which selects the maximum value, both lying within the same range?

**Comment by guyisra** [comment]
+1
