### ISSUE TITLE
Installation fails for 3.0.0

### ISSUE THREAD

**Issue by vburojevic** [xmartlabs/XLForm#352]
When trying to install latest version (3.0.0) via:
pod 'XLForm', '~> 3.0.0'
installation fails with the following message:

[!] Unable to satisfy the following requirements:
- `XLForm (~> 3.0.0)` required by `Podfile`

**Comment by confile** [comment]
Same problem here!

**Comment by peacemoon** [comment]
There is no tag 3.0.0 as i can see

**Comment by stefanfisk** [comment]
And no pod for 3.0.0: https://cocoapods.org/?q=xlform

**Comment by mtnbarreto** [comment]
Please use master branch for now. Version 3.0.0 is not released yet but it is stable for production. 
https://github.com/xmartlabs/XLForm#how-to-use-master-branch

Regards
