### ISSUE TITLE
Custom DatePicker

### ISSUE THREAD

**Issue by jmteixeira** [xmartlabs/XLForm#354]
Hi,

I would like to know if it's possible to change date picker components (month and year only).
I know I can create a custom row, but date row is inline and custom rows don't.
If anyone already achieve this, please help.

Thank you,
José Teixeira

**Comment by ericcgu** [comment]
@mtnbarreto I think its possible by overriding pickerView ViewForRow. True?

**Comment by mats-claassen** [comment]
You should create a custom row for this and use the pickerView's delegate methods. Have a look at the examples where we will add a custom inline row.

**Comment by brianfox201** [comment]
I've implemented the custom inline segmented control. It gives me auto-layout warnings. 
Also the selector  [UISegmentedControl autolayoutView]; is unrecognized.

**Comment by mats-claassen** [comment]
Autolayoutview is a UIView method declared in an extension inside XLForm.

I suppose that those autolayout warnings are form the cell you created or do they have something to do with XLForm itself?
