### ISSUE TITLE
Use of undeclared type 'XLFormViewController'

### ISSUE THREAD

**Issue by j-dawg** [xmartlabs/XLForm#363]
I've been trying to XLForms in Swift using a bridge header.

I've loaded the XLForms Pod and added the bridge file and referenced it in Swift Compiler. The Bridge file references includes "#import ".

However, when I try and compile my project I get "Use of undeclared type 'XLFormViewController'". I assume that means it Swift hasn't got access to the library.

I've tried different versions and attempting the setup again, but I can't seem to get it to find it. If I change "#import " to "#import " Xcode warns me that it can't find the file, so I know that Xcode is finding it with "#import " .. just not allowing me to use it.

Any suggestions?

**Comment by ericcgu** [comment]
Check bridging header.

**Comment by ericcgu** [comment]
http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

**Comment by vitalyster** [comment]
If you have `use_frameworks!` in `Podfile`, then you doesn't need bridging header, `import XLForm` in swift code will do the trick

**Comment by ericcgu** [comment]
Nice but question: do you have to import XLForm in every file?

If so, then I would use bridging header to set that import statement once.

**Comment by vitalyster** [comment]
@ericcgu I just have the same issue with bridging header and it doesn't work in `use_frameworks!` mode

**Comment by ericcgu** [comment]
![screen shot 2015-05-24 at 1 19 42 pm](https://cloud.githubusercontent.com/assets/4943759/7788779/96da1d94-0217-11e5-8bfa-bc54ef74af99.png)

The only advice I can give is that you must check this value to make sure debug and release are all properly set.

**Comment by vitalyster** [comment]
It works when cocoapods are build static libraries, not frameworks. And it is not possible to use static libraries if I include any pod written in Swift. 
http://blog.cocoapods.org/CocoaPods-0.36/

**Comment by mathmatrix828** [comment]
Do the following
In Podfile, set use_frameworks!
Run pod update
Restart Xcode and clean your environment (Command-Shift-K)
Build (Command-B)
In each file you use XLForm, use "import XLForm"
