### ISSUE TITLE
row validation is not performed for "unrendered" row cells.

### ISSUE THREAD

**Issue by wefish** [xmartlabs/XLForm#37]
I have a "long" form with one row descriptor marked as ```required```.  The row cell is out of visible area.

If I call ```[self formValidationErrors]``` after loading, result is an empty array.
If I scroll down until the required row cell is visible and I call ```[self formValidationErrors]```, result is the array with the expected NSError object

**Comment by mtnbarreto** [comment]
@wefish @ddcovery Thanks for the issue report. It was fixed on 28 July 2014. take a look at https://github.com/xmartlabs/XLForm/pull/68
