### ISSUE TITLE
Button Cell turns grey after selection

### ISSUE THREAD

**Issue by gearoidoceallaigh** [xmartlabs/XLForm#373]
I'm able to change the background colour of a ```XLFormButtonCell``` but once it's selected it turns grey and doesn't return to original colour. 

This makes the button appear disabled when validation fails.

Is there any way to change it?

**Comment by mtnbarreto** [comment]
@gearoidoceallaigh yes you should call `-(void)deselectFormRow:(XLFormRowDescriptor *)formRow`  https://github.com/xmartlabs/XLForm/blob/ecc9ec45fb202fb467d7b5a3f9c09bf72535ccc8/XLForm/XL/Controllers/XLFormViewController.m#L541

Regards
