### ISSUE TITLE
Textfields are not aligned correctly in iPhone 6+

### ISSUE THREAD

**Issue by johnjiang** [xmartlabs/XLForm#374]
Textfields seems to be out of alignment by a few pixels compared to the other fields but only on the iPhone 6+

e.g.
![screen shot 2015-05-30 at 8 53 59 pm](https://cloud.githubusercontent.com/assets/1456634/7896954/25aeb282-070e-11e5-94e7-e696cb73b0f7.png)

Seems to work fine on other devices.

**Comment by jwardle** [comment]
+1

**Comment by mats-claassen** [comment]
Closing as related to #627

**Comment by jwardle** [comment]
This is still an issue in the latest release, and #627 was closed 29 days ago. Don't think this should be taken off the radar yet?

**Comment by mats-claassen** [comment]
Hi, the fix is currently on master (#577). We will soon make a new release.
