### ISSUE TITLE
Predicated rows in Swift

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#375]
I have a boolean row and a textview row.
I'd like the textview to show/hide based on the boolean row value

I have:

    enum Tags:String {
        case Switch = "switch"
    }

    var dpSection = XLFormSectionDescriptor.formSection() as XLFormSectionDescriptor
    dpSection.title = "Data Protection Agreement"
    form.addFormSection(dpSection)

    row = XLFormRowDescriptor(tag:Tags.Switch.rawValue, rowType: XLFormRowDescriptorTypeTextView, title:"")
    row.value = "row text"

    row.hidden = NSPredicate(format:"$\(Tags.Switch.rawValue).value==0")
    row.disabled = true
    dpSection.addFormRow(row)

    row = XLFormRowDescriptor(tag:Tags.Switch.rawValue, rowType: XLFormRowDescriptorTypeBooleanSwitch, title:"Show Agreement")
    row.value = true
    dpSection.addFormRow(row)

When I tap my Boolean row nothing changes.
If I swap the TextView for another Boolean row then all works as intended.
Is TextView supported by this show/hide mechanism but needs a different set-up?

I downloaded the latest XLForm, from master, yesterday (2nd June 2015)

**Comment by mtnbarreto** [comment]
@carlhunterroach you are using the same tag `Tags.Switch.rawValue` in two different rows. 
We will add some check to prevent this issue.

Regards

**Comment by carlhunterroach** [comment]
ah! thanks.
