### ISSUE TITLE
Predicate not working with Inline Picker

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#377]
I have a row 
var rowNutritionalSetting : XLFormRowDescriptor = XLFormRowDescriptor(tag: "advanced", rowType: XLFormRowDescriptorTypeSelectorPickerViewInline, title: "Manually Set Goals?")
I set it's value here:
rowNutritionalSetting.value = XLFormOptionsObject(value:0, displayText: "Sometext")

I have another section that I want to hide if the value of row NutritionalSetting is 0 but its not working.
 advancedSection.hidden = NSPredicate(format: "$advanced.value==0") 

If I set my value like this rowNutritionalSetting.value = 0, it does work. 

Is it something I'm doing wrong or is this a bug?

**Comment by mats-claassen** [comment]
In your case the value of the row is a XLFormOptionsObject and therefore row.value will be an object. What you want to do is 
advancedSection.hidden = NSPredicate(format: "$advanced.value.valueData==0")
