### ISSUE TITLE
how to "validate" that a switch row is True/On ?

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#379]
I've found the following approach to checking that a textfield has a certain syntax

    row.addValidator(XLFormValidator.emailValidator())

What's the best approach to validating that a XLFormRowDescriptorTypeBooleanSwitch is switched on? The "required" field is ignored (I can see the logic of why).

**Comment by crivera** [comment]
i did something like this

row = [XLFormRowDescriptor formRowDescriptorWithTag:kAcceptTerms rowType:XLFormRowDescriptorTypeBooleanSwitch title:LocalizedString(@"Accept Terms & Conditions")];
row.required = YES;
[section addFormRow:row];

and then when you validate the form it will throw an error if its off

 NSArray * array = [self formValidationErrors];
        if (array.count > 0){
            [array enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
                XLFormValidationStatus * validationStatus = [[obj userInfo] objectForKey:XLValidationStatusErrorKey];
                UITableViewCell * cell = [self.tableView cellForRowAtIndexPath:[self.form indexPathOfFormRow:validationStatus.rowDescriptor]];
                [self animateCell:cell];
            }];

**Comment by alibasta** [comment]
"row.required = YES;" is not enough! If you select it, validate and deselect it again, the validation is successful and no validation error is shown. It looks like an error in XLForm validation.

**Comment by alibasta** [comment]
The following regex solves your question / problem:

```
row.addValidator(XLFormRegexValidator(msg: "greater than 50 and less than 100", andRegexString: "^(1)$"))
```

**Comment by menaweb** [comment]
```
row.value = @NO;
row.required = YES;
row.addValidator(XLFormRegexValidator(msg: "your message", andRegexString: "^(1)$"))
```

You need to set "row.value = @NO" to show your validation message (regex msg) and not the required row validation message.

**Comment by mats-claassen** [comment]
`Required` should not check if the value of a switch row is true. It should just check that it has been touched so it is working as expected. 
The solution is a validator like the one posted by menaweb.
