### ISSUE TITLE
newValue is NSNull when selecting already selected item

### ISSUE THREAD

**Issue by xergic** [xmartlabs/XLForm#380]
I'm using version 2.2.0 from Cocoapods, `XLFormRowDescriptorTypeSelectorPush` with some items (NSArray of XLFormOptionsObjects). When I select the one which is already selected (or default), `(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)formRow oldValue:(id)oldValue newValue:(id)newValue` gets called but newValue is NSNull. Selecting any other (not selected) item works just fine.

I think it should return both oldValue and newValue regardless the value has actually changed (or differs) or not.

**Comment by mtnbarreto** [comment]
@xergic By selecting a selected item basically you are performing a deselect. As a result nil is assigned to `rowDescriptor.value`. 

XLForm uses kvo to notified abut form values change and we consider is the right way to reflect that a real change on the row value occurs.

You can add a custom selector and get notified about any selection but is not something that XLForm provides by default. Basically you should assign a new instance to rowDescriptor.value even though the real value was not changed.

Regards
