### ISSUE TITLE
No cocoapods release for 3.0.0

### ISSUE THREAD

**Issue by haaakon** [xmartlabs/XLForm#382]
In the readme it says to use
Add the following line in the project's Podfile file: pod 'XLForm', '~> 3.0.0'.

But as far as i can see, there is no 3.0.0 tag relased through cocoapods, so that will fail. It should be 2.2.0 instead

**Comment by rockbarato** [comment]
Using the line above resolves the problem:

```rb
pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git'
```

**Comment by mtnbarreto** [comment]
@haaakon @rockbarato i've just realesed versión 3.0.0.
