### ISSUE TITLE
bug? calling XLFormDescriptor::removeRow prevents subsequent addRow with same tag

### ISSUE THREAD

**Issue by colinator** [xmartlabs/XLForm#384]
I think the problem is in XLFormDescriptor.m, currently line 553:

-(void)removeRowFromTagCollection:(XLFormRowDescriptor *)rowDescriptor
{
    [self.allRowsByTag removeObjectForKey:rowDescriptor];
}

shouldn't it be:? 

    [self.allRowsByTag removeObjectForKey:rowDescriptor.tag];

**Comment by mtnbarreto** [comment]
@colinator Thanks for pointing it out. Fixed! :+1:

**Comment by Janady** [comment]
@mtnbarreto if the row is dynamic insert, the rowDescriptor.tag may be nil. so it crash while remove row

**Comment by mtnbarreto** [comment]
@Janady I think i have already fixed it. 

take a look here;
```obj-c
-(void)removeRowFromTagCollection:(XLFormRowDescriptor *)rowDescriptor
{
    if (rowDescriptor.tag){
        [self.allRowsByTag removeObjectForKey:rowDescriptor.tag];
    }
}
```
