### ISSUE TITLE
XLFormRowDescriptorTypeTextView customization?

### ISSUE THREAD

**Issue by memmons-ntst** [xmartlabs/XLForm#385]
Can `XLFormRowDescriptorTypeTextView` be customized? I'd like to be able to specify a border for the text and have it right-justified. Something that looks more like this:
![example](https://cloud.githubusercontent.com/assets/1521654/8040567/58b878d4-0dc6-11e5-90cc-8962bfc84e39.png)

**Comment by mats-claassen** [comment]
Your image resembles more a `XLFormRowDescriptorTypeTextField`.
You can try this:
```
[row.cellConfigAtConfigure setObject:@(1) forKey:@"textField.layer.borderWidth"];
```
to set the border of a textfield (textView should work just the same).
All the other settings of a textfield should be just the same.

**Comment by mats-claassen** [comment]
@memmons-ntst Could you solve your issue?
