### ISSUE TITLE
Last form field hides beneath enabled navigation controller's toolbar

### ISSUE THREAD

**Issue by ankraft** [xmartlabs/XLForm#386]
There seems to be a problem when the toolbar of a navigation controller is enabled. First, the form behaves well and all the fields are visible. After one edits a field and dismisses the keyboard the last field "hides" behind the toolbar.
Currently, I solve this issue by adding a footerTitle to the last section of the form:

    section.footerTitle = @"\n\n";

**Comment by mtnbarreto** [comment]
@ankraft It should be fixed now!
