### ISSUE TITLE
Subclass for XLFormRowDescriptor

### ISSUE THREAD

**Issue by AlexZd** [xmartlabs/XLForm#389]
You have a code in this class:

```objective-c
+(instancetype)formRowDescriptorWithTag:(NSString *)tag rowType:(NSString *)rowType
{
    return [XLFormRowDescriptor formRowDescriptorWithTag:tag rowType:rowType title:nil];
}

+(instancetype)formRowDescriptorWithTag:(NSString *)tag rowType:(NSString *)rowType title:(NSString *)title
{
    return [[XLFormRowDescriptor alloc] initWithTag:tag rowType:rowType title:title];
}
```

If I subclass your rowDescriptor and will use these methods they won't give me correct entity. I think here should be [[self class] alloc]... 
Or tell me how I can correctly subclass it?

**Comment by MuscleRumble** [comment]
Yeah, having the same issue right now. It's even easier: You only have to do replace `XLFormRowDescriptor` with `self`, because self inside a class method refers to the class object.

**Comment by mtnbarreto** [comment]
@MuscleRumble you are right! I'm gonna change the class method to use `[self class]` instead of `XLFormRowDescriptor`.

**Comment by MuscleRumble** [comment]
Awesome, thanks! :)

**Comment by mtnbarreto** [comment]
done!

@AlexZd Why do you want to extend `XLFormRowDescriptor`? 
It was not originally intended to be extended.

**Comment by MuscleRumble** [comment]
I can also answer this question in my case: I wanted to store more information to the row without having the need to write a wrapper around the row and these information.

So why would I want that? Because I want to be able to access the additional information in `formRowDescriptorValueHasChanged:oldValue:newValue:` without overhead.

For now I've written a wrapper, which is basically the data source, but it seems easier to just subclass `XLFormRowDescriptor`.

**Comment by AlexZd** [comment]
Yes, it is easier to add some custom info in own rowDescriptor, in my case I used custom textField cell and I want to set placeholders for fields, or set security for some or set keyboard for some, or capitalization type... Maybe I did not get how to do it from the box, but it is easy to do with own rowDescriptor.

**Comment by mtnbarreto** [comment]
In most of the scenarios you mentioned you can make use of `cellConfig`, `cellConfigAtConfigure`  and `callConfigIfDisabled` to get the same result. Check it out here: https://github.com/xmartlabs/XLForm#additional-configuration-of-rows.

Anyway I understand that in some cases extending the descriptor is easier than making use of cellConfig.
