### ISSUE TITLE
Consider wiring in US2FormValidator

### ISSUE THREAD

**Issue by grgcombs** [xmartlabs/XLForm#39]
We use [US2FormValidator](https://github.com/ustwo/US2FormValidator) internally and have built a number of add-on validations/conditions beyond the framework's extensive built-in options.  I highly recommend it as a means of effectively extending XLForm's validation capabilities without a lot of labor.

**Comment by mtnbarreto** [comment]
@grgcombs Thanks for the recommendation. 

US2FormValidator integration is not on the project roadmap. 

Based on what i see, `US2FormValidator` works directly with UIViews, i personally prefer a solution that doesn't change the UI, for me each app has its own UI and the UI should be defined by the development team. App users should not recognise that a form was built using XLForm or without it. I mean, XLForm is UI agnostic.

XLForm already provides a lightweight and flexible solution to validate the form and we will be improving it. We might take a approach like angular js form validation having pristine, dirty values on each row. Anyway i have to see how to implement it. 

After all is up to you take our validation solution or use another one.

Regards
