### ISSUE TITLE
In a validation is possible to change the alert title?

### ISSUE THREAD

**Issue by TGNA** [xmartlabs/XLForm#396]
Instead of XLFormViewController_ValidationErrorTitle put your own message.

**Comment by mtnbarreto** [comment]
`XLFormViewController_ValidationErrorTitle` localizable key is used from within `-(void)showFormValidationError:(NSError *)error;`.
`-(void)showFormValidationError:(NSError *)error;` is just a helper to show a validation error as a UIAlertView.
You can override the method and do whatever you want. In fact you are in charge of call it so you can even call another method defined by yourself.

In case you just want to change the  `XLFormViewController_ValidationErrorTitle` string you have to add the this key to your `Localizable.strings` file like this:

`"XLFormViewController_ValidationErrorTitle" = "Oops!";`
