### ISSUE TITLE
Change style XLFormRowDescriptorTypeSelectorPush

### ISSUE THREAD

**Issue by popei69** [xmartlabs/XLForm#397]
Hi,

I can't change the current style of my XLFormRowDescriptorTypeSelectorPush cell. Not sure to understand why, because I should get access to the setters.
`
buttonRow = [XLFormRowDescriptor formRowDescriptorWithTag:kStaffInfoActionReallocate rowType:XLFormRowDescriptorTypeSelectorPush title:@"My push"];
        buttonRow.selectorOptions = @[@"Demo 1", @"Demo 2"];
        [buttonRow.cellConfigAtConfigure setObject:[UIColor colorWithRed:0.0 green:122.0/255.0 blue:1.0 alpha:1.0] forKey:@"textLabel.textColor"];
        [buttonRow.cellConfig setObject:@(NSTextAlignmentCenter) forKey:@"textLabel.textAlignment"];
        [section addFormRow:buttonRow];
`

What is the best way to do that?

**Comment by mtnbarreto** [comment]
@popei69 

You should first change the cell style to change the UITableViewCell Alignment.

Try using this code:
```obj-c
buttonRow.cellStyle = UITableViewCellStyleDefault;
buttonRow.cellConfig[@"textLabel.textColor"] = [UIColor colorWithRed:0.0 green:122.0/255.0 blue:1.0 alpha:1.0];
buttonRow.cellConfig[@"textLabel.textAlignment"] = @(NSTextAlignmentCenter);
```
