### ISSUE TITLE
Navigating between cells using bottom navigation buttons causes table cell dividers to disappear

### ISSUE THREAD

**Issue by chenium** [xmartlabs/XLForm#398]
When navigating between table view cells using the bottom navigation button causes the table cell divider to disappear sometimes. I've tracked it down to the navigateToDirection: method in XLFormViewController. Removing the tableview beginUpdates/endUpdates eliminates the bug. This is likely a bug on UITableView.

**Comment by mtnbarreto** [comment]
done!

**Comment by ernestopino** [comment]
This same problem is happening. At the end how is it that can be solved?
Thank you,

PS: Version 3.0.2
