### ISSUE TITLE
Problem with action.formSelector

### ISSUE THREAD

**Issue by ToddManUtah** [xmartlabs/XLForm#399]
I am having a problem with getting action events.  I've tried both blocks and formSelector but I'm not getting the events.  

Here is my code:
                        XLFormRowDescriptor * buttonRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"button" rowType:XLFormRowDescriptorTypeButton title:@"Button"];
                        [buttonRow.cellConfig setObject:[UIColor colorWithRed:0.0 green:122.0/255.0 blue:1.0 alpha:1.0] forKey:@"textLabel.textColor"];
                        buttonRow.action.formSelector = @selector(didTouchURLButton:);
                        [section addFormRow:buttonRow];

I did compile/run the sample app with no problems.  I can't figure out what the difference is.  I'm not using Cocoa Pods but inserted the code into the project.

It almost seems like the delegate isn't being set correctly but even when I make the call self.form.delegate = self, I still don't get the events.

Any ideas?

**Comment by mtnbarreto** [comment]
Can you tell me where is `didTouchURLButton:` implemented and paste the method code here?
Selector is case sensitive so you should make sure that your method name match with `didTouchURLButton`. 

Which XLForm version are you using?

I recommend you to debug `XLFormButtonCell`, in particular `-(void)formDescriptorCellDidSelectedWithFormController:(XLFormViewController *)controller` method to see what is happening.

**Comment by ToddManUtah** [comment]
Here's the code:

     // ***************************************************************************************************
//
//  didTouchURLButton
//
// ***************************************************************************************************
-(void)didTouchURLButton:(XLFormRowDescriptor *)sender
{
    int i=0; i++;
}

I'm using the latest version of XLForm.  I just downloaded it out of Github last week.  I'll start looking into the button cell code and let you know what I find.

THANKS!!!!!

**Comment by ToddManUtah** [comment]
I just put a break point in formDescriptorCellDidSelectedWithFormController.  The break point never gets hit.  I can see that the button is depressed.  It changes color and blinks.  Any ideas?

**Comment by ToddManUtah** [comment]
I found the problem.

The problem was I had defined the method: didSelectFormRow 

This method was getting the notification and overriding my method.

**Comment by mtnbarreto** [comment]
@ToddManUtah Happy to know you found a solution and it wasn't a XLForm issue.
