### ISSUE TITLE
Noob Help

### ISSUE THREAD

**Issue by shadowae** [xmartlabs/XLForm#401]
Hi, I'm new to iOS dev and i just learnt about CocoaPods. I have downloaded the files here but i don't know how to integrate the form into my existing project. Forms are only one part of the project. Can someone help give me instruction on how to integrate it? Sorry for the noob qn.

**Comment by mtnbarreto** [comment]
I suggest you to check cocoapods [documentation](https://cocoapods.org/) out and then follow this guide of how to [integrate](https://github.com/xmartlabs/XLForm#installation ) XLForm using cocoapods.
