### ISSUE TITLE
Change style UISwitch 

### ISSUE THREAD

**Issue by popei69** [xmartlabs/XLForm#404]
Hey guys,

I'm using a cell with XLFormRowDescriptorTypeBooleanSwitch.

However, I didn't figured out how to change onTintColor.
Is there a good way to do that? Or Should I change XLFormSwitchCell for that?

Thanks,

**Comment by popei69** [comment]
Ok I just found what I needed. 

`[row.cellConfig setObject:[UIColor redColor] forKey:@"accessoryView.onTintColor"];` 

A bit confusing to do that by accessoryView key. In the XLFormSwitchCell class, accessoryView is defined as a UISwitch.

**Comment by adil-appifytech** [comment]
@popei69 - It's not working for me :(. I am using XLFormRowDescriptorTypeBooleanSwitch
