### ISSUE TITLE
Step counter's min and max value

### ISSUE THREAD

**Issue by malakiya** [xmartlabs/XLForm#405]
how can I define the step counter's minimum and maximum value?

I don't find any doc about this, thanks!

**Comment by pastorin** [comment]
@malakiya ,
You can set that values with the following lines:

```objective-c
    row.cellConfigAtConfigure["stepControl.value"] = 30
    row.cellConfigAtConfigure["stepControl.stepValue"] = 10
    row.cellConfigAtConfigure["stepControl.minimumValue"] = 10
    row.cellConfigAtConfigure["stepControl.maximumValue"] = 100
```
We will improve the documentation to help the user avoid this problem.
Thanks for reporting.

Regards,
Martin
