### ISSUE TITLE
Linker command failed when using master branch

### ISSUE THREAD

**Issue by kevindeleon** [xmartlabs/XLForm#408]
Receiving the following error after downloading and trying to run the Swift examples. Using XCode 6.3.

![Image of Error](http://www.kevindeleonphotography.com/screenshots/xlformerror.png)

**Comment by mtnbarreto** [comment]
@kevindeleon  
Thanks for reporting it.
Now it's fixed.

Make sure you run `pod update` form within swift example folder and open the workspace file (not the project)

Regards
