### ISSUE TITLE
long labels squeeze text field

### ISSUE THREAD

**Issue by seboslaw** [xmartlabs/XLForm#409]
Hey guys,

is there a way to define a minimum width for the text field on a XLFormRowDescriptorTypeText type cell (having a label and a text field)? My problem is that if the label is too long, the text field gets squeezed to a point where the input is not visible anymore (see screenshot - 3rd cell from the top)
![ios simulator screen shot 30 06 2015 18 23 41](https://cloud.githubusercontent.com/assets/97770/8436024/747a772a-1f55-11e5-93d0-693a6384dd2f.png)

**Comment by tommypeps** [comment]
what type of cell you use? StepCounter?

**Comment by seboslaw** [comment]
no, textfield. But I've already pushed some changes and created a pull request to fix the issue

**Comment by tommypeps** [comment]
@seboslaw  ok, if you go to send a pull request ok

**Comment by mtnbarreto** [comment]
#298
