### ISSUE TITLE
Convert XLFormOptionsObject to readable array in swift.

### ISSUE THREAD

**Issue by wstudios** [xmartlabs/XLForm#411]
Great form plugin, the only issue I have is getting my form posts. I am using self.form.formValues() but I am getting the following for my options

(
    "< XLFormOptionsObject: 0x7fd39593ade0 >",
    "< XLFormOptionsObject: 0x7fd39593aec0 >"
)

I do not know how to convert that to readable array to post to the server. I would appreciate any help, thanks.

**Comment by mats-claassen** [comment]
A XLFormOptionsObject has a property valueData which contains its value and the displayText property containing the displayed text. For example:
```objc
var obj0 = XLFormOptionsObject(value:0, displayText: "Value=0")
var obj1 = XLFormOptionsObject(value:1, displayText: "Value=1")
row.selectorOptions = [obj0, obj1]
NSLog(row.selectorOptions!.description)
for x : XLFormOptionsObject in [obj0, obj1]{
     NSLog("Object:%@", x.displayText())
}
```
produces the following outcome:

```objc
[<XLFormOptionsObject: 0x7fe4dacb9710>, <XLFormOptionsObject: 0x7fe4dacb97a0>]
Object:Value=0
Object:Value=1
```

**Comment by conradwt** [comment]
@wstudios If you're simply wanting to generate an array from displayText property, one could do the following:

```
let displayTextArray = [obj0, obj1].map { $0.displayText() }
```

If on the other hand, you want to send the values, you could something similar by doing the following:

```
let valueDataArray = [obj0, obj1].map { $0.valueData() }
```
