### ISSUE TITLE
XLFormRowNavigationAccessoryView Crash

### ISSUE THREAD

**Issue by lintaoSuper** [xmartlabs/XLForm#412]
[XLFormRowNavigationAccessoryView _overrideInputAccessoryViewNextResponderWithResponder:]: message sent to deallocated instance 0x1477f1370

**Comment by lintaoSuper** [comment]
-(UIView *)inputAccessoryView
{
//    UIView * inputAccessoryView = [self.formViewController inputAccessoryViewForRowDescriptor:self.rowDescriptor];
//    if (inputAccessoryView){
//        return inputAccessoryView;
//    }
    return [super inputAccessoryView];
}

**Comment by mtnbarreto** [comment]
@lintaoSuper can you provide more info? If possible create a repository which i can reproduce the issue.
