### ISSUE TITLE
Problems with hidden

### ISSUE THREAD

**Issue by yousefhamza** [xmartlabs/XLForm#414]
I have been working with XLForms and it worked smoothly so far

But I noticed 2 issues with the just added hidden property:
- It must be set AFTER row is added to a section otherwise it crashes the program
a quick hack is:
In method evaluteIsHidden checking if -sectionDescriptor- for that row is nil if then ignore the try block

I did that in my copy of the code and it worked just normal, but I'm not sure of the implications so I will see what you think before making a pull request

- Second issue is I used it to hide inLineDate Row and well, the row is hidden but the inLineDate wasn't.

**Comment by yousefhamza** [comment]
And also it crashes when manipulating textview row

**Comment by kevindeleon** [comment]
@yousefhamza is correct. In the Swift example code, it shows this:
```swift
row = XLFormRowDescriptor(tag: Tags.Integer.rawValue, rowType: XLFormRowDescriptorTypeInteger, title:"Integer")
row.hidden = NSPredicate(format: "$\(Tags.Switch.rawValue).value==0")
section.addFormRow(row)
```

If implemented like that, you will receive the following error:
`Can't get value for 'whateverTag' in bindings {}.`

However, if you implement it as follows, you have no issue.  So either the example code should be updated, or XLForm should be updated to allow the example code to work.

```swift
row = XLFormRowDescriptor(tag: Tags.Integer.rawValue, rowType: XLFormRowDescriptorTypeInteger, title:"Integer")
section.addFormRow(row)
row.hidden = NSPredicate(format: "$\(Tags.Switch.rawValue).value==0")
```

**Comment by mats-claassen** [comment]
Which version of Xcode and iOS are you using?
Because it seems to work fine in iOS 8.4

**Comment by kevindeleon** [comment]
XCode 6.3 and iOS 8.4. That's interesting that it works fine for you...wonder what the difference could be.

It builds fine, but as soon as I hit the form page using NSPredicate to hide fields, it bombs with the error that I said above.

**Comment by kevindeleon** [comment]
Also, I should state that when I say "if implemented like that," I mean in MY code...I'm not sure if the example code bombs or not. But as I stated, if I put the row.hidden after my section.addFormRow it works fine. Otherwise, it gives the bindings error above. Also, my form is embedded in a navigation controller...not sure if that makes a difference or not.

**Comment by mats-claassen** [comment]
Could you show me how you set up the form?
And are you using the latest version of master branch?

**Comment by kevindeleon** [comment]
You mean the code in question? It's quite a long form and some stuff is company specific info I'd like to not show...but basically it's exactly how the example is setup, except it lives inside of a viewcontroller that  is embedded in a navigationcontroller. I can screenshot the storyboard if you need that, and here's a bit of the code in question:

This code works:

```swift
row = XLFormRowDescriptor(tag: "performanceDuration", rowType:XLFormRowDescriptorTypeSelectorPickerViewInline, title:"How long will they be needed?")
row.selectorOptions = ["Select one", "15 minutes", "30 minutes", "45 minutes", "1 hour", "1 hour 30 minutes"]
row.value = "Select one"
section.addFormRow(row)
row.hidden = NSPredicate(format: "$\(PredicateTags.PerformEntireEvent.rawValue).value == 1")
```

This code doesn't:

```swift
row = XLFormRowDescriptor(tag: "performanceDuration", rowType:XLFormRowDescriptorTypeSelectorPickerViewInline, title:"How long will they be needed?")
row.selectorOptions = ["Select one", "15 minutes", "30 minutes", "45 minutes", "1 hour", "1 hour 30 minutes"]
row.value = "Select one"
row.hidden = NSPredicate(format: "$\(PredicateTags.PerformEntireEvent.rawValue).value == 1")
section.addFormRow(row)
```

I'm using pod 3.0.0 -- so if that is using the most latest version of master, then yes.

**Comment by mats-claassen** [comment]
I just fixed the second issue (inline dates do not disappear when row is hidden) on master.
Please try your code using the latest commit from master and make sure you are not using duplicated tags for any rows. I could not reproduce the problem setting the hidden property before adding the section.
