### ISSUE TITLE
self.formViewController presentViewController not firing a second time

### ISSUE THREAD

**Issue by batnom** [xmartlabs/XLForm#415]
I'm using the `XLFormImageSelectorCell` and while it's all working well, the image select or camera modal view doesn't pop up **a second time** if you wish to select another photo or hit cancel.

- [XLFormImageSelectorCell.h](https://github.com/xmartlabs/XLForm/blob/master/Examples/Objective-C/Examples/Others/CustomCells/XLFormImageSelectorCell.h)
- [XLFormImageSelectorCell.m](https://github.com/xmartlabs/XLForm/blob/master/Examples/Objective-C/Examples/Others/CustomCells/XLFormImageSelectorCell.m)

Here's the block of code that makes the ViewController pop up.

    #pragma mark - UIActionSheetDelegate

    - (void)actionSheet:(UIActionSheet *)actionSheet clickedButtonAtIndex:(NSInteger)buttonIndex
    {
        UIImagePickerController * imagePickerController = [[UIImagePickerController alloc] init];
        imagePickerController.delegate = self;
        imagePickerController.allowsEditing = YES;
        if (buttonIndex == 0){
            imagePickerController.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
            imagePickerController.mediaTypes = @[(NSString *)kUTTypeImage];
            [self.formViewController presentViewController:imagePickerController animated:YES completion:nil];
        } else if (buttonIndex == 1){
            imagePickerController.sourceType = UIImagePickerControllerSourceTypeCamera;
            imagePickerController.mediaTypes = @[(NSString *)kUTTypeImage];
            [self.formViewController presentViewController:imagePickerController animated:YES completion:nil];
        }
    }

It runs that `presentViewController` code for a second time but nothing pops up, tried in both simulator and on device.

I've tried a few workarounds found on StackOverflow (running on main queue, `CFRunLoopWakeUp` etc) and even `dismissViewControllerAnimated` before the `presentViewController` but none of them display the modal view a second time.

Am I missing something?

**Comment by mats-claassen** [comment]
@batnom have you solved this problem. 
XLFormImageSelectorCell is working without this problem...

**Comment by batnom** [comment]
@mats-claassen Don't think I could figure out the root of the cause, but I believe adding this fixed it:
`imagePickerController.modalPresentationStyle = UIModalPresentationCurrentContext;`
