### ISSUE TITLE
Incompatibility with iAds ?

### ISSUE THREAD

**Issue by Dean151** [xmartlabs/XLForm#419]
I use XLForm with iAds. So I import iAd.frameworks in my app delegate, and for each view, including the XLForms views, i call `self.canDisplayBannerAds = bool`

But if the user buy an in-app purchase, it make the ads disappear, setting it to `false`, otherwise, I set it to `true`
In the case I call `self.canDisplayBannerAds = false` or when it's not present, the XLForm load twice and if rows get hidden, we can see the two forms overlapping, witch make it impossible to use the form.

The only way I could make it work properly was to always set `canDisplayBannerAds` to `true` in `viewDidLoad` right before my `setupForm` method and then setting it to `true`, or `false` according to the in-app status in `viewWillAppear`.

I don't quite know how `canDisplayBannerAds` works especially when it's turned to false of not present

I have encountered this issue with all simulator devices in 8.4, an iPhone 5 in 8.3 and another iPhone 5 in 9.0b3.
My *ugly* solution works with all of these too.

![ios simulator screen shot 9 juil 2015 11 10 32](https://cloud.githubusercontent.com/assets/8696821/8598850/2ba6433a-262b-11e5-84b1-8f532d0ecdce.png)
![ios simulator screen shot 9 juil 2015 11 10 34](https://cloud.githubusercontent.com/assets/8696821/8598851/2bb399fe-262b-11e5-8914-a152ef5751db.png)

**Comment by mtnbarreto** [comment]
@Dean151 Thanks for the report. I'm gonna look into it shortly. 
Are you developing in swift? 
Regards

**Comment by Dean151** [comment]
Yes, I do work with Swift.

**Comment by mats-claassen** [comment]
Could you send us the source code where this appears so that we can look into it?

**Comment by Dean151** [comment]
It seems it's a problem when I use XLForm with a UITableViewController instead of a UIViewController. I can even reproduce it myself on a clean project, I will try to find out how to really reproduce the bug and I come back soon

**Comment by Dean151** [comment]
That's weird because i'm not able to use a class inherited from XLFormViewController with a UITableViewController in the Storyboard, but I was able to do it on my project where the bug appears. It seems to work fine when I use a classic UIViewController

**Comment by conradwt** [comment]
@Dean151 The component within the storyboard should be a UIViewController and not a UITableViewController when using XLForm.
