### ISSUE TITLE
Padding at top of tableView in XLFormViewController subclass

### ISSUE THREAD

**Issue by dansinclair25** [xmartlabs/XLForm#421]
Hi All,

I've created a subclass of an XLFormViewController as explained in the readme, and got it working fine.

I then added a UITableView in storyboard, assigned it to the tableView property of the subclass, set it's style to "grouped", and added constraints to hold it in the right place. Even though this works fine (it displays all the cells I want it to), there seems to be a large gap between the first cell or section and the top of the tableView.

Here's an image to help you understand;
![xlform](https://cloud.githubusercontent.com/assets/2573447/8601303/3a426472-2663-11e5-8f5a-ea34813f2fc0.png)

I've tried lots to try and fix this issue but to no avail;
- Changing the tableView's style from "grouped" to "plain
- Adding a title to the section
- Setting the tableViews autoresizingMask (as it is in XLFormViewController.m)

Is this a bug? Or have I missed something out?

Thanks in advance.

/Dan

**Comment by dansinclair25** [comment]
I found a work around - create a custom cell and add in the 3 labels I needed, setting the formRow.value to the value I need for the price label.

It's not pretty or convenient though.

**Comment by pastorin** [comment]
@dansinclair25,
You can try deselecting the option "Under top bar" in the storyboard of your viewController and then writing the following lines in your VC.

```objc
-(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
{
    if (section == 0) {
        return CGFLOAT_MIN;
    }
    return UITableViewAutomaticDimension;
}
```

Let me know if it works for you.
Regards,
Martin
