### ISSUE TITLE
Email validation: new TLD extensions

### ISSUE THREAD

**Issue by Ruyven** [xmartlabs/XLForm#422]
There are now Top Level Domain extensions with more than 4 letters, for example .productions with 11 letters. I reckon email validation just shouldn't check for extension length anymore.

See https://www.domain.com/domains/new-domain-extensions.bml for a list of new, valid TLD extensions.

**Comment by tommypeps** [comment]
This night  resolved !!

**Comment by tommypeps** [comment]
On file XLFormValidator.h add the line
```objective-C
+(XLFormValidator *)emailValidatorLong;
```
On file XLFormValidator.m
```objective-C
+(XLFormValidator *)emailValidatorLong
{
    return [XLFormRegexValidator formRegexValidatorWithMsg:NSLocalizedString(@"Invalid email address", nil) regex:@"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,11}"];
}

```
