### ISSUE TITLE
XLFormDatePickerCell created multiple times after UIAlertView closes (firstResponder is called) - issue only since iOS 8.3

### ISSUE THREAD

**Issue by roland9** [xmartlabs/XLForm#423]
## Issue Description
If you use an inline date cell (`XLFormRowDescriptorTypeDateInline`) in your form, there is an issue if you have UIAlertViews: after the Alert View closes, the form adds a second `XLFormDatePickerCell` as shown in the screenshot. 
<img src="https://cloud.githubusercontent.com/assets/314794/8650737/9e931bd6-296c-11e5-9758-d5266d917ce2.png" width="320">

Note: This issue is only happening on SDK >= iOS 8.3. It's *not* reproducible on < iOS 8.3. So I assume in iOS 8.3 the handling of the firstResponder after the alert view closes has been changed.
Note 2: This issue also happens if you use the iOS 8 only UIAlertController instead of the UIAlertView.

## How to reproduce:
1. To bring up an Alert View, add the following lines in `viewDidLoad` of the `DatesFormViewController` in the XLForm example project:

```
  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^(void){
    [[[UIAlertView alloc] initWithTitle:@"testing" message:@"just hit cancel" delegate:nil cancelButtonTitle:nil otherButtonTitles:@"Cancel", nil] show];
  });
```
2. Launch the XLForm example app, tap 'Date & Time'
3. On the 'Date & Time' screen, open the inline date picker e.g. by tapping on the third cell called 'Date Time'.
4. After 3 seconds, the `UIAlertView` shows up. Tap Cancel.
5. You have two `XLFormDatePickerCell ` cells now.

## Details:
Here is the call stack - seems UIKit is calling `becomeFirstResponder`, and that causes the new `XLFormDatePickerCell` to be created:

![2](https://cloud.githubusercontent.com/assets/314794/8650760/b522b06e-296c-11e5-89ca-65dca29a92c6.png)

**Comment by roland9** [comment]
There is a simple workaround for this issue: call `endEditing` before opening the AlertView:
```
    [self.view endEditing:YES];
```
That closes the `XLFormDatePickerCell` and thus no duplicates are created

**Comment by pastorin** [comment]
@roland9,

You have to use UIAlertController in iOS 8 since UIAlertView is deprecated. We test the issue using that and it works fine. 

I just make a pull request replacing all UIAlertView and UIActionSheet for UIAlertController.
Thanks for reporting

Regards,
Martin
