### ISSUE TITLE
How to perform action once XLFormRowDescriptorTypeSelectorPush has made choice

### ISSUE THREAD

**Issue by sumowesley** [xmartlabs/XLForm#424]
I call the list of items and select one but I really need to run some code when a selection is made.

I can access the action.formBlock and put code into it but it is never executed. The XLFormRowDescriptorTypeSelectorPush is fine for my needs in making a selection but it would be great to be able to react based on that selection.

Any suggestions?

**Comment by sumowesley** [comment]
OK, I think I can get what I need by setting an observer on my form's property e.g.
```
[self addObserver:self forKeyPath:@"rowActionType.value" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld context:nil];
```
It would be nice to be able to execute that action.formBlock though.

**Comment by mats-claassen** [comment]
In the newest version the XLFormRowDescriptor has a block property executed when its value changes
```objc
@property (copy, nullable) XLOnChangeBlock onChangeBlock;
```
The block is called like this from the rowDescriptor when the value changes
```objc
self.onChangeBlock(oldValue, newValue, self);
```

**Comment by sumowesley** [comment]
That is tremendous news and it is much appreciated.

I've tried doing a pod update but I'm still on 3.0.0 - is that the latest version?

**Comment by mats-claassen** [comment]
No, the pod version has not been updated yet. Please use master branch until we update that
pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git', :branch => 'master'
