### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPush does not work with MZFormSheetPresentationController

### ISSUE THREAD

**Issue by AyeChanPyaeSone** [xmartlabs/XLForm#428]

**Comment by mtnbarreto** [comment]
@AyeChanPyaeSone I would like  to help but i need to see the code or more context.
Regards

**Comment by AyeChanPyaeSone** [comment]
I am using MZFormSheetPresentationController in order to get the pop-up display. In that pop-up,I added XLform. In that XLForm, i added rowdescriptorTypeSelectorPush. When u select that selector, it didn't show anything. Thanks.

**Comment by mtnbarreto** [comment]
@AyeChanPyaeSone To make it works you should embed your formViewController inside a `UINavigationController`.  Take a look [here](https://github.com/xmartlabs/XLForm/blob/bea7afcb60be7f2164422b6a6d549fff37af65b3/XLForm/XL/Cell/XLFormSelectorCell.m#L189
). 
Regards
