### ISSUE TITLE
Slider should continuously change the form row's title

### ISSUE THREAD

**Issue by besi** [xmartlabs/XLForm#430]
I have a slider and when I drag it, it should update the row's title:

![Screenshot](https://cloud.githubusercontent.com/assets/160412/8703683/d51f86b8-2b1e-11e5-9429-488108ee912a.png)

I did figure out, that I can't simply set the `formRow`'s title in the `formRowDescriptorValueHasChanged` callback, so I need to refresh the table view.

This means that I can't continuously update the title label, since the slider is being refreshed underneath. I had to set the stepper delta value to 10 so that the user can do 10-20-30-40-50... steps rather than 1-2-3-4-...

This is my callback:

```ruby
override func formRowDescriptorValueHasChanged(formRow: XLFormRowDescriptor!, oldValue: AnyObject!, newValue: AnyObject!) {
    
    if let tag = formRow.tag{
        if tag == RATE.rawValue{
            
            if !oldValue.isEqual(newValue){
                formRow.title = "Rate \(newValue)%"
                mainQ{
                    if let t = self.tableView{ t.reloadData() }
                }
            }
        }
    }
}
```

I wonder if there is a clean way to achieve continuous binding... Thanks for any help.

**Comment by MGough** [comment]
I've just been looking for a solution in Objective-C but I've had to do something similar. Seems odd there doesn't appear to be anything built in.

**Comment by MGough** [comment]
I discovered what I was looking for 

```
[self updateFormRow:formRow];
```

**Comment by mtnbarreto** [comment]
#231 explains how to update a tableCell having a rowDescriptor.

**Comment by besi** [comment]
Copied from #231 

> ```objc
> row = [self.form formRowWithTag:kRowTag];
> [row setDisabled:YES];
> [self reloadFormRow:row];
> ```
