### ISSUE TITLE
Boolean Switch can't be used in NSPredicate

### ISSUE THREAD

**Issue by popei69** [xmartlabs/XLForm#431]
Hi guys,

Thanks for the last release 3.0, that's great.

I'vs just noticed that the initial value given to a switch is not interpret in the same way in a NSString predicate.

If I try this 
```
row = [XLFormRowDescriptor formRowDescriptorWithTag:kFilterBookingDateBool rowType:XLFormRowDescriptorTypeBooleanSwitch ];
    [row setValue:false];
    [section addFormRow:row];


    row = [XLFormRowDescriptor formRowDescriptorWithTag:kFilterBookingDate rowType:XLFormRowDescriptorTypeDateInline];
    row.hidden = [NSString stringWithFormat:@"$%@ == 0", kFilterBookingDateBool];
    [section addFormRow:row];
```
It doesn't work, the row will be shown.

For the first row, if I changed my default value like that:
```  [row setValue:@0]; ```
It works fine, the second row will be hidden.

The switch element is always in the right state, but for the predicate can't recognised it because of is kind (Boolean vs NSNumber). 

Hope that can help someone else.

**Comment by mtnbarreto** [comment]
@popei69 
`value` property type is `id` and BOOL is a signed char. 
You should set @0 or @1 (object intances) in this case and then the switch cell use the bool value.

Regards

**Comment by cdstamper** [comment]
@mtnbarreto do we have sample code for what this should look like? I'm getting nowhere on this, having a crash on code that looks like this:

`XLFormRowDescriptor *firstRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"22" rowType:XLFormRowDescriptorTypeBooleanSwitch title:first];
firstRow.value = @NO;
secondRow.hidden = [NSString stringWithFormat:@"$%@ == 0", firstRow];`

**Comment by cdstamper** [comment]
(Following up on this one)

Setting a tag string that contains numbers, oddly enough, will crash stringWithFormat and predicateWithFormat. No idea why.

In the above example, changing the tags to textual strings fixes the issue.

**Comment by BigSauce** [comment]
Same thing happens to me.  My tag contains a space, and it crashes.  My tag is `@"constant switch"`.  Once I removed the space, it no longer crashed.
