### ISSUE TITLE
XLFormTextFieldCell - FREEZE ON Iphone 6 plus

### ISSUE THREAD

**Issue by AndreasDpp** [xmartlabs/XLForm#433]
Then i run it on my iphone 6 plus or the 6 plus simulator, its freeze then use XLFormRowDescriptorTypeText or Type name or anything else 

My iOS app is in Swift, i can't find why it's freezing, because i am not the into Obj C. :-1:

**Comment by mtnbarreto** [comment]
@AndreasDpp Which swift, Xcode, XLForm version are you using?
Thanks

**Comment by AndreasDpp** [comment]
The last version, from GitHub

Den torsdag den 23. juli 2015 skrev Martin Barreto <notifications@github.com
