### ISSUE TITLE
TintColor for form rows is not respected

### ISSUE THREAD

**Issue by besi** [xmartlabs/XLForm#434]
In my `viewDidLoad` method I set the `tintColor` property to red, just like in the iOS Calendars example and the checkmarks turn red. However, the XLForm buttons don't change their color (See Multivalue Add Button):

![Wrong-Tint](https://cloud.githubusercontent.com/assets/160412/8742037/49fd8352-2c61-11e5-95a7-7471f4d6c033.png)

**Comment by besi** [comment]
This did the trick:

    sideSectorSection.multivaluedAddButton.cellConfigAtConfigure["textLabel.textColor"] = UIColor.redColor()

IMHO: Since this label acts as a button it should respect the `tintColor` of the given `UIView` like `UISlider` etc. do...

**Comment by tommypeps** [comment]
![this is what you want? @besi ](http://s10.postimg.org/mx7q918bd/por_defecto_2015_07_22_a_las_19_35_22.png)

**Comment by mtnbarreto** [comment]
@besi @tommypeps done!

**Comment by tommypeps** [comment]
@mtnbarreto  thanks!
