### ISSUE TITLE
Pushing data to Cell

### ISSUE THREAD

**Issue by ridvank** [xmartlabs/XLForm#435]
Is there anyway to pass data from ViewController to the Cell class(LocationPickerFormCell.self)? Here is my code:
row = XLFormRowDescriptor(tag: "LocationPicker", rowType: "XLFormRowDescriptorTypeLocationPicker")
        row.action.viewControllerStoryboardId = "PickerViewController"
        row.action.viewControllerPresentationMode = XLFormPresentationMode.Push
        row.cellClass = LocationPickerFormCell.self
        section.addFormRow(row)

**Comment by mtnbarreto** [comment]
@ridvank 
you can define a property within `LocationPickerFormCell` and then you can use

`@property (nonatomic, readonly, nonnull) NSMutableDictionary * cellConfigAtConfigure;` rowDescriptor to pass it to the cell.

Let's say you add `customData` property to `LocationPickerFormCell`.
Then you can assign a value to the property by coding:
`row.cellConfigAtConfigure["customData"] = xyz;`

Hope it helps.
