### ISSUE TITLE
Unable to retrieve the form values from multi-value-form

### ISSUE THREAD

**Issue by conradwt** [xmartlabs/XLForm#439]
Hi, I have tried both of the following to get the values from the multi-value-form:

self.form.formValues() =>  [:]

self.formValues() => [:]

Next, my form looks as follows and I can add as well as delete names:

```    
 func initializeForm() {
    let form : XLFormDescriptor
    var section : XLFormSectionDescriptor
    var row : XLFormRowDescriptor
    
    form = XLFormDescriptor(title: "Enter Name")
    
    // Multivalued section
    section = XLFormSectionDescriptor.formSectionWithTitle("", sectionOptions:XLFormSectionOptions.CanInsert | XLFormSectionOptions.CanDelete, sectionInsertMode:XLFormSectionInsertMode.Button)
    section.multivaluedAddButton!.title = "Add Name"
    row = XLFormRowDescriptor(tag: nil, rowType: XLFormRowDescriptorTypeName)
    row.cellConfigAtConfigure["textField.placeholder"] = "Enter Name"
    section.multivaluedRowTemplate = row
    
    form.addFormSection(section)
    
    self.form = form
  }
```

However, when I attempt the following within the segue,

```
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
    println( "EnterNamesController - prepareForSegue" )
    println( "self.formValues() = \(self.formValues())")   // => [:]
    println( "self.form.formValues() = \(self.form.formValues())" ) // => [:]
  }
```

**Comment by popei69** [comment]
Hey @conradwt, 

Did you try to set a tag? For each element, you can link it with a unique tag. This tag is used as a key to construct the dictionary values.

Your tag are set to nil, so I presume that the formValues methods don't detect any tag / key, so they can't assigned any values into a dictionary. 

See the source example for more details.

**Comment by mtnbarreto** [comment]
@conradwt Thank for answering the question. 

Cells that don't have a tag are not returned in `formValues()` the dictionary.

Regards

**Comment by conradwt** [comment]
The code in my original post is from the sample code of this project but thanks for the feedback.

**Comment by mtnbarreto** [comment]
@conradwt If this is the case we should fix it. ;)

**Comment by conradwt** [comment]
@mtnbarreto Yes, the code should be changed as well the documentation on formValues.  I say this because I struggled a bit whether or not to use a UIViewController vs UITableViewController within the storyboard.  Also, I thought there was default callback form submitting a form.  Now, I'm a much better place in understanding how to use the framework.  All in all, this is a great project and this will save me and many others a lot of time creating forms in iOS apps.  Bravo!!!

**Comment by mtnbarreto** [comment]
@conradwt some people got confused with the same issue (UITableViewController vs UIViewController). I thought this was clear in the examples but it seems that is not. 

Do you have time to improve the doc adding this note about which view controller should be used in the storyboard and this details about the formValues behaviour?

Thanks in advance

**Comment by conradwt** [comment]
@mtnbarreto Yes, I will have time to update the documentation.

**Comment by AlexLisong** [comment]
hello, I am having the same issue here even if I've gave it a tag:

func initializeForm() {
    let form : XLFormDescriptor
    var section : XLFormSectionDescriptor
    var row : XLFormRowDescriptor

    form = XLFormDescriptor(title: "Enter Name")

    // Multivalued section
    section = XLFormSectionDescriptor.formSectionWithTitle("", sectionOptions:XLFormSectionOptions.CanInsert | XLFormSectionOptions.CanDelete, sectionInsertMode:XLFormSectionInsertMode.Button)
    section.multivaluedAddButton!.title = "Add Name"
    row = XLFormRowDescriptor(tag: "tag name", rowType: XLFormRowDescriptorTypeName)
    row.cellConfigAtConfigure["textField.placeholder"] = "Enter Name"
    section.multivaluedRowTemplate = row

    form.addFormSection(section)

    self.form = form
  }
@mtnbarreto can you tell me how did you fix it?

and I am still confused that even if we can add a tag name for the first one/default one, how do we add the tag name for the new items(after we click "Add new ...")

any working code?
Thanks in advance,
