### ISSUE TITLE
Labels disappear when get focus on row

### ISSUE THREAD

**Issue by Freak5M** [xmartlabs/XLForm#442]
Hi

I'm using XLForm to generate a basic form with a text input field.
No problems by following exemples but when I get the focus on a row, the label disappear (or turn to white). 
I also notice that buttons in inputAccessoryView are white.

Does someone had the same issue and how to fix it ?

Thanks 

Here is my form init:
```
func initializeForm() {
        let form : XLFormDescriptor;
        var section : XLFormSectionDescriptor;
        var row : XLFormRowDescriptor;
        
        form = XLFormDescriptor(title: "Saisie Montant");
        
        // Section Montant
        section = XLFormSectionDescriptor.formSectionWithTitle("Montant");
        form.addFormSection(section);
        
        // Montant
        row = XLFormRowDescriptor(tag: Tags.Montant.rawValue, rowType: XLFormRowDescriptorTypeDecimal, title: "Montant");
        section.addFormRow(row);
        
        self.form = form; 
    }
```

**Comment by mtnbarreto** [comment]
@Freak5M Whenever a row gains focus XLForm change the label color to  the cell tintColor. Apparently your cell tint color (view tint color)  is white. 

Try changing the viewController.view.tintColor to other color.

Regards

**Comment by Freak5M** [comment]
Thanks @mtnbarreto , just changed tintColor of my view in IB and everything works fine :+1: 
I keep exploring this nice tool ;)
