### ISSUE TITLE
Best way to resign firstResponder

### ISSUE THREAD

**Issue by popei69** [xmartlabs/XLForm#446]
Try to resign firstResponder in a XLForm.

I used all of that to be sure that the keyboard will be hide when I will clic on the right UIBarButton of my navigationBar. It's still showing the keyboard, I don't know why.

Here is what I tried:
```
    UIView * firstResponderView = [self.tableView findFirstResponder];
    UITableViewCell<XLFormDescriptorCell> * cell = [firstResponderView formDescriptorCell];
    [cell unhighlight];
    [cell endEditing:true];
    [self deselectFormRow:cell.rowDescriptor];
    
    [cell resignFirstResponder];
```

Thanks

**Comment by mtnbarreto** [comment]
try using `[self.view endEditing:YES]`

**Comment by popei69** [comment]
Thanks for your quick answer @mtnbarreto , 

I also try that but it doesn't effect the keyboard. Do you know if there any zay to get access to the textview from my first code?

**Comment by mtnbarreto** [comment]
If the first responder view is inside the table view this code should work.

` [self.tableView endEditing:YES];`

**Comment by popei69** [comment]
Okay, my actual first code was working, I can resign first responder of the active cell like that:
```
UIView * firstResponderView = [self.tableView findFirstResponder];
    UITableViewCell<XLFormDescriptorCell> * cell = [firstResponderView formDescriptorCell];
    [cell unhighlight];
    [cell endEditing:true];
```

My mistake was to show an alertview just after, that seems to change the actual focus and leave the keyboard opened even with my code. The keyboard opened is not a problem until the user clic on 'Done' toolbar button, that causes me a crash.

I added a delay between closing the keyboard and showing the alertview, everything is fine now, thanks for your help.
