### ISSUE TITLE
Any plans for supporting Next/Previous links on the keyboard?

### ISSUE THREAD

**Issue by gulsharan-pv** [xmartlabs/XLForm#45]
I think this will make it easier for the user to navigate between fields. Thoughts?

![image](https://cloud.githubusercontent.com/assets/2501860/3222768/cc4d1c20-f01a-11e3-81bd-1c3a76657f92.png)

**Comment by steveburris** [comment]
I'm using the IQKeyboardManager library with XLForm, and it's working like a charm.  Zero code.  Just added the library to my pod file and I now have next, previous, and done buttons.

**Comment by jbasttdi** [comment]
Has this feature added in the master rep? But I don't see it.

**Comment by mtnbarreto** [comment]
@jbasttdi @steveburris @gulsharan-pv we have been working on this feature but is not stable enough for production apps yet and we are still defining which is the best approach, which methods should us expose, how to configure the navigation among rows, how to indicate that a row has a input accessory view, etc. We may make changes over it. https://github.com/xmartlabs/XLForm/tree/feature/support-navigation-between-fields

**Comment by jbasttdi** [comment]
Thanks for your hard work. Hi @mtnbarreto,I find RETableViewManager has this feature,but RETableViewManager is not easy to use.

**Comment by mtnbarreto** [comment]
@jbasttdi  @steveburris  @gulsharan-pv this feature is already merged on master branch. XLForm implementation has some cool features to configure the navigation. We have also added an example showing the different configurations. Feedback is welcome!

**Comment by carlhunterroach** [comment]
Brilliant timing.

Having committed to using XLForm for a second time in my app I'll no longer have to code a solution for each case. Knock out guys!

Have tried it on iPhone 4 & 6+ with a good range of XL rows - all working smoothly.
