### ISSUE TITLE
Disable a toolbar for a specific row

### ISSUE THREAD

**Issue by C4Grey** [xmartlabs/XLForm#451]
Is there a possibility to disable an accessory toolbar(with "next", "previous" and "done" buttons) for a few rows(XLFormRowDescriptorTypeTimeInline, to be more specific)? This feature is required to make a Calendar-like behaviour of a date selection. I've tried such solution:
```swift
override func didSelectFormRow(formRow: XLFormRowDescriptor!) {
    super.didSelectFormRow(formRow)
    if formRow.rowType == XLFormRowDescriptorTypeTimeInline {
        self.form.rowNavigationOptions = XLFormRowNavigationOptions.None
    } else {
        self.form.rowNavigationOptions = XLFormRowNavigationOptions.Enabled
    }
}
```
but it seems like those options are set before execution of a didSelectFormRow  method, and an accessory toolbar disappears only on a next row.

**Comment by pastorin** [comment]
@C4Grey,

You have to return the inputAccessoryView of the rowDescriptor as nil.
To do that add this line in your VC.

-(UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor
{
    if (rowDescriptor.rowType == XLFormRowDescriptorTypeTimeInline) {
        return nil;
    }
    return [super inputAccessoryViewForRowDescriptor:rowDescriptor];
}

Regards,
Martin

**Comment by mtnbarreto** [comment]
@C4Grey here is the related documentation https://github.com/xmartlabs/XLForm#how-to-disable-input-accessory-view-navigation-view 
There are many issues asking the same: #346, #325, #274 etc.
We will improve the doc to clarify it.

**Comment by C4Grey** [comment]
Sorry, my bad, I missed that part in docs. Thank you for the response!
