### ISSUE TITLE
Decimal local separator

### ISSUE THREAD

**Issue by Freak5M** [xmartlabs/XLForm#452]
Hi,

As french people, I use a comma instead of point as decimal separator ...
When I use a `XLFormRowDescriptorTypeDecimal` row, it displays a decimal keyboard with comma which is great for amount fields.

But as I [noticed](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormTextFieldCell.m#L268) the `-[NSString doubleValue]` isn't respecting the locale decimal separator; it expects a point, not a comma.
So finally my value isn't correct.

Is there a trick to parse correctly my amount value ? 

Thanks a lot.

**Comment by Freak5M** [comment]
I find a solution by replacing
```
self.rowDescriptor.value =  @([self.textField.text doubleValue]);
```
with the following lines
```
NSNumberFormatter * myNumFormatter = [[NSNumberFormatter alloc] init];
[myNumFormatter setLocale:[NSLocale currentLocale]];
[myNumFormatter setNumberStyle:NSNumberFormatterDecimalStyle];
self.rowDescriptor.value =  [myNumFormatter numberFromString:self.textField.text];
```

It's not the perfect solution but it finally get the correct double value.
Hope it will be helpful for next bugfix :)

**Comment by CallMeSH** [comment]
Same problem for me. The bug fix is simple but need to be merged in pod so everyone can use it without forking the project.

**Comment by jeanmartin** [comment]
+1

**Comment by mats-claassen** [comment]
NSFormatter support was merged.

**Comment by jeanmartin** [comment]
This is not solved. Other separators than '.' are not respected.
The line now reads:
```
self.rowDescriptor.value =  [NSDecimalNumber decimalNumberWithString: self.textField.text];
```
To respect the current locale it should read (according to [this](http://stackoverflow.com/questions/15534431/nsdecimalnumber-decimalnumberwithstring-ignores-current-locale)):
```
self.rowDescriptor.value =  [NSDecimalNumber decimalNumberWithString:self.textField.text locale:NSLocale.currentLocale];
```
I will create a pull request... no. 31 as of now :|

**Comment by zinyakov** [comment]
This fix does not help fully. If I have set value to, e.g., "12,34" it is converting to "12.34" after I get out of this field. Using NSNumberFormatter helps to avoid this transformation, however It can't help me with changing this value to dot-format after I select this field again. Is it a good idea to implement a default NSNumberFormatter inside decimal row?

**Comment by zinyakov** [comment]
The smoothest solution is to use 2 number formatters - one in form row and one as extension for NSNumber, which helps to call `displayText` method with formatted value, avoiding glitches of NSNumberFormatter with `useValueFormatterDuringInput` flag

```
extension NSNumber {
    public override func displayText() -> String! {
        let formatter = NSNumberFormatter()
        formatter.decimalSeparator = ","
        formatter.locale = NSLocale.currentLocale()
        formatter.numberStyle = .DecimalStyle
        return formatter.stringFromNumber(self)
    }
}
```
