### ISSUE TITLE
Right to left issue

### ISSUE THREAD

**Issue by mhGaber** [xmartlabs/XLForm#457]
Hello, 
I need to swap between text field and title to match right to left design, I can't find a way to do that.. is there anyway or it's applicable ?

**Comment by tommypeps** [comment]
```objective-C
XLFormRowDescriptor *row; //init
//config
[row.cellConfig setObject:@2 forKey:@"textField.textAlignment"];
```

**Comment by mtnbarreto** [comment]
#612 show how the form behaves when a RTL language is used.
