### ISSUE TITLE
Custom inline selectors

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#459]
Hello,

I saw this in the docs 
"Added generic way to create inline selector rows." Is there an example of this in Swift?

Thank you!

**Comment by mtnbarreto** [comment]
duplicated: #343 
@focusedonfit  We will add a example of how to create a custom inline row shortly.

regards

**Comment by focusedonfit** [comment]
Just checking if this example has been added yet?

**Comment by jdgong** [comment]
up for this one too

**Comment by focusedonfit** [comment]
Any update?
