### ISSUE TITLE
Inline pickers expanding beyond a table

### ISSUE THREAD

**Issue by C4Grey** [xmartlabs/XLForm#465]
When user taps on a cell with inline picker, which is in position near a bottom of a table, an inline picker will be displayed only partially, and a part of it will be beyond a bottom border of a table. I've tried to use the scrollToRowAtIndexPath method, but it scrolls only to a bottom of a cell, without taking into account a height of a picker. The more user-friendly behavior can be seen in the Calendar app, a table is scrolled to show both row and picker. Can such behaviour be achieved in the XLForm-based table?

**Comment by mtnbarreto** [comment]
@C4Grey done! not it works like calendar app.

**Comment by C4Grey** [comment]
Thank you, guys, for your work!
