### ISSUE TITLE
How to add UIImagePickerController to the top of the form?

### ISSUE THREAD

**Issue by conradwt** [xmartlabs/XLForm#475]
I would like to the ability for a user to select a profile photo using the UIImagePickerController.  Without using XLForm, I'm doing the following:

- if the profile picture doesn't exist, show place holder UIImageView which can be tapped to show the UIImagePickerController

- if the profile picture exists, show the UIImageView

Again, I know how to implement the above without using XLForm but I want to know how to integrate the above with XLForm.

**Comment by conradwt** [comment]
I was able to add the UIImageView to the form by doing the following:

- adding a section and a couple of rows

```swift
  section = XLFormSectionDescriptor.formSectionWithTitle("") as XLFormSectionDescriptor
  form.addFormSection(section)
    
    for _ in 1...2 {
      row = XLFormRowDescriptor(tag: "",  rowType: XLFormRowDescriptorTypeText, title: "")
      row.cellConfig.setObject(UIColor.clearColor(), forKey: "separatorColor")  // Not working.
      row.cellConfig.setObject(UIColor.clearColor(), forKey: "backgroundColor")
      section.addFormRow(row)
    }
```

- create the image, UIImageView, and add it to the subView

```swift
  override func viewDidLoad() {
    super.viewDidLoad()
    
    var image = UIImage(named: "sample.jpeg" )
    var imageView = UIImageView(image:  image)
    imageView.frame = CGRectMake(0,0,135,135)
    imageView.frame.origin.x = CGRectGetMidX(view.bounds) - CGRectGetMidX(imageView.bounds)
    imageView.frame.origin.y = 80
    self.view.addSubview( imageView )
  }
```

This isn't an ideal solution because the UIImageView isn't on the same contentView as the form.  Thus, the UIImageView is on top of the form instead above the form on the same content view.

**Comment by conradwt** [comment]
![ios simulator screen shot jul 30 2015 1 41 37 am](https://cloud.githubusercontent.com/assets/20219/8979065/25117e18-365c-11e5-98ba-3201ad5d7ed0.png)

**Comment by conradwt** [comment]
Here's a screenshot.

![ios simulator screen shot jul 30 2015 1 41 37 am](https://cloud.githubusercontent.com/assets/20219/8979228/f1d605d6-365c-11e5-9b40-1c44ea53c0e6.png)

**Comment by conradwt** [comment]
Here's an updated screenshot:

![ios simulator screen shot jul 30 2015 1 41 37 am](https://cloud.githubusercontent.com/assets/20219/8981940/53760908-3671-11e5-945e-519713efe39b.png)

**Comment by C4Grey** [comment]
I can suggest you 3 ways:
1. Create a custom cell.
2. Manually place a UITableVIew and a UIImageView on VC, add all required constraints and then create an outlet for the tableView property of your VC(actually, it will inherited from the XLFormViewController class).
3. Create an empty VC, place inside a view container along with UIImageView(also add all required constraints), and embed your VC with a form inside this container.

**Comment by deckikwok** [comment]
like what C4Grey has mentioned, use a custom cell.
like what the author has done, look at the example project and look for imageSelector in Others > CustomCells and see how they do it. 

I've imported the codes in my project and it worked well; just need some tweaking and enhancements for tailored use cases.

**Comment by conradwt** [comment]
@C4Grey Thanks for the information and it seems that option 3 would work the best because I didn't see an examples 1 or 2 in Swift.
