### ISSUE TITLE
Separator color ignored by XLForm

### ISSUE THREAD

**Issue by conradwt** [xmartlabs/XLForm#477]
I'm trying to set the separatorColor property by doing the following:

```swift    
row = XLFormRowDescriptor(tag: "firstName",  rowType: XLFormRowDescriptorTypeText, title: "")
row.cellConfig.setObject(UIColor.clearColor(), forKey: "separatorColor")
section.addFormRow(row)
```

However, this setting is being ignored by XLForm.  Is there a workaround for this?

**Comment by mats-claassen** [comment]
The separatorColor is a property of the tableView not the tableViewCell
