### ISSUE TITLE
Is it possible to trigger cell delete on tap of "minus" button?

### ISSUE THREAD

**Issue by ghost** [xmartlabs/XLForm#478]
Hi, I'm trying to create a form section with rows that can be deleted and am using the following code:
     
    section = XLFormSectionDescriptor.formSectionWithTitle(t.specialName, sectionOptions: XLFormSectionOptions.CanDelete)

The rows have a red minus button on the left side. I would like for the row to be deleted as soon as this is tapped and without having to tap on the "Delete" button. Is this possible using XLForm? Thanks!

**Comment by mats-claassen** [comment]
The default mechanism of UITableView works like this. 
You can have custom cells with an image on the left and then you can delete that row on the tap of that image.
