### ISSUE TITLE
Custom init?

### ISSUE THREAD

**Issue by memmons-ntst** [xmartlabs/XLForm#479]
What's the proper way to create a custom init for an `XLFormViewController` subclass? I've tried:
```Swift
	public required init(someObject: SomeObject) {
		self.someObject = someObject
		super.init(form:XLFormDescriptor(title: "title"), style: UITableViewStyle.Plain)
		initializeForm()
	}

	public override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
	}
```
We are required to call XLForms' custom super init which then calls the subclasses `init(nib:bundle)` which then re-inits the form and thus looses `someObject` which was passed in my custom init.

I'm confused as to how we should create a custom init.

**Comment by mats-claassen** [comment]
This has changed now. The designated initializers are `init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?) ` and `init?(coder aDecoder: NSCoder)`
