### ISSUE TITLE
XLForm won't scroll fields into view

### ISSUE THREAD

**Issue by dparfrey** [xmartlabs/XLForm#480]
I have a split view iPad app that contains an XLForm in the detail (right) pane. The fields beneath the keyboard won't scroll into view! It's also shown as a Form Sheet, same issue. 

I have this implemented pretty much exactly like the examples, with blank storyboard view controllers in IB and segues. The form works fine, except for the keyboard covering the second half of the form.

I'm hoping there's something obvious I've overlooked. If not, I'll try simplifying my example so I can upload something.

Thanks!

**Comment by batnom** [comment]
Does this help? https://github.com/xmartlabs/XLForm/issues/572

Adding `[super viewWillAppear:animated];` to the top of the `viewWillAppear` function made the form scroll to the selected fields when hitting 'next' for me.

**Comment by dparfrey** [comment]
Yes, thank you! I ended up removing XLForm from the project and doing it all myself, but still needed to put the call to super in so the standard UITableViewController would scroll correctly! I didn't equate this to the XLForm issue until you mentioned it. I'm just starting a new form-heavy app, I'll give XLForm another try. It really is a lot easier.
