### ISSUE TITLE
Form is displayed under navigationBar in ios9

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#483]
Running Xcode 7beta4. 
![xlform](https://cloud.githubusercontent.com/assets/4365485/9022675/61a9e1e2-384d-11e5-9d46-e60d250e8078.png)

**Comment by conradwt** [comment]
@mtnbarreto I can reproduce this issue by using XLForm within a Xcode 7 project.
@focusedonfit XLForm hasn't been upgraded to support Xcode 7.

**Comment by C4Grey** [comment]
As an option, you may try to manually place a table inside your VC in a storyboard/xib, and then create an outlet to the tableView field in the XLFormViewController class. I am not sure that this solution will work since I can not test Xcode 7 for now.

**Comment by focusedonfit** [comment]
Dragging out a UITableView in IB worked as a workaround. Thanks @C4Grey

**Comment by carbocation** [comment]
I actually have this issue in iOS8 / Xcode 6. Dragging UITableView in IB (specifically, creating a "referencing outlet" to the tableView property of the UIViewController) also fixes this for me. (It doesn't work in all orientations, but I think this is an Xcode autolayout bug.)

**Comment by nuudles** [comment]
As another more elegant workaround, you can try adding this code to your view controller:

```
	override func viewDidLayoutSubviews()
	{
		super.viewDidLayoutSubviews()
		tableView.contentInset.top = topLayoutGuide.length
	}
```

Or in Objective C:

```
- (void)viewDidLayoutSubviews
{
	[super viewDidLayoutSubviews];
	self.tableView.contentInset.top = self.topLayoutGuide.length;
}
```

**Comment by chrisballinger** [comment]
@nuudles Can you submit that as a PR?

**Comment by ReDetection** [comment]
@chrisballinger Not sure it's a good idea since it's workaround. Moreover, it assumes that you have at least `UIRectEdgeTop` in the `extendsLayoutUnderEdges` and also `automaticallyAdjustsScrollViewInsets` set and `extendedLayoutIncludesOpaqueBars ` and even check if tableView is first subview in the viewcontroller's view. Apple might change it at any time so it will be hard to mimic.

**Comment by chrisballinger** [comment]
Hmmm, good point, well I'll use this for now until a better solution is merged.

**Comment by mats-claassen** [comment]
In the examples this works just fine (they do all come from a storyboard).
There are two ways we did it there: either by adding a tableView and adding constraints to the four sides (bottom layout guide, top layout guide, trailing, leading) or by 'unticking' the "Under top bars" option.
I believe this is the correct way of setting this up. (It can obviously be performed from code as well)

**Comment by elsurudo** [comment]
@nuudles that no longer works, since `top` of `UIEdgeInsets` is read-only.

I did the following:
```
self.tableView.contentInset = UIEdgeInsetsMake(self.topLayoutGuide.length,
                                                   self.tableView.contentInset.left,
                                                   self.tableView.contentInset.bottom,
                                                   self.tableView.contentInset.right);
```

**Comment by adil-appifytech** [comment]
Tested on Version 7.0 (7A220) - still having same issue. Any idea how it can be fixed? I tried @elsurudo  solution but it add extra space above table view.

<img width="432" alt="screen shot 2015-09-20 at 3 19 22 pm" src="https://cloud.githubusercontent.com/assets/10629648/9981059/61cb738a-5fca-11e5-8331-e0259732ed73.png">

**Comment by ReDetection** [comment]
@adil-appifytech Try @nuudles solution

**Comment by adil-appifytech** [comment]
@ReDetection - self.tableView.contentInset.top is read only property. So it's not going to work.

**Comment by nuudles** [comment]
Sorry, I mostly code in Swift now, so I didn't test my Objective C solution. I figured that if it worked in Swift, it worked in Objective C. The equivalent Objective C code would be something like:

```
- (void)viewDidLayoutSubviews
{
	[super viewDidLayoutSubviews];
	UIEdgeInsets newContentInset = tableView.contentInset;
	newContentInset.top = self.topLayoutGuide.length;
	tableView.contentInset = newContentInset;
}
```

**Comment by adil-appifytech** [comment]
Issue with @nuudles and @elsurudo solution is that it add extra padding, which I really don't want on the top.

<img width="432" alt="9d375162-5fea-11e5-81f3-67f3d89cf87a" src="https://cloud.githubusercontent.com/assets/10629648/9984506/3b94d9aa-6032-11e5-82b7-515b75cf84d2.png">

**Comment by ReDetection** [comment]
@adil-appifytech sorry, I can't see any extra padding on the top. What I see is default padding for the grouped table view. You might want to change it to plain.

**Comment by adil-appifytech** [comment]
@ReDetection - My tableview is Normal. Not a grouped table.

**Comment by ReDetection** [comment]
@adil-appifytech either you made you plain table view to look like grouped one, or this is one.
