### ISSUE TITLE
XLFormStepCounterCell and tint

### ISSUE THREAD

**Issue by sumowesley** [xmartlabs/XLForm#484]
I change my default tint colour when when the app is loaded. Unfortunately, the step counter doesn't seem to pick this up. The example below shows the step control in blue (wrong colour) and the label of the edited textfieldview below it as a green (correct colour).

![xlform_tint_example](https://cloud.githubusercontent.com/assets/5694619/9023590/04e981c2-389a-11e5-8af1-2da620d9748e.png)

I have tried explicitly setting self.view.tintColor in viewDidLoad but result is the same. Just for added confirmation, buttons on the navigation bar are of the correct colour.

Is there somewhere else I need to change the colour of the stepControl?

**Comment by conradwt** [comment]
@sumowesley Can you share the code for which you're having an issue?  Also, is this an Xcode 6.3.2, 6.4, or 7 project?

**Comment by sumowesley** [comment]
Xcode is 6.4 with v 3.0.1 of XLForm (updated through cocoapods this morning).

if i add the following into the didFinishLaunchingWithOptions in your example project's appdelegate I get the behaviour shown in the screen shot. (line is inserted after where you set the background colour).
```
self.window.tintColor = [UIColor colorWithRed:65.0f/255.0f green:117.0f/255.0f blue:5.0f/255.0f alpha:1.0f];
```
![xlform_tint_example_2](https://cloud.githubusercontent.com/assets/5694619/9023770/e91a2e58-38a1-11e5-8917-9a380eb8e875.png)

**Comment by mtnbarreto** [comment]
@sumowesley 
The problem was when XLForm tried to get the tintColor from cell `update` method. Since the cell was not added  to the view hierarchy yet at this point the tintColor was the default blue color. 
I made some changes to fix it.
Regards

**Comment by sumowesley** [comment]
Relieved I was doing something wrong - many thanks for the update.

**Comment by sumowesley** [comment]
I manually applied the changes described in #484.

When I run my project I have two step controls on my form. The first in in blue with the second one being in green. Additionally, formatting of the first cell is wrong (value is on top of title) and a cell where I have right justified the text further down the form has the title closer to the left edge and the value closer to the right edge compared to the other fields.

I have reversed the changes and while tint is incorrect, the formatting is OK.

Example of the formatting below.
![xlform_tint_cell_1_formatting](https://cloud.githubusercontent.com/assets/5694619/9027834/28927dd2-395c-11e5-9e69-ce9866f6bfdd.png)
![xlform_tint_cell_4_tint](https://cloud.githubusercontent.com/assets/5694619/9027836/314a8514-395c-11e5-979c-5da732b305a7.png)
![xlform_tint_cell_10_11_formatting](https://cloud.githubusercontent.com/assets/5694619/9027838/37a61540-395c-11e5-9054-c5a2aa6617c8.png)

**Comment by mtnbarreto** [comment]
@sumowesley Regarding the different stepcounter colors, i think this is because you are setting up the tintColor somewhere. Please make sure your are not using `cellConfig` to set up the tintColor.

Regarding the overlapping, it was my fault and i already fixed it, see master branch and #486.

Regards

**Comment by sumowesley** [comment]
I've done a search for tint in my view controller and can't see it. I set two the tint colour in appdelegate and in the viewdidload of two other the only place I'm setting tintcolor is two view controllers I'm using based on another framework. Neither of those view controllers passes control to an XLFormViewController. I will have another look though just to make sure - just for info, here is the code for the two step counter cells.
```
    self.rowRatingCompleted = [XLFormRowDescriptor formRowDescriptorWithTag:kSTR_TAG_OBJECTIVE_CLOSEDRATING rowType:XLFormRowDescriptorTypeStepCounter title:@"Rating (1-5):"];
    [self.rowRatingCompleted.cellConfigAtConfigure setObject:@1 forKey:@"stepControl.minimumValue"];
    [self.rowRatingCompleted.cellConfigAtConfigure setObject:@5 forKey:@"stepControl.maximumValue"];
    [self.sectionClosed addFormRow:self.rowRatingCompleted];


    self.rowTargetRatio = [XLFormRowDescriptor formRowDescriptorWithTag:kSTR_TAG_OBJECTIVE_TARGETRATIO rowType:XLFormRowDescriptorTypeStepCounter title:@"Ratio(%):"];
    self.rowTargetRatio.required=YES;
    [self.rowTargetRatio.cellConfigAtConfigure setObject:@1 forKey:@"stepControl.minimumValue"];
    [self.rowTargetRatio.cellConfigAtConfigure setObject:@100 forKey:@"stepControl.maximumValue"];
    [self.sectionTarget addFormRow:self.rowTargetRatio];
```

**Comment by sumowesley** [comment]
It is definitely working in the new example program. I will keep looking.

**Comment by sumowesley** [comment]
Not sure of the implication but I have added two test cells to my form, both in the same section. The first is the step counter and a second is a slider. Neither is assigned a value. The step counter has the blue tint but the slider has the green tint.

![xlform_tint_section_mix](https://cloud.githubusercontent.com/assets/5694619/9028578/4ce97202-3976-11e5-8d76-b086924603d3.png)
