### ISSUE TITLE
Font Size Live Preview

### ISSUE THREAD

**Issue by ds1239** [xmartlabs/XLForm#487]
Hello. I am using this api to create settings for my app. One of the setting options is the font size for a specific view of the app. I would like to have a live preview of the text size below the picker, so the user can see what the size looks like without having to switch screens. How could I do this? When I try to change the font size, it makes the cell larger, not the actual text. Thanks!

**Comment by mats-claassen** [comment]
Hi @ds1239 did you solve this?
I would attack this using `onChangeBlock` to change the font of your preview and then updating the cell.
Maybe you want to specify a big default height for the cell and / or disable animations when you update the cell...
