### ISSUE TITLE
Change color of UIBarButtonItem in the accessory view

### ISSUE THREAD

**Issue by MGough** [xmartlabs/XLForm#489]
Is it possible to change the colour of the left, right and done buttons in the accessory view?
I've searched but couldn't find anything. I also tried setting the tint colour of both the individual buttons as well as the window but couldn't get it to work.

**Comment by mats-claassen** [comment]
Have a look at [how-to-change-input-accessory-view-navigation-view](https://github.com/xmartlabs/XLForm#how-to-change-input-accessory-view-navigation-view)

**Comment by MGough** [comment]
Thanks! Didn't realise I could customise it as well as disable it there.

**Comment by MGough** [comment]
I've tried a few things but don't seem able to get it to work. I think I must be missing something obvious here.

```objective-c
- (UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor
{
    XLFormRowNavigationAccessoryView * inputAcc = [[XLFormRowNavigationAccessoryView alloc] init];
    
    UIBarButtonItem * button = [[UIBarButtonItem alloc] initWithTitle:@"Test" style:UIBarButtonItemStylePlain target:self action:nil];
    inputAcc.tintColor = [UIColor orangeColor];
    inputAcc.doneButton = button;
    
    return inputAcc;
}
```

**Comment by MGough** [comment]
Of course I worked it out right after commenting, despite having stared at it for far too long
 
All I was actually looking for was simply
```objective-c
[[XLFormRowNavigationAccessoryView appearance] setTintColor:[UIColor orangeColor]];
```

**Comment by MGough** [comment]
Working solution:

```objective-c
- (UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor
{
    UIView * accView = [super inputAccessoryViewForRowDescriptor:rowDescriptor];
    [accView setTintColor:[UIColor redColor]];
    return accView;
}
```
