### ISSUE TITLE
XLFormButtonCell initWithStyle

### ISSUE THREAD

**Issue by torasike** [xmartlabs/XLForm#490]
Can you allow initialization with style that passed in that method instead of UITableViewCellStyleDefault?

**Comment by mats-claassen** [comment]
You can set the style of a button by setting the cellStyle property of the corresponding rowDescriptor

**Comment by torasike** [comment]
As I know, you cannot change the Style of a UITableViewCell after it has been initialized. 
If look into XLFormButtonCell.m , style always will be UITableViewCellStyleDefault.

- (id)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier
{
    return [super initWithStyle:UITableViewCellStyleDefault reuseIdentifier:reuseIdentifier];
}

**Comment by mats-claassen** [comment]
This will be fixed now. You can set a buttons style also with the `cellStyle` property
