### ISSUE TITLE
Custom Button Cell

### ISSUE THREAD

**Issue by losedges** [xmartlabs/XLForm#492]
ask for advice, how to make 2 buttons in a row, each button calls its modal window? Receive data from from Custom Row based BaseCell works fine.  how to make a call  Custom Button Cell

I would be grateful for the help

**Comment by jett0423** [comment]
+1 for this. I've been struggling the same issue!

**Comment by jiangxin1980** [comment]
+1, thanks

**Comment by FishForLife** [comment]
+1

**Comment by wisesabre** [comment]
Its simple and straight forward to perform action in case of 1 button. In case of 2 buttons, should we use 'leftRightSelectorLeftOptionSelected' ? 

We can use 'leftRightSelectorLeftOptionSelected' to set another 'XLFormRowDescriptor' and then use it to perform action. But it seems to be hacky, what is the suggested way?

`
-(void)rightButtonPressed:(UIButton *)rightButton
{
    NSLog(@"DiD select Right");
    XLFormAction *rightAction = (XLFormAction *)self.rowDescriptor.leftRightSelectorLeftOptionSelected;
    

        UIViewController * controllerToPresent = [self controllerToPresent];
        if (controllerToPresent){
            if (self.formViewController.navigationController == nil || [controllerToPresent isKindOfClass:[UINavigationController class]] || rightAction.viewControllerPresentationMode == XLFormPresentationModePresent){
                [self.formViewController presentViewController:controllerToPresent animated:YES completion:nil];
            }
            else{
                [self.formViewController.navigationController pushViewController:controllerToPresent animated:YES];
            }
        }
        
    
    
}`

**Comment by mats-claassen** [comment]
@wisesabre has an example of this in #917
