### ISSUE TITLE
Can't update value in row

### ISSUE THREAD

**Issue by AlexEdunov** [xmartlabs/XLForm#493]
I can't update value of row using value property in XLFormRowDescriptor, rather I can't update displaying text in cell, value is set.

I implemented data source for updating form. That's reloading method implementation:

	- (void)reloadData
	{
    	self.rowFirstName.value = self.profileEditFormDataSource.user.firstName;
    	self.rowLastName.value = self.profileEditFormDataSource.user.lastName;
    	self.rowEmail.value = self.profileEditFormDataSource.user.email;
	}

After performing this code I expect to see changes in my form cells. I also tried to perform updateFormRow method and updateFormRow, but I still didn't get it.

**Comment by mats-claassen** [comment]
You have to call the reloadFormRow:(XLFormRowDescriptor *)formRow method of the XLFormViewController after changing the values to update your table

**Comment by igor9silva** [comment]
@mats-claassen this should definitely be on the docs! I've had a hard time trying to find that information!

**Comment by mats-claassen** [comment]
[Here](https://github.com/xmartlabs/XLForm#how-to-set-a-value-to-a-row) it is.

**Comment by igor9silva** [comment]
Wow, I really missed it! Thanks @mats-claassen!

**Comment by mats-claassen** [comment]
Maybe our Readme is just too large to find certain topics...
