### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPush not showing value

### ISSUE THREAD

**Issue by sumowesley** [xmartlabs/XLForm#497]
Hi there.

I have an issue whereby the row leads to the appropriate list and I can make a selection which is ticked. The value is not replicated on the originating row until I scroll that row off screen and bring back into view. I'm not sure if this is related to #491 but I am using the the following to update XLForm in my Podfile:
>pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git', :branch => 'master'

I can replicate the issue in the Example Program and have an animated GIF below to show the behaviour.
Xcode 6.4
IOS Target 8.4

![xlform_selectorpush_scroll](https://cloud.githubusercontent.com/assets/5694619/9155551/7201a4c8-3eb3-11e5-9bc9-86e9046b7f35.gif)

**Comment by Mrhyuan** [comment]
Same issue! Any way to solve it?

**Comment by SaturdayLiu** [comment]
Same issue!!!! Any way to solve it???

**Comment by sumowesley** [comment]
Can't see a way yet - thought about using the onChangeBlock to set the value myself before it is picked up but don't thing the displayText on the row descriptor has a setter.

I'm using the XLFormOptionObject protocol to allow XLForm to derive the values I want to display. Are you doing the same or using an array of XLFormOptionObjects?
