### ISSUE TITLE
Error with first dependency installed with pods

### ISSUE THREAD

**Issue by ssabetan** [xmartlabs/XLForm#498]
Hi guys,

After running "pod install" in the examples and tests folder, Xcode complains with this error: 

```
ld: library not found for -lExpecta
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

No matter what example I open(ex, Swift, Obj-C) the error would change depending on the first dependency installed ex:

Error when I ran the Obj-C Example:
```
ld: library not found for -lAFNetworking
```

Error when I ran the Swift Example:
```
ld: library not found for -lAXRatingView
```

**Comment by ssabetan** [comment]
Confirmed issue with brand new Yosemite install w/Xcode.

**Comment by mojidabckuu** [comment]
@ssabetan 
Check your Build Settings tab in project window.
Than navigate using search "Search" and than check `Header Search Paths`, `Framework Search Paths`. They must contain `$(inherited)` flag.

**Comment by mats-claassen** [comment]
@ssabetan Could you resolve this issue?
