### ISSUE TITLE
didSelectFormRow overrides XLFormRowDescriptorTypeSelectorPush

### ISSUE THREAD

**Issue by ds1239** [xmartlabs/XLForm#500]
Hello. I would like to call didSelectFormRow to handle button presses, but it overrides other rows of type "XLFormRowDescriptorTypeSelectorPush" and they don't segue into the view, they just act like a button. How can I fix this?

**Comment by misuqian** [comment]
I am sure you forget to call : super. didSelectFormRow(formRow)

**Comment by mtnbarreto** [comment]
@misuqian :+1:
