### ISSUE TITLE
TextAlignment for dates

### ISSUE THREAD

**Issue by yousefhamza** [xmartlabs/XLForm#501]
Hey there,

I have a usecase where I should having the date field on the left is better but not sure how to do this cellConfig crashes because I guess this is no textField.

![ios simulator screen shot aug 12 2015 12 23 56 am](https://cloud.githubusercontent.com/assets/3893067/9211109/9c5a0c98-4088-11e5-89ae-c2a40bb52c0b.png)

Thanks inadvance!
§Yousef

**Comment by mats-claassen** [comment]
Hi, 
For custom rows you should try by creating a [custom](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row) cell from a nib.
