### ISSUE TITLE
Setting background color of Inline picker

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#502]
How can I set the background color of an Inline Picker?

Thank you

**Comment by mats-claassen** [comment]
Try to do it like this:
```objc
[row.cellConfig setObject:[UIColor redColor] forKey:@"datePicker.backgroundColor"];
```
It works for me with date cells

**Comment by focusedonfit** [comment]
That did not work for me. Did you try it with a inline date?

**Comment by mats-claassen** [comment]
Sorry, it does not work for inline cells.
If you want to change how a type of cell looks by default, look here [How to change the default appearance of a certain cell](https://github.com/xmartlabs/XLForm#how-to-change-the-default-appearance-of-a-certain-cell)
If you just want to change a single row and you cannot customize that row's cell with cellConfig then the best way to solve this, currently, is by overriding the following method in your XLFormViewController subclass:
```objc
-(void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath
{
    [super tableView:tableView willDisplayCell:cell forRowAtIndexPath:indexPath];
    if (<is_my_cell>){
          ...
    }
}
```

**Comment by focusedonfit** [comment]
Overriding willDisplayCell allowed me to customize the inline datepicker 

Thank you
