### ISSUE TITLE
Override entire form.disabled for specific rows/cells

### ISSUE THREAD

**Issue by jdgong** [xmartlabs/XLForm#507]
Hi
In short, I am trying to keep certain cells/rows always editable and some non-editable, while all others controlled by the self.form.disable. Is there an way to achieve that? Thanks!

**Comment by mats-claassen** [comment]
Hi
At this moment no. The form.disable will disable all the form. If you want to disable some of the rows you will have to do it for each row.

**Comment by jdgong** [comment]
Thanks for your reply. If I want to implement an override function to achieve "always enable" for some rows, where should I start? Any suggestions?

**Comment by mats-claassen** [comment]
Well, you could subclass XLFromRowDescriptor and override the `isDisabled` function to return NO always. Then you should use your newRowDescriptor for your always enabled rows.
