### ISSUE TITLE
Reordering Cell

### ISSUE THREAD

**Issue by afnan-ahmad** [xmartlabs/XLForm#51]
I'm wondering if it has the functionality to reorder the row in a table view, Or you have any plans to do it in near future?

**Comment by mtnbarreto** [comment]
@afnan-ahmad  It would be a good feature but I will prioritise another features over it because there are no much people interested in it.

**Comment by mtnbarreto** [comment]
@afnan-ahmad we have implemented reordering functionality and improved insertion and deletion on multivalued sections. Take a look at master branch examples. 

Regards

**Comment by afnan-ahmad** [comment]
@mtnbarreto Great work! :thumbsup:
