### ISSUE TITLE
how trans data to  viewControllerClass instance?

### ISSUE THREAD

**Issue by loufq** [xmartlabs/XLForm#510]
when use  XLFormRowDescriptorTypeSelectorPush type
how do i  trans data to viewControllerClass  instance ,not display  value?

**Comment by mats-claassen** [comment]
Hi,
Your pushed viewController has to conform to the XLFormRowDescriptorViewController protocol. Then you will have access to the pushing rowDescriptor and from there to the whole form.
Have a look at https://github.com/xmartlabs/XLForm#how-to-set-up-a-pushed-view-controller
