### ISSUE TITLE
Push to controller from UIButton inside cell?

### ISSUE THREAD

**Issue by oscarjiv91** [xmartlabs/XLForm#516]
Is it possible to call another controller from a button inside the cell to set a field?
I have this row: 
<img width="370" alt="captura de pantalla 2015-08-21 a las 21 29 02" src="https://cloud.githubusercontent.com/assets/4256218/9421895/de62b480-484b-11e5-80d1-27c264d7103e.png">

And I want the "record" to open another UIView or UIViewcontroller to start recording something. Each row has three fields. I managed to set the "field" with two text values. But to start recording, I need to open another view with the necessary buttons. Is this possible?

**Comment by mats-claassen** [comment]
Hi, you have to create a custom row for this.
When that button is tapped you can just push the new view controller. You can also have a modal controller pop up but this is not in the scope of XLForm.
