### ISSUE TITLE
can XLForm appear in storyboard?

### ISSUE THREAD

**Issue by yongcs76** [xmartlabs/XLForm#518]
hi 

i'm new in using XLForm, and when using the XLForm, there are certain image i want to put in certain row and align it at specific location. I can only do this using storbyboard as i can use the auto layout etc. I can't do it using swift code (as i'm not that good in Xcode).

is this possible? if yes, how can i "enable" it in storyboard? 

or in other words can the XLForm show the design during design in storyboard and not only when execution?

**Comment by mojidabckuu** [comment]
@yongcs76 
Unfortunately no. Make live cell filling, editing using reusable xibs, ect. is not possible in Xcode. Here you can only to code(Objc, Swift) the look of your form and use `rowType` as a behavior of cell.
