### ISSUE TITLE
XLForm not navigating for Multiple selectors

### ISSUE THREAD

**Issue by halbano** [xmartlabs/XLForm#520]
Hi all, I'm a newbie using this and I can't get things working properly for my setup. 
I have my FilterViewController class inheriting from XLFormViewController and I want to have some selectors on this. 

As I can see the XLFormViewController already has a table property that is managed by him "under the hood". When I click my multiple selection row (now configured in the same way as the examples), row is been selected but the navigation to the options VC is not fired. 
Is any additional setup needed doing this kind of navigation? Maybe something related with the table delegate? Or the navigation controller involved? 

I can't also get working selector push and seems that the problem is the same. 

Many thanks.
Regards,
Hernán

**Comment by halbano** [comment]
@mtnbarreto Any help?

**Comment by mtnbarreto** [comment]
@halbano 
I guess you are not using custom cells.

Make sure your form view controller is embedded in a nav controller, we invoke pushViewController in the navigation VC to make the transition. 

If this doesn't work, upload a project to reproduce the issue and I will look into it.

Regards

**Comment by halbano** [comment]
Perfect, thanks for your response and time. The problem was the navigation controller. To clarify, In which scenarios I need to call [super didSelectRowAtIndexPath]? I don't have at this point custom cells, also I'm not implementing didSelectRowAtIndexPath in this case. Only using the table delegate implemented by you. 

Best, 
Hernán

**Comment by mats-claassen** [comment]
Hi,
You just have to call `[super didSelectRowAtIndexPath]` when you are implementing `didSelectRowAtIndexPath`. And if you do implement it you should always call to super.

**Comment by ciumexan** [comment]
hello
i am launching XL FORM  a modal view. can this be done? Thanks
