### ISSUE TITLE
XLFormTextFieldLengthPercentage undeclared identifier

### ISSUE THREAD

**Issue by mapzter** [xmartlabs/XLForm#524]
Hi,

I'm trying to modify the textfield's length by using [row.cellConfigAtConfigure setObject:[NSNumber numberWithFloat:0.7] forKey:XLFormTextFieldLengthPercentage];.

However, there's an error saying it's an undeclared identifier.

**Comment by mtnbarreto** [comment]
@mapzter try importing <XLForm/XLFormTextFieldCell.h> or using "textFieldLengthPercentage" string directly instead of XLFormTextFieldLengthPercentage .

Regards

**Comment by mapzter** [comment]
@mtnbarreto thanks! but it did not work. I tried importing XLFormTextFieldCell.h but it still won't work.
Maybe there is another way to adjust the size of the textfield or detailsTextLabel? It gets cutoff when the question is very long.

Regads

![ios simulator screen shot aug 28 2015 9 51 32 am](https://cloud.githubusercontent.com/assets/3162438/9537423/8083aaa8-4d6a-11e5-85f6-16a037003ec0.png)

**Comment by mapzter** [comment]
@mtnbarreto I got it working! 
Apparently my XLFormTextFieldCell.h and XLFormTextFieldCell.m files were different from the files in the repo. It's weird since I'm already using XLForm (3.0.0) in my pod.
