### ISSUE TITLE
UITableViewCell Layout Styles  (UI/UX, responsive design)

### ISSUE THREAD

**Issue by sedwo** [xmartlabs/XLForm#525]
XLForm seems fixed to a ```UITableViewCellStyleDefault``` placing the title and textfield beside each other on the same line.  This isn't an ideal UI/UX on a smaller iPhone screen.

Does this engine support alternative cell layouts that perhaps match ```UITableViewCellStyleSubtitle``` and place the title and textfield on separate lines within the cell to utilize the full width of the screen?

For reference on responsive design regarding form layouts:
http://baymard.com/blog/mobile-form-usability-label-position

**Comment by PabloLerma** [comment]
You can create them on your own as custom UITableViewCell (check the [CustomRows examples] (https://github.com/xmartlabs/XLForm/tree/master/Examples/Objective-C/Examples/CustomRows)).

**Comment by mojidabckuu** [comment]
@sedwo 
You can subclass original cell from the kit and configure layout behaviors as you need.
Check `XLFormTextFieldCell.m` file and method `-(NSArray *)layoutConstraints`. You can also create similar constraints and handle different layouts depending on device orientation.
