### ISSUE TITLE
TableViewController cannot bind the XLFormViewController class

### ISSUE THREAD

**Issue by priscillatong** [xmartlabs/XLForm#526]
xcode6.4
The TableViewController View in StoryBoard, in identity inspector ,and the custom class textfield, I can not select  my custom class inherit from  XLFormViewController, and input  the custom class name in the textfield, I can not save it , after change focus back to the inspector, the textfield is still empty.
How can I bind the class to the View ? And how does the Examples archive?

**Comment by mtnbarreto** [comment]
@priscillatong 

It seems you made a common mistake, XLFormViewController extends from UIViewController, not from UITableViewController so you should drag a UIViewController into the Storyboard and not a UITableViewController.

Regards
