### ISSUE TITLE
Saving formValues? 

### ISSUE THREAD

**Issue by danr777** [xmartlabs/XLForm#528]
Hello,

I have tried several different ways, but the fact that it does not fall under "NSCoding rules" (sorry new to this topic?)

I can't simply writeToFile on the NSDictionary..
I tried encoding it as JSON and XML and tried a NSKeyedArchiver to no avail..

Does anyone have any pointers to handle the saving and loading of formValues?
Would I have to resort to looping it in on form setup.?

I'd like to use the setValuesForKeysWithDictionary function...

Might be missing something very simple!, thanks in advance!!

**Comment by mapzter** [comment]
I use Realm (https://realm.io) to save and load data for my forms.

**Comment by danr777** [comment]
any other input? :)

**Comment by mapzter** [comment]
First try looking at the docs of Realm.

You need to create objects first. I'll use their example
e.g. (I used name as primary key)
```
// Define your models like regular Objective-C classes
@interface Dog : RLMObject
@property NSString *name;
@property NSInteger age;
@end

// Implementations
@implementation Dog
+ (NSString *)primaryKey{
    return @"name";
}
@end 
```

Then load the form and check if it's an update.

```
// Form Loader
// If is_update is true, search realm for a dog with the name 'dog_name'.
Dog *dog;
NSPredicate *predicate = [NSPredicate predicateWithFormat:@"name == [c] %@",self.dog_name];
if (self.is_update){
     dog = [[Dog objectsWithPredicate:predicate] firstObject];
 }

row = [XLFormRowDescriptor formRowDescriptorWithTag:@"name" rowType:XLFormRowDescriptorTypeText title:@"Dog Name"];
if (self.is_update){
     row.value = dog.name;
 }

row = [XLFormRowDescriptor formRowDescriptorWithTag:@"age" rowType:XLFormRowDescriptorTypeInteger title:@"Dog Age"];
if (self.is_update){
     row.value = dog.age;
 }

//Submit Form
-(void) submit{
self.realm = [RLMRealm defaultRealm];

Dog *dog_submitted = [ Dog new];
[self.realm beginWriteTransaction];
XLFormRowDescriptor *row;
row = [self.form formRowWithTag:@"name"];
dog_submitted.name = row.value;

row = [self.form formRowWithTag:@"age"];
dog_submitted.age = row.value;

//Check the name (Primary Key in realm) in the form. If its unique, it will create a new record in realm. If it's not, update the dog with the same name.
[Dog createOrUpdateInDefaultRealmWithValue:dog_submitted];
[self.realm commitWriteTransaction];
}

```

Hope this helps you. :)

**Comment by mats-claassen** [comment]
Hey @danr777 have you solved this issue?

**Comment by danr777** [comment]
No not really, I don’t want to use Realm.

**Comment by edwinlin** [comment]
I believe you're looking for the -(NSDictionary *)formValues method.

//push all your key/values
NSDictionary *dict = [self formValues];

//grab value with tags as keys
NSLog(@"%@", dict[@"your-tag"]);
