### ISSUE TITLE
How to pass data to XLFormOptionsViewController?

### ISSUE THREAD

**Issue by ridvank** [xmartlabs/XLForm#530]
Hi everyone,
I am trying to pass data to XLFormOptionsViewController class. Here is my code:

        row = XLFormRowDescriptor(tag: "repeat", rowType:XLFormRowDescriptorTypeSelectorPush, title:"Repeat")
        row.value = XLFormOptionsObject(value: 0, displayText: "a")
        row.selectorTitle = "Repeat"
        row.action.viewControllerClass = RepeatViewController.self
        
        row.selectorOptions = [XLFormOptionsObject(value: 0, displayText: Globals.sharedInstance.localize(path: "recurring.never")),
            XLFormOptionsObject(value: 1, displayText: "a"),
            XLFormOptionsObject(value: 2, displayText: "b"),
            XLFormOptionsObject(value: 3, displayText: "c"),
            XLFormOptionsObject(value: 4, displayText: "d")
        ]
        section.addFormRow(row)

RepeatViewController is a subclass of XLFormOptionsViewController. How to pass data to RepeatViewController class?

**Comment by Asinox** [comment]
Any update about it?, i am tying the same thing
Thanks!

**Comment by mojidabckuu** [comment]
@ridvank @Asinox 
In this case `RepeatViewController` must implement `XLFormRowDescriptorViewController` in which you can find property like `rowDescriptor`. When your instance of `RepeatViewController` than viewControllerToShow.rowDescriptor will be filled by cells rowDescriptor instance.
