### ISSUE TITLE
multivaluedAddButton displays when form is disabled

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#533]
When a form is disabled the multivaluedAddButton still shows.  It makes sense to hide these rows if the form is disabled as the user can't add a row to a disabled form.

**Comment by focusedonfit** [comment]
Any thoughts on this one?

**Comment by mats-claassen** [comment]
I think it is OK when these rows are disabled when the form is disabled. 
You can obviously hide them manually when you set the form to be disabled

**Comment by m-revetria** [comment]
Closing this due to lack of response
