### ISSUE TITLE
Is UITableViewCell basic cell types supported?

### ISSUE THREAD

**Issue by conradwt** [xmartlabs/XLForm#538]
Is it possible to use the basic UITableViewCell types to configure with XLForm?  I simply would like to use the properties:  textLabel and imageView.

**Comment by mats-claassen** [comment]
You can make a custom cell that just extends from `XLFormBaseCell` because it has to conform to the `XLFormDescriptorCell` protocol.

**Comment by conradwt** [comment]
@mats-claassen  OK,  I'll try to adding these subclasses to my project by taking a look at the examples.  Wouldn't this be a good candidate to add these standard UITableViewCell types to the XLForm core?
