### ISSUE TITLE
Row show/hide causing exception in XLFormRowDescriptor.m

### ISSUE THREAD

**Issue by earthabbey** [xmartlabs/XLForm#539]
I am getting an exception and I am not sure why. It is stopping on line 331 of XLFormRowDescriptor.m:

```
            self.hidePredicateCache = @([_hidden evaluateWithObject:self substitutionVariables:self.sectionDescriptor.formDescriptor.allRowsByTag ?: @{}]);
```
This is in the method ```-(BOOL)evaluateIsHidden``` 

This exception is happening because I have a row hidden based on a previous row with a switch. 

This is the code causing the exception:

```
    actionTakenRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"firstAidGiven" rowType:XLFormRowDescriptorTypeBooleanSwitch title:@"First Aid Given"];
    actionTakenRow.value = @0;
    [actionTakenSection addFormRow:actionTakenRow];
    
    actionTakenRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"firstAidGivenBy" rowType:XLFormRowDescriptorTypeText];
    actionTakenRow.hidden = [NSString stringWithFormat:@"$%@==0", @"firstAidGiven"];
    [actionTakenRow.cellConfigAtConfigure setObject:@"First Aid Given By" forKey:@"textField.placeholder"];
    [actionTakenSection addFormRow:actionTakenRow];
```

specifically this row: ``` actionTakenRow.hidden = [NSString stringWithFormat:@"$%@==0", @"firstAidGiven"]; ```

Any ideas?

**Comment by mats-claassen** [comment]
Hi, are you sure it is a crash or is it just an exception while debugging?

**Comment by earthabbey** [comment]
Hi, apologies. You are correct, it is an exception. However I work with someone who treats all exceptions as crashes and doesn't want any errors of any kind.

Could you help me understand why this is happening?

**Comment by mats-claassen** [comment]
It is happening because the row has no section yet or the section has no form yet.
In your case you are setting `actionTakenRow.hidden = ...` before `[actionTakenSection addFormRow:actionTakenRow];`

**Comment by earthabbey** [comment]
oh! I thought it operated like a wrapper and had to be last. This makes sense. Thank you so much for your quick replies!

**Comment by earthabbey** [comment]
I have tried moving the ```addFormRow``` above the hidden line. The exception still exists. Did I misunderstand what you meant?

```
   actionTakenRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"firstAidGivenBy" rowType:XLFormRowDescriptorTypeText];
    [actionTakenSection addFormRow:actionTakenRow];
    actionTakenRow.hidden = [NSString stringWithFormat:@"$%@==0", @"firstAidGiven"];
    [actionTakenRow.cellConfigAtConfigure setObject:@"First Aid Given By" forKey:@"textField.placeholder"];
```

**Comment by mojidabckuu** [comment]
@earthabbey 
I putted your code into sample app like this
```obj-c
XLFormSectionDescriptor *sectionAid = [XLFormSectionDescriptor formSection];
    [formDescriptor addFormSection:sectionAid];
    
    XLFormRowDescriptor *actionTakenRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"firstAidGiven" rowType:XLFormRowDescriptorTypeBooleanSwitch title:@"First Aid Given"];
    actionTakenRow.value = @0;
    [sectionAid addFormRow:actionTakenRow];
    
    actionTakenRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"firstAidGivenBy" rowType:XLFormRowDescriptorTypeText];
    actionTakenRow.hidden = [NSString stringWithFormat:@"$%@==0", @"firstAidGiven"];
    [actionTakenRow.cellConfigAtConfigure setObject:@"First Aid Given By" forKey:@"textField.placeholder"];
    [sectionAid addFormRow:actionTakenRow];
```
And it works without any exceptions.

**Comment by earthabbey** [comment]
I put your code into my app, changing the parameter names, and I get an exception.

<img width="965" alt="screen shot 2015-09-05 at 11 12 46 pm" src="https://cloud.githubusercontent.com/assets/11657280/9702863/c216d9e4-5423-11e5-940f-31f250c55ac5.png">

It is related to "evaluateIsHidden". This is in XLFormRowDescriptor.m.

When I po self.sectionDescriptor I get nil. Could this be related to that? Here is the code that is causing the exception:

```self.hidePredicateCache = @([_hidden evaluateWithObject:self substitutionVariables:self.sectionDescriptor.formDescriptor.allRowsByTag ?: @{}]);```

Could that be the problem?

**Comment by mojidabckuu** [comment]
@earthabbey 
It looks like you enabled 'breakpoint when exception occurs' and it makes you confused :)
So, your app always stop in this try/catch block when it raises an exception.
Just try to 'Continue' running by '⌃⌘Y' or by pressing button on console toolbar.
In other case show the crash trace from the log if crash occurs and your applications is terminated :)

**Comment by earthabbey** [comment]
No, I know that it will work if I turn off all exceptions. I'm wondering why this is happening though? I have been trained to have no exceptions in my projects. I know that it works if I turn that off, but I would still like to understand why this is happening.

**Comment by mojidabckuu** [comment]
@earthabbey 
In this case I think that the cause is 'nil' value passed to evaluate method.
try/catch is bad experience and objc/c/c++ communities try to avoid this practice because of performance.

**Comment by earthabbey** [comment]
Okay, thank you. What do you mean by "try/catch"?

**Comment by mojidabckuu** [comment]
@earthabbey 
```objc
@try { 
} 
@catch (NSException *exception) {
}
```
