### ISSUE TITLE
Pass data to Dynamic selector view controller

### ISSUE THREAD

**Issue by shekbagg** [xmartlabs/XLForm#543]
What is the best way to pass data to the dynamic selector view controller. I need to pass a dictionary to the presented table view controller

**Comment by riccardo-destefani** [comment]
Hi shekbagg,
i solved passing a dictionary to the view controller setting it to row.value.
This dictionary contains 
- your dictionary to present
- dictionary or object that is the true selected value of the view controller

When view controller load, it reads data from row.value and get 
- data to present from dictionary
- previous selected value (first time it is nil or empty...)
