### ISSUE TITLE
Actions for UIButtons from XIB not work (iOS 9, XLForm 3.0.1 )

### ISSUE THREAD

**Issue by filippovdev** [xmartlabs/XLForm#546]
I have couple custom XLFormBaseCell's with connected XIB, for register I use this code in AppDelegate:
self.registerNewXLFormCellType("MyCustomTextCellView", key: "MyCustomTextCell")
In XIB "MyCustomTextCellView" I have buttons, and this buttons not working, just don't call TouchUpInside action (make with @IBAction).

At the end find solution, in configure method I add :

let plusButton = self.plusButton (self.plusButton this is @IBOutlet from XIB)
self.addSubview(plusButton)

and all work again.

**Comment by mats-claassen** [comment]
Hi @filippovdev did you have a look at the custom rows in the Examples? The `XLFormWeekDaysCell` works with both IBOutlet and IBAction.
Did you update `XLFormViewController.cellClassesForRowDescriptorTypes`?

**Comment by m-revetria** [comment]
Closing this due to lack of response
