### ISSUE TITLE
Accessibility label on cells

### ISSUE THREAD

**Issue by popei69** [xmartlabs/XLForm#549]
Hey guys,

I would like to know what is the best way to add an accessibility label on XLFormButtonCell and specially on XLFormSelectorCell (and pickers inside).

The main goal is to create UI automation testing.

Thanks,
Ben

**Comment by popei69** [comment]
Hi there,

I find a way for XLFormButtonCell by adding an accessibility label to the textLabel inside the cell, but still searching for XLFormSelectorCell

**Comment by mats-claassen** [comment]
You can set the accessibility label of any cell like this:
```objc
XLFormRowDescriptor* row = [self.form formRowWithTag:kSelectorPickerView];
XLFormSelectorCell* cell = [row cellForFormController:self];
cell.accessibilityLabel = @"Hi there";
```
For more information about accessing picker views see if [this](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIPickerViewAccessibilityDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIPickerViewAccessibilityDelegate/pickerView:accessibilityLabelForComponent:) helps you
