### ISSUE TITLE
Bug: XLFormRowDescriptor.action.viewControllerClass ignored for rowType:XLFormRowDescriptorTypeMultipleSelector

### ISSUE THREAD

**Issue by memmons-ntst** [xmartlabs/XLForm#550]
When using a row type of `XLFormRowDescriptorTypeMultipleSelector` the custom view controller specified in `row.action.ViewControllerClass` is ignored and the default `XLFormOptionsViewController` is used instead.

**Comment by Mrhyuan** [comment]
Same issue

**Comment by cerupcat** [comment]
Any chance of getting this merged?
