### ISSUE TITLE
Setting row of type XLFormRowDescriptorTypeSelectorPickerViewInline to disabled removes the next row from the form

### ISSUE THREAD

**Issue by pdenis1** [xmartlabs/XLForm#553]
I have a form with a selector, followed by a text field.  When the selector row is disabled (with the inline selector NOT visible), the next row gets removed.  

I believe the bug is in XLFormInlineSelectorCell.m, in the resignFirstResponder method.  Regardless of whether the row is already the first responder or not, it removes the next form row.  It should only do this if the selector row IS currently the first responder.

This fix seems to work locally:
```Objective-C
-(BOOL)resignFirstResponder
{
    NSIndexPath * selectedRowPath = [self.formViewController.form indexPathOfFormRow:self.rowDescriptor];
    NSIndexPath * nextRowPath = [NSIndexPath indexPathForRow:selectedRowPath.row + 1 inSection:selectedRowPath.section];
    XLFormRowDescriptor * nextFormRow = [self.formViewController.form formRowAtIndex:nextRowPath];
    XLFormSectionDescriptor * formSection = [self.formViewController.form.formSections objectAtIndex:nextRowPath.section];
    BOOL result = [super resignFirstResponder];

*** BEGIN FIX***
    if (result) {
        [formSection removeFormRow:nextFormRow];
    }
***END FIX***
    return result;
}
```

**Comment by mats-claassen** [comment]
I will fix this soon. Thanks
