### ISSUE TITLE
UI breaks on iPad Pro in Landscape

### ISSUE THREAD

**Issue by shekbagg** [xmartlabs/XLForm#554]
The width of xlform rows does not stretch to bounds of the screen, instead it centers itself. I would assume using autolayout should have mitigated this issue. Here is the screenshot of how the UI looks.
<img width="1376" alt="screen shot 2015-09-14 at 5 33 43 pm" src="https://cloud.githubusercontent.com/assets/2446366/9846781/12ba5bde-5b07-11e5-99b6-03ac47acf1b9.png">
<img width="1377" alt="screen shot 2015-09-14 at 5 33 57 pm" src="https://cloud.githubusercontent.com/assets/2446366/9846782/13a650a2-5b07-11e5-800c-a7334b00c915.png">

**Comment by bmichotte** [comment]
It is not only iPad pro, it's all iPad

![capture d ecran 2015-09-17 a 14 45 11](https://cloud.githubusercontent.com/assets/235510/9933398/e10ee9ce-5d4a-11e5-940e-33451f4034a2.png)
![capture d ecran 2015-09-17 a 14 47 16](https://cloud.githubusercontent.com/assets/235510/9933418/03fdcae0-5d4b-11e5-9af2-8037007a2533.png)

**Comment by conradwt** [comment]
@shekbagg @bmichotte Do anyone of you have an Xcode 7 project which reproduces this issue?

**Comment by bmichotte** [comment]
@conradwt the screenshot i took came from the XLForm obj-c examples

**Comment by bmichotte** [comment]
@mats-claassen Any hint / workaround / idea on the subject ? 

My guess is there's something wrong with constraints, but I can't figure what. 

This issue is really annoying, I'm waiting for a solution to push an iOS 9 update of several apps

**Comment by tonimoeckel** [comment]
Same here .. I'm going to find a solution next week, as I also need to update some apps for iOS 9

**Comment by mats-claassen** [comment]
Hi, could you try [this](http://stackoverflow.com/questions/29572043/ios-8-3-uitableview-cell-not-aligned-indentation-to-the-left) to see if it fixes the problem?

**Comment by bmichotte** [comment]
None of the solution in this thread help

What's really strange is some stuff works. If you take the examples, the "iOS Calendar Event Form" looks like this (looks correct)

![capture d ecran 2015-09-24 a 20 19 38](https://cloud.githubusercontent.com/assets/235510/10082367/9a8bae6a-62f9-11e5-9799-a3b615092d22.png)

But, if I open the "repeat" selector, I got this (which is not correct)

![capture d ecran 2015-09-24 a 20 20 40](https://cloud.githubusercontent.com/assets/235510/10082402/bef5b228-62f9-11e5-857d-782b55a71ece.png)

**Comment by mats-claassen** [comment]
I think I found a bug with the constraints we are setting for some fields.
Will try to make a compatible solution soon.

**Comment by bmichotte** [comment]
@mats-claassen This is way better with your commit... except multi-value sections

![capture d ecran 2015-09-26 a 10 41 33](https://cloud.githubusercontent.com/assets/235510/10116651/39fdff56-643b-11e5-9789-48d5f3334c04.png)

**Comment by zhjuncai** [comment]
I upgrade XLForm to the latest version but due to this issue, I can't submit my app to apple store. so wondering if I could help here to track down the root cause.

**Comment by RobertNNms** [comment]
Hi,

I have a same problem, only on iPAD Landscape ios 9, but ios 8.x works.

Regards

**Comment by jakubprusa** [comment]
Possible fix here:

Pull request: SHA: 6100c7ad78b9c304099504d561d199d47b545507

**Comment by RobertNNms** [comment]
Works for me!

Thanks

2015-10-28 15:29 GMT+01:00 jakubprusa <notifications@github.com>:

**Comment by bmichotte** [comment]
@mats-claassen @mtnbarreto Unfortunately, https://github.com/xmartlabs/XLForm/commit/f2d41467826015a9dc196c402b6903a1717f9370 is not enough, please also consider https://github.com/xmartlabs/XLForm/pull/628 !
