### ISSUE TITLE
Setting textLabel properties on cellConfig

### ISSUE THREAD

**Issue by jeremy-idialogs** [xmartlabs/XLForm#556]
Hi,

Looking to be able to make the text entry in a cell clear automatically on entry of a value.
Trying something like this, but it doesn't seem to work:

row.cellConfig.setObject(true, forKey: "textLabel.clearsOnInsertion")

Thanks,

**Comment by mats-claassen** [comment]
HI, I believe it is the textField you want to clear right?
Try this:
```objc
row.cellConfig.setObject(true, forKey: "textField.clearsOnBeginEditing")
```
