### ISSUE TITLE
Can insert LeftRight Cell

### ISSUE THREAD

**Issue by wieseljonas** [xmartlabs/XLForm#569]
I tried to do an insert only cell with a leftright selector cell and I get this error

`'NSInvalidArgumentException', reason: '-[XLFormOptionsObject copyWithZone:]: unrecognized selector sent to instance 0x7fb0b063eae0'`

        section = XLFormSectionDescriptor.formSectionWithTitle("XLFormSectionInsertModeButton With Inline Cells", sectionOptions:XLFormSectionOptions.CanInsert, sectionInsertMode:XLFormSectionInsertMode.Button)
        
        row = XLFormRowDescriptor(tag: nil, rowType: XLFormRowDescriptorTypeSelectorPush, title:"Add")
        
        row.leftRightSelectorLeftOptionSelected = XLFormOptionsObject(value: 1, displayText: "Main")
        let rightOptions: [AnyObject] = [XLFormOptionsObject(value:0, displayText: "Right Option 1"), XLFormOptionsObject(value: 1, displayText: "Right Option 2"), XLFormOptionsObject(value: 2, displayText: "Right Option 3"), XLFormOptionsObject(value: 3, displayText: "Right Option 4"), XLFormOptionsObject(value: 4, displayText: "Right Option 5")]
        
        var leftRightSelectorOptions = [AnyObject]()
        var mutableRightOptions: [AnyObject] = rightOptions
        mutableRightOptions.removeAtIndex(0)
        var leftRightSelectorOption: XLFormLeftRightSelectorOption = XLFormLeftRightSelectorOption(leftValue: XLFormOptionsObject(value: 0, displayText: "Main"), httpParameterKey: "option_1", rightOptions: mutableRightOptions)
        leftRightSelectorOptions.append(leftRightSelectorOption)
        mutableRightOptions = rightOptions
        mutableRightOptions.removeAtIndex(1)
        leftRightSelectorOption = XLFormLeftRightSelectorOption(leftValue:XLFormOptionsObject(value:1, displayText: "Work"), httpParameterKey: "option_2", rightOptions: mutableRightOptions)
        leftRightSelectorOptions.append(leftRightSelectorOption)
        mutableRightOptions = rightOptions
        mutableRightOptions.removeAtIndex(2)
        leftRightSelectorOption = XLFormLeftRightSelectorOption(leftValue:XLFormOptionsObject(value:2, displayText: "Home"), httpParameterKey: "option_3", rightOptions: mutableRightOptions)
        leftRightSelectorOptions.append(leftRightSelectorOption)
        mutableRightOptions = rightOptions
        mutableRightOptions.removeAtIndex(3)
        leftRightSelectorOption = XLFormLeftRightSelectorOption(leftValue:XLFormOptionsObject(value:3, displayText: "Other"), httpParameterKey: "option_4", rightOptions: mutableRightOptions)
        leftRightSelectorOptions.append(leftRightSelectorOption)
        row.selectorOptions = leftRightSelectorOptions
        row.value = XLFormOptionsObject(value:3, displayText: "Right Option 4")
       
        section.multivaluedRowTemplate = row
        form.addFormSection(section)

**Comment by elsurudo** [comment]
Had the same issue. My workaround was to only set the `formRow.leftRightSelectorLeftOptionSelected` after the cell was already initialized (in my case in the `formRowHasBeenAdded` delegate callback, since it's part of a multi-valued section)

**Comment by wieseljonas** [comment]
@elsurudo  Thanks for your answer. Finally I created a custom cell to meet my need.

**Comment by elsurudo** [comment]
IMO the LeftRight cell isn’t that well thought out, and isn’t that extensible. I actually created a replacement myself as well.

Right now, I’m trying to to get the form value out for the _left_ side of the cell – any luck with that?
