### ISSUE TITLE
can i set XLFormRowDescriptorTypeBooleanSwitch click event? 

### ISSUE THREAD

**Issue by a72** [xmartlabs/XLForm#570]
can i set XLFormRowDescriptorTypeBooleanSwitch click event?

**Comment by adil-appifytech** [comment]
I believe you have to implement following delegate method

```-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)rowDescriptor oldValue:(id)oldValue newValue:(id)newValue.```

In this method you can do something like this


```
    if ([rowDescriptor.tag isEqualToString:@"YOURSWITCHTAG"]) {

        NSLog(@"%@", [newValue valueData]);
    }```

**Comment by a72** [comment]
Thank you. That's it!
