### ISSUE TITLE
Changing UISwitch Control Attributes

### ISSUE THREAD

**Issue by adil-appifytech** [xmartlabs/XLForm#571]
I want to change the color and layer corner radius of UISwitch. I tried something below but it's not working :(

```[row.cellConfig setObject:[UIColor redColor] forKey:@"accessoryView.onTintColor"];```

**Comment by mats-claassen** [comment]
Hi, I think you wanted to say `tintColor` and not `onTintColor` right?
Did you try setting `accessoryView.layer.cornerRadius` for the cornerRadius?
