### ISSUE TITLE
TableView Not Scrolling Up

### ISSUE THREAD

**Issue by adil-appifytech** [xmartlabs/XLForm#572]
My TableView in Scrolling Up as I move to next textfields/textviews in my view. I was wondering what's missing?

**Comment by fanstudiouk** [comment]
Same here. Any fix?

**Comment by adil-appifytech** [comment]
@fanstudiouk - nopes :(

**Comment by fanstudiouk** [comment]
found the fix. Simply implement the method "viewWillAppear" and IMPORTANT: add super.viewWillAppear(animated) on the first line in your XLFormViewController subclass. The super call is mandatory apparently.

**Comment by adil-appifytech** [comment]
@fanstudiouk - It fixed for me too. Thanks for sharing the solution.

**Comment by batnom** [comment]
Many thanks for this!
