### ISSUE TITLE
Hiding a row based on PickerView Selected Field

### ISSUE THREAD

**Issue by adil-appifytech** [xmartlabs/XLForm#573]
I want to hide another row based on PickerView I select, how I can do that?

**Comment by mats-claassen** [comment]
This can be done just like any other row as well. Look [here](https://github.com/xmartlabs/XLForm#make-a-row-or-section-invisible-depending-on-other-rows-values)
This worked for me:
`row.hidden = [NSString stringWithFormat:@"$%@ == 'Option 1'", kPickerViewInline];`
