### ISSUE TITLE
How to set label color of row while it has focus

### ISSUE THREAD

**Issue by 3cooper** [xmartlabs/XLForm#574]
I'm trying to highlight rows with validation errors.  I am using the following:

```
let validationErrors : Array<NSError> = self.formValidationErrors() as! Array<NSError>
if (validationErrors.count > 0){
  for error in validationErrors {
    let userInfo = error.userInfo
    if let validationStatus = userInfo[XLValidationStatusErrorKey],
      row = validationStatus.rowDescriptor {
        row!.cellConfig.setObject(UIColor.redColor(), forKey: "textLabel.color")
        row!.cellConfig.setObject(UIColor.redColor(), forKey: "textLabel.highlightedTextColor")

        self.tableView.reloadData()
    }
  }
```

This will change the color of the text label until it gets focus.  Once it gets focus the label turns blue.  I am new to this project and was unable to find this in the documentation.  Any help would be great.

**Comment by 3cooper** [comment]
For clarification, I would like the label to maintain the selected color when the row is the active row instead of it turning blue.

**Comment by cerupcat** [comment]
Did you find a solution to this?

**Comment by RpX974** [comment]
It's "self.tintColor" =)

**Comment by mats-claassen** [comment]
When the row gets highlighted then the tintColor is set to the label so you might want to change the tintColor of the cell to achieve that as @RpX974 mentioned

**Comment by AlexHedley** [comment]
From the example in [InputsFormViewController](https://github.com/xmartlabs/XLForm/blob/master/Examples/Objective-C/Examples/Inputs/InputsFormViewController.m)

````objc
// Name
row = [XLFormRowDescriptor formRowDescriptorWithTag:kName rowType:XLFormRowDescriptorTypeText title:@"Name"];
row.required = YES;
[section addFormRow:row];
````

Add:
````objc
[row.cellConfig setObject:[UIColor redColor] forKey:@"self.tintColor"];
````

---

Don't do this:
````objc
[row.cellConfig setObject:[UIColor redColor] forKey:@"textLabel.tintColor"];
````
