### ISSUE TITLE
XLFormDescriptorDelegate is not working when add row at runtime

### ISSUE THREAD

**Issue by v2tmobile** [xmartlabs/XLForm#576]
when I add new row on runtime, I don't use XLFormDescriptorDelegate it's working nice :) but if I use XLFormDescriptorDelegate to handle formRowHasBeenAdded it's is not working. XLFormRowDescriptor was added but form is not reload.
I have try to override the XLFormDescriptorDelegate methods of 'XLFormViewController' on MultivaluedFormViewController (your's example project) but it's not working too.

**Comment by mats-claassen** [comment]
Hi, when you override the delegate methods then you must call super in each method. Did you do that?

**Comment by v2tmobile** [comment]
Yeah, thank you for your support. I did not even use it anymore, I will try later.

**Comment by m-revetria** [comment]
closing this due to lack of response
