### ISSUE TITLE
Transparent Background Color PickerView

### ISSUE THREAD

**Issue by muzammilpeer** [xmartlabs/XLForm#58]
If i click on datetime field then the picker shown to me at the bottom of the screen is transparent if i click on any textfield and then go back to any pickerview related field then it's background color changed from transparent to white.

**Comment by mtnbarreto** [comment]
@muzammilpeer i couldn't reproduce the issue on iOS 8 using the master branch version. It seems to me that it was a iOS issue related to inputViews. 
Could you provide me more information on how to reproduce it? device, ios version, etc. 
Feel free to re-open the issue if you are still having the bug.
Regards
