### ISSUE TITLE
Decimal Precision Errors in XLFormTextFieldCell

### ISSUE THREAD

**Issue by cbh2000** [xmartlabs/XLForm#580]
Try typing in `8.14` into a decimal field, and you will see it become `8.14000000000001`. This is because floats and doubles aren't precise enough to represent 8.14 perfectly.

Some ideas:
- Change the underlying type to NSDecimalNumber or NSString
- Add support for "max decimal places" or rounding

**Comment by jeanmartin** [comment]
How is this a feature request and not a bug? Also, I could not find the 'duplicate' of this, could somebody point me to it?

**Comment by mats-claassen** [comment]
In fact this should be fixed already... Did you have this problem with the latest version?

**Comment by jeanmartin** [comment]
Ah, just upgraded and can confirm: it is fixed 👍
