### ISSUE TITLE
XLFormRowDescriptorTypeImage

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/XLForm#583]
I'd like to see a XLFormRowDescriptorTypeImage which would allow the display of an image, picking an image from the photo library (options of which album), or taking a photo (options of front or rear camera).

**Comment by tommypeps** [comment]
+1

**Comment by orlandoamorim** [comment]
+1

**Comment by adamrushy** [comment]
+1

**Comment by adamrushy** [comment]
I am about to add this functionality to an app I working on, happy to share this :+1:

**Comment by tommypeps** [comment]
@adamrushy  🎯

**Comment by rlaferla** [comment]
Awesome.  Please submit it!

**Comment by bmichotte** [comment]
@adamrushy For [ProMotion-XLForm](https://github.com/bmichotte/ProMotion-XLForm) (a RubyMotion wrapper for XLForm), I developed this row. 
If you _read_ Ruby, you could easily port it [xl_form_image_selector.rb](https://github.com/bmichotte/ProMotion-XLForm/blob/master/lib/ProMotion/XLForm/cells/xl_form_image_selector_cell.rb)

**Comment by tommypeps** [comment]
@bmichotte  👏

**Comment by adamrushy** [comment]
Thanks @bmichotte this is handy, I reckon will have something by end of this week :8ball:

**Comment by rlaferla** [comment]
Any update on this cool feature?

**Comment by rlaferla** [comment]
@adamrushy I could try to implement this but if you already have something started, it would be better to use your code so that we don't end up with two different implementations.  Is there anything you can share now?

**Comment by rlaferla** [comment]
bump

**Comment by bmichotte** [comment]
@mtnbarreto This can be closed with the merge of #645 !

**Comment by mtnbarreto** [comment]
:+1:
