### ISSUE TITLE
Best practice for initializing form with model object in XLFormViewController subclass?

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/XLForm#587]
I don't see an example, documentation or support for populating form values from a model object that is passed to a XLFormViewController view controller.  The examples I've seen construct the form and set the default values in the init methods BEFORE setting self.form.  If you set default values AFTER setting self.form, formRowDescriptorValueHasChanged: gets called and that may not be desirable.

Is there a way to toggle whether formRowDescriptorValueHasChanged: gets called?  Is there a better design pattern?  I ended up creating the form in one instance variable, setting the defaults in viewDidLoad and then setting self.form.  It works but it seems like there should be a better way to handle this common pattern.

**Comment by ksbecker** [comment]
This is how I've done it. A couple of notes; 1) I'm using Swift. 2) I'm using a single viewController to add and edit data.

I have 2 properties on the viewController, one of type of the model as an optional.  The other a boolean called isNewX and equal to false initially.

    class MyViewController : XLFormViewController {
        var person: Person?
        var isNewPerson = false
    }

On the viewload method I try to unwrap the optional model object and if it exists I set the value of the class-level optional object to the unwrapped version.  If it's nil I set the boolean to true. After the unwrapping attempt I call the initializeForm() method.  After the initializeForm call I then call the super.viewload method.

    override func viewDidLoad() {
        if let person = person {
            self.person = person
        } else {
            // I have a method to generate a new CoreData model object
            self.person = Person.CreateNewPerson(...)
            isNewPerson = true
        }

        initializeForm()

        super.viewDidLoad()
    }

Inside the initializeForm() method I use the boolean to determine how I should set the row value. I can set it to either the model value or, optionally, a default value.

    initializeForm() {
        // setup form, section, row, etc.
        row = XLFormRowDescriptor(...)
        if ! isNewPerson {
            row.value = person.firstName
        } else {
            row.value = "Bob" // optional else clause for setting initial value
        }

        row = XLFormRowDescriptor(...)
        if ! isNewPerson { row.value = person.lastName } // A little cleaner in a single line w/o default value
    }

**Comment by mats-claassen** [comment]
There is no way to toggle if `formRowDescriptorValueHasChanged ` will be called other than setting the delegate to nil and resetting it afterwards.
Anyway it should still be better to set the form at the end.
