### ISSUE TITLE
inputAccessoryView (Done bar) is not coming up after upgrading  to Xcode 7/(IOS9)

### ISSUE THREAD

**Issue by sdalai** [xmartlabs/XLForm#588]
It is not coming up for XLFormRowDescriptorTypeDateTimeInline

where as it is coming up for XLFormRowDescriptorTypeTextView or XLFormRowDescriptorTypeTextField.

**Comment by mtnbarreto** [comment]
We no longer show the navigation bar for inline rows, at least by default. 
You can change the default behaviour by following this guide: https://github.com/xmartlabs/XLForm#how-to-change-input-accessory-view-navigation-view
