### ISSUE TITLE
Uncheck a boolean row progmatically

### ISSUE THREAD

**Issue by ksbecker** [xmartlabs/XLForm#591]
I'm using a XLFormRowDescriptorTypeBooleanCheck or XLFormRowDescriptorTypeBooleanSwitch to show and hide a few rows.  One of those rows is an update button and when I tap that button I save some data from those rows.  I want those rows to hide automatically after update, which I've done by setting the value of the bool row to 0 and use a predicate on the hidden property.  But the check or switch remains in the true state even though I set the row value to false.

A work-around is I can update the value and then call tableView.reloadData() but that seems like an extra step and potentially "dangerous" call as I'm not sure what effect reloading the table will cause.

**Comment by tschleuss** [comment]
I have a view with multiples switchs, i did something like this to make one switch enable / disable other switch.

```
    switchRow = [XLFormRowDescriptor formRowDescriptorWithTag:kFieldActive rowType:XLFormRowDescriptorTypeBooleanSwitch title:@"Active"];
    switchRow.value = @(NO);
    switchRow.onChangeBlock = ^(id oldValue, id newValue, XLFormRowDescriptor* rowDescriptor) {
        if([newValue boolValue] == YES) {
            [self changeSwitch:kFieldMail toState:NO];
        }
    };
    [section addFormRow:switchRow];
``` 

```
- (void)changeSwitch:(NSString*)tag toState:(BOOL)state
{
    XLFormRowDescriptor *row = [self.form formRowWithTag:tag];
    row.value = @(state);
    [self reloadFormRow:row];
}
```
