### ISSUE TITLE
Label position for XLFormRowDescriptorTypeSelectorPush is not aligned properly

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/XLForm#593]
The label position for XLFormRowDescriptorTypeSelectorPush is not aligned properly.  It is indented a pixel or two to the right of other row types.

**Comment by rlaferla** [comment]
![formsep](https://cloud.githubusercontent.com/assets/1135694/10181802/913877d6-66ea-11e5-8275-823a2d65f673.png)

**Comment by mtnbarreto** [comment]
@rlaferla Thang for reporting it! 
Could you please provide more information SDK, device?

**Comment by rlaferla** [comment]
iOS 9.x simulator

**Comment by bmichotte** [comment]
@mtnbarreto It's related to #554
