### ISSUE TITLE
No table view cell separator in iOS 9

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/XLForm#594]
When I have a row in the form of type XLFormRowDescriptorTypeSelectorPush, I see separator lines between each row.  BUT when the form contains only rows of type XLFormRowDescriptorTypeText, there are no separator lines!

iOS 9 bug?  XLForm bug?

**Comment by rlaferla** [comment]
![nosep](https://cloud.githubusercontent.com/assets/1135694/10181710/73450b0a-66e9-11e5-949e-ca9eda6ebcd4.png)

**Comment by rlaferla** [comment]
![formsep](https://cloud.githubusercontent.com/assets/1135694/10181797/8010cbd4-66ea-11e5-91dd-12740a3d838e.png)

**Comment by bmichotte** [comment]
imho, this bug is related to #554

**Comment by mtnbarreto** [comment]
@rlaferla Is this still happening in iOS 9 master branch? I couldn't reproduce it.

**Comment by mtnbarreto** [comment]
Please, re-open the issue if you consider is not fixed.
