### ISSUE TITLE
Hide multivaluedAddButton when form is disabled

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#596]
How can I achieve this? I can hide rows based on other rows values but not sure how to hide when the form is disabled.
Thank you

**Comment by mats-claassen** [comment]
You cannot achieve this through predicates but you can take the sections that have a multivaluedAddButton and hide it by setting a boolean value to its hidden property.

**Comment by focusedonfit** [comment]
Ok thank you!
