### ISSUE TITLE
prepareForSegue not called for XLFormRowDescriptorTypeSelectorPush

### ISSUE THREAD

**Issue by emkou** [xmartlabs/XLForm#597]
Hello, there are some problems when it comes to passing an extra parameter for any row and I need a reference of the v.controller: 

    row = [XLFormRowDescriptor formRowDescriptorWithTag:kEmployee rowType:XLFormRowDescriptorTypeSelectorPush title:@"Tilldelad:"];
    row.action.formSegueClass = NSClassFromString(@"UIStoryboardPushSegue");
    row.action.viewControllerClass = [EmployeeTableViewController class];
    row.value = [XLFormOptionsObject formOptionsObjectWithValue:[NSMutableArray new] displayText:@"Välj"];
  
    row.required = YES;
    [section addFormRow:row];
    
-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender{
 [super prepareForSegue:segue sender:sender];
 }

Segue is never called during this setup, there was no problem in XLForm 2 and this setup was working

**Comment by memmons-ntst** [comment]
In what version of iOS are you seeing this behavior? I am seeing this exact same thing in iOS9, but in iOS8 `prepareForSegue` is called as expected.

**Comment by emkou** [comment]
Yes, iOS9, I had to change code and go back to using storyboard and segue identifiers.

**Comment by ramazanulucay** [comment]
Hello, 

i have same problem. row.action.formSegueClass is always nil on iOS9 and prepareForSegue doesn't fire. I solve my problem with this code;

```
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    NSArray *viewControllers = self.navigationController.viewControllers;
    if (viewControllers.count > 1 && [viewControllers objectAtIndex:viewControllers.count-2] == self) {
        for (id anVC in viewControllers) {
            if([anVC isKindOfClass:[EmployeeTableViewController class]]) {
                EmployeeTableViewController *employee = (EmployeeTableViewController*)anVC;
                employee =[self.form formValues];
            }
        }
    } else if ([viewControllers indexOfObject:self] == NSNotFound) {
        NSLog(@"View controller was popped");
    }
}
```

**Comment by jrivelli** [comment]
I have found a solution for this.  ``` NSClassFromString("UIStoryboardPushSegue")``` return nil in iOS9.  I created my own custom segue.

```
@objc(CustomShowSegue)
class CustomShowSegue: UIStoryboardSegue {
   
    override func perform() {
        sourceViewController.showViewController(destinationViewController as! UIViewController, sender: sourceViewController)
    }
}
```

Then you can set the row action like this:

```row.action.formSegueClass = NSClassFromString("CustomShowSegue")```

I have validated this works in iOS8 and iOS9.
