### ISSUE TITLE
User pressed return vs. changed text

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/XLForm#598]
XLForm can detect that the text has changed using:

```-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)rowDescriptor oldValue:(id)oldValue newValue:(id)newValue```

but how can it detect that the user pressed return (finished input)?

ie.  ```- textFieldDidEndEditing: vs textField:shouldChangeCharactersInRange```

**Comment by mats-claassen** [comment]
When a user ends editing a textfield then the form view controllers `textFieldDidEndEditing` method is called. You can override that.

**Comment by rlaferla** [comment]
That delegate method is called too late.  I need textFieldShouldEndEditing.  I can contribute a patch so that both shouldEnd and didEnd get called.

**Comment by mats-claassen** [comment]
The textfield cell also calls the `textFieldShouldEndEditing` method [here](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormTextFieldCell.m#L253)
