### ISSUE TITLE
row not hiding

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#599]
I have a row named mondayRowTitle with the tag of "name" and I want to hide a row named 'rowtest' when mondayRowTitle is disabled. I am setting the entire form  self.form.disabled = true but this row is not hiding. 
 
let mondayRowTitle : XLFormRowDescriptor = XLFormRowDescriptor(tag: "name", rowType: XLFormRowDescriptorTypeName, title: "Name")
rowTest.hidden =  NSPredicate(format: "$name.isDisabled == 1 ")

thanks for the help

**Comment by mtnbarreto** [comment]
Disabling the whole form will not trigger the evaluate method. In this case you will have to invoke `evaluateIsDisabled` after you disable the form:

```obj-c
[rowtest evaluateIsDisabled]
```
