### ISSUE TITLE
Unable to retrieve the form values from multi-value-form 

### ISSUE THREAD

**Issue by AlexLisong** [xmartlabs/XLForm#606]
Sorry, I reopened it as a issue, after I followed #439, I still couldn't fix it.

my code looks like:
 func initializeForm() {
    let form : XLFormDescriptor
    var section : XLFormSectionDescriptor
    var row : XLFormRowDescriptor

    form = XLFormDescriptor(title: "Enter Name")

    // Multivalued section
    section = XLFormSectionDescriptor.formSectionWithTitle("", sectionOptions:XLFormSectionOptions.CanInsert | XLFormSectionOptions.CanDelete, sectionInsertMode:XLFormSectionInsertMode.Button)
    section.multivaluedAddButton!.title = "Add Name"
    row = XLFormRowDescriptor(tag: "tag here", rowType: XLFormRowDescriptorTypeName)
    row.cellConfigAtConfigure["textField.placeholder"] = "Enter Name"
    section.multivaluedRowTemplate = row

    form.addFormSection(section)

    self.form = form
  }

and     override func viewWillDisappear(animated: Bool) {

    println( "self.formValues() = \(self.formValues())")   // => [:]
    println( "self.form.formValues() = \(self.form.formValues())" ) // => [:]

and I am still confused that even if we can add a tag name for the first one/default one, how do we add the tag name for the new items(after we click "Add new ...")

any working code?
Thanks in advance,

**Comment by mats-claassen** [comment]
You have to set the multivalued tag to that section:
```
section.multivaluedTag = @"multisectiontag";
```
Your formValues will now show the values for that section.
In fact these rows have no tag, but its section must have.
