### ISSUE TITLE
XLFormRowDescriptorTypeSelectorSegmentedControl localization of titles

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/XLForm#611]
Is there a way to use tags for the option values and supply a list of localized titles.  i.e.

values are 0, 1, 2, 3
English titles are Red, Green, Blue, White
French titles are Rouge, Vert, Bleu, Blanc
etc...

**Comment by tommypeps** [comment]
no :disappointed: 

If you like add NslocalizedString (http://nshipster.com/nslocalizedstring/) for DisplayValue and 0,1,2 for value.
```Objective-C
+(XLFormOptionsObject *)formOptionsObjectWithValue:(id)value displayText:(NSString *)displayText
```

**Comment by mtnbarreto** [comment]
:+1:
