### ISSUE TITLE
Making a form RTL

### ISSUE THREAD

**Issue by hrsalehi** [xmartlabs/XLForm#612]
How can I make a form appear Right to Left? For example the name input labels should come right and the text fields should go left.

I couldn't find any solution to center Section's title and footer texts center. How can I do that?

**Comment by mtnbarreto** [comment]
@haaakon right to left language are fully supported.
Have you tried the examples with a RTL language?  take a look at the attached image:

<img width="281" alt="screen shot 2015-11-13 at 12 13 53 am" src="https://cloud.githubusercontent.com/assets/1746532/11137947/5e0487b4-899b-11e5-81a5-cb1b7d1b86e2.png">


This might helps to center the section header text: http://stackoverflow.com/questions/4875391/iphone-how-to-center-the-section-headers-of-a-tableview

**Comment by haaakon** [comment]
@mtnbarreto Guess you @ me wrong? :smile:

**Comment by hrsalehi** [comment]
I want to force the layout to become RTL not by changing whole system language. is that possible?
