### ISSUE TITLE
Help needed. adding my own cellConfig for my custom cells

### ISSUE THREAD

**Issue by jett0423** [xmartlabs/XLForm#614]
Is this possible to implement in my own custom row class?
I would like to configure more my own rows' properties dynamically before I add them to a section

**Comment by tommypeps** [comment]
Custom Rows see: 

https://github.com/xmartlabs/XLForm/tree/master/Examples/Objective-C/Examples/CustomRows

**Comment by jett0423** [comment]
I already browsed through the whole process of creating my own custom cell. What I'm referring to is how to customize my custom cell's cellConfig property (similar to how we customize the attributes of the default XLFormRowDescriptor types provided) in my XLFormViewController

**Comment by tommypeps** [comment]
many examples:
https://github.com/xmartlabs/XLForm/search?utf8=✓&q=cellConfig


https://github.com/xmartlabs/XLForm/blob/master/Examples/Objective-C/Examples/Others/OthersFormViewController.m 

line 81-88;
```Objective-C
    // step counter
    XLFormRowDescriptor * row = [XLFormRowDescriptor formRowDescriptorWithTag:kStepCounter rowType:XLFormRowDescriptorTypeStepCounter title:@"Step counter"];
    row.value = @50;
    [row.cellConfigAtConfigure setObject:@YES forKey:@"stepControl.wraps"];
    [row.cellConfigAtConfigure setObject:@10 forKey:@"stepControl.stepValue"];
    [row.cellConfigAtConfigure setObject:@10 forKey:@"stepControl.minimumValue"];
    [row.cellConfigAtConfigure setObject:@100 forKey:@"stepControl.maximumValue"];
    [section addFormRow:row];
```

https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormStepCounterCell.m

line 33-34:
```Objective-C
@property (nonatomic) UIStepper *stepControl;
@property (nonatomic) UILabel *currentStepValue;
```

Solution:
mycustomClass.h
```Objective-C
@interface myCustomClass: XLFormBaseCell
@end
```
mycustomClass.m
```Objective-C
@interface myCustomClass ()

@property (nonatomic) myelement1 *ele1;//(UIView) 
@property (nonatomic) myelement2 *ele2; //(UIView)
@end
```

MyViewController.m
```Objective-C
    XLFormRowDescriptor * row = [XLFormRowDescriptor formRowDescriptorWithTag:kCustomTag rowType:XLFormRowDescriptorTypeCustomType title:@"my title"];

    [row.cellConfigAtConfigure setObject:[UIColor purpleColor] forKey:@"elem1.backgroundColor"];
```

**Comment by jett0423** [comment]
oh...I didn't know that's possible. thanks!
