### ISSUE TITLE
Setting autocapitalization on row values

### ISSUE THREAD

**Issue by jeremy-idialogs** [xmartlabs/XLForm#615]
Had a question on how we would set the capitalization of a text field value entered in a form.

Tried:

row.value.autocapitalizationType == UITextAutocapitalizationType.Sentences

 row.value.autocapitalizationType == .Sentences

row.cellConfig.setObject(UITextAutocapitalizationType.Sentences, forKey: "textLabel.autocapitalizationType")

None of these work. 

Thanks.

**Comment by evan-masseau** [comment]
Because the enum is not convertible to AnyObject, you have to take its raw value: 

`< row.cellConfig["textField.autocapitalizationType"] = UITextAutocapitalizationType.Sentences.rawValue >`

**Comment by evan-masseau** [comment]
With other properties I've been able to take the enum's raw value and configure the text field like this:
`
row.cellConfig["textField.textAlignment"] =  NSTextAlignment.Right.rawValue  // Works just fine
row.cellConfig["textField.autocapitalizationType"] = UITextAutocapitalizationType.Sentences.rawValue //Fails and crashes the app, unrecognized key
`
Not sure why but the error says autocapitalizationType is not allowed to be set with key/value coding
At any rate, there is a built in way around this in XLForm, you just have to specify the right row type...

XLFormRowDescriptorTypeText - uses sentence case
XLFormRowDescriptorTypeName - capitalizes each word

**Comment by mats-claassen** [comment]
Hi @jeremy-idialogs are you still battling with this?
Do you want to capitalize the values or what is in the textfield? Did you check all the different row types if none of them has the wanted autocapitalizationType?

**Comment by jeremy-idialogs** [comment]
Hi,

It looks like we resolved this issue. The jira ticket in our system shows a
QA pass.

Thanks for getting back to me though.
Jeremy


On Fri, Dec 11, 2015 at 10:37 AM, Mathias Claassen <notifications@github.com
