### ISSUE TITLE
CollectionView

### ISSUE THREAD

**Issue by Asinox** [xmartlabs/XLForm#617]
Hi guys, i don't know if there is a way to use Collection View, right now I'm using a Push/XLFormRowDescriptorTypeSelectorPush to call my CollectionViewController/xib, but i don't know how i can select multiple cells in the Collection View and pass back to the form.

```
// Selector Push
        row = XLFormRowDescriptor(tag: Tags.Push, rowType: XLFormRowDescriptorTypeSelectorPush, title: "Seleccionar")
        row.action.viewControllerClass = ObjectosRobadosCollectionViewController.self
        row.required = true
        section.addFormRow(row)
```

Any idea?

**Comment by mats-claassen** [comment]
Why don't you use a Multiple Selector row?
You obviously have to set an array as the value of the row which includes an identifier for each of the selected cells or something similar.

**Comment by mats-claassen** [comment]
Could you solve this with Multiple Selector row?
