### ISSUE TITLE
Access the textfields of cells

### ISSUE THREAD

**Issue by mapzter** [xmartlabs/XLForm#620]
Hi!

I have a textfield asking for income. I need the format to follow something like this: 1,223,000.00.

I need to access the textfield of the cell so that I can call tell when the textfield began and ended editing and call the formatting methods.

Any ideas how to achieve this?

**Comment by mats-claassen** [comment]
Hi, if you are using a row of type `XLFormRowDescriptorTypeText` then you can call `[row cellForFormController:...]` cast it as `XLFormTextFieldCell` and access its textfield.
