### ISSUE TITLE
Left Align DetailDisplayText

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#622]
I have attached photos below of my form.  I want the text for 'Barbell Bench Press' & 'Machine Bench Press' to be aligned left.  Any ideas on how to achieve this?
![img_5663](https://cloud.githubusercontent.com/assets/4365485/10640642/89bbae2e-77e3-11e5-970d-729a94093909.jpg)
![img_5664](https://cloud.githubusercontent.com/assets/4365485/10640643/89c47c0c-77e3-11e5-8910-390ab5240dd2.jpg)

**Comment by mtnbarreto** [comment]
@focusedonfit you can accomplish this by doing:

```obj-c
    row = [XLFormRowDescriptor formRowDescriptorWithTag:kSelectorPush rowType:XLFormRowDescriptorTypeSelectorPush title:@""];
    row.cellStyle = UITableViewCellStyleSubtitle;
```

Regards
