### ISSUE TITLE
UITextViewDelegate conflict

### ISSUE THREAD

**Issue by jdgong** [xmartlabs/XLForm#623]
The UITextViewDelegate in XLFormTextViewCell and XLFormViewController seem to conflict with each other. The delegate methods set in XLFormViewController won't get called if not explicitly set the textview delegate to the form but those in XLFormTextViewCell won't be called the other way around, even important ones like setting self.rowDescriptor.value = self.textView.text

Is this an issue or is it designed this way? Do I have to subclass the TextViewCell and override the delegate methods there?

**Comment by mats-claassen** [comment]
In fact the XLFormTextViewCell calls the methods in the XLFormViewController from its delegate methods. You can just override them in your form view controller.
