### ISSUE TITLE
Check For Multiple Values on Hidden Predicate

### ISSUE THREAD

**Issue by adamrushy** [xmartlabs/XLForm#624]
I have not debugged XLForms too much, just trying to find out if anyone has had this issue. So I have a field with selector options HI1, HI2, HI3, HI4, HI5 and Unable To Determine.

If the user selects HI3 / 4 or 5 I have a field that shows below, so currently I have a field hidden predicate which is this;

NOT $Field_0002000 contains 'HI1' OR NOT $Field_0002000 contains 'HI2'

I have tried brackets, removing second NOT, but the first validation only seems to work the 2nd one seems to be invalid, any clues?

**Comment by mtnbarreto** [comment]
@adamrushy have you figured out what was the error? It seems to be an error in the predicate string

**Comment by adamrushy** [comment]
Not quite @mtnbarreto have you had this issue too?

**Comment by mats-claassen** [comment]
Hi @adamrushy could you show your code? Are you setting the `hidden` property with a NSString or a NSPredicate?
I also think your predicate should be 'NOT $Field_0002000 contains 'HI1' **AND** NOT $Field_0002000 contains 'HI2''

**Comment by adamrushy** [comment]
Hi @mats-claassen 

I am closing this ticket, your solution fixed the problem :+1:
