### ISSUE TITLE
Layout issue on 4.7 and 5.5 inches screen devices

### ISSUE THREAD

**Issue by DesmondPang** [xmartlabs/XLForm#626]
Why the layouts of the form on devices with 4.7 and 5.5 inches screen are so weird? The labels and the cells are so blur. The text are bold and the cell height is larger than normal tableview cell. It seems that the whole layout is scaled up by the screen. It is fine on iPhone 5s but not on 4.7 and 5.5 inches devices.
I also found that their is no this issues with xmartlabs/Eureka.

**Comment by DesmondPang** [comment]
Solved. I only used your example to test the form. Maybe it is built for old device. I moved it to a new project and solve it. I think the problem is the storyboard in your example is old and there is no setting of width and height for the storyboard.

**Comment by mtnbarreto** [comment]
@DesmondPang cool!
