### ISSUE TITLE
iPad layout issue on iOS 9.0

### ISSUE THREAD

**Issue by jakubprusa** [xmartlabs/XLForm#627]
Hi,

I have app which run iPad on all orientations. In iOS 8.0 everything works fine. In iOS 9.0 landscape and portrait orientation is broken. 

Does anyone have some walk around or fix? 

Attachements: 

# iOS 8.0 landscape
![ios8-landscape](https://cloud.githubusercontent.com/assets/4330203/10790348/0f2dd466-7d83-11e5-9f29-403ee9827b43.png)

# iOS 8.0 portrait
![ios8-portrait](https://cloud.githubusercontent.com/assets/4330203/10790349/0f58ec1e-7d83-11e5-8b08-9e9ee50f1ef3.png)

# iOS 9.0 landscape
![ios9-landscape](https://cloud.githubusercontent.com/assets/4330203/10790351/0f5b1bba-7d83-11e5-80f1-617e897bea13.png)

# iOS 9.0 portrait
![ios9-portrait](https://cloud.githubusercontent.com/assets/4330203/10790350/0f5aa27a-7d83-11e5-87d2-3cc9a7bb1e64.png)

**Comment by jakubprusa** [comment]
Possible fix here:

SHA: 6100c7ad78b9c304099504d561d199d47b545507

**Comment by mtnbarreto** [comment]
Should be fixed now on master branch.
