### ISSUE TITLE
searchController.searchBar stays on screen when using custom selector using Swift

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#633]
I have a custom selector who presents a VC that has a searchController.searchBar as the TV headerView. When I search and then select a cell, the searchBar remains on the screen as seen in the screenshot. I noticed in the Examples project for ObjectiveC you have a similar implementation with Users table, but in the Swift version, the searchBar is missing. Did you not find a way to make this work?

Thank you
![simulator screen shot nov 1 2015 10 45 58 am](https://cloud.githubusercontent.com/assets/4365485/10869796/090fe2ce-8088-11e5-96f8-35cd5912dab2.png)

**Comment by focusedonfit** [comment]
row.action was loading incorrect form! Closing

**Comment by yfujimot** [comment]
Hi, I'm having the same issue right now, with the search bar disappearing (seems to go off the frame) when I tap it. I can still search things properly, but the screen does not render correctly. Could you please advise? My entire XLForm table relies on XLFormRowDescriptorTypeSelectorPush, and I am referencing the correct viewcontroller storyboardId. Thanks!
