### ISSUE TITLE
Multi-columned SelectorPickerViews?

### ISSUE THREAD

**Issue by cdstamper** [xmartlabs/XLForm#634]
Are there plans to support multiple columns in the UIPickerViews?

As a brief example of why it may be useful, I need to get time duration information from a user while allowing a zero-length duration. As you may know, UIDateTimePicker (and by extension XLForm's CountDownTimer) doesn't allow a 0/null value. 

This is forcing me to write my own date/time picker, and I would like to be able to add hour and minute sections to my custom UIPickerViews.

Perhaps making XLFormOptionsObject aware of a 'section' or 'column' assignment would be the best way to implement this, along with a column count on the RowDescriptor?

**Comment by mtnbarreto** [comment]
@cdstamper We don't have plans to add it but we are open to add it if you come up with a elegant solution.

**Comment by osolano** [comment]
Yes this would be great to have especially when selecting unit and value type options i.e. 1/2 cup , 2 tbsp. etc
