### ISSUE TITLE
change position of TextField and TextView

### ISSUE THREAD

**Issue by hrsalehi** [xmartlabs/XLForm#636]
I have a row descriptor with type XLFromTextFieldAndTextView and I want to change the position of Label and TextField. In default mode the label is positioned left and the text field is on the right and I want to swap they're positions.Is there any way so I can do that?

**Comment by mtnbarreto** [comment]
There is no a easy way to change the provided cell layout.
In your case I strongly recommend  to create custom rows for the project. This was is fully flexible and you can design the cell as you wish.
