### ISSUE TITLE
For a selector can I set both textLabel and detailTextLabel

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#642]
When using XLFormRowDescriptorTypeSelector* is there built-in support for setting both textLabel and detailTextLabel?

I see in the XLForm readme text I see one example setting the font of detailTextLabel but not its content.

XLFormOptionsObject has a value and displayText but no support, that I can see, for setting detailTextLabel.

Can someone point me to an example?

**Comment by mats-claassen** [comment]
The detailTextLabel is set using the `valueDisplayText` function in the [XLFormSelectorCell](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormSelectorCell.m#L46-L91)
You can use the `valueTransformer` to change what will be displayed there.

**Comment by carlhunterroach** [comment]
cheers
