### ISSUE TITLE
PickerView selected index

### ISSUE THREAD

**Issue by hrsalehi** [xmartlabs/XLForm#643]
How can I get a uipickerview selected index. I didn't find any solution to get the picker view selected index only selected value is accessible.

**Comment by mats-claassen** [comment]
The [UIPickerView](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIPickerView_Class/) has a method `- selectedRowInComponent:`

**Comment by ds1239** [comment]
What about if I am using XLFormRowDescriptorTypeSelectorPickerView?
