### ISSUE TITLE
Creating Add Contact Form with Picture on the left side.

### ISSUE THREAD

**Issue by adil-appifytech** [xmartlabs/XLForm#646]
I was wondering if we can create fields with image icon button on the left side of form using XLForms?

![20151116031311](https://cloud.githubusercontent.com/assets/10629648/11180517/1ef45bfa-8c7d-11e5-948a-7bff4f92435f.jpg)

Thanks.

**Comment by dong** [comment]
ping

**Comment by mats-claassen** [comment]
Hi, currently there is nothing like this in XLForm, but you could create a [custom row](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row) that includes those three text fields and the image on the left. You would then store three strings in the value of that row.
