### ISSUE TITLE
Create a hidden row and delegate for value changed dont work

### ISSUE THREAD

**Issue by prsolucoes** [xmartlabs/XLForm#654]
Hi,

Im trying make two thing work, but no success. Im running in ios9 and swift.

1 - Im trying creating a row hidden to show after specific condition when a value was changed. But instead of row be hidden if place a gray space between rows and the space still used:

```
        // passaporte
        row = XLFormRowDescriptor(tag: "passaporte", rowType:XLFormRowDescriptorTypeText, title: "Passaporte")
        row.cellConfigAtConfigure.setObject("Passaporte", forKey: "textField.placeholder")
        row.cellConfigAtConfigure.setObject(true, forKey: "hidden")
        section.addFormRow(row)
```

2 - When i change some row value on any row, the function of value changed is not called :(   My method is like the sample:

```
override func formRowDescriptorValueHasChanged(formRow: XLFormRowDescriptor!, oldValue: AnyObject!, newValue: AnyObject!) {
        super.formRowDescriptorValueHasChanged(formRow, oldValue: oldValue, newValue: newValue)
        ...
}
```

Can anyone help me?

![screenshot 2015-11-27 01 18 18](https://cloud.githubusercontent.com/assets/395096/11433469/cf739dfe-94a4-11e5-89c4-fce451850fc8.png)
![screenshot 2015-11-27 01 18 03](https://cloud.githubusercontent.com/assets/395096/11433470/cf7cf192-94a4-11e5-91f2-924fdd265dd9.png)

**Comment by mats-claassen** [comment]
Hi if you want to set a row to be hidden you must use its `hidden` property, and not `cellConfigAtConfigure` as that will just hide the cell.

For the second point, are you sure your view controller is set as the delegate of the form? (should be automatic if you subclassed XLFormViewController and properly called [super viewDidLoad])
