### ISSUE TITLE
XLFormRowDescriptorTypeSelectorLeftRight question (Contacts app like behavior)

### ISSUE THREAD

**Issue by pventura1976** [xmartlabs/XLForm#655]
Is it possible to setup a row with a selector on the left side and a UITextBox on the right side? Like the Contacts app behavior when you are adding a new phone number.

**Comment by mats-claassen** [comment]
You can not do it with the current XLFormRowDescriptorTypeSelectorLeftRight.
You can obviously create your own [custom rows](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row).
