### ISSUE TITLE
Action Sheet is not giving useable data via [self formValues]

### ISSUE THREAD

**Issue by earthabbey** [xmartlabs/XLForm#656]
It is my understanding that [self formValues] should give the data in a useable format. Strings, numbers, etc. However I am using an action sheet for one of my fields:

```    
personRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"personGender"  rowType:XLFormRowDescriptorTypeSelectorActionSheet title:@"Gender"];
[personsSection addFormRow:personRow];
personRow.selectorOptions = @[[XLFormOptionsObject formOptionsObjectWithValue:@(0) displayText:@"Male"], [XLFormOptionsObject formOptionsObjectWithValue:@(1)  displayText:@"Female"],  ];
personRow.value = [XLFormOptionsObject formOptionsObjectWithValue:@(2) displayText:@""];
```

The action sheet item is coming out of [self formValues] as an XLForm object. How can I convert this to usable data? 

```
(lldb) po [self formValues]
{
    personBirthdate = "2015-11-28 00:22:46 +0000";
    personGender = "<XLFormOptionsObject: 0x7ffa8a6627a0>";
    personInvolved = "<null>";
}
```

**Comment by mats-claassen** [comment]
Hi, in fact it must not return strings and numbers only. In this case you are setting an object to a row so if that row is selected you will want to get that object back. You can get the objects values from the XLFormOptionsObject. by using its `valueData` property.
This might not be so obvious when your objects are Integers but if you were using a class `Person` for example then it is.
