### ISSUE TITLE
XLFormRowDescriptorTypeColor

### ISSUE THREAD

**Issue by bmichotte** [xmartlabs/XLForm#658]
@mtnbarreto In the exact same way as `XLFormRowDescriptorTypeImage`, I also added a `XLFormRowDescriptorTypeColor` cell to [ProMotion-XLForm](https://github.com/bmichotte/ProMotion-XLForm) using the pod [RSColorPicker](https://github.com/RSully/RSColorPicker)

This looks like this : 
![color](https://cloud.githubusercontent.com/assets/235510/11482045/e5b9489e-97a0-11e5-84a0-adfb62e9c19b.gif)

Do you want I PR it ?

The quality of the color is not great in gif, but this looks fine in real 

![capture d ecran 2015-11-30 a 20 30 07](https://cloud.githubusercontent.com/assets/235510/11482089/2baf0dca-97a1-11e5-9e42-b6734f715974.png)

**Comment by mtnbarreto** [comment]
@bmichotte I like the idea but adding it to XLForm makes everyone import 'QuartzCore', 'CoreGraphics', 'Accelerate' frameworks in addition to have a pod dependency reference over RSColorPicker. 

What about adding this custom selector to the example project and leave the decision of integrating it up to everyone?

**Comment by mats-claassen** [comment]
I will close this issue. If somebody is interested in such a row he can contact @bmichotte 
As @mtnbarreto mentioned this is a very custom row and we won't merge it to XLForm's core.
