### ISSUE TITLE
How to make the tableHeaderView fixed when I scrolling the table

### ISSUE THREAD

**Issue by marshallYin** [xmartlabs/XLForm#659]
when I set up a tableHeaderView in a subclass of UITableViewController，it works fine
![67fa1fe6ede70f5df3e64929610a9b3c](https://cloud.githubusercontent.com/assets/16058230/11496776/5e3f3c70-984f-11e5-8f24-5f46fef187d9.png)

but I don't know why when I use the subclass of XLFormViewController, it looks like this 
![img_0433](https://cloud.githubusercontent.com/assets/16058230/11496817/9f1a2ee4-984f-11e5-950d-f667946caa82.JPG)

Could you please tell me how to fix this problem? thank you!

**Comment by mats-claassen** [comment]
Hi, could you fix this?
I created a UITableViewController and its header would just scroll like a XLFormViewController.
```
UIView * view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 300, 40)];
    view.backgroundColor = [UIColor redColor];
    self.tableView.tableHeaderView = view;
```

**Comment by marshallYin** [comment]
what I use is PathCover  https://github.com/JackTeam/PathCover ,it works.Check and see the way he fixes it,it seems to have something to do with UIScrollView,hope it helps:)
