### ISSUE TITLE
onChangeBlock and formRowDescriptorValueHasChanged cause blank form

### ISSUE THREAD

**Issue by sumowesley** [xmartlabs/XLForm#660]
I don't think i'm imagining this on Xcode 7.1.1 in IOS 9.1

I've tried code to hide another field in both onChangedBlock for the row descriptor and formRowDescriptorValueHasChanged.
```
-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)rowDescriptor oldValue:(id)oldValue newValue:(id)newValue
{
    [super formRowDescriptorValueHasChanged:rowDescriptor oldValue:oldValue newValue:newValue];
    if ([rowDescriptor.tag isEqualToString:@"closed"]){
        NSNumber *numHide = (NSNumber *)newValue;
        BOOL boolHide = [numHide boolValue];
        self.rowClosedDate.hidden = boolHide ? @NO : @YES;
        NSLog(@"Here");
    }
}
```

I broke down the use of the boolean just to make sure it wasn't something with the data being passed.

That code is executed when the form is opened - I can see the log entry. The form is blank. The operation following does what is expected - the rowdescriptor with a tag of "closed" is a switch. Toggling it hides/shows the date row mentioned.

if I comment out the line
`self.rowClosedDate.hidden = boolHide ? @NO : @YES;`
I get a fully populated form but of course I lose my hide/show capability. It is exactly the same in the onChangeBlock for the row descriptor.

In the onChangeBlock I've tried using a weak reference to self and then used that weak reference to have a strong reference inside the block but the behaviour is identical to the above.

Is there something else I need to be doing here?

**Comment by sumowesley** [comment]
I should also mention, if I include a line to reload the tableview, it all displays fine but I am nervous about focus loss if I extend the form.

```
    self.rowClosed.onChangeBlock = ^(id oldValue, id newValue, XLFormRowDescriptor *row) {
        weakSelf.rowClosedDate.hidden = [(NSNumber *)newValue boolValue] ? @NO : @YES;
        NSLog(@"Got there");
        [weakSelf.tableView reloadData];
    };
```

**Comment by mats-claassen** [comment]
I have just tried that `formRowDescriptorValueHasChanged` you posted, in one of the examples and I did not notice anything rare in the form. 
Anyway I would not use this way to hide a row. Is there a specific reason for not setting a predicate for that 'rowClosedDate' instead of setting a boolean value each time manually?
Have you double checked that you are not repeating tags?

**Comment by sumowesley** [comment]
Tags are definitely not repeated and I will give using the predicate a go.

**Comment by sumowesley** [comment]
Predicate working fine although initial form display is not showing the data - have to scroll items off screen to get them to update. Will close this call and open another once I've done some more checking and can replicate the problem.

**Comment by sumowesley** [comment]
meant to close

**Comment by manjuhere** [comment]
stuck with same problem... few rows stay blank after `reloadFormRow` method called on them in `formRowDescriptorValueHasChanged:` method... have to scroll the form offscreen to display again. any help would greatly be appreciated
