### ISSUE TITLE
How to add the customized cell to the row?

### ISSUE THREAD

**Issue by dong** [xmartlabs/XLForm#661]
Hi all, i am very new to the xlform. I know there are already a lot of template cells. Is there an easy way to add the customized cell to the row? For example, i made usercell with images, and I want to add this cell to the first section. What is the better way to do that?

```
XLFormDescriptor * form;
XLFormSectionDescriptor * section;
XLFormRowDescriptor * row;

form = [XLFormDescriptor formDescriptorWithTitle:@"Settings"];

// First section
section = [XLFormSectionDescriptor formSectionWithTitle:@"Account"];
[form addFormSection:section];

// User image
row = [XLFormRowDescriptor formRowDescriptorWithTag:@"image" rowType:XLFormRowDescriptorTypeText title:@"Username:"];
[section addFormRow:row];
// Is there  a way to hook the customized UserCell with row together here?
```

**Comment by mats-claassen** [comment]
Hi, did you have a look at the Readme [here](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row)?
Please tell us if that section does not explain it well enough
