### ISSUE TITLE
Helping with predicate for _hidden

### ISSUE THREAD

**Issue by Khronoss** [xmartlabs/XLForm#662]
Hi,

I'm using the inline datePicker to select a date (dd/mm/yyyy). It's a birthdate, and I have to show a form row if the date is less than [NSDate date] minus 18 years.

And I'm totally struggling with the predicates for show or hiding the row :x 

Here is the code I use to setup the row I need to hide if the user is less than 18 years old
```

	XLFormRowDescriptor *row = [XLFormRowDescriptor formRowDescriptorWithTag:kAuthorization rowType:MyXLFormDescriptionTypeCheck title:@"Parents authorization"]];

	row.hidden = [NSString stringWithFormat:@"$%@.value >= CAST(%f, 'NSDate')", kDateOfBirth, [eighteenYearsAgo timeIntervalSince1970]];

	[section addFormRow:row];

```

When I run my application, a breakpoint stops the execution at XLFormRowDescriptor.m (line 342)

where : 
    self is the actual row,
    _hidden is equal to "$birthday.value >= CAST(881190000.000000, "NSDate")"
    and self.sectionDescriptor.formDescriptor.allRowsByTag is nil because self.sectionDescriptor is nil too

And here is the NSException's description in the @catch block : 
    Can't get value for 'birthday' in bindings {}.

Thank you for your help \o

**Comment by Khronoss** [comment]
I found a solution that I explained here http://stackoverflow.com/questions/34093058/xlform-predicate-for-nsdate-comparison/34132902#34132902

But if there is a better solution using the _hidden property with the NSPredicate, I would be happy to know that. 

:)

**Comment by mats-claassen** [comment]
The exception you mentioned was happening because at the first execution the row was not yet added to the section. This exception should not popup anymore.
I have no experience with casting dates in a Predicate so I do not know if this use case works.
