### ISSUE TITLE
Hidden and Disabled Predicates should not be evaluated before form loads

### ISSUE THREAD

**Issue by hirad** [xmartlabs/XLForm#664]
I just started using XLForm and it's a great library. The most annoying thing so far is when it attempts to evaluate `hidden` predicates as soon as a value is assigned to the `hidden` property. 

At that point in execution, this is expected to fail, so it's wrapped in `@throw { } @catch { }`:

```objective-c
@try {
    self.hidePredicateCache = @([_hidden evaluateWithObject:self substitutionVariables:self.sectionDescriptor.formDescriptor.allRowsByTag ?: @{}]);
}
@catch (NSException *exception) {
     // predicate syntax error.
    self.isDirtyHidePredicateCache = YES;
};
```

I don't know any iOS developers who don't work with the "All Exceptions" breakpoints turned on, so triggering an exception here is very inconvenient and interruptive when trying to debug unrelated issues.

On my fork, I have tried to alleviate this by adding a boolean `formHasLoaded` property to the form, section, and row descriptors, which the form view controller can set to `YES` in `viewDidLoad:`. However, I'm not too familiar with the overall architecture of the library yet, so this seems to have broken some features (eg. inline rows for things like inline picker cells). 

I reckon this should be an easy fix for someone familiar with the architecture. Otherwise, I'd be happy to keep trying at it with some guidance.

*EDIT*

To clarify: in my implementation, in `evaluateIsHidden`, I do this: 

```objective-c
if (![self hasFormLoaded]) return NO;
```

**Comment by mats-claassen** [comment]
This fix will just remove the exceptions that are thrown because formDescriptor is not set yet.
If you set a predicate to a row that depends on a row declared afterwards then an exception will still be thrown. But these cases are much less likely.

**Comment by hirad** [comment]
Awesome! Thanks @mats-claassen!
