### ISSUE TITLE
can i set custom row click event?

### ISSUE THREAD

**Issue by williambao** [xmartlabs/XLForm#67]
hi,
can i set my custom row click event?
i try to set the tableview 'didSelectRowAtIndexPath' delegate,
then all xlform row's click event is can't work.
how can i to do these ? 
thanks very much:)

**Comment by mtnbarreto** [comment]
@williambao @shams-ahmed @bazik123  If you are setting up a `XLFormRowDescriptorTypeButton` you can also configure tap event handlers by either assigning a block or a selector to `action.formBlock` or `action.formSelector` respectively. `action` is a `XLFormRowDescriptor` property only available on master branch for now.
