### ISSUE TITLE
how can present a cell with 2 different types of value ?

### ISSUE THREAD

**Issue by ivanyang1984** [xmartlabs/XLForm#675]
I now have to present a cell with   Weight  for left title.      the Number for right value and an unit of measure   right options value   such as  km/s(it has several options).

**Comment by ivanyang1984** [comment]
eg:  weight(left)           1(right)  kg(right2)

**Comment by loufq** [comment]
you can use cellConfig to set cell's accessoryView

<img width="487" alt="11eac725-3b0d-4510-a193-c7ce8eb4e5b5" src="https://cloud.githubusercontent.com/assets/506803/11913280/db5e8f1e-a699-11e5-82a0-dbb64c0fb7a6.png">
<img width="324" alt="0d68e39d-a559-41cf-90f2-c15b158b7ade" src="https://cloud.githubusercontent.com/assets/506803/11913281/ed2045c6-a699-11e5-84d0-c8ac5ea6b923.png">

**Comment by ivanyang1984** [comment]
i mean the  there was 3 value there,   the position in Name is my left title label , the i may have a number value just left beside the kg  。 then i have 2 right values.     the number and the measure unit kg.   how can submit that two right values ?

**Comment by ivanyang1984** [comment]
the  kg  is an option      it might have other unit like  g,  mg, t

**Comment by mats-claassen** [comment]
If you want the user to be able to choose two different options then you will have to create a [custom row](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row). 
If the `kg` is not changed by the user but programmatically then you can use the answer @loufq presented. Do not forget to set the alignment of the textfield to right in this case.
