### ISSUE TITLE
formRowDescriptorValueHasChanged formRow.tag is nil on multivalued sections

### ISSUE THREAD

**Issue by winzig** [xmartlabs/XLForm#677]
I've defined a multivalued section like this:

```
section = XLFormSectionDescriptor.formSectionWithTitle(nil, sectionOptions: [XLFormSectionOptions.CanInsert, XLFormSectionOptions.CanDelete], sectionInsertMode:XLFormSectionInsertMode.LastRow)
section.multivaluedTag = Tags.MediaFile.rawValue
form.addFormSection(section)

row = XLFormRowDescriptor(tag: Tags.MediaFile.rawValue, rowType: XLFormRowDescriptorTypeMediaPicker)
section.addFormRow(row)
```

When my first row in this section changes, and `formRowDescriptorValueHasChanged` is called, the formRow.tag is filled in appropriate with the Tags.MediaFile.rawValue. However, if I click the green (+) to add a new row, and then change that new row's value, `formRowDescriptorValueHasChanged` is called again, yet with a `nil` value for formRow.tag. 

I thought by setting section.multivaluedTag during initialization of the section, that this would automatically cause all my row tags to be set to that value. Am I misunderstanding, or is this a bug?

**Comment by winzig** [comment]
It seems as though this line is the reason why:

https://github.com/xmartlabs/XLForm/blob/6ef46a60263b281d88dbe4561581227b8349ac42/XLForm/XL/Controllers/XLFormViewController.m#L430

Still not clear as to whether this is intended or not? 

I'm trying to workaround the issue by overriding `multivaluedInsertButtonTapped(XLFormRowDescriptor!)` to set the tag explicitly, but it seems like I must be using this incorrectly.

**Comment by mats-claassen** [comment]
In fact this is intended yes. 
multivaluedTag is a tag for that section and is used to get the values of that section.
Have a look at the `formValues` implementation [here](https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Descriptors/XLFormDescriptor.m#L286-L308)

**Comment by winzig** [comment]
OK, now I understand how that's working, thank you for the link. 

So how do most people handle the situation where you've overridden `formRowDescriptorValueHasChanged`, and you're trying to determine what type of row it is? Usually I do this using the `.tag`, but since it's `nil` for all but the first row, that doesn't work.

**Comment by mats-claassen** [comment]
I know this issue is pretty old but for future readers I guess the best way to solve this problem is to check for the `row.sectionDescriptor.multivaluedTag` to know that the row is from that specific multivalued section and if you must know the index of the row in that section then you could get that from the `sectionDescriptor`'s `formRows` property.
