### ISSUE TITLE
How get values from custom row

### ISSUE THREAD

**Issue by NBibikov** [xmartlabs/XLForm#678]
I need your help! Sorry if i not found, but i really can't find)
I have custom cell with 2 UITextFields and 1 button.
Can i read values from UITextFields straight in my viewController??
![screen shot 2015-12-18 at 8 50 40 pm](https://cloud.githubusercontent.com/assets/8437488/11904478/0c645de0-a5c9-11e5-92e5-c2d308589573.png)

```
XLFormBaseCell
@property (weak, nonatomic) IBOutlet UIButton *imageAvatar;
@property (weak, nonatomic) IBOutlet UITextField *firstNameTextField;
@property (weak, nonatomic) IBOutlet UITextField *lastNameTextField;
@property (strong, nonatomic) NSString* avatarURL;

- (IBAction)changeAvatarButton:(UIButton *)sender;
```

```
MyViewControllerClass
row = [XLFormRowDescriptor formRowDescriptorWithTag:kEditAvatar rowType:XLFormRowDescriptorTypeEditAvatar];
    [row.cellConfigAtConfigure setObject:@"First name" forKey:@"firstNameTextField.placeholder"];
    [row.cellConfigAtConfigure setObject:@"Last name" forKey:@"lastNameTextField.placeholder"];
    
    [row.cellConfigAtConfigure setObject:self.userProfile.name forKey:@"firstNameTextField.text"];
    [row.cellConfigAtConfigure setObject:self.userProfile.second_name forKey:@"lastNameTextField.text"];
    [row.cellConfigAtConfigure setValue:self.userProfile.avatar_url forKey:@"avatarURL"];
    
    [section addFormRow:row];
```

**Comment by loufq** [comment]
you can trans a object as value. or simplest .value= @[@"a",@"b"] ,in customer cell update the object

**Comment by ivanyang1984** [comment]
i have the same requirements in crm .   i always have more than 2 values in my custom cell.

**Comment by misuqian** [comment]
I figure it by using  row.value = Dictionary<String,AnyObject>() (the dic save your data)

**Comment by mats-claassen** [comment]
@NBibikov How did you solve it?
I think a dictionary is the best option.

**Comment by NBibikov** [comment]
@mats-claassen yes, i get data with dictionary! thanks

**Comment by mats-claassen** [comment]
So I think we can close this, right?

**Comment by smileat** [comment]
@misuqian could you show some code of cell, because i don't get value with [self httpParameters].

my cell code :
`#define REMARK @"remark"`
`-(void)update
{
    [super update];
    self.valueDic = [[NSMutableDictionary alloc] init];
    self.textView.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    self.textView.placeHolderLabel.font = self.textView.font;
    self.textView.delegate = self;
    self.textView.keyboardType = UIKeyboardTypeDefault;
    
    self.textView.text = [self.rowDescriptor.value valueForKey:REMARK];
    
    self.textLabel.text = ((self.rowDescriptor.required && self.rowDescriptor.title && self.rowDescriptor.sectionDescriptor.formDescriptor.addAsteriskToRequiredRowsTitle) ? [NSString stringWithFormat:@"%@*", self.rowDescriptor.title]: self.rowDescriptor.title);
}`
`-(void)textViewDidEndEditing:(UITextView *)textView
{
    if ([self.textView.text length] > 0) {
        [self.valueDic setValue:self.textView.text forKey:REMARK];
    }
    else {
        [self.valueDic setValue:self.textView.text forKey:REMARK];
    }
    self.rowDescriptor.value = self.valueDic;
    [self.formViewController endEditing:self.rowDescriptor];
    [self.formViewController textViewDidEndEditing:textView];
}

-(void)textViewDidChange:(UITextView *)textView{
    if ([self.textView.text length] > 0) {
        [self.valueDic setValue:self.textView.text forKey:REMARK];
    }
    else {
        [self.valueDic setValue:@"" forKey:REMARK];
    }
    self.rowDescriptor.value = self.valueDic;
}`

**Comment by hungdm9999** [comment]
I strongly recommend you to define "dataSource" and "delegate" protocols for your own customized cell. The new cell should render data only only and data is kept and processed by the ViewController that contains the cell. The logic is clear that overwrite "update" method with data extract from data source and all changes will be notified to your delegate
The other way is by transfer back/forward all cell sub values with a dictionary but i myself prefer above.
