### ISSUE TITLE
How can I change Switch onTintColor

### ISSUE THREAD

**Issue by misuqian** [xmartlabs/XLForm#683]
Can I change the switch tintcolor in XLFormRowDescriptorTypeBooleanSwitch?

I found that row.cellConfigAtConfigure["self.tintiColor"] and row.cellConfigAtConfigure["self.onTintColor"] is nor work

**Comment by loufq** [comment]
yes u can 
    [rows.cellConfigAtConfigure setObject:[UIColor redColor] forKey:@"accessoryView.tintColor"];
    [rows.cellConfigAtConfigure setObject:[UIColor blackColor] forKey:@"accessoryView.onTintColor"];

**Comment by mats-claassen** [comment]
Hi, that is correct, this also works:
```
[row.cellConfigAtConfigure setObject:[UIColor redColor] forKey:@"switchControl.onTintColor"];
```
