### ISSUE TITLE
Hide and show  couple of  textViews using switch

### ISSUE THREAD

**Issue by yj10041004** [xmartlabs/XLForm#684]
I am going to show  rows  dynamically. All rows are textview types  and  the number of rows  vary. It can be 1 or  more than 1.  I would want to add switch button to expand and shrink each cell.

What happen is that only the last switch button is working. I guess this is because each row has same tag value "   "formRowDescriptorWithTag:kAccessoryViewRowNavigationEnabled ".  
Can we make  each row works independently?. 

 [section.field  enumerateObjectsUsingBlock:^(Field  * field, NSUInteger idx, BOOL * stop) {

XLFormRowDescriptor * switchRow;
        switchRow = [XLFormRowDescriptor formRowDescriptorWithTag:kAccessoryViewRowNavigationEnabled rowType:XLFormRowDescriptorTypeBooleanSwitch title:field.name];   //field.name is unique.
        switchRow.value = @YES;
        [formSection addFormRow:switchRow];

        row = [XLFormRowDescriptor formRowDescriptorWithTag:field.name rowType:XLFormRowDescriptorTypeTextView title:nil];
        [formSection addFormRow:row];

 [row.cellConfigAtConfigure setObject:field.value  forKey:@"textView.placeholder"];
        [formSection addFormRow:row];
         row.hidden = [NSString stringWithFormat:@"$%@ ==1", switchRow];
}];

**Comment by mats-claassen** [comment]
Hi, each row must have a different tag for this to work.
You could append the index to your tag so that the tags would be unique.
