### ISSUE TITLE
Selecting the same option when using XLFormRowDescriptorTypeSelectorPush sets NSNull value

### ISSUE THREAD

**Issue by mrvincenzo** [xmartlabs/XLForm#688]
The row type is XLFormRowDescriptorTypeSelectorPush. When selecting the row, a XLFormOptionsViewController is pushed to the navigation stack. When selecting an option that is already selected, instead of popping the view option's view controller and leaving the row value unchanged, XLForm "unselects" the row and sets NSNull value for the row which is incorrect.

**Comment by dmorentsov** [comment]
I've observed the same issue and would appreciate if someone can provide a solution. Thank you.

**Comment by dmorentsov** [comment]
Is there a recommended way to force the row to retain the selection instead of setting it to NSNull?

**Comment by mrvincenzo** [comment]
Found it. All you need to do is set the row as required.
