### ISSUE TITLE
allow selector text label to align right

### ISSUE THREAD

**Issue by lucastan** [xmartlabs/XLForm#690]
How to make the selector text appear left instead of right?

I tried `detailedLabel.textAlignment` == NSTextAlignmentRight but to no avail

![screen shot 2015-12-29 at 10 34 10 pm](https://cloud.githubusercontent.com/assets/742503/12036403/a5137142-ae80-11e5-9aa6-0542a07010d8.png)

**Comment by mats-claassen** [comment]
Duplicated by #689
