### ISSUE TITLE
function 'containsString' can't run on IOS7.0 

### ISSUE THREAD

**Issue by jbasttdi** [xmartlabs/XLForm#691]
HI,
Using the master branch code on my IOS7.0 iPhone,throws
````
 -[__NSCFString containsString:]: unrecognized selector sent to instance 0x16574610
````
I found the line 121 in XLFormRowDescriptor.m using 
```
            if ([cellClassString containsString:@"/"]) {
```
but containsString can't run on ios7.0,so throw exception.

**Comment by mtnbarreto** [comment]
#687 fixes this issue.
