### ISSUE TITLE
Unable to display navigation bar, or edit its title.

### ISSUE THREAD

**Issue by rogerluan** [xmartlabs/XLForm#693]
I'm using XLForm in 2 different view controllers. The first is being presented with a navigation controller (push) and is displaying the navigation bar, but I not its title (it's blank) and I'm unable to edit it. Tried 
```
self.navigationController.title = @"test";
self.navigationItem.title = @"test2";
self.navigationController.navigationItem = @"test3";
```

but did not succeed.

The second view controller is being presented modally, and it is not displaying the navigation bar at all, even though I set so on the storyboard, and set the view controller's property `    self.navigationController.navigationBarHidden = NO;`

Any clue on what might be happening?

As a side note, I'm also getting this warning every time the form is presented: ```Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.```

**Comment by rogerluan** [comment]
Just fixed this. This had nothing to do with XLForm at all, as I thought. :sweat_smile: 

For the title problem, my title.textAttribute was white, so the text was there, yet I couldn't see it.
And for the navigation bar problem, I simply embed my modal view controller inside a navigation controller.

It's working like a charm now, hope this can help someone.

Note: still having the constraints warning though. Haven't found a solution for that one yet.

**Comment by samjarman** [comment]
Ha. I just hit this too. Thanks @rogerluan. Gosh darn iOS 7 changes!
