### ISSUE TITLE
how to deselect a button row

### ISSUE THREAD

**Issue by ncscdev** [xmartlabs/XLForm#697]
Hello, 
i was trying to deselect an XMLFormRow of type Button. But, i could not. 
i went through the examples and found that it is calling a dummy method of deselect buttons. 
If anyone could post a snippet if how to achieve the deselect thing i would be thankful. 

Thanks,

**Comment by sumowesley** [comment]
OthersFormViewController.m in the example files has a couple of examples in it using strong and weak references to self to deselect the row e.g. [weakSelf deselectFromRow:sender];

**Comment by ncscdev** [comment]
Thanks, 
Now, i am having this Exception 
+[OTRXLFormCreator deselectFormRow:]: unrecognized selector sent to class 0x101d08608

**Comment by sumowesley** [comment]
And the sender is the XLFormRowDescriptor class?

**Comment by ncscdev** [comment]
Yes. 
`sendRow.action.formBlock = ^(XLFormRowDescriptor * sender){ 
[weakSelf deselectFromRow:sender];
}
`

**Comment by sumowesley** [comment]
Could you implement something like this:

```
-(void)didSelectFormRow:(XLFormRowDescriptor *)formRow
 {
     [super didSelectFormRow:formRow];

     if ([formRow.tag isEqual:@"yourtag"]) {
        [self deselectFormRow:formRow];
    }
}
```

Haven't tried it but feels like it should work.

**Comment by ncscdev** [comment]
Thanks, 
i was trying to do the deselect method from within my XLFormCreator Class which was wrong for me. 
i tried to do it from my XLFormViewController<XLFormDescriptorDelegate>.
