### ISSUE TITLE
Swift files are ObjC code

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#698]
The files in https://github.com/xmartlabs/XLForm/tree/master/Examples/Swift/Examples are OBjC.
I think this directory can be deleted as the Swift example code is in a different directory.

The "Swift" code is in https://github.com/xmartlabs/XLForm/tree/master/Examples/Swift/SwiftExample

**Comment by mats-claassen** [comment]
You are right, thanks or pointing out.
