### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPush not working

### ISSUE THREAD

**Issue by devloe** [xmartlabs/XLForm#699]
Hi, Ive implemented XLFormRowDescriptorTypeSelectorPush, and it was working just fine until today.
All of a sudden, it stoped working. When the row gets hit, it doesn't do anything.

Any toughts?
![captura de pantalla 2016-01-13 a las 18 09 48](https://cloud.githubusercontent.com/assets/122845/12301554/f20a85de-ba20-11e5-809c-c213deb662d7.png)

**Comment by sumowesley** [comment]
Are you tapping and the cell stays gray like above?
For me this has usually meant that the .selectorOptions has been set to nil or the array has no entries. Worth checking the number of entries just after you assign into rowCanal.selectorOptions

**Comment by devloe** [comment]
1. Yes
2. The array has 10 entries, Ive check it in the console

Even duplicating the "Repeat" example from https://github.com/xmartlabs/XLForm/blob/master/Examples/Swift/SwiftExample/Inputs/InputsFormViewController.swift, it doesn't work.

**Comment by devloe** [comment]
If it helps: http://cl.ly/2t152J0h0Z1F

**Comment by devloe** [comment]
Solved it!

In the didSelectFormRow override func, I forgot to call super.didSelectFormRow!

Thanks.
