### ISSUE TITLE
Button Done in UITextField

### ISSUE THREAD

**Issue by JeanLebrument** [xmartlabs/XLForm#70]
Hi,

I would like to set a Done button in an UITextField.

I tried this: 

```
        let row = XLFormRowDescriptor(tag : name, rowType : type)
        
        row.cellConfigAtConfigure.setObject(placeholder, forKey: "textField.placeholder")
        row.cellConfigAtConfigure.setObject(UIReturnKeyType.Done.toRaw(), forKey: "textField.returnKeyType")
        row.required = !optional
```

But the XLForm SIGABRT in XLFormRowDescriptor at line 69 in `cellForFormController` method: 

```
[_cell setValue:value forKeyPath:keyPath];
```

**Comment by mtnbarreto** [comment]
@JeanLebrument @ProjectDent I did a trick to allow to configure the property using either `cellConfigAtConfigure ` or `cellConfig`. 

Take a look at my last commit https://github.com/xmartlabs/XLForm/commit/1f7736a13a272419ee10b8ff15dfa9571b132175 .

Now you can set the property by coding:

swift
`row.cellConfigAtConfigure.setObject(UIReturnKeyType.Done.rawValue, forKey:"returnKeyType");`
or in obj-c
`[row.cellConfigAtConfigure setObject:@(UIReturnKeyTypeDone) forKey:@"returnKeyType"];`

Hope it helps.

**Comment by bladev2** [comment]
For anyone that finds this issue: the correct key is
```objc
@"returnKeyType"
```
**not**
```objc
@"textField.returnKeyType"
````

**Comment by ptdenovo** [comment]
practiceRow.cellConfigAtConfigure.setObject(NSTextAlignment.Left.rawValue, forKey: "textLabel.textAlignment")
        practiceRow.cellConfigAtConfigure.setObject(UITableViewCellAccessoryType.DisclosureIndicator.rawValue, forKey: "accessoryType")


Not working....
