### ISSUE TITLE
XLFormRowDescriptorTypeBooleanCheck check only one

### ISSUE THREAD

**Issue by devloe** [xmartlabs/XLForm#702]
Having a series of XLFormRowDescriptorTypeBooleanCheck rows, how can I set it up in order to allow only one to be checked instead of multiple?

**Comment by mats-claassen** [comment]
Hi, you could use the "onChange" block to uncheck all the rows in one section when a row is tapped.

**Comment by devloe** [comment]
Can you tell me where do I find an example?

**Comment by mats-claassen** [comment]
I would do something like this: (I did not test it and you can also get it tidier)
```
row.onChangeBlock = { [weak self] oldValue, newValue, rowDescriptor in
            if (newValue as? Bool) == true {
                for row in rowDescriptor.sectionDescriptor.formRows where row as! XLFormRowDescriptor != rowDescriptor {
                    (row as! XLFormRowDescriptor).value = false
                }
            }
}
```

**Comment by mats-claassen** [comment]
Have a look at #512  as well

**Comment by JordekFluffball** [comment]
Here's a method for making a section work like a radio selection:

`- (void)makeRadioSection:(XLFormSectionDescriptor *)section{
    typeof(self) __weak weakself = self;
    for (XLFormRowDescriptor *row in section.formRows) {
        row.onChangeBlock = ^(id oldValue, id newValue, XLFormRowDescriptor* __unused rowDescriptor){
            if ([newValue  isEqual: @YES]) {
                for (XLFormRowDescriptor *r in rowDescriptor.sectionDescriptor.formRows) {
                    if(r != rowDescriptor){
                        r.value = @NO;
                        [weakself reloadFormRow:r];
                    }
                    
                }
                
            }
            
        };
        
    }
    
}`

**Comment by pnkjdubey0** [comment]
problem with `-(void)makeRadioSection:(XLFormSectionDescriptor *)section` is that, user can unselect the last selected row as well. How can we have at least one selected anyway?

I tried following but got error
`- (void)makeRadioSection:(XLFormSectionDescriptor *)section {
    typeof(self) __weak weakself = self;
    for (XLFormRowDescriptor *row in section.formRows) {
        row.onChangeBlock = ^(id oldValue, id newValue, XLFormRowDescriptor* __unused rowDescriptor) {
            if ([newValue isEqual: @YES]) {
                for (XLFormRowDescriptor *r in rowDescriptor.sectionDescriptor.formRows) {
                    if(r != rowDescriptor){
                        r.value = @NO;
                        [weakself reloadFormRow:r];
                    }
                }
            }
            else {
                rowDescriptor.value = @YES;
                [self reloadFormRow:rowDescriptor];
            }
        };
    }
}`
