### ISSUE TITLE
How to get a callback from Button in a form

### ISSUE THREAD

**Issue by tkeithblack** [xmartlabs/XLForm#706]
I have defined a row in a form as a XLFormRowDescriptorTypeButton. This works fine and I can see and click on the button. But how do I trap the callback from the button so I can do processing?

I see how to link to another form using:
row.action.viewControllerClass = EditAccountViewController.self (in Swift)

But I need to trap the click and do some work.

Thanks,
Keith

**Comment by sumowesley** [comment]
In objective-c you would be using something similar to:
```
self.rowCalc.action.formBlock = ^(XLFormRowDescriptor * sender) {
    // your work in here
};
```

**Comment by tkeithblack** [comment]
Thanks sumowesley, can you explain how the formBlock property is used? I see several properties such as formBlock, formSelector, formSegueClass, etc. but have no idea what they do. I can't find any documentation on them either.

BTW, I'm using Swift, not objective-c. 

Thanks Again.

**Comment by sumowesley** [comment]
I'm afraid I don't know Swift so can't help you with explicit code samples there, hence my Objective-C example.

In the case of the XLFormRowDescriptorTypeButton:

formBlock you would define the block of code to execute when the button is pressed (you may want to deselect the row as part of the same block) e.g.
```
    __typeof(self) __weak weakSelf=self;
    self.rowFind.action.formBlock = ^(XLFormRowDescriptor * sender) {
        [weakSelf.tableView deselectRowAtIndexPath:[weakSelf.form indexPathOfFormRow:sender] animated:YES];
       // now do my work
    };
```
formSelector allows you to define a target selector rather than having to define a block. The selector needs a signature of something like
```
-(void)doSomething:(XLFormRowDescriptor *)row
```
and then you can assign it with:
```
myRow.action.formSelector=@selector(doSomething:);
```
There is also formSegueIdentifier which means you can call a form that your current form links to using a named segue which also means that prepareForSegue: will be invoked e.g.
```
myRow.action.formSegueidentifier = @"SegueToNextForm"
```
The OthersFormViewController.m file in the example app shows some of these being used.

**Comment by tkeithblack** [comment]
sumowesley, great!

The following works in swift:
row.action.formSelector = "doWork"

func doWork {
    print("doing work")
}

Not sure how to get the XLFormRowDescriptor passed into doWork quite yet, but I'll continue to experiment. I'll play with the other options as well. Being able to use prepareForSegue will be a huge benefit.

Thanks,
Keith

**Comment by sumowesley** [comment]
Hi Keith. How about this?
```
func didTouchButton(sender: XLFormRowDescriptor)
```

**Comment by tkeithblack** [comment]
OK, finally figured out how to get the LXFormRowDescription data passed to the callback in swift.    

    private func initializeForm() {
        let form : XLFormDescriptor
        var section : XLFormSectionDescriptor
        var row : XLFormRowDescriptor
...
   row = XLFormRowDescriptor(tag: "soWorkButton", rowType: XLFormRowDescriptorTypeButton, title:"Do Some Work")
   **row.action.formBlock = doMoWork**
...
}

 **  func doMoWork(row: XLFormRowDescriptor) {
        print("doing mo work")
        print(row)
    }**

**Comment by tkeithblack** [comment]
sumowesley, thanks for your help!  Also used your suggestion of deselecting the row in the callback. This was something that was bothering me that I would have had to hunt down so you saved me time on that too. ;)

Here's what it looks like in Swift:    

 func doMoWork(row: XLFormRowDescriptor) {
        // Deselect row.
        **self.tableView.deselectRowAtIndexPath(self.form.indexPathOfFormRow(row)!, animated: true)**
        print("doing mo work")
        print(row)
    }

**Comment by tkeithblack** [comment]
I found that this will also work:

row.action.formSelector = "doMoWork:"   // With Semicolon it passes the XLFormRowDescriptor 

func doMoWork(row: XLFormRowDescriptor) {
     print("doing mo work")
}

**Comment by tkeithblack** [comment]
sumowesley,

I'm now trying to detect when a UISwitch (XLFormRowDescriptorTypeBooleanSwitch) changes state. Any ideas on how to do that? All the usual ways of doing it in a regular ViewController seem to be obfuscated by the XLForm framework.

Thanks!

**Comment by sumowesley** [comment]
Taken from the sample swift app:
```

        row.onChangeBlock = {

            let noValue = "No Value"

            let message = "Old value: \($0 ?? noValue), New value: \($1 ??
noValue)"

            let alertView = UIAlertController(title: "Account Field changed",
message: message, preferredStyle: UIAlertControllerStyle.ActionSheet)

            alertView.addAction(UIAlertAction(title: "Cancel", style:
UIAlertActionStyle.Cancel, handler: nil))

            let row = $2

            self.navigationController?.presentViewController(alertView,
animated: true, completion: nil)

        }

```

You can also have a single method being used to track all changes in the
form too:

```

   override func formRowDescriptorValueHasChanged(formRow:
XLFormRowDescriptor!, oldValue: AnyObject!, newValue: AnyObject!) {

        super.formRowDescriptorValueHasChanged(formRow, oldValue: oldValue,
newValue: newValue)

        if formRow.tag ==
Tags.AccessoryViewRowNavigationStopDisableRow.rawValue
{

            if formRow.value!.boolValue  == true {

                self.form.rowNavigationOptions = self.form.rowNavigationOptions
| XLFormRowNavigationOptions.StopDisableRow

            }

            else{

                self.form.rowNavigationOptions = self.form.rowNavigationOptions
& (~XLFormRowNavigationOptions.StopDisableRow)

            }

        }

        else if formRow.tag ==
Tags.AccessoryViewRowNavigationStopInlineRow.rawValue
{

            if formRow.value!.boolValue  == true {

                self.form.rowNavigationOptions = self.form.rowNavigationOptions
| XLFormRowNavigationOptions.StopInlineRow

            }

            else{

                self.form.rowNavigationOptions = self.form.rowNavigationOptions
& (~XLFormRowNavigationOptions.StopInlineRow)

            }

        }

        else if formRow.tag ==
Tags.AccessoryViewRowNavigationSkipCanNotBecomeFirstResponderRow.rawValue
{

            if formRow.value!.boolValue  == true {

                self.form.rowNavigationOptions = self.form.rowNavigationOptions
| XLFormRowNavigationOptions.SkipCanNotBecomeFirstResponderRow

            }

            else{

                self.form.rowNavigationOptions = self.form.rowNavigationOptions
& (~XLFormRowNavigationOptions.SkipCanNotBecomeFirstResponderRow)

            }

        }



    }

```

**Comment by tkeithblack** [comment]
sumowesley, sweet, that's exactly what I needed.  That block change example was on an edit box in the sample code and not a switch control so I didn't find it, but you're correct, it works on the switches too. It's working just like I need it to now!

I really appreciate your help, thanks!

**Comment by sumowesley** [comment]
My pleasure and happy you have it working.

I'm sure it would help the contributors out if you can close the call if you think your questions have been answered.
