### ISSUE TITLE
XLFormOptionsObject in FormValues dictionary (is this a bug?)

### ISSUE THREAD

**Issue by richardoti** [xmartlabs/XLForm#715]
When I get form values by invoking:
`[self formValues];` in `XLFormViewController` I get `XLFormOptionsObject`s in the NSDictionary. Is this intended behavior or should form return actual value of the `XLFormOptionsObject` in dictionary? If it is a bug, it can be fixed by checking for kind of row and adding either the row's value or the row's  `XLFormOptionsObject` value to the final dictionary:

```Objective-C
    NSMutableDictionary * result = [NSMutableDictionary dictionary];
    for (XLFormSectionDescriptor * section in self.form.formSections) {
        if (!section.isMultivaluedSection){
            for (XLFormRowDescriptor * row in section.formRows) {
                if (row.tag && ![row.tag isEqualToString:@""]){
                    // Check for row type here
                    [result setObject:(row.value ?: [NSNull null]) forKey:row.tag];
                }
            }
        }
        else{
            NSMutableArray * multiValuedValuesArray = [NSMutableArray new];
            for (XLFormRowDescriptor * row in section.formRows) {
                if (row.value){
                    [multiValuedValuesArray addObject:row.value];
                }
            }
            [result setObject:multiValuedValuesArray forKey:section.multivaluedTag];
        }
    }
    return result;
```

**Comment by tommypeps** [comment]
I think not, XLFormOptionsObject is a object with
```Objective-C
    NSString * _formDisplaytext;
    id _formValue;
```
This class permit allow 2 value a value "Display" and other "id" or object, so is a good idea your adapt your code a this format, if you like continue a implementation chord your project

**Comment by richardoti** [comment]
@tommypeps and this is why I'm asking: I think, it's reasonable to put `formValue` to the form output by default. This way it would be easier to get all form values and send to the server/store locally.

**Comment by mats-claassen** [comment]
Hi, it seems reasonable to get the values of the object. Anyway we will have to create a new method to be compatible with older apps.

**Comment by richardoti** [comment]
@mats-claassen allright. I may implement it then.

**Comment by richardoti** [comment]
I've found out another method, `[self httpParameters];` which does exactly what I need, so there is no need in any modification.
