### ISSUE TITLE
Add image to XLFormRowDescriptorTypeText

### ISSUE THREAD

**Issue by devloe** [xmartlabs/XLForm#722]
Is it possible to add an image to a XLFormRowDescriptorTypeText?

Doing below fails:

let emailField = XLFormRowDescriptor(tag: "email", rowType: XLFormRowDescriptorTypeText, title: "Email")
emailField.cellConfig["image"] = UIImage(named: "email")

**Comment by mats-claassen** [comment]
Hi @devloe, try:
```
emailField.cellConfig["imageView.image"] = UIImage(named: "email")
```
