### ISSUE TITLE
"XLFormImageCell.h file not found" (XLFormImageCell.h and .m files not added to project)

### ISSUE THREAD

**Issue by immaterialgoods** [xmartlabs/XLForm#726]
Trying to build with Carthage (or manually) produces an error 'XLFormImageCell.h file not found' because the XLFormImageCell.h file is missing from the project. (To be clear, the file exists, it simply hasn't been added to the Xcode project.)

**Comment by mats-claassen** [comment]
This issue should have been fixed with [this commit](https://github.com/xmartlabs/XLForm/commit/6caa5b32f758ad7bd136423a0f0f67c09e247a35). Are you using the latest version?

**Comment by immaterialgoods** [comment]
Yes and no... This took me a couple of hours to figure out, but: Carthage downloads the most recent _version tag_ it can find. At this time, that's 3.1.0 which was created on December 14. That later commit is not included.

I couldn't find a way to get Carthage to download the master at all; I had to fork it, tag it 3.1.1, and point Carthage at my fork. I'm new to Carthage though so maybe I'm doing something wrong.

**Comment by mats-claassen** [comment]
Closing as there is a new release now (3.1.1)
