### ISSUE TITLE
row.cellClass and row.action.viewControllerClass are mutually exclusive?

### ISSUE THREAD

**Issue by romanr** [xmartlabs/XLForm#727]
I have custom row and custom row action controller at the same time.
If I add customCell to the row, the action.ViewControlelrClass is not called anymore on row select.

Once you set `cellClass` XLForm don't perform row action anymore and expect it to be done by  customCell? 

Do I have to perform initialization and display of action.viewControllerClass manually from my CustomCell?

```objc
row = [XLFormRowDescriptor formRowDescriptorWithTag:@"item" rowType:rowTypePopoverPush title:@"Item"];
row.cellClass = [ItemCell class];
row.action.viewControllerClass = [Picker class];
[section addFormRow:row];
```

ItemCell:

```objc
- (id)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier {
	self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
	if (self) {
		self.textLabel.text=@"Item";
	}
	return self;
}

- (void)configure
{

}

- (void)update
{

	
}
```

**Comment by mats-claassen** [comment]
Hi,
Yes you have to do it manually. The `XLFormButtonCell` does it for example but it is not an inherited feature.

**Comment by romanr** [comment]
That should be mentioned in Custom Cell Class chapter of documentation. I spent hours trying to understand why nothing happens when you tap custom cell.
