### ISSUE TITLE
inline date picker with minuteInterval/minimumDate/maximumDate

### ISSUE THREAD

**Issue by bhirt-bpl** [xmartlabs/XLForm#73]
I need to set min/max dates and an interval for the selection.   I can't seem to figure out how to do this with the current master branch.    I've added some properties to XLFormDateCell to control these and updated setModeToDatePicker: to set the options on the date picker.

    -(void)setModeToDatePicker:(UIDatePicker *)datePicker
    {
        if ((([self.rowDescriptor.rowType isEqualToString:XLFormRowDescriptorTypeDateInline] || [self.rowDescriptor.rowType isEqualToString:XLFormRowDescriptorTypeDate]) && self.formDatePickerMode == XLFormDateDatePickerModeGetFromRowDescriptor) || self.formDatePickerMode == XLFormDateDatePickerModeDate){
            datePicker.datePickerMode = UIDatePickerModeDate;
        }
        else if ((([self.rowDescriptor.rowType isEqualToString:XLFormRowDescriptorTypeTimeInline] || [self.rowDescriptor.rowType isEqualToString:XLFormRowDescriptorTypeTime]) && self.formDatePickerMode == XLFormDateDatePickerModeGetFromRowDescriptor) || self.formDatePickerMode == XLFormDateDatePickerModeTime){
            
            datePicker.datePickerMode = UIDatePickerModeTime;
        }
        else{
            datePicker.datePickerMode = UIDatePickerModeDateAndTime;
        }
        
        if (self.minuteInterval)
            datePicker.minuteInterval = self.minuteInterval;
        
        if (self.minimumDate)
            datePicker.minimumDate = self.minimumDate;
        
        if (self.maximumDate)
            datePicker.maximumDate = self.maximumDate;
        
    }

Then in my form setup I can do this to get the desired effect:

    row = [XLFormRowDescriptor formRowDescriptorWithTag:@"ends" rowType:XLFormRowDescriptorTypeTimeInline title:@"Ends"];
    row.value = [NSDate dateWithTimeIntervalSinceNow:60*60*25];
    XLFormDateCell * dateEndCell = (XLFormDateCell *)[row cellForFormController:self];
    dateEndCell.minuteInterval = 15;
    dateEndCell.minimumDate = start;

If there is another way to do this without modifying the XLForm code, let me know.   If this feature isn't currently supported and my solution seems acceptable to you, I can submit a pull request.

![screenshot_835](https://cloud.githubusercontent.com/assets/7284485/3760483/80f215ce-1878-11e4-89c5-b4b23bf533ff.png)

**Comment by brianfox201** [comment]
Can we change min/max date properties run time ?

**Comment by JerryWang761208** [comment]
Instead of using row.cellConfigAtConfigure...
I try to use the following, and it works.
````objective-c
[row.cellConfig setObject:minimumDate_you_want forKey:@"minimumDate"];
````

**Comment by i-am-chris** [comment]
@brianfox201 did you have any success with that?? I am looking for the same thing.

**Comment by ManiRelavant** [comment]
NSDate *currentDate = [NSDate date];
NSDictionary *dict = @{
        @"datePicker.maximumDate" : currentDate
    };
    [row.cellConfigAtConfigure addEntriesFromDictionary: dict];

try to use
