### ISSUE TITLE
rowDescriptor not available to init or configure?

### ISSUE THREAD

**Issue by jpmhouston** [xmartlabs/XLForm#731]
A cell's `rowDescriptor` is currently not set until `-[XLFormViewController updateFormRow:]`, which gets the cell from the `XLFormRowDescriptor` itself with `rowDescriptor == nil`, then for some reason its up to the view controller's to set `rowDescriptor`. `XLFormRowDescriptor` creates the cell, why doesn't it set this property itself?

A custom `init` method which passes this in might makes sense, or perhaps calling the setter after the fact to make the nib & non-nib cases more similar.

Doing this would make `rowType` available during `-configure` (if not `init` too), which could improves a common pattern in the builtin cell classes where what's clearly configuration is done at `update` time. I'd also like to see when `configure` and `configureCellAtCreationTime` occurs to be swapped so that the latter can take precedence over configuration based on `rowType`.

**Comment by mats-claassen** [comment]
You are right, the rowDescriptor should be set earlier. Will fix this soon.
