### ISSUE TITLE
Currency Localization

### ISSUE THREAD

**Issue by Wildregar** [xmartlabs/XLForm#734]
Hi,

I created a row with XLFormRowDescriptorTypeDecimal type. When my keyboard is open I see a comma (,), but if I write the comma, this is cancelled. This row type allow only (.) decimal.

There is a way to use localization separator?

**Comment by mats-claassen** [comment]
Have a look at NSFormatter support examples in the examples app. You should be able to set  a formatter for your row

**Comment by m-revetria** [comment]
Closing this due to lack of response
