### ISSUE TITLE
How to dynamically set the height of the Cell

### ISSUE THREAD

**Issue by cooliean** [xmartlabs/XLForm#742]
I have a CustomRow, but I want to change the dynamic of his height. What am I supposed to do, thank you

**Comment by saturnaa** [comment]
Override getHeightForRowAtIndexPath in your tableview and you could call a method there like customCell.getHeight() inside the block and calculate the height dynamically for that cell. Also inside your custom cell's controller you can call setNeedsDisplay() that will force the cell to redraw itself. That also causes drawRect() method to trigger which you can also override.
