### ISSUE TITLE
Can I just add a normal UITableViewCell instance to XLForm

### ISSUE THREAD

**Issue by SuperMarioBean** [xmartlabs/XLForm#747]
hi, there. I am new to XLForm, and I love it! what is my problem is, as we known, usually a form include some only show row, it did not need edit to submit, and I got a lot of this kind of cell, they contain image views and label. I want to show show this cell on xlform and did not want to subclass the XLFormBaseCell because these cell just for showing, not edit.

I think adapt to UITableViewCell(just show) and XLFormBaseCell(edit, show, validate) is very useful, your form DSL is very easy to inherit to build complex from classes compared to UItableivew itself.

**Comment by mats-claassen** [comment]
No, you have to subclass XLFormBaseCell
