### ISSUE TITLE
Configuring DateInline and MultipleSelector Rows (backgroundColor, tint, etc)

### ISSUE THREAD

**Issue by batnom** [xmartlabs/XLForm#756]
Hi all, I'm trying customise the extra bits that come out of the rows such as `XLFormRowDescriptorTypeMultipleSelector` and `XLFormRowDescriptorTypeDateInline`

When you tap on `XLFormRowDescriptorTypeMultipleSelector` the date picker slides down, but it's the default white background.  Similarly with `XLFormRowDescriptorTypeDateInline` and the new tableview it pushes to for the selection.

Is there a way to set the backgroundColor, tint, etc for these parts?  

I've tried many variations of the following and searched through a whole lot of Github Issues with no luck.

```
    if (row.rowType == XLFormRowDescriptorTypeDateInline) {
        [row.cellConfigAtConfigure setObject:[UIColor redColor] forKey:@"datePicker.backgroundColor"];
        [row.cellConfigAtConfigure setObject:[UIColor blackColor] forKey:@"datePicker.tintColor"];
    }
```

Many thanks.

**Comment by Jeff-F** [comment]
in your subcontroller of xlformviewcontroller,  overide method: 

> -(void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath;

if cell is XLFormDatePickerCell class, then set datepicker's backgroudcolor and textColor;

**Comment by mats-claassen** [comment]
That is a valid way. Do not forget to call super when you override that method

**Comment by batnom** [comment]
@Jeff-F @mats-claassen Thanks for this, was able to get it working as below.

Do you have any thoughts on how to handle the whole pushed view controller's (from a `XLFormRowDescriptorTypeMultipleSelector` row) background/text colours too?

Date Picker solution:

    - (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath {

      XLFormRowDescriptor *row = [self.form formRowAtIndex:indexPath];
      if ([row.rowType isEqualToString:@"datePicker"]) {
          // set background color in here
      }

      // this has to be at the bottom
      [super tableView:tableView willDisplayCell:cell forRowAtIndexPath:indexPath];
    
    }

Many thanks again
