### ISSUE TITLE
how can two booleanSwitchs importing mutex relationship

### ISSUE THREAD

**Issue by bibubi** [xmartlabs/XLForm#757]
i add two booleanSwitchs in my form(A and B),
i want the form can do this
when i click A. its value will be YES;
and then i click B. B Value be YES and A be NO.
Simply,they only one of them can be isChecked;

BTW,i'm Chinese user.my English is poor :(

**Comment by iBenjamin** [comment]
#512

**Comment by mats-claassen** [comment]
Also you can do that easily like explained in #702
