### ISSUE TITLE
Can't change the keyboard type for XLFormRow 

### ISSUE THREAD

**Issue by JaydenR** [xmartlabs/XLForm#761]
I want to be able to use UIKeyboardTypeNumpad to enter a 19 digit customer reference number, but with XLFormRowDescriptorTypeInteger the XLFormTextFieldCell sets the value to an integer which is too small, and if I try to use XLFormRowDescriptorTypeText and change the keyboardType the  XLFormTextFieldCell update method automatically changes the keyboard type back to the default keypad.

**Comment by ernestopino** [comment]
I have the same problem… in my case the field is for user security code (4 digits from 0 to 9). Configuring cell with XLFormRowDescriptorTypeInteger the user can not enter the code "0000", the value of the cell always is "0" (integer value).

How can I change the keyboard type for cell of type "XLFormRowDescriptorTypeText" to show UIKeyboardTypeNumberPad ???

Thanks !!!

**Comment by ernestopino** [comment]
@JaydenR, here is my solution… I hope it helps ;)

### 1. Create a class that inherits from XLFormTextFieldCell

#### `TASecurityCodeFieldCell.h`

Important, declare a new constant for a custom type of cell, in my case… **TAFormRowDescriptorTypeSecurityCodeField**

```
#import "XLFormTextFieldCell.h"

extern NSString * const TAFormRowDescriptorTypeSecurityCodeField;

@interface TASecurityCodeFieldCell : XLFormTextFieldCell

@end
```

#### `TASecurityCodeFieldCell.m`

In the implementation file, use `load` class method to register your new class. Then, override `update` method and configure the textfield with your preferences.

```
#import "TASecurityCodeFieldCell.h"

NSString * const TAFormRowDescriptorTypeSecurityCodeField = @"TAFormRowDescriptorTypeSecurityCodeField";

@implementation TASecurityCodeFieldCell

+(void)load
{
    [XLFormViewController.cellClassesForRowDescriptorTypes setObject:[TASecurityCodeFieldCell class] forKey:TAFormRowDescriptorTypeSecurityCodeField];
}

#pragma mark - XLFormDescriptorCell

-(void)update
{
    [super update];
    
    self.textField.keyboardType = UIKeyboardTypeNumberPad;
    self.textField.autocorrectionType = UITextAutocorrectionTypeNo;
    self.textField.secureTextEntry = YES;
}

@end
```

### 2. Configure your row in the corresponding view controller

Use your new type of cell **TAFormRowDescriptorTypeSecurityCodeField** to obtain a row descriptor. Then, add other configurations if you like… placeholder, validator, transformer, etc.

```
...

row = [XLFormRowDescriptor formRowDescriptorWithTag:@"security-code" rowType:TAFormRowDescriptorTypeSecurityCodeField];
[row.cellConfigAtConfigure setObject:@"●●●●" forKey:@"textField.placeholder"];
[row addValidator:[XLFormRegexValidator formRegexValidatorWithMsg:NSLocalizedString(@"configForm.securityCode.validation", nil) regex:kPinValidationRegex]];
row.valueTransformer = [TASecurityCodeTransfomer class];
row.required = YES;
row.requireMsg = NSLocalizedString(@"form.validator.required-field", nil);

[section addFormRow:row];

...
```

### Bonus

Here is my `TASecurityCodeTransfomer` class… if you need it ;)

#### `TASecurityCodeTransfomer.h`

```
#import <Foundation/Foundation.h>

@interface TASecurityCodeTransfomer : NSValueTransformer

@end
```

#### `TASecurityCodeTransfomer.m`

```
#import "TASecurityCodeTransfomer.h"

@implementation TASecurityCodeTransfomer

+ (Class)transformedValueClass
{
    return [NSString class];
}

+ (BOOL)allowsReverseTransformation
{
    return NO;
}

- (id)transformedValue:(id)value
{
    if (!value) return nil;
    
    if ([value isKindOfClass:[NSNumber class]])
    {
        return [value stringValue];
    }
    
    return nil;
}

@end
```

**Comment by mats-claassen** [comment]
Yeah you must create a subclass of XLFormTextFieldCell (or similar) and change keyboardtype. The solution of @ernestopino looks good. 

@JaydenR I believe we can close this?

**Comment by JaydenR** [comment]
Hi, thanks for the replies,

@ernestopino I did consider making a subclass, but I hoped there was a more convenient way to change the keyboard type, though since you have provided your solution that is pretty convenient, thank you :).

@mats-claassen  Yeah we can close this, though out of curiosity, is it necessary to set the keyboard type to UIKeyboardTypeDefault in the update method for XLFormTextFieldCell when the row type is XLFormRowDescriptorTypeText?

My temporary solution was to comment out this line and so far I have not encountered any problems. Removing this line should preserve the functionality of all the other row types yet allow the keyboard type to be changed for Text, though I don't know if there are any situations where the line is necessary.

**Comment by mats-claassen** [comment]
Well, I did just try to use `cellConfig` for this but it seems UITextField is not key-value coding compliant for this attribute. 

As you pointed out it might not be necessary to set the default value to the textfield.
