### ISSUE TITLE
XLFormRowDescriptorTypeImage value is null 

### ISSUE THREAD

**Issue by focusedonfit** [xmartlabs/XLForm#763]
This is my first time using the new Image row. I am able to select an image and the image changes to the new image in the row, however when I look at the values it's null.

```
let rowPhoto : XLFormRowDescriptor = XLFormRowDescriptor(tag: "image_id", rowType: XLFormRowDescriptorTypeImage, title: "Photo")

var formValues = self.form.httpParameters(self) as! [String:AnyObject]
```
`"image_id": <null>`

**Comment by focusedonfit** [comment]
I would expect that the it would be a UIImage correct?

**Comment by focusedonfit** [comment]
I was using httpParameters and it returns nil
formValues() returns the UIImage

**Comment by mats-claassen** [comment]
I think this is correct, you wont be sending the image over HTTP by default. Normally you will have to upload it separately.
