### ISSUE TITLE
Remove section header/top space

### ISSUE THREAD

**Issue by royherma** [xmartlabs/XLForm#766]
How can we remove the top space (/header) above each of the first rows in a new section (see attached photo):

![screen shot 2016-04-12 at 12 58 26 pm](https://cloud.githubusercontent.com/assets/3466248/14473790/96b434c6-00ae-11e6-941d-6c1e54daefbd.png)

**Comment by mats-claassen** [comment]
You can override the tableviews datasource methods and set that value. Look out for `tableView(tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat` and set it to something small. In my experience 0 does not work well

**Comment by royherma** [comment]
@mats-claassen That doesn't work i tried it (`RubiFormViewController` is a subclass of `XLFormViewController`) ..

```
@interface RubiFormViewController () <UITableViewDelegate>

@end

@implementation RubiFormViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.tableView.delegate = self;
    self.tableView.sectionHeaderHeight = 0;
    self.tableView.sectionFooterHeight = 0;
    self.automaticallyAdjustsScrollViewInsets = NO;
}

- (void)endEditing:(XLFormRowDescriptor *)rowDescriptor {
    [super endEditing:rowDescriptor];
    [[NSNotificationCenter defaultCenter] postNotificationName:kProfileIsDirty object:nil];
}
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section {
    return 0;
}
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section {
    return 0;
}
@end
```

**Comment by mats-claassen** [comment]
What style has your tableview? Grouped or Plain? 
I believe grouped should work if you return 0.01 in 
`- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section`

**Comment by maheshlalu** [comment]
![simulator screen shot 04-oct-2016 3 35 23 pm](https://cloud.githubusercontent.com/assets/18379397/19070348/6c2ed1d8-8a48-11e6-9450-97e6b88f9d8f.png)
I want To remove the space between particular section how can i do . please help me

**Comment by mats-claassen** [comment]
It should really work with `- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section` and `- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section`.  Did you try that? 
You must just not return 0 but something like 0.1 and if you want it just for one section then you have to check that `section` is your section.

**Comment by LLietz** [comment]
Is it a grouped TableView? In that case you need to set the height of the tableView.tableHeaderView bigger than 0 (for example = 0.01), otherwise iOS will set a default value to it.
Let me know if it helped!

**Comment by agoubi** [comment]
yes probably its because you have a grouped tableview style so you can just change the height of your header from 0 to 0.1 and it will work

**Comment by abmomin** [comment]
To make heightForFooterInSection method be called you first need to have a viewForFooterInSection, this is same for header. without a view whom will you give a height?. In case if you don't want default height to be appear, you can provide a empty view and set heightForFooterInSection return 0.0

**Comment by eskimo** [comment]
I know this is an old thread, but came here from google and I'm sure others will too, you don't need to do 0.01 for the height for header/footer, you can return nil from viewForHeaderInSection.
