### ISSUE TITLE
segment title truncated on XLFormSegmentedCell

### ISSUE THREAD

**Issue by yj10041004** [xmartlabs/XLForm#768]
if a segment title  does not fit the segment width,  its truncated like "..."
added  below to prevent  truncation.

self.segmentedControl.apportionsSegmentWidthsByContent = YES;

**Comment by mats-claassen** [comment]
I think that setting should not be set by default but it can be set using `cellConfig`.

```swift
row.cellConfig["segmentedControl.apportionsSegmentWidthsByContent"] = true
```

Thanks for the comment. I am closing this because I do not think it is an issue.
