### ISSUE TITLE
How can XLForm be added to an existing project?

### ISSUE THREAD

**Issue by tciuro** [xmartlabs/XLForm#771]
What are the steps needed to add XLForm to an existing project? It would be great if the documentation had a section explaining what the steps are, especially for projects that don't use CocoaPods or Carthage.

**Comment by mats-claassen** [comment]
Hi @tciuro you can drag the XLForm.xcodeproj of the root folder into your project and add the XLForm.framework to the embedded binaries of your project.

Then `#import "XLForm/XLFormViewController.h"`
or whatever you need
