### ISSUE TITLE
Unrecognized Selector on placeholder for textField

### ISSUE THREAD

**Issue by negry** [xmartlabs/XLForm#778]
code:

row = XLFormRowDescriptor(tag: Tags.curp, rowType: XLFormRowDescriptorTypeText, title: "CURP: ")
        row.cellConfigAtConfigure["textField.placeholder"] = "Required"
        row.cellConfig["textField.textColor"] = UIColor.whiteColor()
        row.cellConfig.setObject(UIColor.purpleColor(), forKey: "textField.attributedPlaceholder")
        row.required = true
        section.addFormRow(row)

**Comment by negry** [comment]
this is the error: unrecognized selector sent to instance 0x154571c80

**Comment by mats-claassen** [comment]
Setting placeholder like that should work but you cannot set a color to the `attributedPlaceholder `. You have to set an attributedString or just set the textColor.

**Comment by hanwenbo** [comment]
怎么设置占位符的字体大小呢？

**Comment by mats-claassen** [comment]
I don't understand Chinese, but Google translate lets me guess you want to set the size of the placeholder. If so, have a look at how attributed strings are used. Its not an XLForm issue.

Closing this issue as answered
