### ISSUE TITLE
Things are broken on the iOS8/Xcode6

### ISSUE THREAD

**Issue by ReDetection** [xmartlabs/XLForm#78]
Created simple form like this

``` objective-c
    XLFormDescriptor *form = [XLFormDescriptor formDescriptorWithTitle:@"Test"];
    XLFormRowDescriptor *row = [XLFormRowDescriptor formRowDescriptorWithTag:@"phone" rowType:XLFormRowDescriptorTypePhone title:@"Phone"];
    XLFormSectionDescriptor *section = [XLFormSectionDescriptor formSection];
    [section addFormRow:row];
    [form addFormSection:section];
    self.form = form;
```

and got screen like this
![ios simulator screen shot aug 4 2014 22 30 06](https://cloud.githubusercontent.com/assets/458005/3799234/476264e0-1bec-11e4-8786-2ef1eddac77c.png)

**Comment by guyisra** [comment]
In this case, should the controller have a the same title as formDescriptorWithTitle? because it's not working for me.. Am I missing something?
