### ISSUE TITLE
how to dynamically create form within a form and pass the pushed form values back to the origin form?

### ISSUE THREAD

**Issue by leewi9** [xmartlabs/XLForm#783]
when click on `XLFormRowDescriptorTypeButton`, a new form with 3 or 4 fields will be pushed, and then after inputing all the fields in the new form, how to get the new form values and pass them back to the original form, and assemble it in the new form's `formValues`?

**Comment by leewi9** [comment]
<img width="880" alt="2016-05-20 11 48 23" src="https://cloud.githubusercontent.com/assets/10832544/15416690/d00e88bc-1e80-11e6-928a-59827538f517.png">

please help, thanks.

**Comment by hanwenbo** [comment]
你的placehoder的大小如何设置的  我就是设置不了

**Comment by leewi9** [comment]
@hanwenbo 

```
    //
    row = [XLFormRowDescriptor formRowDescriptorWithTag:@"position" rowType:XLFormRowDescriptorTypeName title:@"岗位"];
    [row.cellConfigAtConfigure setObject:@"占位文字" forKey:@"textField.placeholder"];
    [section addFormRow:row];
```

**Comment by mats-claassen** [comment]
Hi @leewi9 I would suggest using a `XLFormRowDescriptorTypeButton`. 
You can then push another form viewController. 
To show the values in the initial form you might have to create your custom subclass of `XLFormButtonCell`

**Comment by jeantimex** [comment]
Thanks @mats-claassen, how to pass the form data between two form view controllers? Is it possible to use segue and unwind segue? Thanks!!

**Comment by smstudio2008** [comment]
EASY !

- (void)fillEditForm {
 
    if ([self.Name.displayText isEqualToString:@"John"]) {
        [self.form formRowWithTag:@"FirstNamel"].value =
        [XLFormOptionsObject formOptionsObjectWithValue:self.Name.displayText
                                            displayText:NSLocalizedString(@"Smith", nil)];
        
        
        
    }
    
}

**Comment by m-revetria** [comment]
Closing this due to lack of response
