### ISSUE TITLE
不可以垂直居中

### ISSUE THREAD

**Issue by hanwenbo** [xmartlabs/XLForm#784]
当我把左侧字体大小改成14时，就不垂直居中了，这个改怎么办呢

**Comment by hanwenbo** [comment]
默认字体是16吧？我觉得太大了 要和整体UI统一 改成14后对不齐，不知道如何解决

**Comment by hanwenbo** [comment]
神奇的是：如果右侧是XLFormRowDescriptorTypeSelectorSegmentedControl 元素 那么左侧14也是垂直居中的。

**Comment by hanwenbo** [comment]
如果是XLFormRowDescriptorTypeText 字体设置小了 就不垂直居中了

**Comment by mats-claassen** [comment]
Sorry @hanwenbo but I don't speak Chinese... Could you translate that to english?

**Comment by korgx9** [comment]
He things China is everywhere )
