### ISSUE TITLE
Get attributed text from textview

### ISSUE THREAD

**Issue by prgorasiya** [xmartlabs/XLForm#799]
I am setting attributed text (With HTML Tags) as [row.cellConfig setObject:description forKey:@"textView.attributedText"]
So, at the time of saving data I want to get that attributed text in return but I couldn't find any way to get that.

**Comment by mats-claassen** [comment]
Did you try calling `cellForFormController` to get the cell of a rowDescriptor and then casting it to the appropiate type and accessing its textView?

**Comment by prgorasiya** [comment]
```
XLFormRowDescriptor * descriptionRowDescriptor = [XLFormRowDescriptor formRowDescriptorWithTag:@"Description" rowType:XLFormRowDescriptorTypeTextView];
XLFormTextViewCell * textViewCell = (XLFormTextViewCell *)[descriptionRowDescriptor cellForFormController:self];
```

I have done this but I am not able to get attributed text of the textview.
Apart from that, I am trying to achieve my result by adding a custom cell, I have done all the things same as mentioned into one of your examples, but I am not able to load that custom cell, it is being loaded as blank row and child objects of that cell like text view and label are null when I checked into the method

```
- (void)configure
{
    [super configure];    
    NSLog(@"%@", self.label);
}
```

My code to create custom row

```
row = [XLFormRowDescriptor formRowDescriptorWithTag:@"Description" rowType:XLFormRowDescriptorTypeHTML];
row.cellClass = [descriptionTableViewCell class];
row.required = YES;
[section addFormRow:row];
```

Can you please help me with that ?
Thanks

**Comment by mats-claassen** [comment]
Your textView issue looks more to be something with UITextView. Look [here](http://stackoverflow.com/questions/18926399/how-to-get-current-attributed-string-in-non-editable-uitextview), you may have to set it selectable to get the attributed text.

On your other question, did you remember to add it:
```
[[XLFormViewController cellClassesForRowDescriptorTypes] setObject:[MYCustomCellClass class] forKey:kMyAppCustomCellType];
```

In the readme there is [a section](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row) about custom rows.

**Comment by m-revetria** [comment]
closing this due to lack of response
