### ISSUE TITLE
How can change Done button text of XLFormRowDescriptorTypeSelectorPickerView?

### ISSUE THREAD

**Issue by kuko91** [xmartlabs/XLForm#802]
I have created this selectorpickerview and I want to change the text of done button in the toolbar...
Thanks!
row = [XLFormRowDescriptor formRowDescriptorWithTag:@"kSelectorPickerView" rowType:XLFormRowDescriptorTypeSelectorPickerView title:@"Talla de camiseta"];
    row.selectorOptions = @[[XLFormOptionsObject formOptionsObjectWithValue:@(0) displayText:@"XS"],
                            [XLFormOptionsObject formOptionsObjectWithValue:@(1) displayText:@"S"],
                            [XLFormOptionsObject formOptionsObjectWithValue:@(2) displayText:@"M"],
                            [XLFormOptionsObject formOptionsObjectWithValue:@(3) displayText:@"L"],
                            [XLFormOptionsObject formOptionsObjectWithValue:@(4) displayText:@"XL"]
                            ];
    row.value = [XLFormOptionsObject formOptionsObjectWithValue:@(0) displayText:@"XS"];
    [section addFormRow:row];

**Comment by mats-claassen** [comment]
Do you want to change the input accessory view? Have a look at [this](https://github.com/xmartlabs/XLForm#how-to-change-input-accessory-view-navigation-view) in the readme

**Comment by kuko91** [comment]
I want to change de "Done" text of the selector picker view.
![screenshot](https://cloud.githubusercontent.com/assets/12160439/16049812/6505c540-3216-11e6-8ab1-aa29f65297f9.png)

**Comment by mats-claassen** [comment]
Currently there is no easy way of doing that. You would have to override `-(UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor;` and return a custom view. But you would also have to implement all of its functionality...

This is because the done button has style UIBarButtonSystemItemDone and you cannot change its title.

**Comment by kuko91** [comment]
Ok, I got it.

Thank you!
