### ISSUE TITLE
Failed to push from formviewcontroller to a custom viewcontroller

### ISSUE THREAD

**Issue by CaliosD** [xmartlabs/XLForm#803]
In a navigation controller stack, the first controller is a normal controller, while the form controller is the second one. I want to push from a cell of the second controller to a custom view controller like this.

```objc
    XLFormRowDescriptor *phoneRow = [XLFormRowDescriptor formRowDescriptorWithTag:kPhone rowType:XLFormRowDescriptorTypeButton title:@"Phone"];
    __typeof(self) __weak weakSelf = self;
    phoneRow.action.formBlock = ^(XLFormRowDescriptor *sender){
        [weakSelf deselectFormRow:sender];
        // ContactViewController is my custom controller, which is just inherited from UIViewController.
        ContactViewController *contactVC = [[ContactViewController alloc] init];
        [weakSelf.navigationController pushViewController:contactVC animated:YES];
    };
    [section addFormRow:phoneRow];
```

However, I find myself fail to push to contactVC all the time. Is there anything else I need to do? I followed the example demo, but not work for my issue.

PS: I also tried to set the form controller as the first in navigation stack, and it pushes all right! I don't know if it makes any sense...And wish someone could help me. Thanks in advance.

**Comment by m-revetria** [comment]
Hi @CaliosD,

Could you elaborate more on what is not working? 

I modified a bit the example to push a new viewcontroller similar to your example and it worked fine:

```objc
    // From the ExamplesFormViewController.m in the example project
    
    // NativeEventFormViewController
    row = [XLFormRowDescriptor formRowDescriptorWithTag:@"realExamples" rowType:XLFormRowDescriptorTypeButton title:@"iOS Calendar Event Form"];
//    row.action.formSegueIdentifier = @"NativeEventNavigationViewControllerSegue";
    row.action.formBlock = ^(XLFormRowDescriptor *sender) {
        UIViewController *viewController = [UIViewController new];
        [self.navigationController pushViewController:viewController animated:YES];
    };
    [section addFormRow:row];
```

And the `viewController` created in the formBlock is pushed correctly.

![issue_803](https://cloud.githubusercontent.com/assets/4791678/26556624/f676916c-4471-11e7-87c1-bd3d2e5653ee.gif)

**Comment by CaliosD** [comment]
It's so kind of you to add the code and gif. However, it's been a long time ago and I remembered that the controller was designed more complicated and I didn't use XLForm there.
It seems to work fine and you can close this issue at present. I'll let you know if I meet any other problem later. 

Thanks again for your attention. :D
