### ISSUE TITLE
Objective-C Examples crash on 3.2.0

### ISSUE THREAD

**Issue by ngheungyu** [xmartlabs/XLForm#808]
Hi Team,

I ran the Examples Objectve-C and once I clicked on "Selectors" & "NSFormatter support" row, it crashed. Other rows like "Text Fields" are working fine.

Setup:
Cocoapod v1.0.1
XCode 7.3.1
Simulator iPhone 6

Please see my log below:

> 2016-06-24 22:51:38.807 XLForm[4529:201081] Simulator user has requested new graphics quality: 10
> 2016-06-24 22:51:40.854 XLForm[4529:201081] -[XLFormRowDescriptor setValueFormatter:]: unrecognized selector sent to instance 0x7ffd3a64e750
> 2016-06-24 22:51:40.860 XLForm[4529:201081] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[XLFormRowDescriptor setValueFormatter:]: unrecognized selector sent to instance 0x7ffd3a64e750'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x0000000103f86d85 __exceptionPreprocess + 165
> 	1   libobjc.A.dylib                     0x00000001039fadeb objc_exception_throw + 48
> 	2   CoreFoundation                      0x0000000103f8fd3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
> 	3   CoreFoundation                      0x0000000103ed5cfa ___forwarding___ + 970
> 	4   CoreFoundation                      0x0000000103ed58a8 _CF_forwarding_prep_0 + 120
> 	5   XLForm                              0x0000000100e78c06 -[FormattersViewController init] + 438
> 	6   XLForm                              0x0000000100eef938 -[XLFormButtonCell controllerToPresent] + 248
> 	7   XLForm                              0x0000000100eef58b -[XLFormButtonCell formDescriptorCellDidSelectedWithFormController:] + 2139
> 	8   XLForm                              0x0000000100f29c55 -[XLFormViewController didSelectFormRow:] + 181
> 	9   XLForm                              0x0000000100f2eaf6 -[XLFormViewController tableView:didSelectRowAtIndexPath:] + 374
> 	10  UIKit                               0x00000001025c61c6 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1887
> 	11  UIKit                               0x00000001025c641b -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 388
> 	12  UIKit                               0x000000010248af62 _runAfterCACommitDeferredBlocks + 317
> 	13  UIKit                               0x000000010249ee4c _cleanUpAfterCAFlushAndRunDeferredBlocks + 95069814
> 	14  UIKit                               0x00000001024ab147 _afterCACommitHandler + 90
> 	15  CoreFoundation                      0x0000000103eabc37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
> 	16  CoreFoundation                      0x0000000103eabba7 __CFRunLoopDoObservers + 391
> 	17  CoreFoundation                      0x0000000103ea17fb __CFRunLoopRun + 1147
> 	18  CoreFoundation                      0x0000000103ea10f8 CFRunLoopRunSpecific + 488
> 	19  GraphicsServices                    0x0000000106ad3ad2 GSEventRunModal + 161
> 	20  UIKit                               0x000000010247ef09 UIApplicationMain + 171
> 	21  XLForm                              0x0000000100e625cf main + 111
> 	22  libdyld.dylib                       0x00000001053aa92d start + 1
> 	23  ???                                 0x0000000000000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb)

**Comment by ziogaschr** [comment]
Will try to check this during the weekend. Apologies if this is something I missed. It works fine on Swift at the moment

**Comment by ngheungyu** [comment]
thank @ziogaschr for the prompt response! Appreciate it.

**Comment by fwhenin** [comment]
Can you post your code on how you set the row up?

**Comment by ngheungyu** [comment]
@fwhenin it's in the [Examples/Objective-C](https://github.com/xmartlabs/XLForm/tree/master/Examples/Objective-C)

**Comment by mats-claassen** [comment]
Hi @ngheungyu are you sure you did not change anything? 
This does not crash for me on simulator (neither master branch nor release 3.2.0 source code)

**Comment by ngheungyu** [comment]
@mats-claassen thanks. I clone it fresh and didn't change anything. But I did upgrade Cocoapods to 1.0.1 .... now same problem crashed on 3.1.2. Any thoughts would be much appreciated!

**Comment by ngheungyu** [comment]
So in the end, it's related to Cocoapod caching issue [explained here](https://github.com/CocoaPods/CocoaPods/issues/5341). I've managed to solve it by deleting stuffs inside DerivedData. Thanks guys!

**Comment by mats-claassen** [comment]
Great to know you resolved the issue
