### ISSUE TITLE
How to dynamic show photo in cell with xlform

### ISSUE THREAD

**Issue by dwjdwj1216** [xmartlabs/XLForm#811]
I want to design a cell, which is used to show photos that user selected. But the number of photos is dynamic. So the cell's width and height is dynamic. I don't know how to make it happen. Can anyone give me a suggestion?.

**Comment by mats-claassen** [comment]
You can use the `height` property to define the height of your cell. The width should be the width of the tableView always.
But are you sure you want to do this in a tableView cell? Why do not put this in another view?

**Comment by dwjdwj1216** [comment]
Ok.I think i have a way to finish it. But there is an another problem. I click the button in the custom cell, and push new controller. When come back, the cell's update method did't call, what's the problem?

**Comment by dwjdwj1216** [comment]
Of course i can put it in a view. But how can i compose what i need using the view with XLForm?

**Comment by mats-claassen** [comment]
Since 3.2.0 there is a `height` property. There is [an example](https://github.com/xmartlabs/XLForm#how-to-change-the-height-of-one-cell) in the readme.
And you can use `onChangeBlock` to update that view when a new photo is selected or whatever. There is an example in #702

**Comment by dwjdwj1216** [comment]
the onChangeBlock is awesome!! Thank you!
