### ISSUE TITLE
Setting autocapitalizationType property on textField crashes the control.

### ISSUE THREAD

**Issue by vishal-p** [xmartlabs/XLForm#812]
Example 

`row = XLFormRowDescriptor(tag: Tags.Name, rowType: XLFormRowDescriptorTypeText, title: "Full name")
row.cellConfig["textField.capitalizationType"] = UITextAutocapitalizationType.Words.rawValue`

Crash:

`2016-06-29 14:43:17.777 Homepass[23844:29908723] Exception name=NSUnknownKeyException, reason=[<UITextField 0x7f8e51e14dd0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key capitalizationType., userInfo={
    NSTargetObjectUserInfoKey = "<UITextField: 0x7f8e51e14dd0; frame = (0 0; 0 0); text = 'Junaid khan'; clipsToBounds = YES; opaque = NO; layer = <CALayer: 0x7f8e51e15120>>";
    NSUnknownUserInfoKey = capitalizationType;
} addresses=(0x10700fd6d 0x1082c0deb 0x10700f9c9 0x102e3c19b 0x1051044b6 0x102e6b5ed 0x106602b84 0x106f411e6 0x106f410af 0x10660292c 0x1066027e7 0x1066030f5 0x1051a74f4 0x1051a762c 0x10517bd4f 0x1051b0686 0x105197344 0x105104980 0x1044cec00 0x1044c308e 0x1044c2f0c 0x1044b73c9 0x1044e5086 0x10507619b 0x106f34c37 0x106f34ba7 0x106f2a7fb 0x106f2a0f8 0x10b079ad2 0x105049f09 0x1009e7c87 0x10920592d 0x3)`

**Comment by m-revetria** [comment]
Hi @vishal-p,

Notice that the property name is `autocapitalizationType`. So, you should have used: 
```swift
row.cellConfig["textField.autocapitalizationType"] = UITextAutocapitalizationType.Words.rawValue
   ``` 
instead of:
 ```swift
row.cellConfig["textField.capitalizationType"] = UITextAutocapitalizationType.Words.rawValue
```

Regards
