### ISSUE TITLE
Accept Conditions of Use and Privacy Notice When finish the form

### ISSUE THREAD

**Issue by AlbertoMrFz** [xmartlabs/XLForm#813]
Hi,
it is possible to make something similar this?
![testamazon](https://cloud.githubusercontent.com/assets/9303324/16478710/c4e9d7bc-3e9b-11e6-99f2-fe2f6f8597d5.PNG)

**Comment by mats-claassen** [comment]
You should use `-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section` and `-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath` to accomplish that.
Just define those methods in your `XLFormViewController subclass`

**Comment by AlbertoMrFz** [comment]
Hi, thanks for your answer, but how i can inmplements that in swift??

**Comment by mats-claassen** [comment]
What do you mean? Those delegate methods?

**Comment by m-revetria** [comment]
Closing this due to lack of response.
