### ISSUE TITLE
How to write selectorOption in ladder form?

### ISSUE THREAD

**Issue by TaichiAkimoto** [xmartlabs/XLForm#820]
I have written options on xlform using selectorOption so far.
Now, I want to show them in ladder form, like date(calender) is shown on xlfrom.
If you know how to do it, please tell me.
Thanks in advance.

**Comment by mats-claassen** [comment]
What do you mean by ladder? Can you be more explicit? 
Do you mean the UIPicker? Have you tried `XLFormRowDescriptorTypePicker`

**Comment by TaichiAkimoto** [comment]
UIPicker is exactly what I've been looking for.
Thank you!

Moreover, I want to show two ladders in parallel if I click XLForm cell.
How can I implement a view like this?
If you know, I would appreciate if you tell me.

**Comment by mats-claassen** [comment]
You would have to create a custom cell for example in a nib file and arrange views as you like. #676 might help you

**Comment by TaichiAkimoto** [comment]
I could implement correct program by increasing numberOfComponentsInPickerView or other methods.
But, thank you for kind answer! I will try to use custom view, though it looks a little difficult.

**Comment by m-revetria** [comment]
Closing this, seems to be solved.
