### ISSUE TITLE
About XLOnChangeBlock

### ISSUE THREAD

**Issue by XinwenCheng** [xmartlabs/XLForm#822]
Hi @mats-claassen ,

I want to modify property value of data object when user change text form, so I copy source code from your official demo (in Examples/Swift/SwiftExample/PredicateExamples/PredicateFormViewController.swift) like following:
```
self.subjectRowDescriptor.onChangeBlock = {
    [weak self] oldValue, newValue, _ in
    self?.originalPlan.subject = newValue
}
```
It always cause a build error says _Error: cannot assign value of type '(_, _, _) -> ()?' to type 'XLOnChangeBlock?'_ But no such error during official demo's build.

What should I do?

**Comment by mats-claassen** [comment]
That error might come from `newValue` being `AnyObject?` and not the expected type for `originalPlan.subject`. Xcode error messages are not always accurate. This is just a guess, it could be something similar.
Otherwise your code is correct, I think

**Comment by XinwenCheng** [comment]
Great! @mats-claassen , thanks for your suggestion, it works for 
'''
self?.originalPlan.subject = ("\(newValue!)" ?? "")
'''
