### ISSUE TITLE
Can I have a different display text for a form row to that selected in a XLFormRowDescriptorTypeSelectorPush ?

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#823]
I have a row of type `XLFormRowDescriptorTypeSelectorPush`

I've set `row.selectorOptions = [XLFormOptionsObject]()` (with a populated array)

After a user selects from the list can I display different text in the main form? An empty string for example? When I've used a custom controller I've set `row.valueTransformer` to achieve this but without a custom view controller then my transformer is called for both the row in the table as well as for every item in the list.

**Comment by mats-claassen** [comment]
I can not remember a way to do this currently. You may have to use a custom controller for this

**Comment by carlhunterroach** [comment]
thanks.

If an approach does spring to mind please fire it this way.
thanks again

**Comment by m-revetria** [comment]
Closing this due to lack of responses
