### ISSUE TITLE
Catching "existing item tapped" for a XLFormRowDescriptorTypeSelectorPush item

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#824]
I have a row of type `XLFormRowDescriptorTypeSelectorPush`

I've set `row.selectorOptions = [XLFormOptionsObject]()` (with a populated array)

When a new item is selected I am catching `formRowDescriptorValueHasChanged()`
If the user taps the existing selected item what event can I catch?

**Comment by mats-claassen** [comment]
There is currently no event for this. But you could use a customViewController.

**Comment by m-revetria** [comment]
Closing this due to lack of response
