### ISSUE TITLE
"numeric" row tags crash if used by NSPredicate()

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#825]
I have used strings such as "6900" to tag my rows.

This has been fine until I wanted to do this:

`row.hidden = NSPredicate(format:"$6650.isHidden == 0")
`
which crashes when called.

but an a-z prefix works.

`row.hidden = NSPredicate(format:"$q6650.isHidden == 0")`

Is there a syntax for `NSPredicate()` I can use that would enable me to forgo the prefix.

**Comment by LixinQian** [comment]
Variable cannot begin with Numbers.I also met the same situation, how do you solve?
 @carlhunterroach

**Comment by carlhunterroach** [comment]
hi @LixinQian,  I continued to use a prefix for my tags.
