### ISSUE TITLE
How to apply an NSPredicate to a custom row

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#826]
I have a row of type `XLFormRowDescriptionTypeSelectorPush`

I set `row.value` to a custom class `"Agreement"` and `row.addValidator(AgreementValidator())`

I want another to be hidden/shown depending upon the value of `Agreement.agree` (which is `"Accepted"` or `"Declined"`).

I can't figure out how to do this.

`other_row.hidden = NSPredicate(format:"$other_tag.value != "Accepted")`

But the value of the `other_tag` row is `Agreement` and not a string. How can I compare with `Agreement.agree`?

An alternate example, taken from the XLForm readme page:

`row = [XLFormRowDescriptor formRowDescriptorWithTag:kSelectorMap rowType:XLFormRowDescriptorTypeSelectorPush title:@"Coordinate"];
// set up the selector controller class
row.action.viewControllerClass = [MapViewController class];

// Set up a NSValueTransformer to convert CLLocation to NSString, it's used to show the select value description (text).  
row.valueTransformer = [CLLocationValueTrasformer class];
// Set up the default value
row.value = [[CLLocation alloc] initWithLatitude:-33 longitude:-56];`

How would one add an NSPredicate to make another row show/hide depending upon a specific lat/lon set by the row above?

**Comment by carlhunterroach** [comment]
I've an ugly workaround…

I add an 3rd row, a text row, and hide it.
I "point" the NSPredicate of my 2nd row to the value of the 3rd.
When the 1st row's value changes I change the value of the additional 3rd row: this then causes the 2nd row to update by firing off the NSPredicate.

Ugly. Hoping a direct solution is available.

**Comment by mats-claassen** [comment]
I guess that in your predicate "$other_tag.value != "Accepted"", predicate `$other_tag.value` is your `Agreement`. Have you tried with "$other_tag.value.agree != "Accepted""?

**Comment by mats-claassen** [comment]
@carlhunterroach could you find a solution for this?

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
