### ISSUE TITLE
XLFormRowDescriptorTypeImage cancel option

### ISSUE THREAD

**Issue by kuko91** [xmartlabs/XLForm#827]
Why the XLFormRowDescriptorTypeImage doesn't have a cancel option before to going to the photos albums view?
I'm testing in iPhone and when I try to add a image, I must go to  "Choose from library" option for cancel.
In iPad works fine because if you tap the screen, the "actionsheet" close automatically.

Thanks.

**Comment by mats-claassen** [comment]
This is not correct. 
Have a look at the examples. `XLFormRowDescriptorTypeImage ` has a cancel option and you can close it by tapping the screen
