### ISSUE TITLE
How to set up the form of internationalization does not follow the mobile phone system

### ISSUE THREAD

**Issue by ablexie** [xmartlabs/XLForm#828]
I want  to make a table with English Language when the mobile phone system is in Chinese, how can I do it, thank you

**Comment by ablexie** [comment]
In other words，how to change the XLFormRowDescriptorTypeDate 's  internationalization?
![snip20160720_8](https://cloud.githubusercontent.com/assets/12047755/16976877/f2bfa1c8-4e84-11e6-8f59-28bd1f0a89c8.png)

**Comment by ablexie** [comment]
In other words，how to change the XLFormRowDescriptorTypeDate 's internationalization?
![Uploading Snip20160720_9.png…]()

**Comment by ablexie** [comment]
In other words，how to change the XLFormRowDescriptorTypeDate 's internationalization?
![Uploading Snip20160720_9.png…]()

**Comment by mats-claassen** [comment]
Sorry for the late answer.
You can obviously set the title for each row in English. 
For Date pickers you will have to set an english locale.
You cannot change the language of the keyboard, only the user can change it. Therefore user input will be in chinese if the user has that locale set.

Is there another case I am forgetting?

**Comment by ablexie** [comment]
Thank you for your answer.
