### ISSUE TITLE
How To Show Characters in XLFormRowDescriptorTypePassword?

### ISSUE THREAD

**Issue by XinwenCheng** [xmartlabs/XLForm#829]
Hi @mats-claassen ,

Is there any way to show/hide characters in XLFormRowDescriptorTypePassword? I tried following line, but it doesn't work, and I didn't find out any clue in demo or document yet.
```
self.passwordRowDescriptor.cellConfigAtConfigure["textField.secureTextEntry"] = false
```

**Comment by mats-claassen** [comment]
Hi,
You should try with `cellConfig` instead of cellConfigAtConfigure

**Comment by XinwenCheng** [comment]
Great, thanks!
