### ISSUE TITLE
XLFormDateCell's property missing datePicker.locale setting way

### ISSUE THREAD

**Issue by ablexie** [xmartlabs/XLForm#830]
XLFormDateCell.h 
add line:
@property (nonatomic) NSLocale   *locale;

XLFormDateCell.m
add line:
if (self.locale) {
        datePicker.locale = self.locale;
    }
in -(void)setModeToDatePicker:(UIDatePicker *)datePicker;

**Comment by ablexie** [comment]
I hope it can be done.However,thanks for XLForm team.Tomorrow will be better!Thank you again.

**Comment by mats-claassen** [comment]
Why don't you use `cellConfig` or `cellConfigAtConfigure` to set your locale?
```
[row.cellConfigAtConfigure setObject:[NSLocale localeWithLocaleIdentifier:@"de"] forKey:@"datePicker.locale"];
```

**Comment by ablexie** [comment]
I have used cellConfig or cellConfigAtConfigure to set the locale,but it's useless.Like that:
![snip20160722_14](https://cloud.githubusercontent.com/assets/12047755/17044384/2fe53054-4ff2-11e6-9213-d2633310eb26.png)


And my app use the rowType "XLFormRowDescriptorTypeDateInline" for DatePicker. As a result, I found there missing property locale in XLFormDateCell.h and XLFormDateCell.m
Finally,my code change to:
![snip20160722_15](https://cloud.githubusercontent.com/assets/12047755/17044393/49e2901e-4ff2-11e6-8e5c-3fdaf22c9bad.png)


That's all.Thank you!

**Comment by ablexie** [comment]
I have used cellConfig or cellConfigAtConfigure to set the locale,but it's useless.And my app use the rowType "XLFormRowDescriptorTypeDateInline" for DatePicker. As a result, I found there missing property locale in XLFormDateCell.h and XLFormDateCell.m  
Finally,my code change to:
[row.cellConfig setObject:[NSLocale localeWithLocaleIdentifier:@"de"] forKey:@"locale"];
