### ISSUE TITLE
How to delete date row input which is not required?

### ISSUE THREAD

**Issue by CaliosD** [xmartlabs/XLForm#833]
I used the row type of `XLFormRowDescriptorTypeDateInline` in my form. But I found it unable to clear the date I selected. 
Is there a property or a solution to handle this kind of problem? 
Thanks in advance if anyone could help.

**Comment by CaliosD** [comment]
@mats-claassen Could you please have a look at this issue? Thanks for your time and attention. :)

**Comment by mats-claassen** [comment]
This is not a build in functionality. You can do it by adding a button somewhere and in the action of that button set the value of the date inline row to nil and update its cell.

**Comment by riccardo-destefani** [comment]
Sorry @mats-claassen, can you explain me the way to add a button to that row?
Thanks

**Comment by mats-claassen** [comment]
@riccardo-destefani I did not mean adding a button *to that row*. I was thinking of adding a simple UIButton in the header or footer of the section. You can do this using the delegates provided by UIKit for the tableView (`-(UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section`).

If you want to add it to the row itself, I guess you will have to subclass it or create your own row with that functionality.

**Comment by riccardo-destefani** [comment]
Can you give me a hint? 
I'd like to add to XLFormRowDescriptorTypeDate a button next to current selected date row value to set rowValue = nil when it is pressed.
What class do i have to subclass? XLFormBaseCell? or directly XLFormDateCell?
How do i add button? in configure method?

Thank you for support

**Comment by CaliosD** [comment]
@riccardo-destefani  I didn't subclass any class. As @mats-claassen said above, I just add a clear button in the row class I need. Here's some of the code I added in `XLFormDateCell`. Hope it helps. :]

```
// XLFormDateCell.m
-(void)update
{
    ......  
    [self configureClearBtn];
}

- (void)configureClearBtn
{
    if (self.rowDescriptor.value && self.isEditing) {
        [self showClearBtn];
    }
    else{
        [self hideClearBtn];
    }
}

- (void)showClearBtn
{
    UIButton *clearBtn = [[UIButton alloc] initWithFrame:CGRectMake(kScreenWidth - kCommonInset_X * 3, 10, 30, 30)];
    [clearBtn setImage:[UIImage imageNamed:@"clear"] forState:UIControlStateNormal];
    [clearBtn addTarget:self action:@selector(clearDate) forControlEvents:UIControlEventTouchUpInside];
    
    self.accessoryView = clearBtn;
}

- (void)hideClearBtn
{
    self.accessoryView = nil;
}

- (void)clearDate
{
    self.rowDescriptor.value = nil;
    self.detailTextLabel.text = [self valueDisplayText];
    [self hideClearBtn];
}

```

**Comment by riccardo-destefani** [comment]
Thank you @CaliosD for code, but you are directly modifying library, and this is dangerous, because when i update libraries from pod your code is lost.
I think the best way to achive our goal is to subclass XLFormDateCell, and there write your code.

I tried this approach, clear button is shown, but when i tap on row value (the date) no date picker is shown.

Can @mats-claassen clear my ideas?

Thank you guys

**Comment by mats-claassen** [comment]
@riccardo-destefani You can implement it somewhat like this if you want the button as the accessoryView of the row:
```
class MyDateInline: XLFormDateCell {

    var clearButton: UIButton!

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    override func configure() {
        super.configure()
        clearButton = UIButton()
        clearButton.setTitle("Clear", for: .normal)
        clearButton.setTitleColor(UIColor.black, for: .normal)
        clearButton.addTarget(self, action: #selector(MyDateInline.clear), for: .touchUpInside)
        clearButton.sizeToFit()
    }

    override func update() {
        super.update()
        if rowDescriptor.value != nil && isFirstResponder {
            accessoryView = clearButton
        } else {
            accessoryView = nil
        }
    }

    func clear() {
        rowDescriptor.value = nil
        detailTextLabel?.text = nil
    }
}
```

And to use it:
```
row = XLFormRowDescriptor(tag: Tags.CustomRowInline2, rowType: XLFormRowDescriptorTypeDateInline)
        row.cellClass = MyDateInline.self
        section.addFormRow(row)
```

In my opinion it does not look good as accessoryView as the row is too packed. I would put it somewhere else like the section's header or footer.

**Comment by riccardo-destefani** [comment]
Thank you, it work like a charm!
The key point is was:    row.cellClass = MyDateInline.self

Thanks
