### ISSUE TITLE
Why is old version in pod?

### ISSUE THREAD

**Issue by daheli** [xmartlabs/XLForm#834]
I find the latest version is '3.2.0' in github, 
but why am I searching from pod, I got an older version.
why?

> pod search XLForm
```
-> XLForm (3.1.1)
   XLForm is the most flexible and powerful iOS library to create dynamic table-view forms.
   pod 'XLForm', '~> 3.1.1'
   - Homepage: https://github.com/xmartlabs/XLForm
   - Source:   https://github.com/xmartlabs/XLForm.git
   - Versions: 3.1.1, 3.1.0, 3.0.2, 3.0.1, 3.0.0, 2.2.0, 2.1.0, 2.0.0, 1.0.1, 1.0.0 [master repo]
```

> pod --version
```
1.0.1
```

**Comment by mats-claassen** [comment]
Are you searching at [cocoapods](https://cocoapods.org/?q=xlform)? I am seeing a 3.2.0 there.

**Comment by mats-claassen** [comment]
If such a problem arises you would probably have to run `pod repo update` before `pod install`
