### ISSUE TITLE
Can you add Swift translations of the code in README?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/XLForm#835]
I can see that a lot of the Objective-C code has been translated into swift already. I really appreciate that. But the code snippets about multivalued sections, dynamic forms and custom cells hasn't been translated. I can't read Objective-C code that well, especially those method declarations shown in the dynamic forms section.

**Comment by AlexHedley** [comment]
Could you not use [Eureka](https://github.com/xmartlabs/Eureka) instead?

**Comment by Sweeper777** [comment]
Okay, I guess I'll use eureka then.
