### ISSUE TITLE
How can I add default values to rows?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/XLForm#836]
Let's say that I want users to fill in quite a long form. I want to add a "save as draft" option to temporarily store the form's values in an object. And later, when the user wants to continue filling in the form, he/she can just tap a button and the form is presented with the values that he/she just entered.

So I just did a little test like this:

```
        let form = XLFormDescriptor(title: "Some title")
        
        var section = XLFormSectionDescriptor()
        form.addFormSection(section)
        
        var row = XLFormRowDescriptor(tag: "title", rowType: XLFormRowDescriptorTypeText)
        row.cellConfigAtConfigure.setObject("Hello", forKey: "textField.text")
        section.addFormRow(row)
        
        self.form = form
```

I thought this would show a form with a single row which has the string "Hello" already in the text field. But the text field has nothing in it when I run the app.

What did I do wrong? Is there a simpler way to add a default value to a row? If not, can you add one?

**Comment by luxystech** [comment]
row.value = @"it works";

**Comment by mats-claassen** [comment]
The function `formValues` of `XLFormDescriptor` might help you to get a dictionary of all the values. I would just save this dictionary as draft and then put all the values to each row when you reload the form. You would not be type checking in this case, but XLForm was mainly written for Objective-C. There is no documentation as to which type of value is accepted by each row.

**Comment by Sweeper777** [comment]
Okay I see. Thanks.
