### ISSUE TITLE
Custom button row design not working

### ISSUE THREAD

**Issue by luxystech** [xmartlabs/XLForm#837]
Hello!
Trying to use as an example code
```
XLFormRowDescriptor * buttonRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"btnClaim" rowType:XLFormRowDescriptorTypeButton title:@"Send"];
    buttonRow.action.formSelector = @selector(didTouchButton:);
    [row.cellConfigAtConfigure setObject:[UIColor redColor] forKey:@"backgroundColor"];
    [row.cellConfig setObject:[UIColor whiteColor] forKey:@"textLabel.color"];
```

But not working. Thank in advance for any help.

**Comment by mats-claassen** [comment]
You mean the configuration of colors?
`backgroundColor` is working for me and the second one is not working because textLabel has no property color. I believe you might mean `textColor`, right?
It works for me
