### ISSUE TITLE
How To Change Button's Title

### ISSUE THREAD

**Issue by XinwenCheng** [xmartlabs/XLForm#838]
Hi @mats-claassen ,

I have a question, how to change title of a button (XLFormRowDescriptorTypeButton) after added into form.

For instance, there's button, its title is "Unclicked", and after user clicked it, title needs to be changed into "Clicked". I checked demo source code, and seems it uses self.updateFormRow(), but I use it after each time I set title to a button programmatically, there's a new button with new title appear in form, self.reloadFormRow() has the same behaviour.

Which method should I use for this requirement? Thanks!

**Comment by mats-claassen** [comment]
You should call `reloadFormRow`. I did not completely get what is happening to you. You say there is a new button added to the form? Are you inserting new buttons to the form?
I did not try it but something like the following should work:
```
row.title = "New title"
self.reloadFormRow(row)
```

**Comment by XinwenCheng** [comment]
@mats-claassen , I tried reloadFormRow method, but there still will be a new row each time. And there's no code to insert new one. Due to source code relates to my business logic, it's not convenience to show you yet, I'll debug more and discuss with you if I still cannot handle this problem, thanks!

**Comment by XinwenCheng** [comment]
Hi @mats-claassen , I got the reason, if I change title of button row and invoke reloadFormRow() directly like sample does, it works. But the real business logic is I have to change title after accessed database, so I do it in following code:
```
SwiftEventBus.onMainThread(self, name: EventNames.TEMPLATE_LIKE) {
    result in
    // Change title and invoke reloadFormRow() here.        
}
```
Each time there will be a new row added in form.

Do you have any experience on this? If yes, that would be very helpful, thanks!

**Comment by XinwenCheng** [comment]
Hi @mats-claassen , I found the reason, in sample code, we change title and invoke reloadFormRow() directly, it works. But in real business logic, I have to change and invoke after database operation, as following two pieces of code:
```
// In SwiftEventBus' document, onMainThread is for UI thread.
SwiftEventBus.onMainThread(self, name: EventNames.TEMPLATE_LIKE) {
    result in
    self.likeButtonRowDescriptor.title = NSDate().toStringWithFormat("HH:mm:ss")
    self.reloadFormRow(self.likeButtonRowDescriptor)
}
```
In this way, each time there's a new row be added in section.
```
SwiftEventBus.onMainThread(self, name: EventNames.TEMPLATE_LIKE) {
    result in
    let workingQueue = dispatch_queue_create("setLikeButtonTitle", nil)
    dispatch_async(workingQueue) {
        dispatch_async(dispatch_get_main_queue()) {
            self.likeButtonRowDescriptor.title = NSDate().toStringWithFormat("HH:mm:ss")
            self.reloadFormRow(self.likeButtonRowDescriptor)
        }
    }
}
```
Even in this way, there still be a new row added each time.

Do you have any experience on this kind of problem?

**Comment by XinwenCheng** [comment]
Hi @mats-claassen , would you please let me know if you have any plan to handle this problem? I need to decide to find other ways if you won't, thanks!

**Comment by mats-claassen** [comment]
@XinwenCheng I have this code and nothing strange happens:
```
row.onChangeBlock = { _, _, row in
            GCDHelper.runOnMainThread({
                let other = row.sectionDescriptor.formDescriptor.formRowWithTag(Tags.Button)
                other?.title = arc4random() % 2 == 0 ? "Changed" : "Unchanged"
                self.reloadFormRow(other)
                
            })
        }
```

This code will just keep changing the title of the button but never adds a new row.
Are you sure you have no code in a delegate method like `formRowDescriptorValueHasChanged` which adds rows to your form?

Did you try getting the row by tag instead of having a variable? It should not be related to that though.

**Comment by mats-claassen** [comment]
@XinwenCheng did you find the issue?

**Comment by XinwenCheng** [comment]
Hi @mats-claassen , sorry I have no time to work on that project recently, you can close this issue if you need, and I will change my code by your solution and check it later, thanks again!
