### ISSUE TITLE
textlabel Not align

### ISSUE THREAD

**Issue by foolish1016** [xmartlabs/XLForm#839]
[https://github.com/foolish1016/testProject/blob/master/562FD521-ADA4-4DBB-9E0C-B01E03AFB6A8.png](url)
how  solve the problem？

**Comment by foolish1016** [comment]
https://github.com/foolish1016/testProject/blob/master/562FD521-ADA4-4DBB-9E0C-B01E03AFB6A8.png

**Comment by mats-claassen** [comment]
Hi which version are you using? 
We recently [fixed this issue in Eureka](https://github.com/xmartlabs/Eureka/commit/7bfbeec940fb963aab63223a716e8f1a975bb80f). I believe it must be similar in XLForm. You could start with that and submit a pull request.

**Comment by foolish1016** [comment]
i use  XLFormRowDescriptorTypeText ,XLFormRowDescriptorTypeDate,XLFormRowDescriptorTypeRate  types.
If these 3 types are set imageView. this question is  still.

**Comment by foolish1016** [comment]
the code 
//        // Date
        row = [XLFormRowDescriptor formRowDescriptorWithTag:kDate rowType:XLFormRowDescriptorTypeDate title:@"Date"];
        row.value = [NSDate new];
        [row.cellConfig setObject:[UIImage imageNamed:@"default_avatar"] forKey:@"imageView.image"];
        [row.cellConfigAtConfigure setObject:[NSDate new] forKey:@"minimumDate"];
        [row.cellConfigAtConfigure setObject:[NSDate dateWithTimeIntervalSinceNow:(60*60*24*3)] forKey:@"maximumDate"];
        [row.cellConfig setObject:[UIImage imageNamed:@"default_avatar"] forKey:@"imageView.image"];
        [section addFormRow:row];
        
        row = [XLFormRowDescriptor formRowDescriptorWithTag:@"text" rowType:XLFormRowDescriptorTypeText title:@"text"];
        
        [row.cellConfig setObject:[UIImage imageNamed:@"default_avatar"] forKey:@"imageView.image"];
        [section addFormRow:row];
        
        
        
        row = [XLFormRowDescriptor formRowDescriptorWithTag:@"textTest" rowType:XLFormRowDescriptorTypeRate title:nil];
        [row.cellConfig setObject:@"titleName" forKey:@"textLabel.text"];
        [row.cellConfig setObject:[UIImage imageNamed:@"default_avatar"] forKey:@"imageView.image"];
        [section addFormRow:row];
//
        // Time
        row = [XLFormRowDescriptor formRowDescriptorWithTag:kTime rowType:XLFormRowDescriptorTypeTime title:@"Time"];
        [row.cellConfigAtConfigure setObject:@(10) forKey:@"minuteInterval"];
        row.value = [NSDate new];
        [section addFormRow:row];
        
        
        // DateTime
        row = [XLFormRowDescriptor formRowDescriptorWithTag:kDateTime rowType:XLFormRowDescriptorTypeDateTime title:@"Date Time"];
        row.value = [NSDate new];
        [section addFormRow:row];

**Comment by foolish1016** [comment]
https://github.com/foolish1016/testProject/blob/master/8405258F-4297-459E-814B-54D9A6989465.png

**Comment by foolish1016** [comment]
3q   !!!!!
in XLFormTextFieldCell    225 row delete
and add  this code:
   self.dynamicCustomConstraints = [NSMutableArray arrayWithArray:[NSLayoutConstraint constraintsWithVisualFormat:@"H:[image]-(15)-[label]-[textField]-|" options:0 metrics:nil views:views]];
