### ISSUE TITLE
Add image to XLFormRowDescriptorTypeBooleanCheck

### ISSUE THREAD

**Issue by devloe** [xmartlabs/XLForm#840]
How can I add an image to a XLFormRowDescriptorTypeBooleanCheck?

Using Swift.

**Comment by devloe** [comment]
Anyone?

**Comment by mats-claassen** [comment]
You mean to the imageView of the cell?
This should work:
```
row.cellConfig["imageView.image"] = UIImage(named: "default_avatar")
```

Or do you mean to the `accessoryView`?

**Comment by mats-claassen** [comment]
@devloe Can we close this?
