### ISSUE TITLE
How to create the "add" button in a multivalued section?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/XLForm#841]
In the README, there seems to be an add button at the last row of a multivalued section. It seems to be an `XLFormRowDescriptorTypeButton`. I tried to recreate this in my own code.

        let section = XLFormSectionDescriptor.formSectionWithTitle("My Section", sectionOptions: [.CanDelete, .CanInsert])
        section.multivaluedTag = "mySection"
        form.addFormSection(section)
        
        let row = XLFormRowDescriptor(tag: nil, rowType: XLFormRowDescriptorTypeText, title: "Some Text")

I thought I need to set the `multivaluedAddButton` of the section but then I found out that it is read-only.

I tried adding a row like this:

        let row2 = XLFormRowDescriptor(tag: nil, rowType: XLFormRowDescriptorTypeButton, title: "Add")
        section.addFormRow(row2)

And I got some really weird behaviours.

How can I do those buttons that say "Add Item"?

**Comment by mats-claassen** [comment]
You can have a look t the Examples. For example in `MultivaluedFormViewController` you find this:
```
section = XLFormSectionDescriptor.formSectionWithTitle("Multivalued Push Selector example", sectionOptions: XLFormSectionOptions.CanInsert.union(.CanDelete).union(.CanReorder), sectionInsertMode: .Button)
        section.footerTitle = "MultivaluedFormViewController.swift"
        form.addFormSection(section)
```

I think you are lacking the `sectionInsertMode: .Button`

**Comment by Sweeper777** [comment]
Okay, thanks.
