### ISSUE TITLE
XLForm Delegate Method is Not Working in Custom FloatingCell

### ISSUE THREAD

**Issue by dev-vinoth** [xmartlabs/XLForm#842]
```
    row = XLFormRowDescriptor(tag: Tags.UserName, rowType: XLFormRowDescriptorTypeFloatLabeledTextField, title: "User Name : ")
    row.required = true
    section.addFormRow(row)
```

Note : This is my custom RowType

```
override func formRowDescriptorValueHasChanged(formRow: XLFormRowDescriptor, oldValue: AnyObject, newValue: AnyObject) {
    // super implementation MUST be called
    super.formRowDescriptorValueHasChanged(formRow, oldValue: oldValue, newValue: newValue)

    print("formRow : \(formRow)")

}
```

This delegate method is not working in Custom row FloatingCell.

Even, not working in this link also
https://github.com/xmartlabs/XLForm/blob/master/Examples/Swift/SwiftExample/CustomRows/CustomRowsViewController.swift

please help me to fix this issue!

**Comment by mats-claassen** [comment]
As it is your custom row I do not know where the problem lies but that delegate function is called when the `value` of the rowDescriptor changes. Is your custom cell correctly updating that `value` property?

**Comment by mats-claassen** [comment]
Hey @dev-vinoth could you fix this?

**Comment by dev-vinoth** [comment]
Sorry for the delay, I have fixed the issue just include the below code in shouldChangeCharactersInRange.  
@mats-claassen 

func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
        
        if floatLabeledTextField == textField {
            if let rowDescriptor = rowDescriptor, let text = self.floatLabeledTextField.text {
                
                if (text + " ").isEmpty == false {
                    rowDescriptor.value = self.floatLabeledTextField.text! + string
                } else {
                    rowDescriptor.value = nil
                }
            }
        }
        
        return self.formViewController().textField(textField, shouldChangeCharactersInRange: range, replacementString: string)
    }
