### ISSUE TITLE
Why can I deselect options using XLFormRowDescriptorTypeSelectorPush?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/XLForm#846]
Say I have a `XLFormRowDescriptorTypeSelectorPush` form row. By default, Option 1 is selected. Now if I tap on Option 1 in the pushed view controller, Option 1 will be deselected. Why? Few forms have this feature. Selector rows are supposed to let the user choose from options, not "nothing"!

You see, the other types of selectors don't have an option to deselect the selected option. Why `XLFormRowDescriptorTypeSelectorPush`?

Is this intended and why?

**Comment by mats-claassen** [comment]
You can change this by using a custom `XLFormOptionsViewController`.

Maybe we could add a feature to choose if the user can deselect an option or not.

**Comment by kiancheong** [comment]
There's already a check on rowDescriptor's required value, setting it to true will prevent the value from being set to nil. I've made additional changes to prevent the checkmark from being removed. 

[https://github.com/xmartlabs/XLForm/pull/882](url)
