### ISSUE TITLE
How can I properly remove a XLFormRowDescriptorTypeSelectorPickerViewInline form row in its extended state?

### ISSUE THREAD

**Issue by Sweeper777** [xmartlabs/XLForm#847]
In a section of my form, there is a `XLFormRowDescriptorTypeSelectorSegmentedControl` row. (The options are "A" and "B". Let's call this "above row") The row below will change according to the value of the above row. (Let's call this "below row")

If the above row has the value of "A", the below row is changed to an `XLFormRowDescriptorTypeText` row. If he above row has the value of "B", the below row is changed to an `XLFormRowDescriptorTypeSelectorPickerViewInline` row.

Here is my code:

    func showTextRow() {
        let sec = form.formSectionAtIndex(2)!
        
        sec.removeFormRowAtIndex(1)
        
        let row = XLFormRowDescriptor(tag: "someValue", rowType: XLFormRowDescriptorTypeText, title: NSLocalizedString("Message", comment: ""))
        sec.addFormRow(row)
    }
    
    func showPickerViewInlineRow() {
        let sec = form.formSectionAtIndex(2)!
        
        sec.removeFormRowAtIndex(1)
        
        let row = XLFormRowDescriptor(tag: "someOtherValue", rowType: XLFormRowDescriptorTypeSelectorPickerViewInline, title: NSLocalizedString("Sound", comment: ""))
        row.selectorOptions = ["xxx", "yyy", "zzz"]
        row.value = "xxx"
        
        sec.addFormRow(row)
    }
    
    override func formRowDescriptorValueHasChanged(formRow: XLFormRowDescriptor!, oldValue: AnyObject!, newValue: AnyObject!) {
        super.formRowDescriptorValueHasChanged(formRow, oldValue: oldValue, newValue: newValue)
        
        if formRow.tag == nil {
            return
        }
        
        switch formRow.tag! {
        case "xxx":
            if (newValue as! String) == "B" {
                showPickerViewInlineRow()
            } else if (newValue as! String) == "A" {
                showTextRow()
            }
        default:
            break
        }
    }

As you can see, I first removed the existing second row from the section and put a new row in it. However, if I try to change the value of the above row when the below row is at this "expanded" state:

<img width="309" alt="screen shot 2016-08-11 at 12 25 52 pm" src="https://cloud.githubusercontent.com/assets/13585047/17578738/9636926c-5fbf-11e6-85b7-8f898e82ed89.png">

The app crashes with an `NSInternalInconsistencyException`.

So the question is, how can I remove a row that's in the "expanded" state?

**Comment by mats-claassen** [comment]
You will have to remove two rows as the 'inline picker' is another row. And you will probably have to remove the second row first.

Why don't you use the `hidden` property and let XLForm manage the adding and removing of rows?
