### ISSUE TITLE
How to auto-resize a row according to length of contents?

### ISSUE THREAD

**Issue by JGQuinodoz** [xmartlabs/XLForm#850]
How can rows like this be set to auto resize when and if the row.value is initialized too long to fit in one line?

![screen shot 2016-08-13 at 11 18 31 pm](https://cloud.githubusercontent.com/assets/14239269/17646978/922c1676-61ac-11e6-8084-019a94be95ee.png)

I am having the same problem with XLFormRowDescriptorTypeText, XLFormRowDescriptorTypeTextView, and XLFormRowDescriptorTypeInfo. I am of course open to using other row types if that solves the problem. 

Here is my code:

` 

```
row = [XLFormRowDescriptor formRowDescriptorWithTag:GLOKeyContent
                                           rowType:XLFormRowDescriptorTypeText
                                             title:NSLocalizedString(@"For", @"For")];

[row.cellConfigAtConfigure setObject:@(NSTextAlignmentRight) forKey:@"textField.textAlignment"];
row.required = YES;
row.value = self.content;
row.disabled = @YES;
[row.cellConfigIfDisabled setObject:[UIColor blackColor] forKey:@"textLabel.textColor"];

[section addFormRow:row];`
```

Thanks!

**Comment by mats-claassen** [comment]
#742 is an option. 
You can also play with the `height` property of `XLFormRowDescriptor`

**Comment by convitza** [comment]
@mats-claassen Hi, I would like to ask whether there was a way to update a specific row height programmatically after the form is already generated? (In this case, I don't want to re-load the whole form).
Looking forward to hearing from you.
Thanks

**Comment by mats-claassen** [comment]
If you have a row that works with Autolayout constraints then you could try setting `UITableViewAutomaticDimension` to the `height` property of XLFormRowDescriptor.

**Comment by m-revetria** [comment]
Closing this due to lack of response
