### ISSUE TITLE
XLFormDateCell do not support valueFormatter ??

### ISSUE THREAD

**Issue by snaill** [xmartlabs/XLForm#852]
Such as the title...

**Comment by mats-claassen** [comment]
Yes they do. Have a look at the implementation of `XLFormDateCell` at https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Cell/XLFormDateCell.m#L159-L186.

**Comment by snaill** [comment]
use rowType not valueFormatter！
I need use custom valueFormatter to make my date string，not some predefined style date string.

**Comment by mats-claassen** [comment]
You can have a look at the examples. There is a custom DateValueTransformer. Maybe that helps you.
