### ISSUE TITLE
Restrict the number of characters of a UITextfield

### ISSUE THREAD

**Issue by kaushil111** [xmartlabs/XLForm#855]
How do I use to form to restrict the number of characters of a XLFormRowDescriptor?

For example limiting the character length of Pin Code to 5 characters or phone number to 10 characters?

**Comment by JorgeAGomez** [comment]
Found any solution for this? 

I want to make the UITextField to only accept a MAX of 5 characters. I found a way to do it but it only works with Numbers.

**Comment by choefele** [comment]
You can override `textField(_, shouldChangeCharactersIn, replacementString)` in a subclass of `XLFormViewController` and return `false` if the string exceeds your length requirement. Unfortunately, I haven't yet found a good way to know which row I'm dealing with (I need different lengths for rows)

**Comment by mats-claassen** [comment]
You can use `textFieldMaxNumberOfCharacters` property now. This is not yet in the latest release but you can get it pointing to the master branch
