### ISSUE TITLE
keep data in the textfield 

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/XLForm#859]
I am building a form for my app. The form has multiple view controllers.  Each view controller has a nagivation toolbar, so when a user fills personal information form (firstViewController), click "next" (UIBarButtonRight) and goes to the nextView Controller (medical information View controller) and here is when I am having a problem. If the user fills the medical View Controller and decides to click "Back" and go to personal information view controller (maybe wants to change something in the form), and I click "next" again to go to medical view controller, all the textfields are empty. How can I keep the data in the textfields even if I jump from one view controller to another (backward or forward)?

**Comment by mats-claassen** [comment]
When you tap "back" on the second controller, then that view controller will be released and it will be instantiated again when the user taps "next" on the first controller. If you want to keep the data then you will have to store them when you pop your viewController and load it back when you push a new "medical view controller".
