### ISSUE TITLE
directly input value into XLFormRowDescriptorTypeSelectorPickerView

### ISSUE THREAD

**Issue by TaichiAkimoto** [xmartlabs/XLForm#860]
I use xlform to show some data. Especially XLFormRowDescriptorTypeSelectorPickerView.
Every time I show xlform, I input values into rowDescriptor.value directly as one of its options.
And it's working fine.
But, when I click a cell, a value highlighted is different from what I have input.
For example, let's assume there are 3 options {Japan, US, China}, and my direct input is US.
In this case, when I click the cell, ladder-like form appears. But highlighted option is not always US.
it's sometimes Japan or China.
Although, value itself remains to be US, I feel uncomfortable for this.
If anyone knows solution for this, please let me know.

Thanks!

**Comment by TaichiAkimoto** [comment]
I could solve this problem by myself, so let me tell you guys!
On a method called -(UIPickerView *)pickerView (in XLFormSelectorCell), you call another method called 
[_pickerView selectRow:[self selectedIndex:0] inComponent:0 animated:NO];.
this [self selectedIndex:0] stands for index in options on each component.
So, you can call this method for each component(by changing value of inComponent),
then correct values will be highlighted when you click xlform cell!

**Comment by mats-claassen** [comment]
Thanks for providing the solution.
