### ISSUE TITLE
size image icon when take it

### ISSUE THREAD

**Issue by AlbertoMrFz** [xmartlabs/XLForm#862]
hi,
How i can change the size og image mini that appear when i take it from library or my caMERA??

**Comment by mats-claassen** [comment]
You mean the image in the accessoryView of the XLFormImageCell? Try this:
```swift
row.cellConfigAtConfigure["accessoryView.frame"] = NSValue(CGRect: CGRect(x: 0, y: 0, width: 44, height: 44))
```

**Comment by mats-claassen** [comment]
Did that work for you?

**Comment by dariopellegrini** [comment]
It worked well for me! What about the content mode?

**Comment by mats-claassen** [comment]
Did you try setting `row.cellConfigAtConfigure["accessoryView.contentMode"]`?

**Comment by dariopellegrini** [comment]
Unfortunately the app crashes with that.

**Comment by mats-claassen** [comment]
@dariopellegrini This code works for the image row in the examples. Note the `.rawValue`:
```
row.cellConfigAtConfigure["accessoryView.frame"] = NSValue(cgRect: CGRect(x: 0, y: 0, width: 32, height: 32))
        row.cellConfigAtConfigure["accessoryView.contentMode"] = UIViewContentMode.scaleAspectFill.rawValue
```

**Comment by dariopellegrini** [comment]
I forgot .rawValue at the end. Don't ask me why. Thanks, it's solved!
