### ISSUE TITLE
NSRangeException (NSArray out of bounds) when resizing XLFormViewController

### ISSUE THREAD

**Issue by zero0cool0** [xmartlabs/XLForm#863]
In my app, XLFormViewController is presented as popup, anchored top right. In landscape mode, the view fits the screen, but is automatically resized to show the keyboard as soon as I tap onto a text field. After that, the app crashes.

`**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 4 beyond bounds [0 .. 3]'

**\* First throw call stack:
(
    0   CoreFoundation                      0x02ae6494 **exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x025a0e02 objc_exception_throw + 50
    2   CoreFoundation                      0x029abaa3 -[__NSArrayM objectAtIndex:] + 243
    3   CoreFoundation                      0x02a233b8 -[NSArray objectAtIndexedSubscript:] + 40
    4   UIKit                               0x011d716c -[UITableView _updateVisibleCellsNow:isRecursive:] + 4941
    5   UIKit                               0x011f5416 __29-[UITableView layoutSubviews]_block_invoke + 52
    6   UIKit                               0x012106cc -[UITableView _performWithCachedTraitCollection:] + 88
    7   UIKit                               0x011f52eb -[UITableView layoutSubviews] + 214
    8   UIKit                               0x0114b3d4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 810
    9   libobjc.A.dylib                     0x025b5059 -[NSObject performSelector:withObject:] + 70
    10  QuartzCore                          0x05d3e096 -[CALayer layoutSublayers] + 144
    11  QuartzCore                          0x05d318b6 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 388
    12  QuartzCore                          0x05d3171a _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 26
    13  QuartzCore                          0x05d23ee7 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 317
    14  QuartzCore                          0x05d58847 _ZN2CA11Transaction6commitEv + 561
    15  QuartzCore                          0x05d5a0b8 _ZN2CA11Transaction17flush_transactionEv + 50
    16  QuartzCore                          0x05d69867 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 593
    17  QuartzCore                          0x05d69ccd _ZN2CA7Display16TimerDisplayLink8callbackEP16__CFRunLoopTimerPv + 123
    18  CoreFoundation                      0x02a30136 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION** + 22
    19  CoreFoundation                      0x02a2fb32 __CFRunLoopDoTimer + 1250
    20  CoreFoundation                      0x029ee39a __CFRunLoopRun + 2202
    21  CoreFoundation                      0x029ed846 CFRunLoopRunSpecific + 470
    22  CoreFoundation                      0x029ed65b CFRunLoopRunInMode + 123
    23  GraphicsServices                    0x057d4664 GSEventRunModal + 192
    24  GraphicsServices                    0x057d44a1 GSEventRun + 104
    25  UIKit                               0x0107aeb9 UIApplicationMain + 160
    26  App                    0x001046ea main + 138
    27  libdyld.dylib                       0x037f3a25 start + 1
    28  ???                                 0x00000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by mats-claassen** [comment]
Are you sure this issue has to do with XLForm?
To reproduce this we would need some code example...

**Comment by m-revetria** [comment]
Closing this due to lack of response
