### ISSUE TITLE
formRowDescriptorValueHasChanged: delegate not working on iOS 10, Swift 3

### ISSUE THREAD

**Issue by eyalzohar** [xmartlabs/XLForm#865]
XLFormDescriptorDelegate formRowDescriptorValueHasChanged: delegate not working when i run my code on iOS 10 device with Swift 3.
**It's working on iOS 9**, so no changes were made to the code.
Do i need to change the code in order to make it work again ?

Thank you.

**Comment by mats-claassen** [comment]
Hi I just tried this in the examples (Obj-C) with a `XLFormRowDescriptorTypeBooleanSwitch` and it was called. 

In Swift 3 you must change your function to `override func formRowDescriptorValueHasChanged(_ formRow: XLFormRowDescriptor!, oldValue: Any!, newValue: Any!)`. Note that AnyObject has changed to Any. 

Seems that Swift 3 translates it differently

**Comment by eyalzohar** [comment]
That did the trick.
Thank you.
