### ISSUE TITLE
Assertion failure in -[UIPickerTableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]

### ISSUE THREAD

**Issue by kartikaykeepworks** [xmartlabs/XLForm#867]
I have created a form with fields DateAndTimePicker and UITextView. When I tap on the DatePickerView, then tap on textView and then tap again on datePickerView, the app crashes with error: 
**Assertion failure in -[UIPickerTableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]**

Can anyone please help me out with this?

**Comment by mats-claassen** [comment]
I cannot reproduce this issue but I found there are some possible fixes mentioned on StackOverflow like [here](http://stackoverflow.com/questions/19155082/assertion-failure-in-uipickertableview-createpreparedcellforglobalrowwithind).

As I cannot reproduce it I do not know if a possible fix actually fixes it. If some of that solutions works for you then great

**Comment by m-revetria** [comment]
Closing this due to lack of response
