### ISSUE TITLE
Strange behaviour with subclass of XLFormViewController, which creates CoreData object in viewDidLoad

### ISSUE THREAD

**Issue by fletz** [xmartlabs/XLForm#870]
Hello,
I have a class, which extends XLFormViewController. The instance is loaded via Storyboard. I do implement initWithNibName and initWithCoder as described in the documentation. I use one common initializeForm to load all the data. All of that works just fine.

But I do have a instance variable (property, nonatomic, strong), which is a class that extends NSManagedObject. I do create a new entity of this class in viewDidLoad. Up to the end of that method everything works fine, but as soon as we reach viewWillAppear I get an error stating that I'm mutating a managed object after it has been removed from its context.

The whole thing works perfectly fine if there is no XLFormViewController. And it also happens in a different XLFormViewController.
When I output (NSLog(..)) my object in viewDidLoad it just looks as it should and when I do the sam ein viewWillAppear I get "data:`<fault>`", where usually all the properties are listed. The object reference/pointer (the hex number in the beginning) is the same though.

Is there anything happening in between viewDidLoad and viewWillAppear which could alter my property variable? 

Thanks for your help!

**Comment by mats-claassen** [comment]
`XLFormViewController` should not be modifying your variable unless you are overriding a variable from its superclass.

Are you properly calling the super methods?

**Comment by m-revetria** [comment]
Closing this due to lack of response, it you're still experiencing this issue please open this again.
