### ISSUE TITLE
Is possible to set custom NSDateFormatter in XLFormRowDescriptorTypeDateTimeInline

### ISSUE THREAD

**Issue by psarakism** [xmartlabs/XLForm#871]
Hello , i try to set custom DateFormatter  in XLFormRowDescriptorTypeDateTimeInline.. reading a previous issue but the app crash with log
''this class is not key value coding-compliant for the key dateFormatter.''

[row.cellConfigAtConfigure setObject:dateformatter forKey:@"dateFormatter"];

Is possible to set custom NSDateFormatter ?

**Comment by mats-claassen** [comment]
There is no `dateFormatter` property in that cell. What you have to do is use a NSValueTranformer like:
`row.valueTransformer = MyValueTransformer`

In the examples there is a `DateValueTransformer` doing this.

**Comment by m-revetria** [comment]
Closing this
