### ISSUE TITLE
Is it possible to show title and input in two different lines?

### ISSUE THREAD

**Issue by perroyverde** [xmartlabs/XLForm#875]
I wonder if this can be done with "XLFormRowDescriptorTypeText". I've only achieved this effect with "XLFormRowDescriptorTypeDate" and "row.cellStyle = UITableViewCellStyleSubtitle". 

![captura de pantalla 2016-09-30 a las 12 47 17](https://cloud.githubusercontent.com/assets/22542161/18989488/937a0012-870c-11e6-9daf-d8808184437c.png)

**Comment by mats-claassen** [comment]
`XLFormRowDescriptorTypeText` uses layout constraints which fix the textfield to the right side of the cell and cannot be moved below the title. You would have to create your custom row for that.

**Comment by m-revetria** [comment]
Closing this due to lack of response
