### ISSUE TITLE
How to play custom animation inside a cell when the row value changed?

### ISSUE THREAD

**Issue by fans3210** [xmartlabs/XLForm#879]
Eg: to animate a uiswitch on/off when the row value changed. 

Currently I cannot access the cell in the viewcontroller. The only way I can get the cell instance is in 'updateformrow' method. However, when I want to call the method of my customized cell to on/off the uiswitch with animation, the result is not what I want. The switch did on/off but without any animation

**Comment by fans3210** [comment]
Here is my code:
//    SomeCell *cell = (SomeCell *)[self updateFormRow:row];
//    [cell testAnimateSwitchOn];

**Comment by mats-claassen** [comment]
If you use `XLFormSwitchCell` then the switch will be set to `on` or `off` in theupdate method and you cannot animate that. You can [create a custom row](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row) to do it animated.

You might also try with the `onChangeBlock` which is called when the value of the row changes.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
