### ISSUE TITLE
How to add "Submit button" in form?

### ISSUE THREAD

**Issue by murilo-campaner** [xmartlabs/XLForm#881]
Hello everyone,

I need to add a "submit" button like this one in my form:
http://codepen.io/zabielski/full/qOXKXR/

Anyone know how I can do it?

Thanks!

**Comment by mats-claassen** [comment]
I would normally do this providing a view as the footer of a section.
XLForm does not provide a way to do this but as it uses a simple `UITableView` you can use its datasource and delegate methods to display a view as the footer of that section.

**Comment by m-revetria** [comment]
Closing this due to lack of response
