### ISSUE TITLE
Inline countdown is not using the right type of value

### ISSUE THREAD

**Issue by dvkch** [xmartlabs/XLForm#884]
Hi, after a lot of debugging in my app I realised that a countdown cell doesn't use the right value, it sets/gets the `date` value of the `datePicker` instead of `countDownDuration`. The issue is `date` depends on the current user timezone, and a value of `date` saved when the user is in timezone A is not valid anymore when the user switches to timezone B.

Two fixes are possible : 
- fixing the timezone to GMT, preventing the value from becoming obsolete when the timezone changes
- using the `countDownDuration` value, wrapped in `NSNumber *`, but for people already using this type of cell is would be a breaking change, though the `value` would have more meaning

I am good with making a pull request for both those solutions, just tell me which one is to be done.

**Comment by mats-claassen** [comment]
I would prefer to go with the first option of fixing the timezone to GMT. It would be nice if you could create that PR
