### ISSUE TITLE
row Chinese cannot be left aligned

### ISSUE THREAD

**Issue by bianxu** [xmartlabs/XLForm#885]
rowType：XLFormRowDescriptorTypeText with XLFormRowDescriptorTypeSelectorPickerView， When using Chinese cannot be left aligned
![c071125f-1aa1-4bda-964e-45feb937d65b](https://cloud.githubusercontent.com/assets/13793820/19377920/539649b8-921c-11e6-8093-c8d42de084e9.png)

**Comment by mats-claassen** [comment]
Which are the margins and separatorInsets of those cells? I believe the issue lays with that

**Comment by aimchina** [comment]
how can  I do？still not align。

**Comment by aimchina** [comment]
iphone 6 plus， still not align。

**Comment by mats-claassen** [comment]
Have you set a different `separatorInset` or `layoutMargins`?

**Comment by m-revetria** [comment]
Closing this due to lack of response
