### ISSUE TITLE
Custom Section Header

### ISSUE THREAD

**Issue by fabidona** [xmartlabs/XLForm#886]
Hi!
I would like to customize the section header view with a custom view which subclass UITableHeaderFooterView but in viewForHeaderInSection the dequeueReusableHeaderFooterWithIdentifier method return nil.

In my XLFormViewController subclass:

`- (void)initializeForm {
    //REGISTER CLASS FOR CUSTOM SECTION HEADER VIEW
    [self.tableView registerClass:[PromoFormTopHeader class] forHeaderFooterViewReuseIdentifier:@"promoFormTopHead"];
 /*Other form initialization code...*/
}`

`-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
    PromoFormTopHeader* view = (PromoFormTopHeader*)[tableView dequeueReusableHeaderFooterViewWithIdentifier:@"promoFormTopHead"]; 
/*This return nil!!!*/
    return view;
}`

Is the right way to get a custom section header or XLForm follows another pattern? I use this approach in others project with standard UITableView and UITableViewDelegate and all is right.

thanks all for advice!

**Comment by mats-claassen** [comment]
That is the right pattern as XLForm does not provide another way to do this.

**Comment by Connor-Chappell** [comment]
Has anyone found a solution to this? I am running into the same problem with the view being nil.
