### ISSUE TITLE
Obj-C Type Annotations for NSArray/NSDictionary/etc

### ISSUE THREAD

**Issue by chrisballinger** [xmartlabs/XLForm#887]
Not sure if this is a duplicate issue, but I couldn't find any existing issues or PRs.

To make Swift compatibility smoother (and nicer for Obj-C as well), it would be beneficial to annotate the types. For instance: https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Descriptors/XLFormDescriptor.h#L52

``` objc
@property (readonly, nonatomic, nonnull) NSMutableArray<XLFormSectionDescriptor*> * formSections;
```

If there is a possibility of these changes being merged, I'd help by annotating some of the low hanging fruit and submitting a PR.

**Comment by mats-claassen** [comment]
Yeah, if you want you can submit a Pull Request with some annotations

**Comment by m-revetria** [comment]
Closing this due to lack of response
