### ISSUE TITLE
Creat city pickView

### ISSUE THREAD

**Issue by JIAZoro** [xmartlabs/XLForm#888]
My English maybe very bad.sorry!
How to creat a city pickView like date pickView?
and when pop the city-pickView ,the selected cell not be shield.
thank you!

**Comment by mats-claassen** [comment]
Have you tried using the picker view or inline picker view rows? (`XLFormRowDescriptorTypeSelectorPickerView, XLFormRowDescriptorTypePicker or XLFormRowDescriptorTypeSelectorPickerViewInline`)

You can see them in the selector section of the examples.

**Comment by loveJuly** [comment]
看到楼主的英语，我就放心说中文了。
想问一下这个解决了吗？

**Comment by loveJuly** [comment]
@JIAZoro Can you share this part of the code?
