### ISSUE TITLE
AXRatingView/AXRatingView.h file not found

### ISSUE THREAD

**Issue by olegshevt** [xmartlabs/XLForm#889]
Hi! 
When I install using cocoapods its gives me few errors:
1) AXRatingView/AXRatingView.h file not found
2) Failed to import bridging header '/Users/oleg/Desktop/WORK/SwiftExample/SwiftExample-Bridging-Header.h'

Can you help me, please

**Comment by mats-claassen** [comment]
To try the Swift examples you should run `pod install` in the `.../Examples/Swift` directory to install the dependencies and then you can use the Examples.
