### ISSUE TITLE
XLFormInlineSelectorCell "required"  being ignored because "formDescriptorCellLocalValidation" is not implemented

### ISSUE THREAD

**Issue by Heroico** [xmartlabs/XLForm#89]
Hi There!

I noticed that a row descriptor of type **XLFormRowDescriptorTypeSelectorPickerViewInline**, when set to "required", doesn´t report an error when a value is not set. This seems to be caused by **XLFormInlineSelectorCell** not having implemented a "formDescriptorCellLocalValidation" message.

To have the form trigger a validation error, I created a custom cell class similar to:

```objective-c
@implementation XLFormInlineSelectorCellCustom

-(NSError *)formDescriptorCellLocalValidation
{
    if (self.rowDescriptor.required && !self.rowDescriptor.value){
        return [[NSError alloc] initWithDomain:XLFormErrorDomain code:XLFormErrorCodeRequired userInfo:@{ NSLocalizedDescriptionKey: [NSString stringWithFormat:NSLocalizedString(@"%@ can't be empty", nil), self.rowDescriptor.title] }];
        
    }
    return nil;
}

@end
```

Is there any specific reason why the inline selector cell doesn´t have an error report?

Thanks!

**Comment by mtnbarreto** [comment]
@Heroico formDescriptorCellLocalValidation doesn't exist any more. We changed the validation implementation and now we check only the XLFormRowDescriptor value property that always exists.

Regards
