### ISSUE TITLE
Picker Font

### ISSUE THREAD

**Issue by marinofaggiana** [xmartlabs/XLForm#892]
Hi !
It's possible change type font on picker view ?

Thanks

**Comment by mats-claassen** [comment]
For which type of row do you want to do that? Normally this is done using `cellConfig` or `cellConfigAtConfigure`.
You currently cannot for XLFormRowDescriptorTypeSelectorPickerView as a UIPickerView has no font attribute. You would have to override `pickerView:titleForRow:forComponent:` in that cell.
