### ISSUE TITLE
Hide Cell

### ISSUE THREAD

**Issue by mobilestar0223** [xmartlabs/XLForm#896]
Hello
Thanks for providing great library. It's very useful for me.
But I have one problem.
I tried to remove one cell when select value in inline picker cell.
So I implement like this:
```
override func formRowDescriptorValueHasChanged(_ formRow: XLFormRowDescriptor!, oldValue: Any!, newValue: Any!) {
        ....
       descriptor.hidden = condition
       cell.update()
}
```
First time, condition become true and cell is hidden.
After that, condition become false and cell should show again. But it doesn't work.
I don't know this is bug or not.
Thanks.

**Comment by mats-claassen** [comment]
I don't know what is happening to you but this is not a bug. For example this code works as expected:
```
if ([newValue  isEqual: @"a"]) {
        [self.form formRowWithTag:kDatePicker].hidden = @YES;
    } else {
        [self.form formRowWithTag:kDatePicker].hidden = @NO;
    }
```
