### ISSUE TITLE
attaching to the change event of the slider component

### ISSUE THREAD

**Issue by gristoi** [xmartlabs/XLForm#898]
HI, Love the framework, great job. I am however having one issue, i am using the slider component, between 0 and 100 and am trying to work out how to hook into the change event of the slider and get the value so that i can update the label in real time with the current value.

any pointers?

**Comment by mats-claassen** [comment]
Did you try using the `onChangeBlock` on your `rowDescriptor`? That closure is called when the value of the row changes
