### ISSUE TITLE
XLFormRowDescriptorTypeSelectorPickerViewInline cell doesn´t update its value

### ISSUE THREAD

**Issue by Heroico** [xmartlabs/XLForm#90]
Hi There!

I noticed that **XLFormRowDescriptorTypeSelectorPickerViewInline** cell (**XLFormInlineSelectorCell **) doesn´t update its value when the user is scrolling the options, when first tapping the cell. The form value itself does get updated, but the cell does not.

The cell seems to update when the user taps the original cell so that the picker is hidden. After that, as I scroll, the value does get updated. I haven´t figured out yet why this happens.

Thanks!

**Comment by mtnbarreto** [comment]
@Heroico i couldn't reproduce the issue. It would be great if you give me more information.

Regards.
