### ISSUE TITLE
How can i change this color?

### ISSUE THREAD

**Issue by tospery** [xmartlabs/XLForm#901]
![image](https://cloud.githubusercontent.com/assets/3716286/20858253/b42a9afe-b97c-11e6-8d20-2683adee9d21.png)
![snip20161203_1](https://cloud.githubusercontent.com/assets/3716286/20858256/c8c33d68-b97c-11e6-824b-f4da6ffbdad9.png)
Can't use appearance to change.

**Comment by mats-claassen** [comment]
The color of that button should be `view.tintColor`. You can try setting that.

**Comment by mats-claassen** [comment]
@tospery Did you fix this?
