### ISSUE TITLE
About customHeaderView   open section and close section

### ISSUE THREAD

**Issue by demoker** [xmartlabs/XLForm#904]
![img_1184](https://cloud.githubusercontent.com/assets/10993817/20886671/29c6d370-bb32-11e6-9a84-0bd74662996b.PNG)
![img_1185](https://cloud.githubusercontent.com/assets/10993817/20886672/2a630a7e-bb32-11e6-8af4-fe07124951f4.PNG)
Hi,I use XLForm to work for my project,but here has some problem about customHeaderView open or close section. First, I let "tableView:numberOfRowsInSection:" return 0,next,let it return 5 when tap it.But after tap it ,become textfield to first responder,and the interface in a mess,upward movement many pixels only the cell. And that is good after rolling the tableView.

Thanks for your advice!

**Comment by mats-claassen** [comment]
Are you correctly setting the height of the header view in `tableView(_:heightForHeaderInSection:)`?

**Comment by demoker** [comment]
Yes,the height of header is fixed (60.0).Now,I overwriting the method of keyword showing and hidden,then  no problem.

**Comment by demoker** [comment]
I use [the third SDK ()](https://github.com/molon/MLInputDodger.git) to deal the problem,and cancel the keyboard showing or hidden method of XLForm .This is my repair method.After opening section and the TextField become first responser,then the location of cell is changed.So , I think the reason in  keyword oberver.

**Comment by mats-claassen** [comment]
I would need some code to reproduce this to find the issue. If your workaround fixes it we can leave it as it is until someone else requests a fix.

**Comment by demoker** [comment]
LBBSClientAuctionSetViewController : subClass of XLFormViewController
`- (void)keyboardWillShow:(NSNotification *)notification
{
    DDLogDebug(@"LBBSClientAuctionSetViewController keyboardWillShow:");
}

- (void)keyboardWillHide:(NSNotification *)notification
{
    DDLogDebug(@"LBBSClientAuctionSetViewController keyboardWillHide:");
}`

In fact, be cancelled XLForm the keyboard event monitoring, switch to a third party components.I don't know why confusion until now, I only in this way to avoid it, so I hope to meet with me friends can use this method to avoid the same problem.
