### ISSUE TITLE
row cannot be left aligned？？how can i do？

### ISSUE THREAD

**Issue by aimchina** [xmartlabs/XLForm#905]
` row = [XLFormRowDescriptor formRowDescriptorWithTag:kName rowType:XLFormRowDescriptorTypeText
                                                  title:@"合同名称"];
    [row.cellConfigAtConfigure setObject:@"输入合同名称" forKey:@"textField.placeholder"];
    row.value = self.editVCArr[0];

    row.required = YES; // 默认初始化行
    [section addFormRow:row];
i
![notalign](https://cloud.githubusercontent.com/assets/11752702/20912797/65ea2d4a-bbad-11e6-915a-363dce5c5957.png)

 // 客户名称
    row = [XLFormRowDescriptor formRowDescriptorWithTag:kSelectorPush rowType:XLFormRowDescriptorTypeSelectorPush title:@"所属客户"];
    
    row.value = self.editVCArr[7];
    
    row.action.viewControllerClass = [CutomListViewController class];
    [section addFormRow:row];`

**Comment by mats-claassen** [comment]
Same as #885
