### ISSUE TITLE
CountDownTimer row set default select time is wrong.

### ISSUE THREAD

**Issue by Jeff-F** [xmartlabs/XLForm#907]
// CountDownTimer

       ` row = [XLFormRowDescriptor formRowDescriptorWithTag:kCountDownTimerInline rowType:XLFormRowDescriptorTypeCountDownTimerInline title:@"Countdown Timer"];
        NSDateComponents * dateComp = [NSDateComponents new];
        dateComp.hour = 0;
        dateComp.minute = 7;
        dateComp.timeZone = [NSTimeZone systemTimeZone];
        NSCalendar * calendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian];
        row.value = [calendar dateFromComponents:dateComp];
        [section addFormRow:row];`

set default time is 0h 7m, but show 16h 1m

Examples can find this problem.

**Comment by mats-claassen** [comment]
As far as I can tell this is an issue with NSDate and NSDateComponents. Try logging the date created from those components and you will see it is not correct. Setting the `year` helps but NSDate will still correct the date to your timezone.

**Comment by m-revetria** [comment]
Closing this because of lack of response
