### ISSUE TITLE
setting autocorrectionType of cells

### ISSUE THREAD

**Issue by TheRealDarklord** [xmartlabs/XLForm#909]
Hi, I just tried to change the autocorrectionType-Property of a cell because I'm not satisfied with the default one. But it seems that this property cannot be set with the cellConfig-property of the rowDescriptor.

`[row.cellConfig setValue:@(UITextAutocorrectionTypeNo) forKey:@"textField.autocorrectionType"];`

row is, of course, an instance of XLFormRowDescriptor. But it fails with the following error:

`*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITextField 0x7a6a0c40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key autocorrectionType.'`

Unfortunately on every cell update the autocorrectionType gets the value which is the default for that cell type so that setting autocorrectionType after creating the cell does not work. Am I missing something to make this work?

**Comment by mats-claassen** [comment]
Your syntax is correct. It seems that UITextField is not key value coding-compliant for `autocorrectionType`.

So what you can do is follow #761 although that is a los of code to change an autocorrectionType :).
