### ISSUE TITLE
Changing the value in a row programatically

### ISSUE THREAD

**Issue by mark5422** [xmartlabs/XLForm#911]
I've been trying to change the value of an XLForm row programatically after I load some data from an API call. The form is on screen so needs to be reloaded as its visible.

I've tried setting a new options object. Forcing a call to say that the values have changes. Reloading the table view and nothing is working. I've also tried to change the value like this.

```[(XLFormRowDescriptor *)self.formRows[@"year"] setValue:self.trade.year];```

Can someone please let me know how to change one?

**Comment by multinerd** [comment]
Try

    // inside IBAction or however your calling it programmatically 
    [myXLFormRowDescriptor.cellConfig setObject:"1999" forKey:@"textView.text"];


See: https://github.com/xmartlabs/XLForm#additional-configuration-of-rows

**Comment by mats-claassen** [comment]
Have a look at #493 or [the FAQ](https://github.com/xmartlabs/XLForm#how-to-set-a-value-to-a-row). Does that help?

**Comment by mark5422** [comment]
Ultimately I moved things around so I didn't need to do this any longer as I wasn't able to get it working in time for my needs.
