### ISSUE TITLE
set font for row not work

### ISSUE THREAD

**Issue by hackjie** [xmartlabs/XLForm#913]
XLFormRowDescriptorTypeSelectorSegmentedControl

[row.cellConfigAtConfigure setObject:[UIFont systemFontOfSize:15] forKey:@"_textLabel.font"];

but still not work

**Comment by mats-claassen** [comment]
Try with `[row.cellConfig setObject:[UIFont systemFontOfSize:36] forKey:@"textLabel.font"];`

Fonts should be set with `cellConfig` and not `cellConfigAtConfigure`

**Comment by hackjie** [comment]
Thanks
