### ISSUE TITLE
UIRefreshControl?

### ISSUE THREAD

**Issue by grimmwerks** [xmartlabs/XLForm#918]
How does one utilize UIRefreshControl with XLForm?

**Comment by multinerd** [comment]
The same way you would any other `UITableView`.

`XLFormViewController` mimics a `UITableViewController`, and by that i mean you can reference `self.tableView` in your forms instance

https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.h#L84
