### ISSUE TITLE
-(NSDictionary *)formValues returns (no summary)

### ISSUE THREAD

**Issue by multinerd** [xmartlabs/XLForm#921]
Hi, im using XLForms as an update form, when the view is loaded, the form is initialized, after a webservice call, the forms values gets updated with the necessary data.

Heres my problem.

When i hit save, i pull the values using `[self.form formValues]`. However, even though the text is in the textfield, the dictionary returns `(no summary)` and will remain to do so until i you manually edit the row. this can be problematic when the user doesnt need to touch a specific row.

You can see a demo here  
https://github.com/multinerd/XLForm-Bug

if i find a fix, ill do a PR

**Comment by multinerd** [comment]
A workaround is to save my values to a instance variable `NSString` and use that if the field is showing as (no summary). this way if the user dosent touch the row, i use the original value, otherwise new value from dict.

**Comment by mats-claassen** [comment]
You should set the value of the rowDescriptor and call `-(void)reloadFormRow:(XLFormRowDescriptor *)formRow` as explained [in this FAQ section](https://github.com/xmartlabs/XLForm#how-to-set-a-value-to-a-row).

Related to #493

**Comment by multinerd** [comment]
After tinkering with the `-(void)reloadFormRow:(XLFormRowDescriptor *)formRow`method, and from my understanding, i should use `taskRow.value = @"ksjdfhksfhksf"` instead of `[taskRow.cellConfig setObject:@"ksjdfhksfhksf" forKey:@"textView.text"]` when setting values from my webservice call correct?
