### ISSUE TITLE
XLFormRowDescriptorTypeTextView

### ISSUE THREAD

**Issue by marinofaggiana** [xmartlabs/XLForm#923]
Hi,
it's possible change color background of TextView disabled ? 

This is my code : 
previewFileName.cellConfig.setObject(UIColor(red: 247/255, green: 247/255, blue: 247/255, alpha: 1), forKey: "backgroundColor" as NSCopying) but this it's for cell, i want only for TextView ...

This is the bad result  :
![schermata 2017-01-13 alle 18 32 20](https://cloud.githubusercontent.com/assets/8616947/21939134/a87a34f0-d9be-11e6-9b47-09e2124b015a.png)

i want the backgrond color as the Section.

Thanks

**Comment by mats-claassen** [comment]
You need to change the key. Try with `textView.backgroundColor`

**Comment by marinofaggiana** [comment]
Thanks @mats-claassen ! 
And it's possible change separator color or UITableViewCellSeparatorStyle.none for a sigle section and not for all TableView with : 

self.tableView.separatorStyle = UITableViewCellSeparatorStyle.none

**Comment by mats-claassen** [comment]
You can do what you could do with any UITableView. I think you can't change the separator for a single section. Your code changes it for the entire form.
