### ISSUE TITLE
possible to Programmatically present a pickerview row?

### ISSUE THREAD

**Issue by multinerd** [xmartlabs/XLForm#927]
I have a switch and a picker view. when the switch is off, pickerview is hidden and vice versa. I am looking for a way to programmatically present the pickerview with the switch is turned on. do you have any ideas on how i can achieve this?

I want the flow to be 
> uses taps switch on
> user picks an item

rather than 
> user taps switch on
> user selects newly added row
> user picks an item

**Comment by mats-claassen** [comment]
You could use the `onChangeBlock` on your switch row to assign the first responder to the picker view when the value of the switch is on.

**Comment by multinerd** [comment]
might be a stupid question but how do i access the pickerview from the `XLFormRowDescriptor`?

**Comment by mats-claassen** [comment]
You can get the cell for that row with `cellForFormController` on XLFormRowDescriptor. If you cast that cell to `XLFormPickerCell` (or whatever you are using) you can access the pickerView

**Comment by multinerd** [comment]
Maybe you can help me out. using the following code, cell is always nil for me. You can see my full initForm method here
https://gist.github.com/multinerd/d6159781199c0bc0aada7fa6a7284ecb

    dueSwitch.onChangeBlock  = ^(id oldValue, id newValue, XLFormRowDescriptor *rowDescriptor){
        if ([newValue isEqual:@YES]) {
            id cell = [weakdueRow cellForFormController:weakSelf];
            MNLogMin(@"%@", cell);
        }
    };

**Comment by multinerd** [comment]
Acutally, ive added the `id cell = [weakdueRow cellForFormController:weakSelf];` to `-(void)formRowHasBeenAdded:(XLFormRowDescriptor *)formRow atIndexPath:(NSIndexPath *)indexPath` and its not nil here, so ill tinker with implementing the logic here. Thanks for your help

**Comment by mats-claassen** [comment]
I think `weakdueRow` is nil there. You assign it before creating `dueRow`

**Comment by multinerd** [comment]
I went the delegate route, less headache and got it working in 5 minutes =D. Thanks again for the help and this amazing framework.
