### ISSUE TITLE
the app crash

### ISSUE THREAD

**Issue by JIAZoro** [xmartlabs/XLForm#930]
in one table ,have two XLFormRowDescriptorTypeSelectorPickerView,
when i click one of the row,the app crash,
 crash info:[exc_bad_access code=1, address=....]. in the line    [_pickerView selectRow:[self selectedIndex] inComponent:0 animated:NO];   XLFormSelectorCell.h
not always crash，it is contingency.

**Comment by mats-claassen** [comment]
I put two XLFormRowDescriptorTypeSelectorPickerView in the Examples of XLForm and cannot reproduce this crash. I will need more information to know where the issue is. Are you sure it is not caused by some code of your app?
