### ISSUE TITLE
How to set the controllers language in XLForm

### ISSUE THREAD

**Issue by r00tify** [xmartlabs/XLForm#931]
I'm using XLForm in this app and the month in the date picker controller is showing in the iPhone language. However, I need it to be shown in a different language, i.e. the app language. How do I do that?

**Comment by mats-claassen** [comment]
Did you try setting the `locale` property of your cell using `cellConfigAtConfigure`?

**Comment by r00tify** [comment]
No, how do I do that?

**Comment by mats-claassen** [comment]
Have a look at the [Additional configuration of rows](https://github.com/xmartlabs/XLForm#additional-configuration-of-rows) section of the readme.

**Comment by r00tify** [comment]
It did work at display, but when I pick a date from date picker, the selected date is shown in phone locale not my custom locale.

**Comment by mats-claassen** [comment]
Where is it shown like that? In the console?
The row returns you a date. You can print or show that date in whatever language you want.

**Comment by r00tify** [comment]
No, I mean when I pick (select) a date from the date picker,  the `formattedDate` method inside `XLFormDateCell.m` is returning `[NSDateFormatter localizedStringFromDate:date dateStyle:NSDateFormatterNoStyle timeStyle:NSDateFormatterShortStyle]` which uses the iPhone locale not the one I provide in the row configuration.
