### ISSUE TITLE
Odd rendering of accessoryview background

### ISSUE THREAD

**Issue by carlhunterroach** [xmartlabs/XLForm#932]
On iOS 8.x all is fine. But on an iOS 10.x the accessoryview - the uitoolbar - that appears above the keyboard doesn't have a full opaque background but instead, a background that is only a few pixels high. Suggestions welcomed.

Fine on iOS 8 and iOS 9:
<img width="319" alt="toolbar height ios 8" src="https://cloud.githubusercontent.com/assets/1036041/23401267/faa0f198-fd9e-11e6-9451-a1f95ae75a4c.png">

<img width="321" alt="toolbar height ios 9" src="https://cloud.githubusercontent.com/assets/1036041/23401294/13d56be4-fd9f-11e6-9b26-2f18ffff5276.png">

But toolbar height is too short on iOS 10:
<img width="320" alt="toolbar height ios 10" src="https://cloud.githubusercontent.com/assets/1036041/23401298/189670f6-fd9f-11e6-9cd8-aeb90cd446bf.png">

**Comment by mats-claassen** [comment]
This is weird. It does not happen to me in the Examples of XLForm (iOS 10.2). Could you try it in the Examples in iOS 10.3?

**Comment by mats-claassen** [comment]
Tested this in iOS 10.3 in the Examples and could not reproduce it. 
@carlhunterroach Can you reproduce it in the examples? Or is it a problem with your particular set up?

**Comment by m-revetria** [comment]
Closing this due to lack of response
