### ISSUE TITLE
formRowDescriptorValueHasChanged not called (but other XLFormDescriptorDelegate methods are)

### ISSUE THREAD

**Issue by tiritea** [xmartlabs/XLForm#933]
[Objective-C]

So I'm setting up and using a generic XLFormViewController programmatically (ie not using a subclass, nor a nib), and setting its parent UIViewController as the XLFormDescriptor's delegate. Basically like this:

```
    XLFormDescriptor *xlform = [XLFormDescriptor formDescriptorWithTitle:@"some title"];
    xlform.delegate = self;
    XLFormSectionDescriptor *section;
    XLFormRowDescriptor *row;
    
    section = [XLFormSectionDescriptor formSection];
    [xlform addFormSection:section];
   <loop>
       ...
       row = [XLFormRowDescriptor formRowDescriptorWithTag:xxx rowType:yyy];
        [section addFormRow:row];
   </loop>
```

and then using this xlform to init a XLFormViewController, like this:

```
    XLFormViewController *controller = [XLFormViewController.alloc initWithForm:xlform];
    controller.form.delegate = self; // tried this in case delegate was lost, but doesnt help...
    [self.navigationController pushViewController:controller animated:YES];

```
My parent UIViewController (self) implements all the XLFormDescriptorDelegate methods:

```
-(void)formSectionHasBeenAdded:(XLFormSectionDescriptor *)formSection atIndex:(NSUInteger)index
{
    NSLog(@"%s",__FUNCTION__);
}
...
-(void)formRowDescriptorValueHasChanged:(XLFormRowDescriptor *)formRow oldValue:(id)oldValue newValue:(id)newValue
{
    NSLog(@"%s",__FUNCTION__);
}
```

While my xlform is being constructed I can see all the relevant delegate methods being called - formSectionHasBeenAdded:, formRowHasBeenAdded, ... *BUT* thereafter, once the XLFormViewController is pushed and displayed and I start entering new values, formRowDescriptorValueHasChanged: is never called!?

I realize that I'm not using a XLFormViewController subclass, but it would seem that's not a strict requirement (?) and by-and-large everything else is working as expected. But I just cant seem to get my formRowDescriptorValueHasChanged: delegate to ever get called as I change values in the form. Am I doing something obviously wrong?

**Comment by mats-claassen** [comment]
I can't tell you what it is but that delegate method is called from this line (https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Descriptors/XLFormRowDescriptor.m#L321). You could put a breakpoint there and see why it is not calling. That would be really helpful

**Comment by tiritea** [comment]
OK. So did this and put in breakpoint at XLFormRowDescriptor.m#L321 as suggested:

```
-(void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context
{
    if (!self.sectionDescriptor) return;
    if (object == self && ([keyPath isEqualToString:@"value"] || [keyPath isEqualToString:@"hidePredicateCache"] || [keyPath isEqualToString:@"disablePredicateCache"])){
        if ([[change objectForKey:NSKeyValueChangeKindKey] isEqualToNumber:@(NSKeyValueChangeSetting)]){
            id newValue = [change objectForKey:NSKeyValueChangeNewKey];
            id oldValue = [change objectForKey:NSKeyValueChangeOldKey];
            if ([keyPath isEqualToString:@"value"]){
                id WHOAMI = self.sectionDescriptor.formDescriptor.delegate; // DEBUG!
                [self.sectionDescriptor.formDescriptor.delegate formRowDescriptorValueHasChanged:object oldValue:oldValue newValue:newValue];
                if (self.onChangeBlock) {
                    self.onChangeBlock(oldValue, newValue, self);
                }
            }
            else{
                [self.sectionDescriptor.formDescriptor.delegate formRowDescriptorPredicateHasChanged:object oldValue:oldValue newValue:newValue predicateType:([keyPath isEqualToString:@"hidePredicateCache"] ? XLPredicateTypeHidden : XLPredicateTypeDisabled)];
            }
        }
    }
}

```

As soon as I hit first letter in keyboard when changing a row the breakpoint fires, so it is detecting the keypath "value" is being changed. But WHOAMI is an XLFormViewController* (!), ie *not* my generic UIViewController, which should have been (and previously was) the delegate. This rather explains why I stop getting the notifications. So is the formDescriptor.delegate getting changed somewhere during or after you init an new XLFormViewController with it?

**Comment by tiritea** [comment]
BTW, please excuse my delay(s) in responding - I'm in New Zealand, some 9 timezones away from ya... :-)

**Comment by mats-claassen** [comment]
Yes, it is changed in viewDidLoad method. But you have to take care to assign the delegate to a simple UIViewController as the XLFormViewController does use the delegate to implement some features. So I suggest that you implement the delegate in your XLFormViewController because otherwise you will have to implement all the delegate methods and add the code that a XLFormViewController would execute there.

To see this have a look at https://github.com/xmartlabs/XLForm/blob/master/XLForm/XL/Controllers/XLFormViewController.m#L273-L341

**Comment by tiritea** [comment]
Cheers.

So, XLFormViewController is effectively an 'abstract' superclass, which *must* be subclassed - at least for XLFormDescriptorDelegate to work properly; correct? If that's the case then it might be worth making it explicit in the docs, and enforcing it with, say

```
@interface XLFormDescriptor : NSObject
...
@property (weak, nullable) XLFormViewController<XLFormDescriptorDelegate> delegate;
...
```

Aside: I do think it'd be great if you could use '''[XLFormViewController.alloc initWithForm:xlform]''' - ie without subclassing - as I tried. Maybe something to consider for the future... BTW, great package - thanks!

**Comment by tiritea** [comment]
Closed issue b/c working as designed - XLFormDescriptorDelegate requires XLFormViewController subclass.

**Comment by mats-claassen** [comment]
Thanks for your comments @tiritea. Maybe we should enforce that yes.
