### ISSUE TITLE
Customize XLFormSelectorCell

### ISSUE THREAD

**Issue by r00tify** [xmartlabs/XLForm#934]
Is there any simple way to make `XLFormSelectorCell` appear on two lines (title as a label and selected value bellow in the 2nd line)? Maybe something like the `FloatLabeledTextField` From the examples project..

The idea is to prevent selected values from being truncated for long strings.

**Comment by mats-claassen** [comment]
You can try using `row.cellStyle = UITableViewCellStyleSubtitle;`

**Comment by r00tify** [comment]
Great, thanks!
