### ISSUE TITLE
How can I hide the keyboard toolbar button

### ISSUE THREAD

**Issue by yepesasecas** [xmartlabs/XLForm#936]
I want to hide the toolbar "Done" Button in some scenarios when I only have one TextField and one action button. see image below.

![img_2184](https://cloud.githubusercontent.com/assets/1679292/24067508/df27d368-0b4b-11e7-9e1f-8b5272e85bf0.jpg)

**Comment by mats-claassen** [comment]
I think currently the easiest way is to override `-(UIView *)inputAccessoryViewForRowDescriptor:(XLFormRowDescriptor *)rowDescriptor` in your XLFormViewController subclass.

**Comment by yepesasecas** [comment]
Thank you @mats-claassen 
I will try your solution.

**Comment by mats-claassen** [comment]
@yepesasecas Did that work for you?

**Comment by yepesasecas** [comment]
@mats-claassen not yet.

**Comment by m-revetria** [comment]
Closing this due to lack of response
