### ISSUE TITLE
Error -[UItableview findFirstResponder:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by GioAlba** [xmartlabs/XLForm#938]
I'm trying to use the library.
I installed the latest version via pod. I'm using the sample code in the example and got the following error in 

UIView * firstResponder = [self.tableView findFirstResponder];

-[UItableview findFirstResponder:]: unrecognized selector sent to instance

where am I wrong?
Thanks

**Comment by mats-claassen** [comment]
`findFirstResponder` is declared in `UIView+XLFormAdditions.h` in XLForm. This is included from `XLForm.h`, did you import that header?
I tried this code in the examples and it did not crash.

**Comment by GioAlba** [comment]
I do not know why but I settled with carthage. Definitely a problem with my pod
Thanks

**Comment by mats-claassen** [comment]
So I think we can close this, right? Feel free to reopen if you think so
