### ISSUE TITLE
How to chang pickcell detailTextLabel.frame

### ISSUE THREAD

**Issue by smileat** [xmartlabs/XLForm#939]
Hi,please help me. How to chang pickcell detailTextLabel.frame.x 、y、width、height。I use 

rowType:XLFormRowDescriptorTypeSelectorPickerView

**Comment by mats-claassen** [comment]
The `detailTextLabel` is the one of UITableViewCell. You can try setting its frame but I am not sure how UIKit handles that.
To do this you can use `cellConfig` or `cellConfigAtConfigure`.
