### ISSUE TITLE
Change Cell Separator Color

### ISSUE THREAD

**Issue by AlexHedley** [xmartlabs/XLForm#943]
How do you change the Cell Separator color?

```objc
self.tableView.separatorColor = [UIColor redColor];
```

I've tried removing it, without any luck also.

```objc
self.tableView.separatorInset = UIEdgeInsetsMake(0, 0, 0, 0);
```

```objc
self.tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
```

```objc
UIEdgeInsets inserts = UIEdgeInsetsMake(0.0, 0.0, 0.0, 0.0);
[row.cellConfigAtConfigure setObject:inserts forKey:@"cell.separatorInset"];
```

**Comment by mats-claassen** [comment]
It does work with this line:

```objc
self.tableView.separatorColor = [UIColor redColor];
```

You just have to take care where you execute it. It should be in `viewDidLoad` after calling super.

**Comment by AlexHedley** [comment]
Thanks @mats-claassen I think I'd tried it everywhere but!

I'd tried it at the start of ```initializeForm```, after ```self.form = form;```  etc.

Appreciate you taking the time to respond :)
