### ISSUE TITLE
Make XLFormOptionsObject formValue and formDisplayText writeable?

### ISSUE THREAD

**Issue by tiritea** [xmartlabs/XLForm#944]
So I have an XForm application where I need to change the text & value of one of a XLFormRowDescriptorTypeMultipleSelector row's XLFormOptionsObject objects _after_ its been added to the row's selectorOptions [in response to user input]. Unfortuantely, because the XLFormOptionsObject's formValue and formDisplayText are read-only - you can only set them during initWithValue:displayText:, which may return a new object - the only way to do so presently is by re-creating an entirelynew XLFormOptionsObject with the new values. Further, because the row's selectorOptions is not mutable, this in turn requires re-creating and re-populating its selectorOptions too. I've tried this, it mostly works, but I've noticed that after having done so, I can actually get the old (and removed!) XLFormOptionsObject passed back in the newValue array to formRowDescriptorValueHasChanged:oldValue:newValue: (!) Presumably something somewhere is still retaining the old option that I was trying to replace...

Anyway, all this would be much simpler if formValue and formDisplayText were writable. I checked the XLFormOptionsObject.m source and there doesn't really seem any compelling reason why they _must_ be read-only; they just expose the internal vars called _formValue and __formDisplaytext. And it could actually simplify the XLFormOptionsObject.m code somewhat by simply making them both regular r/w instance variables (no need to define getters). And allowing folks to change an existing XLFormOptionsObject would only increase its flexibility. 

Or am I missing something? Is there a reason why these _need_ to be read-only?

Cheers,

- Gareth

**Comment by mats-claassen** [comment]
I think `formDisplayText` could be writable but why would you want to change the `formValue` of an option? I mean would it not be a new object then?

**Comment by tiritea** [comment]
My use case is a (custom) XLFormRowDescriptorTypeSelectorPush where the last option is ‘Other’, which when picked brings up a textField to allow the user to enter a custom value. Hence I need to be able to update that option’s formValue - and preferably formDisplayText too - after they’ve entered their desired value. Does that make sense?
