### ISSUE TITLE
Change selected background color

### ISSUE THREAD

**Issue by tobib89** [xmartlabs/XLForm#945]
Is it possible to change the background color of a selected XLFormButtonCell?

It is possible with a UITableViewCell:
UIView *view = [[UIView alloc] init];
view.backgroundColor = [UIColor redColor];
cell.selectedBackgroundView = view;

**Comment by AlexHedley** [comment]
Are you happy to change the background color of the whole cell?

`row.cellConfigAtConfigure[@"backgroundColor"] = [UIColor redColor];`

**Comment by tobib89** [comment]
No, i want to change the color of a selected XLFormButtonCell. The Color of the selected cell is by default gray.

**Comment by AlexHedley** [comment]
It would be good to be able to change this selection style.
- UITableViewCellSelectionStyleNone
- UITableViewCellSelectionStyleBlue
- UITableViewCellSelectionStyleGray
- UITableViewCellSelectionStyleDefault

```objc
[row.cellConfig setObject:@(UITableViewCellSelectionStyleBlue) forKey:@"selectionStyle"];
```

---

You could use a Custom Row

- [How To Create a Custom Row](https://github.com/xmartlabs/XLForm#how-to-create-a-custom-row)

---

You could create a custom cell then change the `selectionStyle`

```objc
self.selectionStyle = UITableViewCellSelectionStyleNone
```

And implement

```objc
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated { ... }
```

---

Doesn't change the color but stops it staying grey.

- [Button Cell turns grey after selection - 373](https://github.com/xmartlabs/XLForm/issues/373)

```objc
- (void)deselectFormRow:(XLFormRowDescriptor *)formRow
```

**Comment by tobib89** [comment]
Thanks for your reply.
I just add this lines of code in XLFormBaseCell:
- (void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated
{
    if (highlighted) {
        self.backgroundColor = [UIColor redColor];
    } else {
        self.backgroundColor = [UIColor whiteColor];
    }
}
Of course it's also possible with cutom rows, but i need the same background color for every in row in my project.
