### ISSUE TITLE
Pickercontroller allowsEditing=no

### ISSUE THREAD

**Issue by GioAlba** [xmartlabs/XLForm#946]
How I can use row cell XLFormRowDescriptorTypeImage with picker controller with option allowsEditing=NO

Thanks

**Comment by mats-claassen** [comment]
This is currently not easy to change. You would have to subclass the XLFormImageCell and then override `formDescriptorCellDidSelectedWithFormController:` or `openImage:`

**Comment by mats-claassen** [comment]
This is currently not easy to change. You would have to subclass the XLFormImageCell and then override `formDescriptorCellDidSelectedWithFormController:` or `openImage:`

**Comment by m-revetria** [comment]
Closing this because of lack of response
