### ISSUE TITLE
Add image to custom row for button

### ISSUE THREAD

**Issue by smileat** [xmartlabs/XLForm#950]
How can I add an image to a button. In custom row, have a button "btnLocation",
 I use:
 `[row.cellConfig setObject:[UIImage imageNamed:@"scan_blue"] forKey:@"btnLocation.imageView.image"];
`

I konw add image to button, need use:
 `[self.btnLocation setImage:[UIImage imageNamed:@"scan_blue"] forState:UIControlStateNormal];
`

but I need use row.cellConfig to add some different image.

**Comment by mats-claassen** [comment]
@smileat Could you find a solution? 

What is the error when you execute:
`[row.cellConfig setObject:[UIImage imageNamed:@"scan_blue"] forKey:@"btnLocation.imageView.image"];` ?

**Comment by smileat** [comment]
@mats-claassen the image is not show. But I use Debug View Hierarchy to check, find this :
<img width="568" alt="7f990f6c-2b53-78c6-950c-22f8dbe3406d" src="https://cloud.githubusercontent.com/assets/11358644/25471568/475d35f8-2b5a-11e7-8ed1-e0cb85f30c78.png">

**Comment by smileat** [comment]
I find UIButton->imageView is readonly.
`@property(nullable, nonatomic,readonly,strong) UIImageView *imageView  NS_AVAILABLE_IOS(3_0);`

**Comment by mats-claassen** [comment]
Ah, I get it. I think you will not be able to use `setImage:forState:` using cellConfig.
As it is a custom row you can make a workaround by creating a property in the cell and in its setter call `setImage:forState:`

**Comment by smileat** [comment]
@mats-claassen Now, I use UIImageView and UIButton to do a "UIButton",like this:

`[self.contentView addSubview:self.imageViewBtnBack];
[self.contentView addSubview:self.btnLocation];

[self.btnLocation mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.equalTo(self.contentView).offset(-left_space_15);
        make.width.mas_equalTo(50);
        make.height.mas_equalTo(25);
        make.centerY.equalTo(self.contentView);
    }];
    
    [self.imageViewBtnBack mas_makeConstraints:^(MASConstraintMaker *make) {
        make.right.width.height.centerY.equalTo(self.btnLocation);
    }];`
then we can set 
`[row.cellConfig setObject:[UIImage imageNamed:@"scan_blue"] forKey:@"imageViewBtnBack.image"];`

But I have new problem（I submit issue before）： how can I set `self.imageViewBtnBack` frame or size to fit `[UIImage imageNamed:@"scan_blue"]`

**Comment by smileat** [comment]
<img width="410" alt="qq 20170503083223" src="https://cloud.githubusercontent.com/assets/11358644/25645041/3efa5238-2fdd-11e7-81bc-e0c9f3196b85.png">

**Comment by mats-claassen** [comment]
Did you try with the different `contentMode`'s of the image view? 
Do you want to change the image after it has been shown or just support different image sizes for this row?

If it is the second case then you could parametrize the constraints. I don't know when you set the constraints but if it is after `configure` then you could have properties in that cell for the constants in the constraints and then change that properties with `cellConfigAtConfigure`.

**Comment by smileat** [comment]
I set `self.imageViewBtnBack.contentMode = UIViewContentModeRight;` yet.
I want to support different image sizes for this row.

How to "set the constraints but if it is after `configure`"?  I set all the constraints in `configure`

**Comment by mats-claassen** [comment]
I know constraints should go in the `configure`. What I meant was somehow change some parameters in `celConfigAtConfigure` and then update the constraints in `update` for example.

You could have constraints for height and width of the UIImageView and then update the constants of those constraints in `update` according to what you set in `cellConfigAtConfigure`

**Comment by smileat** [comment]
@mats-claassen Perfect solution. I am very excited. Thank you for your patience! Thank you!
