### ISSUE TITLE
Add XLFormViewController's view to UIViewController's view as subview

### ISSUE THREAD

**Issue by ShaiGivati464** [xmartlabs/XLForm#953]
I have two controllers: one inherits UIViewController and the other inherits XLFormViewContoller.
I would like to add the view of the XLFormViewContoller as subview of the regular UIViewController. Is it possible?

**Comment by mats-claassen** [comment]
I think so but you should still keep the XLFormViewController to control the form

**Comment by m-revetria** [comment]
Closing this due to lack of response
