### ISSUE TITLE
formValues() always nil for selectorOptions

### ISSUE THREAD

**Issue by AlexeyFreelancer** [xmartlabs/XLForm#956]
Hi

`pod 'XLForm', :git => 'https://github.com/jcs/XLForm.git', :branch => 'master'`

```
row = XLFormRowDescriptor(tag: "Test", rowType:XLFormRowDescriptorTypeSelectorPush, title:"Push")
        row.selectorOptions = [XLFormOptionsObject(value: 0, displayText: "Option 1"),
                               XLFormOptionsObject(value: 1, displayText:"Option 2"),
                               XLFormOptionsObject(value: 2, displayText:"Option 3"),
                               XLFormOptionsObject(value: 3, displayText:"Option 4"),
                               XLFormOptionsObject(value: 4, displayText:"Option 5")
        ]
        row.value = XLFormOptionsObject(value: 1, displayText:"Option 2")
        section.addFormRow(row)
```

`let formValues = self.form.formValues()`

Doesn't matter what was selected - value always nil.

**Comment by mats-claassen** [comment]
Hi @AlexeyFreelancer, do you have another row with the same tag? In that case you would never get the values for this row.

**Comment by AlexeyFreelancer** [comment]
Hi @mats-claassen No, I have only one row with name "Test". And even more - it worked before (about 1 years ago. Yeah, I didn't update my app a long of time) but after update all works well except Selector :(
If you need more info I can prepare more examples with screenshots.

**Comment by mats-claassen** [comment]
It is working for me on master with the examples. I see you are pointing to master of a fork (https://github.com/jcs/XLForm.git). Maybe there is a commit on that fork that breaks this.

**Comment by AlexeyFreelancer** [comment]
Ah, maybe I use wrong repository path! I'll check it asap and add feedback. Thanks!

**Comment by AlexeyFreelancer** [comment]
The same error. My steps:
1. Changed Podfile:
`pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm', :branch => 'master'`
2. Updated libs
`pod --verbose update`
Log:
`-> Installing XLForm 3.3.0 (was 3.3.0)`
3. Implemented test method:
```
func test() {
        let form : XLFormDescriptor
        var section : XLFormSectionDescriptor
        var row : XLFormRowDescriptor

        form = XLFormDescriptor(title: "Test https://github.com/xmartlabs/XLForm/issues/956")

        section = XLFormSectionDescriptor.formSection(withTitle: "Test section")

        form.addFormSection(section)

        row = XLFormRowDescriptor(tag: "TestUniqueKeyForIssue956", rowType:XLFormRowDescriptorTypeSelectorPush, title:"Push")
        row.selectorOptions = [XLFormOptionsObject(value: "option_1", displayText: "Option 1"),
                               XLFormOptionsObject(value: "option_2", displayText:"Option 2")
        ]
        row.value = XLFormOptionsObject(value: "option_2", displayText:"Option 2")
        section.addFormRow(row)

        let formValuesOrig = form.formValues()
        let formValuesDictionary: NSDictionary = form.formValues() as NSDictionary
        let selectorValue = formValuesDictionary.value(forKey: "TestUniqueKeyForIssue956") as? String

        print(selectorValue)
    }
```

Result:
selectorValue is nil

Expected result:
selectorValue should be "option_2"

Screenshot:
<img width="1018" alt="screen shot 2017-05-02 at 17 27 30" src="https://cloud.githubusercontent.com/assets/1579687/25622590/8b660656-2f5d-11e7-8d9d-5ae5fbc6772f.png">

**Comment by mats-claassen** [comment]
You can see that the object is in the dictionary on the right side of the debugger console. The value for key `TestUniqueKeyForIssue956 ` is a XLFormOptionsObject. That is why casting it to String gives nil. Try printing that objects value or displayText.

**Comment by AlexeyFreelancer** [comment]
You're right. Thanks! and sorry for disturb
