### ISSUE TITLE
Make new row first responder when adding via multivaluedAddButton

### ISSUE THREAD

**Issue by RescueThemes** [xmartlabs/XLForm#957]
I have a multivalued section and when I tap the multivaluedAddButton I would like to set that added row as first responder. Any suggestions on how to achieve that?
Thank you

**Comment by mats-claassen** [comment]
Testing with the examples, with the first section of the `Multivalued Sections` form that seems to happen. The new row gets first responder after you tap the add button.

**Comment by RescueThemes** [comment]
Thank you, this is a custom row

**Comment by RescueThemes** [comment]
Haha, OK. Simple mistake. I forgot to implement -
(BOOL)formDescriptorCellCanBecomeFirstResponder
{
   return (!self.rowDescriptor.isDisabled);
}
