### ISSUE TITLE
Row indexPath

### ISSUE THREAD

**Issue by AlexHedley** [xmartlabs/XLForm#958]
Example: Store user preferences
I'm calling an API to return an array of objects which have an _Id_ and a _Name_.

| Id | Name           |
|----|----------------|
| 1  | Food and Drink |
| 2  | Family         |

These are stored in an Array

```objc
@property (nonatomic, strong) NSMutableArray *categories;
```

I'm using Switch controls to display these items:

```objc
XLFormRowDescriptor *row = [XLFormRowDescriptor formRowDescriptorWithTag:@(category.Id) rowType:XLFormRowDescriptorTypeBooleanSwitch title:category.categoryName];
...
row.value = @1; //Turn on switch
```

<img src="https://cloud.githubusercontent.com/assets/1573469/26150060/b39ceeee-3af4-11e7-8496-9733736efbb9.png" width="300" alt="categories">

I can call `httpParameters allKeys` to get the Titles
```objc
NSArray *categories = [[self httpParameters] allKeys];
```
I can call the boolValue on value to see if the switch is on or off.

I'd like to get the Tags (or Ids) to use to send the chosen rows back to an API.

---

Usually I would use the following to get the value from the array based on the cell row.
```objc
Category *category = [_ categories objectAtIndex:indexPath.row];
```
If the Category object had multiple properties what would be the best way to retrieve and use that data?

**Comment by mats-claassen** [comment]
I do not completely understand your problem. You want to map the rows to its associated category? You should be able to find the correct category with its `id` which you set as tag to the row.

**Comment by AlexHedley** [comment]
I was hoping for another method like `formValues` or `httpParameters` but for tags.

- `-(NSDictionary *)formValues;`
- `-(NSDictionary *)httpParameters;`

So if I just mimic those methods and loop rows and get the `row.tag` property?

**Comment by mats-claassen** [comment]
`formValues` returns a Dictionary that maps the row's tags to their values so that you get all the tags there.

**Comment by AlexHedley** [comment]
Thanks, sorry I'd missed that.
