### ISSUE TITLE
Creating two selectors fails to respond to value updates

### ISSUE THREAD

**Issue by alex-taffe** [xmartlabs/XLForm#963]
Creating two selectors of any time fails to update values on the second selector. For example with this code:

```
//Gender
row = XLFormRowDescriptor(tag: Tags.Gender, rowType:XLFormRowDescriptorTypeSelectorSegmentedControl, title:"Gender")
row.selectorOptions = ["Male", "Female"]
row.value = "Male"
section.addFormRow(row)
        
//Gender Interest
row = XLFormRowDescriptor(tag: Tags.Interest, rowType:XLFormRowDescriptorTypeSelectorSegmentedControl, title:"I am interested in")
row.selectorOptions = ["Women", "Men"]
row.value = "Women"
section.addFormRow(row)
```

The gender interest row will fail to update and receive the value of women

**Comment by m-revetria** [comment]
Hi @alex-taffe,

Can you show how you are updating the value of the second selector?

That is not done by `XLForm` automatically, you should implement the function `formRowDescriptorValueHasChanged` and check if the row changed was the first selector then update the second selector properly.

Regards

**Comment by alex-taffe** [comment]
It actually turned out that it was me being an idiot and assigning an image to a text row by accident inside of a closure, my bad!
