### ISSUE TITLE
Possibility of using as a TableView instead of TableViewController?

### ISSUE THREAD

**Issue by AdventuresOfMar** [xmartlabs/XLForm#965]
Hello!:) Is it possibility to use this cocoapod as a tableview instead of having it as the table view controller. Essentially I need a fixed header and fixed footer that don't scroll with the table view

**Comment by mats-claassen** [comment]
You **must** conform to XLFormViewController which is an UIViewController, not an UITableViewController.  That XLFormViewController has a tableView and you can set its headers and footers as you want.

**Comment by AdventuresOfMar** [comment]
Thanks so much! That gives me an idea on where to start my changes
