### ISSUE TITLE
How to set fixed button?

### ISSUE THREAD

**Issue by luxystech** [xmartlabs/XLForm#982]
Could you give any idea how to make button fixed on bottom and always over the form when scrolling?

http://joxi.ru/4AkOO4kiy8POqA

**Comment by delmarz** [comment]
1+ for this.

**Comment by santiagofm** [comment]
I think you should ask this question in stackoverflow as it has little to do with XLForm.

Anyways, you should add the button you want to the form's parent `view`(probably your viewcontroller's view) and setup the appropriate constraints to have the button below the form and at the bottom of the view.
I think it's pretty straightforward but you can search stackoverflow and you'll find lot's of threads, [like this one](https://stackoverflow.com/questions/38887389/a-floating-button-fixed-at-the-bottom-of-uitableview-with-scrollviewdidscroll-no).

Cheers
