### ISSUE TITLE
Changing background color

### ISSUE THREAD

**Issue by ajitam** [xmartlabs/XLForm#999]
Hello, my first task was to change the background color of the form.
I manage to do this with this code:

```cpp
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    tableView.backgroundColor = [UIColor whiteColor];
    tableView.tableHeaderView.backgroundColor = [UIColor whiteColor];
    return tableView.tableHeaderView;
}
```

**Q1:** Is there a better way to check table background (here I'm catching tableview every time header is rendered)

**Q2:** how do I change the background color of the `XLFormRowDescriptorTypeSelectorPush` view

**Comment by halpz** [comment]
I'm having this problem too!

**Comment by ajitam** [comment]
Dear XLForm owners,

I think it would be appropriate to remove sentence form the first page

> Do not panic, we will continue maintaining and improving XLForm, obj-c rocks!!

if you are not planing to actively **maintain and improve** the project. People (like me) are making decisions (also) based on things like this.

**Comment by ajitam** [comment]
btw @halpz in the end I just created my own custom push view instead of using "out of the box" one
